### ISSUE TITLE
cryptography.exceptions.InternalError: Unknown OpenSSL error.

### ISSUE THREAD

**Issue by bmcnally-uw** [pyca/cryptography#10267]
Environment:

- Ubuntu 22.04
- python3 3.10.6-1~22.04
- python3-cryptography 3.4.8-1ubuntu2.1
- openssl 3.0.2-0ubuntu1.12
- python3-openssl 21.0.0-1

```
# python3
Python 3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from OpenSSL import crypto
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3/dist-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import crypto, SSL
  File "/usr/lib/python3/dist-packages/OpenSSL/crypto.py", line 17, in <module>
    from OpenSSL._util import (
  File "/usr/lib/python3/dist-packages/OpenSSL/_util.py", line 6, in <module>
    from cryptography.hazmat.bindings.openssl.binding import Binding
  File "/usr/lib/python3/dist-packages/cryptography/hazmat/bindings/openssl/binding.py", line 189, in <module>
    Binding.init_static_locks()
  File "/usr/lib/python3/dist-packages/cryptography/hazmat/bindings/openssl/binding.py", line 163, in init_static_locks
    cls._ensure_ffi_initialized()
  File "/usr/lib/python3/dist-packages/cryptography/hazmat/bindings/openssl/binding.py", line 151, in _ensure_ffi_initialized
    _openssl_assert(
  File "/usr/lib/python3/dist-packages/cryptography/hazmat/bindings/openssl/binding.py", line 77, in _openssl_assert
    raise InternalError(
cryptography.exceptions.InternalError: Unknown OpenSSL error. This error is commonly encountered when another library is not cleaning up the OpenSSL error stack. If you are using cryptography with another library that uses OpenSSL try disabling it before reporting a bug. Otherwise please file an issue at https://github.com/pyca/cryptography/issues with information on how to reproduce this. ([_OpenSSLErrorWithText(code=310378599, lib=37, reason=103, reason_text=b'error:12800067:DSO support routines::could not load the shared library'), _OpenSSLErrorWithText(code=310378599, lib=37, reason=103, reason_text=b'error:12800067:DSO support routines::could not load the shared library'), _OpenSSLErrorWithText(code=126353445, lib=15, reason=524325, reason_text=b'error:07880025:common libcrypto routines::reason(524325)')])
```

I get this error on numerous freshly built systems, but not necessarily consistently, which suggests maybe other conditions are placing errors on the OpenSSL error stack per your FAQ. I'm not sure how I'd check to know which other libraries were actively using this stack or how to even look at the current state of the error stack.

**Comment by alex** [comment]
Can you provide instructions for us to reproduce this issue from a clean baseline?

**Comment by bmcnally-uw** [comment]
I'm not sure if I can yet. We build via Canonical's MAAS tool, and then we apply configs (package updates, service configuration, etc.) via Puppet configuration management. I haven't yet reproduced the issue for systems that haven't had Puppet run on them, but I've also rebuilt systems that were previously problematic and not had issues with them after Puppet was run.

**Comment by alex** [comment]
It's very difficult for us to offer any guidance if we don't know how to reproduce this issue. 

Are installing things exclusively via Ubuntu packages, or also using pip to install packages?
