### ISSUE TITLE
Broken ec.derive_private_key()

### ISSUE THREAD

**Issue by m-spiessens** [pyca/cryptography#10319]
```bash
$ pip show cryptography
Name: cryptography
Version: 42.0.2
Summary: cryptography is a package which provides cryptographic recipes and primitives to Python developers.
Home-page: 
Author: 
Author-email: The Python Cryptographic Authority and individual contributors <cryptography-dev@python.org>
License: Apache-2.0 OR BSD-3-Clause
Location: /home/spiessens/.local/lib/python3.10/site-packages
Requires: cffi
Required-by:
```

```python
from cryptography.hazmat.primitives.asymmetric.ec import derive_private_key,SECP256R1

derive_private_key(private_value=1, curve=SECP256R1)
```

```
Traceback (most recent call last):
  File "bla.py", line 3, in <module>
    ec.derive_private_key(private_value=1, curve=ec.SECP256R1)
  File "/home/spiessens/.local/lib/python3.10/site-packages/cryptography/hazmat/primitives/asymmetric/ec.py", line 346, in derive_private_key
    return rust_openssl.ec.derive_private_key(private_value, curve)
TypeError: curve must be an EllipticCurve instance
```

**Comment by alex** [comment]
You need to pass an instance of the curve, not the curve class itself:
`curve=SECP256R1()`
