### ISSUE TITLE
ImportError: DLL load failed while importing _rust: No se encontró el proceso especificado.

### ISSUE THREAD

**Issue by sochoac1** [pyca/cryptography#10388]
* Version of Python: 3.9.1
* ``cryptography``:  42.0.2
*  ``cffi``: 1.16.0
*  ``pip``:  24.0
* ``wheel``:  0.42.0
* ``setuptools``:  69.1.0
* `Operative System`: Windows 11
 
* How you installed ``cryptography``: I installed `paramiko` using the command `pip install paramiko`, and `cryptography` was automatically installed as a dependency.
* Clear steps for reproducing your bug:
1. Create a virtual enviroment using `pipenv shell`
2. Install `paramiko` using `pip install paramiko`
3. Run a Python file containing 1 line: `import paramiko`

**Output - Error**:
Traceback (most recent call last):
  File "C:\...\repo\error.py", line 1, in <module>
    import paramiko
  File "C:\...\.virtualenvs\repo\lib\site-packages\paramiko\__init__.py", line 22, in <module>
    from paramiko.transport import (
  File "C:\...\.virtualenvs\repo\lib\site-packages\paramiko\transport.py", line 33, in <module>
    from cryptography.hazmat.primitives.ciphers import algorithms, Cipher, modes
  File "C:\...\.virtualenvs\repo\lib\site-packages\cryptography\hazmat\primitives\ciphers\__init__.py", line 11, in <module>
    from cryptography.hazmat.primitives.ciphers.base import (
  File "C:\...\.virtualenvs\repo\lib\site-packages\cryptography\hazmat\primitives\ciphers\base.py", line 10, in <module>
    from cryptography.exceptions import (
  File "C:\...\.virtualenvs\repo\lib\site-packages\cryptography\exceptions.py", line 9, 
in <module>
    from cryptography.hazmat.bindings._rust import exceptions as rust_exceptions
ImportError: DLL load failed while importing _rust: Specified process not found.

**Comment by reaperhulk** [comment]
This appears to be a bug in Python 3.9.1. Please upgrade to a newer Python 3.9 and see if it still occurs.

Previous issue: https://github.com/pyca/cryptography/issues/10300

**Comment by sochoac1** [comment]
Python upgraded to 3.12 and issue fixed. Thank you.

**Comment by terrok9** [comment]
Issue reported also in python 3.9.0

If anyone knows how to handle the conflicts without changing python version, it would be great.

**Comment by alex** [comment]
Upgrading to a newer version of Python 3.9 (e.g., 3.9.18) should be sufficient.
