### ISSUE TITLE
ImportError: cannot import name 'ObjectIdentifier' from 'cryptography.hazmat.bindings._rust' (unknown location)

### ISSUE THREAD

**Issue by rkintzi** [pyca/cryptography#10429]
Not sure what dependency am I missing:

```
$ mkdir test; cd test
$ python -m venv pyenv
$ wget https://files.pythonhosted.org/packages/7c/98/940c7cab9ba0718119e7ab2bdc61df2f5effec81ca163bf2b599b988f4cb/cryptography-42.0.3-pp310-pypy310_pp73-manylinux_2_28_x86_64.whl
$ export PYTHONPATH=`pwd`/cryptography-42.0.3-pp310-pypy310_pp73-manylinux_2_28_x86_64.whl
$ ./pyenv/bin/python -c "import cryptography.hazmat.primitives.asymmetric.ec"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/radek/test/cryptography/hazmat/primitives/asymmetric/ec.py", line 11, in <module>
    from cryptography.hazmat._oid import ObjectIdentifier
  File "/home/radek/test/cryptography/hazmat/_oid.py", line 7, in <module>
    from cryptography.hazmat.bindings._rust import (
ImportError: cannot import name 'ObjectIdentifier' from 'cryptography.hazmat.bindings._rust' (unknown location)
```

**Comment by reaperhulk** [comment]
Are you running on pypy?

**Comment by rkintzi** [comment]
@alex Why? Is this specific to cryptorgraphy? According to https://docs.python.org/3/using/cmdline.html#envvar-PYTHONPATH this should work? And it works for other libraries?

**Comment by reaperhulk** [comment]
Cryptography contains compiled code, which is covered in the docs as `Extension modules cannot be imported from zipfiles.`

**Comment by rkintzi** [comment]
Invalid

**Comment by alex** [comment]
I don't think either of us have any familiarity with Python extensions for PostgreSQL. In general though, extension modules are a fairly common use case, so I'd expect there's a solution, but you'd have to ask the postgresql folks.
