### ISSUE TITLE
ImportError: DLL load failed while importing _rust: The specified procedure could not be found.

### ISSUE THREAD

**Issue by byteherder** [pyca/cryptography#11325]
I am trying to install Scrapy using PyCharm as my IDE. I have followed the install procedure on their website. I am getting the following error.

Traceback (most recent call last):
  File "C:\Users\chris\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\chris\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\chris\PycharmProjects\WebCrawler\venv\Scripts\scrapy.exe\__main__.py", line 4, in <module>
  File "c:\users\chris\pycharmprojects\webcrawler\venv\lib\site-packages\scrapy\cmdline.py", line 9, in <module>
    from scrapy.commands import BaseRunSpiderCommand, ScrapyCommand, ScrapyHelpFormatter
  File "c:\users\chris\pycharmprojects\webcrawler\venv\lib\site-packages\scrapy\commands\__init__.py", line 11, in <module>
    from scrapy.crawler import CrawlerProcess
  File "c:\users\chris\pycharmprojects\webcrawler\venv\lib\site-packages\scrapy\crawler.py", line 27, in <module>
    from scrapy.core.engine import ExecutionEngine
  File "c:\users\chris\pycharmprojects\webcrawler\venv\lib\site-packages\scrapy\core\engine.py", line 28, in <module>
    from scrapy.core.downloader import Downloader
  File "c:\users\chris\pycharmprojects\webcrawler\venv\lib\site-packages\scrapy\core\downloader\__init__.py", line 16, in <module>
    from scrapy.signalmanager import SignalManager
  File "c:\users\chris\pycharmprojects\webcrawler\venv\lib\site-packages\scrapy\signalmanager.py", line 6, in <module>
    from scrapy.utils import signal as _signal
  File "c:\users\chris\pycharmprojects\webcrawler\venv\lib\site-packages\scrapy\utils\signal.py", line 20, in <module>
    from scrapy.utils.log import failure_to_exc_info
  File "c:\users\chris\pycharmprojects\webcrawler\venv\lib\site-packages\scrapy\utils\log.py", line 26, in <module>
    from scrapy.utils.versions import scrapy_components_versions
  File "c:\users\chris\pycharmprojects\webcrawler\venv\lib\site-packages\scrapy\utils\versions.py", line 13, in <module>
    from scrapy.utils.ssl import get_openssl_version
  File "c:\users\chris\pycharmprojects\webcrawler\venv\lib\site-packages\scrapy\utils\ssl.py", line 3, in <module>
    import OpenSSL._util as pyOpenSSLutil
  File "c:\users\chris\pycharmprojects\webcrawler\venv\lib\site-packages\OpenSSL\__init__.py", line 8, in <module>
    from OpenSSL import SSL, crypto
  File "c:\users\chris\pycharmprojects\webcrawler\venv\lib\site-packages\OpenSSL\SSL.py", line 11, in <module>
    from OpenSSL._util import (
  File "c:\users\chris\pycharmprojects\webcrawler\venv\lib\site-packages\OpenSSL\_util.py", line 6, in <module>
    from cryptography.hazmat.bindings.openssl.binding import Binding
  File "c:\users\chris\pycharmprojects\webcrawler\venv\lib\site-packages\cryptography\hazmat\bindings\openssl\binding.py", line 15, in <module>
    from cryptography.exceptions import InternalError
  File "c:\users\chris\pycharmprojects\webcrawler\venv\lib\site-packages\cryptography\exceptions.py", line 9, in <module>
    from cryptography.hazmat.bindings._rust import exceptions as rust_exceptions
ImportError: DLL load failed while importing _rust: The specified procedure could not be found.

I upgraded OpenSSL to the latest but that did not solve the issue.

**Comment by alex** [comment]
Are you using windows 7?

**Comment by byteherder** [comment]
I am using Windows 10.

**Comment by alex** [comment]
What version of Python 3.9 are you using? Is it 3.9.0 or 3.9.1?

**Comment by byteherder** [comment]
Python 3.9.1 (tags/v3.9.1:1e5d33e, Dec  7 2020, 17:08:21) [MSC v.1927 64 bit (AMD64)] on win32

**Comment by alex** [comment]
Please try upgrading to a more recent Python 3.9, 3.9.1 had some issues.

**Comment by byteherder** [comment]
I'll try that. Thanks.

**Comment by byteherder** [comment]
I installed Python 3.9.13 and it solved the issue.

Issue solved.

**Comment by alex** [comment]
Great, glad to hear it.
