### ISSUE TITLE
Docker Build on ARMv7: _cffi_backend.cpython-313-arm-linux-musleabihf.so: _PyErr_WriteUnraisableMsg: symbol not found;  Cryptography-Cffi/build.rs:39:9 ; Error: Failed to Run Custom Build Command for Cryptography-Cffi v0.1.0 (/Tmp/Pip-Install[...]/Cryptography[...]/Src/Rust/Cryptography-Cffi) and Build-Script-Build Exit Status 101

### ISSUE THREAD

**Issue by ksaadDE** [pyca/cryptography#11349]
Hi,

I am currently upgrading a docker compose stack that **I've build and deployed and has been working just a month ago** (see Dockerfile V1, below)

The new version Dockerfile V2 (see blow) fails to build and shows the specified Rust error (more detail see below):
 - `/pip/buildwheel/[...]/src/Rust/Cryptography-Cffi)`
 - `Build-Script-Build [...] Exit Status 101 [...] Cryptography-Cffi/build.rs:39:9`
 - `[...] _cffi_backend.cpython-313-arm-linux-musleabihf.so: _PyErr_WriteUnraisableMsg: symbol not found`

How to fix this? **Armv7 is still around and required these days**, especially in private/uni projects. 

**Regarding the dependency hell**
I have managed to fix several other issues before. But it appears literally as dependency hell.  There is no progress on my side, only because that cryptography Rust dependency (despite being installed via apk and pip) breaks! The current dependency hell wastes multiple days to fix many simple, yet undocumented issues - with uncertain outcome.

I have no problem with Rust, in fact I love Rust. I appreciate the memory safety (mem safety) and that argument in #5771 but I rather prefer a simple and efficient way to build and install things in my spare time. 

# Docker Build Error Messages

## First Err Summary
```bash
error: failed to run custom build command for `cryptography-cffi v0.1.0 (/tmp/pip-install-gsjt3pd2/cryptography_b85e510a57f7475f8fa55b95626f6596/src/rust/cryptography-cffi)`
393.1
393.1       Caused by:
393.1         process didn't exit successfully: `/tmp/pip-install-gsjt3pd2/cryptography_b85e510a57f7475f8fa55b95626f6596/src/rust/target/release/build/cryptography-cffi-78fbfd6ef6e5c816/build-script-build` (exit status: 101)
393.1         --- stdout
393.1         cargo:rustc-check-cfg=cfg(python_implementation, values("CPython", "PyPy"))
393.1         cargo:rerun-if-env-changed=PYO3_PYTHON
393.1         cargo:rerun-if-changed=../../_cffi_src/
393.1         cargo:rerun-if-changed=../../cryptography/__about__.py
393.1
393.1         --- stderr
393.1         thread 'main' panicked at cryptography-cffi/build.rs:39:9:
393.1         failed to run build_openssl.py, stdout:
```

## 2nd Run Err Summary
```
248.7   Building wheel for cryptography (pyproject.toml): still running...
371.8   error: subprocess-exited-with-error
371.8
371.8   × Building wheel for cryptography (pyproject.toml) did not run successfully.
371.8   │ exit code: 1
371.8   ╰─> [79 lines of output]
371.8       Running `maturin pep517 build-wheel -i /usr/local/bin/python --compatibility off`
371.8       📦 Including license file "/tmp/pip-install-v698h_81/cryptography_1c37d73120e64095be91748fc4eab84d/LICENSE"
371.8       📦 Including license file "/tmp/pip-install-v698h_81/cryptography_1c37d73120e64095be91748fc4eab84d/LICENSE.APACHE"
371.8       📦 Including license file "/tmp/pip-install-v698h_81/cryptography_1c37d73120e64095be91748fc4eab84d/LICENSE.BSD"
371.8       🍹 Building a mixed python/rust project
371.8       🔗 Found pyo3 bindings with abi3 support for Python ≥ 3.7
371.8       🐍 Not using a specific python interpreter
371.8       📡 Using build options features, locked from pyproject.toml
371.8          Compiling proc-macro2 v1.0.86
371.8          Compiling target-lexicon v0.12.15
371.8          Compiling unicode-ident v1.0.12
371.8          Compiling cc v1.1.6
371.8          Compiling once_cell v1.19.0
371.8          Compiling vcpkg v0.2.15
371.8          Compiling pyo3-build-config v0.22.2
371.8          Compiling quote v1.0.36
371.8          Compiling pkg-config v0.3.30
371.8          Compiling syn v2.0.71
371.8          Compiling libc v0.2.155
371.8          Compiling openssl-sys v0.9.103
371.8          Compiling cfg-if v1.0.0
371.8          Compiling autocfg v1.3.0
371.8          Compiling pyo3-macros-backend v0.22.2
371.8          Compiling pyo3-ffi v0.22.2
371.8          Compiling memoffset v0.9.1
371.8          Compiling heck v0.5.0
371.8          Compiling foreign-types-shared v0.1.1
371.8          Compiling openssl v0.10.65
371.8          Compiling foreign-types v0.3.2
371.8          Compiling pyo3 v0.22.2
371.8          Compiling bitflags v2.6.0
371.8          Compiling indoc v2.0.5
371.8          Compiling unindent v0.2.3
371.8          Compiling cryptography-key-parsing v0.1.0 (/tmp/pip-install-v698h_81/cryptography_1c37d73120e64095be91748fc4eab84d/src/rust/cryptography-key-parsing)
371.8          Compiling cryptography-cffi v0.1.0 (/tmp/pip-install-v698h_81/cryptography_1c37d73120e64095be91748fc4eab84d/src/rust/cryptography-cffi)
371.8          Compiling cryptography-openssl v0.1.0 (/tmp/pip-install-v698h_81/cryptography_1c37d73120e64095be91748fc4eab84d/src/rust/cryptography-openssl)
371.8          Compiling cryptography-rust v0.1.0 (/tmp/pip-install-v698h_81/cryptography_1c37d73120e64095be91748fc4eab84d/src/rust)
371.8          Compiling base64 v0.22.1
371.8       error: failed to run custom build command for `cryptography-cffi v0.1.0 (/tmp/pip-install-v698h_81/cryptography_1c37d73120e64095be91748fc4eab84d/src/rust/cryptography-cffi)`
371.8
371.8       Caused by:
371.8         process didn't exit successfully: `/tmp/pip-install-v698h_81/cryptography_1c37d73120e64095be91748fc4eab84d/src/rust/target/release/build/cryptography-cffi-78fbfd6ef6e5c816/build-script-build` (exit status: 101)
371.8         --- stdout
371.8         cargo:rustc-check-cfg=cfg(python_implementation, values("CPython", "PyPy"))
371.8         cargo:rerun-if-env-changed=PYO3_PYTHON
371.8         cargo:rerun-if-changed=../../_cffi_src/
371.8         cargo:rerun-if-changed=../../cryptography/__about__.py
371.8
371.8         --- stderr
371.8         thread 'main' panicked at cryptography-cffi/build.rs:39:9:
371.8         failed to run build_openssl.py, stdout:
371.8
371.8         stderr:
371.8         Traceback (most recent call last):
371.8           File "/tmp/pip-install-v698h_81/cryptography_1c37d73120e64095be91748fc4eab84d/src/rust/cryptography-cffi/../../_cffi_src/build_openssl.py", line 18, in <module>
371.8             ffi = build_ffi_for_binding(
371.8                 module_name="_openssl",
371.8             ...<25 lines>...
371.8                 ],
371.8             )
371.8           File "/tmp/pip-install-v698h_81/cryptography_1c37d73120e64095be91748fc4eab84d/src/rust/cryptography-cffi/../../_cffi_src/utils.py", line 49, in build_ffi_for_binding
371.8             return build_ffi(
371.8                 module_name,
371.8                 cdef_source="\n".join(types + functions),
371.8                 verify_source=verify_source,
371.8             )
371.8           File "/tmp/pip-install-v698h_81/cryptography_1c37d73120e64095be91748fc4eab84d/src/rust/cryptography-cffi/../../_cffi_src/utils.py", line 61, in build_ffi
371.8             ffi = FFI()
371.8           File "/tmp/pip-build-env-08iz9nt1/overlay/lib/python3.13/site-packages/cffi/api.py", line 48, in __init__
371.8             import _cffi_backend as backend
371.8         ImportError: Error relocating /tmp/pip-build-env-08iz9nt1/overlay/lib/python3.13/site-packages/_cffi_backend.cpython-313-arm-linux-musleabihf.so: _PyErr_WriteUnraisableMsg: symbol not found
371.8
371.8
371.8         note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
371.8       warning: build failed, waiting for other jobs to finish...
371.8       💥 maturin failed
371.8         Caused by: Failed to build a native library through cargo
371.8         Caused by: Cargo build finished with "exit status: 101": `env -u CARGO CARGO_ENCODED_RUSTFLAGS="-C\u{1f}target-feature=-crt-static" PYO3_ENVIRONMENT_SIGNATURE="cpython-3.13-64bit" PYO3_PYTHON="/usr/local/bin/python" PYTHON_SYS_EXECUTABLE="/usr/local/bin/python" "cargo" "rustc" "--features" "pyo3/abi3-py37" "--message-format" "json-render-diagnostics" "--locked" "--manifest-path" "/tmp/pip-install-v698h_81/cryptography_1c37d73120e64095be91748fc4eab84d/src/rust/Cargo.toml" "--release" "--lib"`
371.8       Error: command ['maturin', 'pep517', 'build-wheel', '-i', '/usr/local/bin/python', '--compatibility', 'off'] returned non-zero exit status 1
371.8       [end of output]
371.8
371.8   note: This error originates from a subprocess, and is likely not a problem with pip.
371.8   ERROR: Failed building wheel for cryptography
371.8 Failed to build cryptography
371.8 ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (cryptography)
```

## 3rd Run Summary With the Cffi and RUST_BACKTRACE Flag
```
=> CACHED [nkhub 12/26] RUN pip3 install cffi                                                                                                                                           0.0s
=> ERROR [nkhub 13/26] RUN RUST_BACKTRACE=1 pip3 install cryptography                                                                                                                 282.3s
------
> [nkhub 13/26] RUN RUST_BACKTRACE=1 pip3 install cryptography:
11.53 Collecting cryptography
11.88   Downloading cryptography-43.0.0.tar.gz (686 kB)
12.24      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 686.9/686.9 kB 2.1 MB/s eta 0:00:00
13.85   Installing build dependencies: started
49.57   Installing build dependencies: finished with status 'done'
49.58   Getting requirements to build wheel: started
50.28   Getting requirements to build wheel: finished with status 'done'
50.29   Preparing metadata (pyproject.toml): started
62.83   Preparing metadata (pyproject.toml): finished with status 'done'
62.95 Requirement already satisfied: cffi>=1.12 in /usr/local/lib/python3.13/site-packages (from cryptography) (1.16.0)
62.97 Requirement already satisfied: pycparser in /usr/local/lib/python3.13/site-packages (from cffi>=1.12->cryptography) (2.22)
62.99 Building wheels for collected packages: cryptography
63.00   Building wheel for cryptography (pyproject.toml): started
135.0   Building wheel for cryptography (pyproject.toml): still running...
201.4   Building wheel for cryptography (pyproject.toml): still running...
278.7   Building wheel for cryptography (pyproject.toml): still running...
278.8   Building wheel for cryptography (pyproject.toml): finished with status 'error'
279.0   error: subprocess-exited-with-error
279.0
279.0   × Building wheel for cryptography (pyproject.toml) did not run successfully.
279.0   │ exit code: 1
279.0   ╰─> [85 lines of output]
279.0       Running `maturin pep517 build-wheel -i /usr/local/bin/python --compatibility off`
279.0       📦 Including license file "/tmp/pip-install-_nsz_h6q/cryptography_53f4bbad0ac94d4ab16476d6c0ebe8b2/LICENSE"
279.0       📦 Including license file "/tmp/pip-install-_nsz_h6q/cryptography_53f4bbad0ac94d4ab16476d6c0ebe8b2/LICENSE.APACHE"
279.0       📦 Including license file "/tmp/pip-install-_nsz_h6q/cryptography_53f4bbad0ac94d4ab16476d6c0ebe8b2/LICENSE.BSD"
279.0       🍹 Building a mixed python/rust project
279.0       🔗 Found pyo3 bindings with abi3 support for Python ≥ 3.7
279.0       🐍 Not using a specific python interpreter
279.0       📡 Using build options features, locked from pyproject.toml
279.0          Compiling target-lexicon v0.12.15
279.0          Compiling proc-macro2 v1.0.86
279.0          Compiling unicode-ident v1.0.12
279.0          Compiling cc v1.1.6
279.0          Compiling vcpkg v0.2.15
279.0          Compiling pyo3-build-config v0.22.2
279.0          Compiling quote v1.0.36
279.0          Compiling syn v2.0.71
279.0          Compiling once_cell v1.19.0
279.0          Compiling pkg-config v0.3.30
279.0          Compiling libc v0.2.155
279.0          Compiling openssl-sys v0.9.103
279.0          Compiling cfg-if v1.0.0
279.0          Compiling autocfg v1.3.0
279.0          Compiling pyo3-ffi v0.22.2
279.0          Compiling pyo3-macros-backend v0.22.2
279.0          Compiling foreign-types-shared v0.1.1
279.0          Compiling heck v0.5.0
279.0          Compiling memoffset v0.9.1
279.0          Compiling openssl v0.10.65
279.0          Compiling foreign-types v0.3.2
279.0          Compiling pyo3 v0.22.2
279.0          Compiling bitflags v2.6.0
279.0          Compiling indoc v2.0.5
279.0          Compiling unindent v0.2.3
279.0          Compiling cryptography-key-parsing v0.1.0 (/tmp/pip-install-_nsz_h6q/cryptography_53f4bbad0ac94d4ab16476d6c0ebe8b2/src/rust/cryptography-key-parsing)
279.0          Compiling cryptography-cffi v0.1.0 (/tmp/pip-install-_nsz_h6q/cryptography_53f4bbad0ac94d4ab16476d6c0ebe8b2/src/rust/cryptography-cffi)
279.0          Compiling cryptography-openssl v0.1.0 (/tmp/pip-install-_nsz_h6q/cryptography_53f4bbad0ac94d4ab16476d6c0ebe8b2/src/rust/cryptography-openssl)
279.0          Compiling cryptography-rust v0.1.0 (/tmp/pip-install-_nsz_h6q/cryptography_53f4bbad0ac94d4ab16476d6c0ebe8b2/src/rust)
279.0          Compiling base64 v0.22.1
279.0       error: failed to run custom build command for `cryptography-cffi v0.1.0 (/tmp/pip-install-_nsz_h6q/cryptography_53f4bbad0ac94d4ab16476d6c0ebe8b2/src/rust/cryptography-cffi)`
279.0       note: To improve backtraces for build dependencies, set the CARGO_PROFILE_RELEASE_BUILD_OVERRIDE_DEBUG=true environment variable to enable debug information generation.
279.0
279.0       Caused by:
279.0         process didn't exit successfully: `/tmp/pip-install-_nsz_h6q/cryptography_53f4bbad0ac94d4ab16476d6c0ebe8b2/src/rust/target/release/build/cryptography-cffi-78fbfd6ef6e5c816/build-script-build` (exit status: 101)
279.0         --- stdout
279.0         cargo:rustc-check-cfg=cfg(python_implementation, values("CPython", "PyPy"))
279.0         cargo:rerun-if-env-changed=PYO3_PYTHON
279.0         cargo:rerun-if-changed=../../_cffi_src/
279.0         cargo:rerun-if-changed=../../cryptography/__about__.py
279.0
279.0         --- stderr
279.0         thread 'main' panicked at cryptography-cffi/build.rs:39:9:
279.0         failed to run build_openssl.py, stdout:
279.0
279.0         stderr:
279.0         Traceback (most recent call last):
279.0           File "/tmp/pip-install-_nsz_h6q/cryptography_53f4bbad0ac94d4ab16476d6c0ebe8b2/src/rust/cryptography-cffi/../../_cffi_src/build_openssl.py", line 18, in <module>
279.0             ffi = build_ffi_for_binding(
279.0                 module_name="_openssl",
279.0             ...<25 lines>...
279.0                 ],
279.0             )
279.0           File "/tmp/pip-install-_nsz_h6q/cryptography_53f4bbad0ac94d4ab16476d6c0ebe8b2/src/rust/cryptography-cffi/../../_cffi_src/utils.py", line 49, in build_ffi_for_binding
279.0             return build_ffi(
279.0                 module_name,
279.0                 cdef_source="\n".join(types + functions),
279.0                 verify_source=verify_source,
279.0             )
279.0           File "/tmp/pip-install-_nsz_h6q/cryptography_53f4bbad0ac94d4ab16476d6c0ebe8b2/src/rust/cryptography-cffi/../../_cffi_src/utils.py", line 61, in build_ffi
279.0             ffi = FFI()
279.0           File "/tmp/pip-build-env-2kvnmqfs/overlay/lib/python3.13/site-packages/cffi/api.py", line 48, in __init__
279.0             import _cffi_backend as backend
279.0         ImportError: Error relocating /tmp/pip-build-env-2kvnmqfs/overlay/lib/python3.13/site-packages/_cffi_backend.cpython-313-arm-linux-musleabihf.so: _PyErr_WriteUnraisableMsg: symbol not found
279.0
279.0
279.0         stack backtrace:
279.0            0: rust_begin_unwind
279.0            1: core::panicking::panic_fmt
279.0            2: build_script_build::main
279.0            3: core::ops::function::FnOnce::call_once
279.0         note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
279.0       warning: build failed, waiting for other jobs to finish...
279.0       💥 maturin failed
279.0         Caused by: Failed to build a native library through cargo
279.0         Caused by: Cargo build finished with "exit status: 101": `env -u CARGO CARGO_ENCODED_RUSTFLAGS="-C\u{1f}target-feature=-crt-static" PYO3_ENVIRONMENT_SIGNATURE="cpython-3.13-64bit" PYO3_PYTHON="/usr/local/bin/python" PYTHON_SYS_EXECUTABLE="/usr/local/bin/python" "cargo" "rustc" "--features" "pyo3/abi3-py37" "--message-format" "json-render-diagnostics" "--locked" "--manifest-path" "/tmp/pip-install-_nsz_h6q/cryptography_53f4bbad0ac94d4ab16476d6c0ebe8b2/src/rust/Cargo.toml" "--release" "--lib"`
279.0       Error: command ['maturin', 'pep517', 'build-wheel', '-i', '/usr/local/bin/python', '--compatibility', 'off'] returned non-zero exit status 1
279.0       [end of output]
279.0
279.0   note: This error originates from a subprocess, and is likely not a problem with pip.
279.0   ERROR: Failed building wheel for cryptography
279.0 Failed to build cryptography
279.0 ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (cryptography)
------
failed to solve: process "/bin/sh -c RUST_BACKTRACE=1 pip3 install cryptography" did not complete successfully: exit code: 1
```

# Old _working_ And _successful_ Dockerfile and Cryptography Build From a Month Ago (V1)

```Dockerfile
FROM arm32v7/python:3.12-rc-alpine3.18

RUN apk add openssl-dev musl-dev
RUN apk add --no-cache --virtual=build-dependencies build-base cargo libffi-dev python3-dev
RUN apk add gcc g++ make libffi-dev openssl-dev
RUN apk add python3-dev build-base --update-cache
RUN apk add --no-cache gcc libffi python3
RUN python3 -m ensurepip
RUN pip3 install -U --no-cache-dir pip wheel
RUN pip3 install cryptography

# Create a user
#RUN useradd -ms /bin/bash quart

RUN adduser -D quart

# Set working directory for the purpose of this Dockerfile
WORKDIR /home/quart

# Copy requirements to the app root
COPY app/requirements.txt ./

RUN rm -rf /var/cache/apk/*

# Create a virtual environment and install the dependecies
RUN pip3 install --no-cache-dir -r requirements.txt

RUN chown -R quart:quart ./

# Copy the app into our user root
COPY app/ /home/quart/

# Make our entrypoint executable
VOLUME /home/quart/app
RUN chown quart:quart /home/quart/app
RUN chown quart:quart /home/quart/app/*.*
RUN chmod 755 /home/quart/app
RUN chown -R quart:quart ./

RUN echo "**** cleanup ****" && \
apk del --purge \
build-dependencies && \
rm -rf \
/tmp/* \
$HOME/.cache \
$HOME/.cargo

# Set the user
USER quart
# Set the entrypoint

#ENTRYPOINT ["sh", "./boot.sh"]
CMD ["hypercorn", "-b", "0.0.0.0:5000", "main:app"]

```
Just built time is about 1000 seconds (without caching). I've copy pasted and engineered it for two days - a real hassle.

# Failing, Newer Version of My Dockerfile Where Cryptography Build Fails (V2)
```Dockerfile
FROM arm32v7/python:3.13-rc-alpine3.20
#:3.12-rc-alpine3.18

# added --no-cache

RUN apk update --no-cache
RUN apk add --no-cache openssl-dev musl-dev
RUN apk add --no-cache --virtual=build-dependencies build-base cargo libffi-dev python3-dev
RUN apk add --no-cache gcc g++ make libffi-dev openssl-dev
RUN apk add --no-cache python3-dev build-base --update-cache
RUN apk add --no-cache gcc libffi python3
RUN apk add --no-cache libc-dev linux-headers libffi-dev
RUN python3 -m ensurepip
RUN pip3 install --upgrade pip
RUN pip3 install -U --no-cache-dir pip wheel
RUN pip3 install cryptography

RUN rm /var/cache/apk/* -r # add

# Create a user
#RUN useradd -ms /bin/bash quart

RUN adduser -D quart

# Set working directory for the purpose of this Dockerfile
WORKDIR /home/quart

# Copy requirements to the app root
COPY app/requirements.txt ./

RUN rm -rf /var/cache/apk/*

# Create a virtual environment and install the dependecies
RUN pip3 install --no-cache-dir -r requirements.txt

RUN chown -R quart:quart ./

# Copy the app into our user root
COPY app/ /home/quart/

# Make our entrypoint executable
VOLUME /home/quart/app
RUN chown quart:quart /home/quart/app
RUN chown quart:quart /home/quart/app/*.*
RUN chmod 755 /home/quart/app
RUN chown -R quart:quart ./

RUN echo "**** cleanup ****" && \
apk del --purge \
build-dependencies && \
rm -rf \
/tmp/* \
$HOME/.cache \
$HOME/.cargo

# Set the user
USER quart
# Set the entrypoint

#ENTRYPOINT ["sh", "./boot.sh"]
CMD ["hypercorn", "-b", "0.0.0.0:5000", "main:app"]
```

# Unchanged requirements.txt

```requirements.txt
requests
asyncio
quart
pycryptodome
pbkdf2
cryptography
```

# How to Build

I am using the docker compose build command, as it's a docker compose stack
```bash
screen -L docker compose build (--no-cache)
```

works too by only using docker build (for a single container) 
```
docker build (--no-cache)
```

# Tried Solutions

- RUN pip3 upgrade
- RUN apk add libffi-dev
- RUN pip3 install libffi-dev (adds additional 130.8s to the build!)

# Observed Issues of Both Dockerfiles
Due to the limited nature of armv7 there are a few main issues with these docker files as Cryptography pip install is resource intensive. The rust build and pip install cryptography (toml wheels etc) can **exhaust ALL resources**, whether it be CPU or Memory (memory exhaustion). More-likely it just runs for 1000s and then reports a EOF, indicating a **timeout** (especially the first one). Sometimes it works, sometimes not. Rather new issue is the cargo, rust and cryptography code **dependency hell**.

**Comment by alex** [comment]
You appear to be using Python 3.13, which isn't yet supported. In particularly, you're encountering that cffi does not yet have a release which supports Python 3.13: https://github.com/python-cffi/cffi/issues/71

There's no action for us to take at this juncture besides patience.

**Comment by ksaadDE** [comment]
@alex Thank you very much for this insane fast reply! 

I did not think of that possibility. Probably due to  the previous negative experiences with the cryptography setup.

If I am allowed to I would recommend to keep it open until https://github.com/python-cffi/cffi/issues/71 is solved, in case others will open issues regarding this. Maybe you can give a warning or information into changelog or somewhere where it's visible, pretty sure others will try this too.

I will stick with the old Dockerfile until the issue is resolved.

**Comment by alex** [comment]
We have #9722 open to test this as soon as we can, but there's nothing to say or discuss here, so there's little value in an issue. (Particularly given that even with an open issue, we get a ton of dupes.)

**Comment by ksaadDE** [comment]
Nw, still thank you very much! I will keep looking into it, or if you recall this issue just ping me when you roll out a stable py 3.13 version, so I can upgrade and test.
