### ISSUE TITLE
pyinstaller & py2app fail to import all cryptography libraries/backend components

### ISSUE THREAD

**Issue by douglasmccormickjr** [pyca/cryptography#1338]
After running my program (compiled either by pyinstaller or py2app) and getting to an internal step that uses the cryptography module (I'm using the Fernet piece), here's my error:

+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Traceback (most recent call last):
  File "<string>", line 4162, in <module>
  File "<string>", line 1281, in get_my_demo_account
  File "<string>", line 1223, in get_comparisonkey
  File "/Users/douglasmccormickjr/Downloads/pyinstaller-pyinstaller-91b490a/ATDD_270_mac/build/ATDD_270_mac/out00-PYZ.pyz/cryptography.fernet", line 41, in **init**
  File "/Users/douglasmccormickjr/Downloads/pyinstaller-pyinstaller-91b490a/ATDD_270_mac/build/ATDD_270_mac/out00-PYZ.pyz/cryptography.hazmat.backends", line 52, in default_backend
  File "/Users/douglasmccormickjr/Downloads/pyinstaller-pyinstaller-91b490a/ATDD_270_mac/build/ATDD_270_mac/out00-PYZ.pyz/cryptography.hazmat.backends", line 35, in _available_backends
  File "/Users/douglasmccormickjr/Downloads/pyinstaller-pyinstaller-91b490a/PyInstaller/loader/pyi_importers.py", line 270, in load_module
    exec(bytecode, module.__dict__)
  File "/Users/douglasmccormickjr/Downloads/pyinstaller-pyinstaller-91b490a/ATDD_270_mac/build/ATDD_270_mac/out00-PYZ.pyz/cryptography.hazmat.backends.commoncrypto", line 16, in <module>
  File "/Users/douglasmccormickjr/Downloads/pyinstaller-pyinstaller-91b490a/PyInstaller/loader/pyi_importers.py", line 270, in load_module
    exec(bytecode, module.**dict**)
  File "/Users/douglasmccormickjr/Downloads/pyinstaller-pyinstaller-91b490a/ATDD_270_mac/build/ATDD_270_mac/out00-PYZ.pyz/cryptography.hazmat.backends.commoncrypto.backend", line 253, in <module>
  File "/Users/douglasmccormickjr/Downloads/pyinstaller-pyinstaller-91b490a/ATDD_270_mac/build/ATDD_270_mac/out00-PYZ.pyz/cryptography.hazmat.backends.commoncrypto.backend", line 53, in **init**
  File "/Users/douglasmccormickjr/Downloads/pyinstaller-pyinstaller-91b490a/ATDD_270_mac/build/ATDD_270_mac/out00-PYZ.pyz/cryptography.hazmat.bindings.commoncrypto.binding", line 44, in **init**
  File "/Users/douglasmccormickjr/Downloads/pyinstaller-pyinstaller-91b490a/ATDD_270_mac/build/ATDD_270_mac/out00-PYZ.pyz/cryptography.hazmat.bindings.commoncrypto.binding", line 54, in _ensure_ffi_initialized
  File "/Users/douglasmccormickjr/Downloads/pyinstaller-pyinstaller-91b490a/ATDD_270_mac/build/ATDD_270_mac/out00-PYZ.pyz/cryptography.hazmat.bindings.utils", line 47, in build_ffi
ImportError: No module named cf
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

Packaging works fine on Windows but fails miserably on OSX (despite my best efforts to import everything manually) -- I'll need to rip out my cryptography code and use a library/module that wont fail.

Also getting cryptography installed on OSX (without using Conda) is problematic as well.  I was getting into issues with "clang" -- not sure what that was about.  I hope someone can fix this library for the OSX environment.

**Comment by LipuFei** [comment]
@douglasmccormickjr @alex I am having the same issue here using `py2app`. I tries with both `python-cryptography` 0.7 and 0.8 but they didn't work. The problems I have are as follows:

1. The dynamically loaded `.h` and `.c` files. `py2app` will not pack those files into the package. This can be temporarily solved by copy-pasting the contents from `.h` and `.c` into the corresponding `.py` files so the missing C files do not matter any more.
2. The `commoncrypto` and `openssl` modules in `backends` and `bindings`. `py2app` does not pack all of them into the package as well. I think it's because that in `python-cryptography`, those modules are not directly referred to or imported, so `py2app` doesn't take them into account as dependencies. This issue can be temporarily solved by specifically naming those missing modules in the `py2app` setup script.
3. RuntimeError "Attempted implicit compile of a cffi module. All cffi modules should be pre-compiled at installation time." After I had done (1) and (2), I started having this trouble. I still have no solution yet because I don't know why the modules that are packed by `py2app` are not compiled.

@alex My system is Mac 10.9. Everything works fine except the `py2app` packaging part. I am wondering if you could help with this? Thanks!

**Comment by maxvt** [comment]
@LipuFei If you have recently installed or upgraded xcode, you might need to run `xcode-select --install` in a terminal to create the correct links for the command line tools to work. 

If you don't have a `/usr/include` folder on your machine, this is a likely reason for this error.

**Comment by reaperhulk** [comment]
See #2039
