### ISSUE TITLE
UnicodeDecodeError while installing with pip

### ISSUE THREAD

**Issue by osakaaa** [pyca/cryptography#1625]
Trying to install latest (0.7.1 i suppose) cryptography module with pip install cryptography 

Get the following error:
```
distutils.errors.DistutilsError: Setup script exited with error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

----------------------------------------
Cleaning up...
Command /usr/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip_build_root/cryptography/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-IuAPaz-record/install-record.txt --single-version-externally-managed --compile failed with error code 1 in /tmp/pip_build_root/cryptography
Traceback (most recent call last):
  File "/usr/bin/pip", line 9, in <module>
    load_entry_point('pip==1.5.4', 'console_scripts', 'pip')()
  File "/usr/lib/python2.7/dist-packages/pip/__init__.py", line 185, in main
    return command.main(cmd_args)
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 161, in main
    text = '\n'.join(complete_log)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xd0 in position 49: ordinal not in range(128)
```

**Comment by alex** [comment]
I think this is actually a pip bug? /cc @dstufft

**Comment by dstufft** [comment]
Yea, and it should be fixed in pip 6+

**Comment by alex** [comment]
@osakaaa Can you upgrade to pip 6 and let us know what the result is?

**Comment by osakaaa** [comment]
@alex  @dstufft Yep, pip 6.1 solved the problem, thanks and sorry for wrong issue
