### ISSUE TITLE
Error in Installation for Windows Python - cryptography-0.8.1

### ISSUE THREAD

**Issue by duytrung** [pyca/cryptography#1771]
```
C:\Users\eep1>pip install -U cryptography
Collecting cryptography from https://pypi.python.org/packages/cp27/c/cryptography/cryptography-0.8.1-cp27-none-win32.whl
#md5=866615b382b2bf77a871e61d7e8a1fff
  Downloading cryptography-0.8.1-cp27-none-win32.whl (961kB)
    100% |################################| 962kB 221kB/s
Requirement already up-to-date: six>=1.4.1 in c:\python\lib\site-packages (from cryptography)
Requirement already up-to-date: enum34 in c:\python\lib\site-packages (from cryptography)
Requirement already up-to-date: cffi>=0.8 in c:\python\lib\site-packages (from cryptography)
Requirement already up-to-date: setuptools in c:\python\lib\site-packages (from cryptography)
Requirement already up-to-date: pyasn1 in c:\python\lib\site-packages (from cryptography)
Requirement already up-to-date: pycparser in c:\python\lib\site-packages (from cffi>=0.8->cryptography)
Installing collected packages: cryptography
  Found existing installation: cryptography 0.8
    Uninstalling cryptography-0.8:
      Successfully uninstalled cryptography-0.8

  Exception:
  Traceback (most recent call last):
    File "c:\Python\lib\site-packages\pip\basecommand.py", line 232, in main
      status = self.run(options, args)
    File "c:\Python\lib\site-packages\pip\commands\install.py", line 347, in run
      root=options.root_path,
    File "c:\Python\lib\site-packages\pip\req\req_set.py", line 560, in install
      requirement.commit_uninstall()
    File "c:\Python\lib\site-packages\pip\req\req_install.py", line 680, in commit_uninstall
      self.uninstalled.commit()
    File "c:\Python\lib\site-packages\pip\req\req_uninstall.py", line 153, in commit
      rmtree(self.save_dir)
    File "c:\Python\lib\site-packages\pip\_vendor\retrying.py", line 49, in wrapped_f
      return Retrying(*dargs, **dkw).call(f, *args, **kw)
    File "c:\Python\lib\site-packages\pip\_vendor\retrying.py", line 212, in call
      raise attempt.get()
    File "c:\Python\lib\site-packages\pip\_vendor\retrying.py", line 247, in get
      six.reraise(self.value[0], self.value[1], self.value[2])
    File "c:\Python\lib\site-packages\pip\_vendor\retrying.py", line 200, in call
      attempt = Attempt(fn(*args, **kwargs), attempt_number, False)
    File "c:\Python\lib\site-packages\pip\utils\__init__.py", line 61, in rmtree
      onerror=rmtree_errorhandler)
    File "c:\Python\lib\shutil.py", line 247, in rmtree
      rmtree(fullname, ignore_errors, onerror)
    File "c:\Python\lib\shutil.py", line 247, in rmtree
      rmtree(fullname, ignore_errors, onerror)
    File "c:\Python\lib\shutil.py", line 247, in rmtree
      rmtree(fullname, ignore_errors, onerror)
    File "c:\Python\lib\shutil.py", line 247, in rmtree
      rmtree(fullname, ignore_errors, onerror)
    File "c:\Python\lib\shutil.py", line 252, in rmtree
      onerror(os.remove, fullname, sys.exc_info())
    File "c:\Python\lib\site-packages\pip\utils\__init__.py", line 73, in rmtree_errorhandler
      func(path)
  WindowsError: [Error 5] Access is denied: 'c:\\users\\eep1\\appdata\\local\\temp\\pip-ld4_uy-uninstall\\python\\lib\\s
ite-packages\\cryptography\\_cryptography_cffi_f3e4673fx399b1113.pyd'
```

**Comment by reaperhulk** [comment]
The access denied error suggests this probably isn't a cryptography problem, but what happens if you `pip install cryptography==0.8`?

**Comment by reaperhulk** [comment]
Closing due to lack of activity.

**Comment by QyonCheesecat** [comment]
Same problem here:
> pkg_resources.ExtractionError: Can't extract file(s) to egg cache
> 
> The following error occurred while trying to extract file(s) to the Python egg
> cache:
> 
>   [Error 5] Odmowa dost?pu: 'C:\\Users\\Qyon\\AppData\\Roaming\\Python-Eggs\\pyopenssl-0.13.1-py2.7-win32.egg-tmp\\OpenSSL\\crypto.pyd'
> 
> The Python egg cache directory is currently set to:
> 
>   C:\Users\Qyon\AppData\Roaming\Python-Eggs

**Comment by reaperhulk** [comment]
@QyonCheesecat that error lists pyopenssl 0.13.1, which did not use cryptography (the project this issue is under). I'm not sure what the problem is, but it's definitely not related to this project, sorry :cry:

**Comment by QyonCheesecat** [comment]
Ups. My mistake. Sorry!

**Comment by darkmorpher** [comment]
Similar error to @duytrung for every time I update cryptography

Log: http://paste.is/12871/22134714/raw/

**Comment by reaperhulk** [comment]
@darkmorpher that looks like a pip issue. Upgrade to the latest and if you still see that happening file an issue with pip

**Comment by darkmorpher** [comment]
@reaperhulk Was already using pip 8.0.2
