### ISSUE TITLE
python setup.py fails on AIX 5.3

### ISSUE THREAD

**Issue by pottmi** [pyca/cryptography#1900]
This is error I receive when trying to install cryptography-0.8.2 on aix 5.3:

```
# ksh ./install.ksh
"_configtest.c", line 1.1: 1506-731 (S) The '__thread' keyword is not supported on the target platform.  The keyword is ignored.
Note: will not use '__thread' in the C code
The above error message can be safely ignored
"/usr/include/alloca.h", line 34.1: 1506-224 (I) Incorrect pragma ignored.
"c/_cffi_backend.c", line 5665.15: 1506-068 (W) Operation between types "void*" and "char(*)(char,char)" is not allowed.
"c/_cffi_backend.c", line 5666.15: 1506-068 (W) Operation between types "void*" and "long(*)(int,long)" is not allowed.
"c/_cffi_backend.c", line 5667.15: 1506-068 (W) Operation between types "void*" and "long long(*)(long long,long long)" is not allowed.
"c/_cffi_backend.c", line 5668.15: 1506-068 (W) Operation between types "void*" and "double(*)(float,double)" is not allowed.
"c/_cffi_backend.c", line 5669.15: 1506-068 (W) Operation between types "void*" and "float(*)(float,double)" is not allowed.
"c/_cffi_backend.c", line 5670.15: 1506-068 (W) Operation between types "void*" and "void(*)(void)" is not allowed.
"c/_cffi_backend.c", line 5671.15: 1506-068 (W) Operation between types "void*" and "int*(*)(int*)" is not allowed.
"c/_cffi_backend.c", line 5672.15: 1506-068 (W) Operation between types "void*" and "short(*)(struct _testfunc7_s)" is not allowed.
"c/_cffi_backend.c", line 5674.15: 1506-068 (W) Operation between types "void*" and "int(*)(int,...)" is not allowed.
"c/_cffi_backend.c", line 5675.16: 1506-068 (W) Operation between types "void*" and "struct _testfunc7_s(*)(int)" is not allowed.
"c/_cffi_backend.c", line 5676.16: 1506-068 (W) Operation between types "void*" and "struct _testfunc11_s(*)(int)" is not allowed.
"c/_cffi_backend.c", line 5677.16: 1506-068 (W) Operation between types "void*" and "struct _testfunc12_s(*)(int)" is not allowed.
"c/_cffi_backend.c", line 5678.16: 1506-068 (W) Operation between types "void*" and "struct _testfunc13_s(*)(int)" is not allowed.
"c/_cffi_backend.c", line 5679.16: 1506-068 (W) Operation between types "void*" and "struct _testfunc14_s(*)(int)" is not allowed.
"c/_cffi_backend.c", line 5680.16: 1506-068 (W) Operation between types "void*" and "struct _testfunc15_s(*)(int)" is not allowed.
"c/_cffi_backend.c", line 5681.16: 1506-068 (W) Operation between types "void*" and "struct _testfunc16_s(*)(int)" is not allowed.
"c/_cffi_backend.c", line 5682.16: 1506-068 (W) Operation between types "void*" and "struct _testfunc17_s(*)(int)" is not allowed.
"c/_cffi_backend.c", line 5683.16: 1506-068 (W) Operation between types "void*" and "int(*)(struct _testfunc17_s*)" is not allowed.
"c/_cffi_backend.c", line 5684.16: 1506-068 (W) Operation between types "void*" and "long double(*)(long double,int)" is not allowed.
"c/_cffi_backend.c", line 5685.16: 1506-068 (W) Operation between types "void*" and "short(*)(struct _testfunc7_s*)" is not allowed.
"c/_cffi_backend.c", line 5686.16: 1506-068 (W) Operation between types "void*" and "int(*)(struct _testfunc21_s)" is not allowed.
"c/_cffi_backend.c", line 5687.16: 1506-068 (W) Operation between types "void*" and "struct _testfunc22_s(*)(struct _testfunc22_s,struct _testfunc22_s)" is not allowed.
"c/_cffi_backend.c", line 5688.16: 1506-068 (W) Operation between types "void*" and "int(*)(char*)" is not allowed.
"c/_cffi_backend.c", line 5906.5: 1506-196 (W) Initialization between types "void*" and "int(*)(struct _object*)" is not allowed.
"c/_cffi_backend.c", line 5907.5: 1506-196 (W) Initialization between types "void*" and "int(*)(struct _object*)" is not allowed.
"c/_cffi_backend.c", line 5908.5: 1506-196 (W) Initialization between types "void*" and "int(*)(struct _object*)" is not allowed.
"c/_cffi_backend.c", line 5909.5: 1506-196 (W) Initialization between types "void*" and "int(*)(struct _object*)" is not allowed.
"c/_cffi_backend.c", line 5910.5: 1506-196 (W) Initialization between types "void*" and "int(*)(struct _object*)" is not allowed.
"c/_cffi_backend.c", line 5911.5: 1506-196 (W) Initialization between types "void*" and "unsigned int(*)(struct _object*)" is not allowed.
"c/_cffi_backend.c", line 5912.5: 1506-196 (W) Initialization between types "void*" and "long long(*)(struct _object*)" is not allowed.
"c/_cffi_backend.c", line 5913.5: 1506-196 (W) Initialization between types "void*" and "unsigned long long(*)(struct _object*)" is not allowed.
"c/_cffi_backend.c", line 5914.5: 1506-196 (W) Initialization between types "void*" and "int(*)(struct _object*)" is not allowed.
"c/_cffi_backend.c", line 5915.5: 1506-196 (W) Initialization between types "void*" and "struct _object*(*)(char*,struct _ctypedescr*)" is not allowed.
"c/_cffi_backend.c", line 5916.5: 1506-196 (W) Initialization between types "void*" and "char*(*)(struct _object*,struct _ctypedescr*)" is not allowed.
"c/_cffi_backend.c", line 5917.5: 1506-196 (W) Initialization between types "void*" and "struct _object*(*)(long*)" is not allowed.
"c/_cffi_backend.c", line 5918.5: 1506-196 (W) Initialization between types "void*" and "void(*)(void)" is not allowed.
"c/_cffi_backend.c", line 5919.5: 1506-196 (W) Initialization between types "void*" and "void(*)(void)" is not allowed.
"c/_cffi_backend.c", line 5920.5: 1506-196 (W) Initialization between types "void*" and "struct _object*(*)(char)" is not allowed.
"c/_cffi_backend.c", line 5921.5: 1506-196 (W) Initialization between types "void*" and "struct _object*(*)(char*,struct _ctypedescr*)" is not allowed.
"c/_cffi_backend.c", line 5922.5: 1506-196 (W) Initialization between types "void*" and "int(*)(char*,struct _ctypedescr*,struct _object*)" is not allowed.
"c/_cffi_backend.c", line 5923.5: 1506-196 (W) Initialization between types "void*" and "struct _object*(*)(char*,struct _ctypedescr*)" is not allowed.
"c/_cffi_backend.c", line 5925.5: 1506-196 (W) Initialization between types "void*" and "unsigned short(*)(struct _object*)" is not allowed.
"c/_cffi_backend.c", line 5926.5: 1506-196 (W) Initialization between types "void*" and "struct _object*(*)(unsigned short)" is not allowed.
"c/_cffi_backend.c", line 5931.5: 1506-196 (W) Initialization between types "void*" and "long double(*)(struct _object*)" is not allowed.
"c/_cffi_backend.c", line 5932.5: 1506-196 (W) Initialization between types "void*" and "_Bool(*)(struct _object*)" is not allowed.
"c/_cffi_backend.c", line 5933.5: 1506-196 (W) Initialization between types "void*" and "long(*)(struct _ctypedescr*,struct _object*,char**)" is not allowed.
"c/_cffi_backend.c", line 5934.5: 1506-196 (W) Initialization between types "void*" and "int(*)(char*,struct _ctypedescr*,struct _object*)" is not allowed.
"c/_cffi_backend.c", line 5935.5: 1506-196 (W) Initialization between types "void*" and "struct _object*(*)(char*,const struct _cffi_type_context_s*)" is not allowed.
unable to execute ./Modules/ld_so_aix: No such file or directory
Traceback (most recent call last):
  File "setup.py", line 342, in <module>
    **keywords_with_side_effects(sys.argv)
  File "/opt/freeware/lib/python2.7/distutils/core.py", line 112, in setup
    _setup_distribution = dist = klass(attrs)
  File "build/bdist.aix-5.3/egg/setuptools/dist.py", line 265, in __init__
  File "build/bdist.aix-5.3/egg/setuptools/dist.py", line 310, in fetch_build_eggs
  File "build/bdist.aix-5.3/egg/pkg_resources/__init__.py", line 824, in resolve
  File "build/bdist.aix-5.3/egg/pkg_resources/__init__.py", line 1069, in best_match
  File "build/bdist.aix-5.3/egg/pkg_resources/__init__.py", line 1081, in obtain
  File "build/bdist.aix-5.3/egg/setuptools/dist.py", line 377, in fetch_build_egg
  File "build/bdist.aix-5.3/egg/setuptools/command/easy_install.py", line 629, in easy_install
  File "build/bdist.aix-5.3/egg/setuptools/command/easy_install.py", line 659, in install_item
  File "build/bdist.aix-5.3/egg/setuptools/command/easy_install.py", line 842, in install_eggs
  File "build/bdist.aix-5.3/egg/setuptools/command/easy_install.py", line 1070, in build_and_install
  File "build/bdist.aix-5.3/egg/setuptools/command/easy_install.py", line 1058, in run_setup
distutils.errors.DistutilsError: Setup script exited with error: command './Modules/ld_so_aix' failed with exit status 1
```

The install script is as follows:
```
function installmodule {
   module=$1
   gtar -xzf ${module}.tar.gz
   cd $module
   python setup.py install --user
   cd ..
}

export LIBPATH=/opt/freeware/lib
export LD_LIBIRARY_PATH=/opt/freeware/lib
BASEDIR=$HOME/mystuff/
export PYTHONUSERBASE=$BASEDIR/python

installmodule cryptography-0.8.2
```

**Comment by alex** [comment]
This looks like a bug in `cffi`, not cryptography (or maybe a bug in the AIX compiler, I don't know anything about it :-))

Can you share what compiler is being used?

**Comment by pottmi** [comment]
Note: all the compile errors related to ffi are warnings.  Although I don't like to ignore warnings, I am not sure that is causing the problem because the thing that is stopping the run is:
`unable to execute ./Modules/ld_so_aix: No such file or directory`

```
# cc -qversion
IBM XL C/C++ Enterprise Edition V8.0 for AIX
Version: 08.00.0000.0000
```

I confirmed that cc was being used despite gcc also being installed on this computer.  I confirmed with 
`ls -lu  $(which cc)`
and could see the timestamp changed after the install script ran.

**Comment by alex** [comment]
Oh, good catch. Sorry about that.

I have no idea what to do with this error message unfortunately :-(

On Sun, May 3, 2015 at 8:11 PM, Michael Potter <notifications@github.com>
wrote:

> Note: all the compile errors related to ffi are warnings. Although I don't
> like to ignore warnings, I am not sure that is causing the problem because
> the thing that is stopping the run is:
> unable to execute ./Modules/ld_so_aix: No such file or directory
>
> # cc -qversion
> IBM XL C/C++ Enterprise Edition V8.0 for AIX
> Version: 08.00.0000.0000
>
> I confirmed that cc was being used despite gcc also being installed on
> this computer. I confirmed with
> ls -lu $(which cc)
> and could see the timestamp changed after the install script ran.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pyca/cryptography/issues/1900#issuecomment-98558565>.
>



-- 
"I disapprove of what you say, but I will defend to the death your right to
say it." -- Evelyn Beatrice Hall (summarizing Voltaire)
"The people's good is the highest law." -- Cicero
GPG Key fingerprint: 125F 5C67 DFE9 4084

**Comment by pottmi** [comment]
If you google this:
`unable to execute ./Modules/ld_so_aix: No such file or directory`
you will see other modules that have this same issue.

I suspect it is the same for this module, but I am not smart enough to convert those solutions to this module.

**Comment by elitest** [comment]
It looks like Python.org has a [copy](http://svn.python.org/projects/python/trunk/Modules/ld_so_aix) of  ```ld_so_aix```.  Have you tried pulling that down to wherever ```Modules``` is located?

**Comment by pottmi** [comment]
From memory because I am not at the computer right now:
ld_so_aix is in the config folder it the python install folder.  There is references to it in the Makefile.

Other people are solving this problem by modifying the source that invokes the ld_so_aix OR putting a softlink in the spot that it is being expected.

**Comment by pottmi** [comment]
@elitest : I don't know where ./Modules is located.  Do you know?

**Comment by pottmi** [comment]
I am attempting to install 0.9 and now get additional error output:
```
unable to execute ./Modules/ld_so_aix: No such file or directory
Traceback (most recent call last):
  File "setup.py", line 342, in <module>
    **keywords_with_side_effects(sys.argv)
  File "/opt/freeware/lib/python2.7/distutils/core.py", line 112, in setup
    _setup_distribution = dist = klass(attrs)
  File "build/bdist.aix-5.3/egg/setuptools/dist.py", line 265, in __init__
  File "build/bdist.aix-5.3/egg/setuptools/dist.py", line 310, in fetch_build_eggs
  File "build/bdist.aix-5.3/egg/pkg_resources/__init__.py", line 824, in resolve
  File "build/bdist.aix-5.3/egg/pkg_resources/__init__.py", line 1069, in best_match
  File "build/bdist.aix-5.3/egg/pkg_resources/__init__.py", line 1081, in obtain
  File "build/bdist.aix-5.3/egg/setuptools/dist.py", line 377, in fetch_build_egg
  File "build/bdist.aix-5.3/egg/setuptools/command/easy_install.py", line 629, in easy_install
  File "build/bdist.aix-5.3/egg/setuptools/command/easy_install.py", line 659, in install_item
  File "build/bdist.aix-5.3/egg/setuptools/command/easy_install.py", line 842, in install_eggs
  File "build/bdist.aix-5.3/egg/setuptools/command/easy_install.py", line 1070, in build_and_install
  File "build/bdist.aix-5.3/egg/setuptools/command/easy_install.py", line 1058, in run_setup
distutils.errors.DistutilsError: Setup script exited with error: command './Modules/ld_so_aix' failed with exit status 1
```

I still get all the c error, but the python Traceback has more information.

**Comment by pottmi** [comment]
I got it installed with these changes:

WARNING: This is a complete hack. Someone needs to figure out why this was successful and put in a real fix.
```
/opt/freeware/lib/python2.7/config:
# diff ld_so_aix.orig ld_so_aix
89c89
< impfile="./python.exp"
---
> impfile="/opt/freeware/lib/python2.7/config/python.exp"
116a117
>         impfile="/opt/freeware/lib/python2.7/config/python.exp"
```
Note: the second setting of impfile is to override the command line setting of it.
```
/opt/freeware/lib/python2.7:
# diff _sysconfigdata.py.original _sysconfigdata.py
20c20
<  'BLDSHARED': './Modules/ld_so_aix xlc_r -ma -I/opt/freeware/include -DAIX_GENUINE_CPLUSCPLUS -Wl,-brtl -bI:./Modules/python.exp -L/opt/freeware/lib',
---
>  'BLDSHARED': '/opt/freeware/lib/python2.7/config/ld_so_aix xlc_r -ma -I/opt/freeware/include -DAIX_GENUINE_CPLUSCPLUS -Wl,-brtl -bI:./Modules/python.exp -L/opt/freeware/lib',
366c366
<  'LDSHARED': './Modules/ld_so_aix xlc_r -ma -I/opt/freeware/include -DAIX_GENUINE_CPLUSCPLUS -Wl,-brtl -bI:./Modules/python.exp -L/opt/freeware/lib',
---
>  'LDSHARED': '/opt/freeware/lib/python2.7/config/ld_so_aix xlc_r -ma -I/opt/freeware/include -DAIX_GENUINE_CPLUSCPLUS -Wl,-brtl -bI:./Modules/python.exp -L/opt/freeware/lib',
```

**Comment by reaperhulk** [comment]
This issue is related to the AIX compilation toolchain and how it interacts with distutils, etc. cryptography (unfortunately) can't help with this. Closing.
