### ISSUE TITLE
Error under PyPy 2.6.0

### ISSUE THREAD

**Issue by alex** [pyca/cryptography#2002]
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/alex_gaynor/projects/cryptography/src/cryptography/hazmat/backends/__init__.py", line 40, in default_backend
    _default_backend = MultiBackend(_available_backends())
  File "/Users/alex_gaynor/projects/cryptography/src/cryptography/hazmat/backends/__init__.py", line 27, in _available_backends
    "cryptography.backends"
  File "/Users/alex_gaynor/.virtualenvs/cryptography/site-packages/pkg_resources/__init__.py", line 2351, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/Users/alex_gaynor/projects/cryptography/src/cryptography/hazmat/backends/commoncrypto/__init__.py", line 7, in <module>
    from cryptography.hazmat.backends.commoncrypto.backend import backend
  File "/Users/alex_gaynor/projects/cryptography/src/cryptography/hazmat/backends/commoncrypto/backend.py", line 244, in <module>
    backend = Backend()
  File "/Users/alex_gaynor/projects/cryptography/src/cryptography/hazmat/backends/commoncrypto/backend.py", line 44, in __init__
    self._binding = Binding()
  File "/Users/alex_gaynor/projects/cryptography/src/cryptography/hazmat/bindings/commoncrypto/binding.py", line 44, in __init__
    self._ensure_ffi_initialized()
  File "/Users/alex_gaynor/projects/cryptography/src/cryptography/hazmat/bindings/commoncrypto/binding.py", line 56, in _ensure_ffi_initialized
    modules=cls._modules,
  File "/Users/alex_gaynor/projects/cryptography/src/cryptography/hazmat/bindings/utils.py", line 31, in load_library_for_binding
    lib = ffi.verifier.load_library()
  File "/Users/alex_gaynor/.pyenv/versions/pypy-2.6.0/lib_pypy/cffi/verifier.py", line 97, in load_library
    return self._load_library()
  File "/Users/alex_gaynor/.pyenv/versions/pypy-2.6.0/lib_pypy/cffi/verifier.py", line 207, in _load_library
    return self._vengine.load_library()
  File "/Users/alex_gaynor/.pyenv/versions/pypy-2.6.0/lib_pypy/cffi/vengine_gen.py", line 86, in load_library
    self._load(module, 'loaded', library=library)
  File "/Users/alex_gaynor/.pyenv/versions/pypy-2.6.0/lib_pypy/cffi/vengine_gen.py", line 112, in _load
    method(tp, realname, module, **kwds)
  File "/Users/alex_gaynor/.pyenv/versions/pypy-2.6.0/lib_pypy/cffi/vengine_gen.py", line 446, in _loaded_gen_constant
    value = self._load_constant(is_int, tp, name, module)
  File "/Users/alex_gaynor/.pyenv/versions/pypy-2.6.0/lib_pypy/cffi/vengine_gen.py", line 441, in _load_constant
    value = function()
NotImplementedError: constant kCFTypeDictionaryKeyCallBacks: ctype 'CFDictionaryKeyCallBacks' not supported as return value (it is a struct declared with "...;", but the C calling convention may depend on the missing fields)
```

**Comment by alex** [comment]
Armin suggests this might be a cffi-on-PyPy bug.

**Comment by hynek** [comment]
Should we document somewhere that cryptography is incompatible with PyPy 2.6.0?  Does anyone know whether PyPy fixed it in master already?

**Comment by reaperhulk** [comment]
We resolved this by changing to `set_source` compilation in #1986. Starting with the next release we'll require pypy 2.6+.
