### ISSUE TITLE
py2exe FileNotFoundError: [Errno 2] No such file or directory \dist\\library .zip\\cryptography\\hazmat\\bindings\\openssl\\src/osrandom_engine.h'

### ISSUE THREAD

**Issue by catpython** [pyca/cryptography#2155]
I meet an error when I try to make an exe file, my python is 3.4, And in C:\Users\jpu\AppData\Local\Continuum\Anaconda3\Lib\site-packages\cryptography\hazmat\bindings\openssl\src\ there are two files: osrandom_engine.c , osrandom_engine.h
After I created the exe, and run the myprogram.exe file,
it tells me that:

FileNotFoundError: [Errno 2] No such file or directory: 'c:\\test\\dist\\library
.zip\\cryptography\\hazmat\\bindings\\openssl\\src/osrandom_engine.h'

In the myprogram.exe, I import the pyopenssl as: 
from OpenSSL import crypto
…..
…
….

What is the error caused by?
how to fix this problem? 

Thanks,

cat

c:\test>python setup.py py2exe
running py2exe

  11 missing Modules
  ------------------
? backports                           imported from setuptools.ssl_support
? packaging                           imported from pkg_resources
? pywintypes                          imported from -
? setuptools_svn                      imported from setuptools.command.egg_info
? testing                             imported from cffi.recompiler
? urllib.pathname2url                 imported from setuptools.compat
? urllib.splittag                     imported from setuptools.compat
? urllib.url2pathname                 imported from setuptools.compat
? win32api                            imported from platform, win32evtlogutil
? win32com                            imported from setuptools.sandbox
? wincertstore                        imported from setuptools.ssl_support
Building 'dist\teSSL.exe'.
Building shared code archive 'dist\library.zip'.
Copy c:\users\jpu\appdata\local\continuum\anaconda3\python34.dll to dist
Copy C:\Users\jpu\AppData\Local\Continuum\Anaconda3\lib\site-packages\win32\win3
2evtlog.pyd to dist\win32evtlog.pyd
Copy C:\Users\jpu\AppData\Local\Continuum\Anaconda3\DLLs\pyexpat.pyd to dist\pye
xpat.pyd
Copy C:\Users\jpu\AppData\Local\Continuum\Anaconda3\lib\site-packages\_cffi_back
end.pyd to dist\_cffi_backend.pyd
Copy C:\Users\jpu\AppData\Local\Continuum\Anaconda3\DLLs\_ctypes.pyd to dist\_ct
ypes.pyd
Copy C:\Users\jpu\AppData\Local\Continuum\Anaconda3\DLLs\_decimal.pyd to dist\_d
ecimal.pyd
Copy C:\Users\jpu\AppData\Local\Continuum\Anaconda3\lib\site-packages\cryptograp
hy\_Cryptography_cffi_c6806e2axd5c405b7.pyd to dist\cryptography._Cryptography_c
ffi_c6806e2axd5c405b7.pyd
Copy C:\Users\jpu\AppData\Local\Continuum\Anaconda3\DLLs\_bz2.pyd to dist\_bz2.p
yd
Copy C:\Users\jpu\AppData\Local\Continuum\Anaconda3\DLLs\_lzma.pyd to dist\_lzma
.pyd
Copy C:\Users\jpu\AppData\Local\Continuum\Anaconda3\DLLs\_multiprocessing.pyd to
dist\_multiprocessing.pyd
Copy C:\Users\jpu\AppData\Local\Continuum\Anaconda3\DLLs\select.pyd to dist\sele
ct.pyd
Copy C:\Users\jpu\AppData\Local\Continuum\Anaconda3\DLLs\unicodedata.pyd to dist
\unicodedata.pyd
Copy C:\Users\jpu\AppData\Local\Continuum\Anaconda3\lib\site-packages\cryptograp
hy\_Cryptography_cffi_a8febd48xffc7b1ce.pyd to dist\cryptography._Cryptography_c
ffi_a8febd48xffc7b1ce.pyd
Copy C:\Users\jpu\AppData\Local\Continuum\Anaconda3\DLLs\_ssl.pyd to dist\_ssl.p
yd
Copy C:\Users\jpu\AppData\Local\Continuum\Anaconda3\DLLs\_socket.pyd to dist\_so
cket.pyd
Copy C:\Users\jpu\AppData\Local\Continuum\Anaconda3\DLLs\_hashlib.pyd to dist\_h
ashlib.pyd
Copy C:\Users\jpu\AppData\Local\Continuum\Anaconda3\lib\site-packages\cryptograp
hy\_Cryptography_cffi_b03f9c7x62b488b1.pyd to dist\cryptography._Cryptography_cf
fi_b03f9c7x62b488b1.pyd
Copy DLL C:\Users\jpu\AppData\Local\Continuum\Anaconda3\MSVCR100.dll to dist\
Copy ExtensionDLL C:\Users\jpu\AppData\Local\Continuum\Anaconda3\lib\site-packag
es\win32\pywintypes34.dll to dist\

c:\test>cd dist
---------------------------------------------------------------------------------------------------------------------------

c:\test\dist>teSSL.exe
Traceback (most recent call last):
  File "teSSL.py", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1191, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1161, in _load_backward_compatible
  File "C:\Users\jpu\AppData\Local\Continuum\Anaconda3\lib\site-packages\OpenSSL
\__init__.py", line 8, in <module>
    from OpenSSL import rand, crypto, SSL
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1191, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1161, in _load_backward_compatible
  File "C:\Users\jpu\AppData\Local\Continuum\Anaconda3\lib\site-packages\OpenSSL
\rand.py", line 11, in <module>
    from OpenSSL._util import (
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1191, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1161, in _load_backward_compatible
  File "C:\Users\jpu\AppData\Local\Continuum\Anaconda3\lib\site-packages\OpenSSL
\_util.py", line 6, in <module>
    from cryptography.hazmat.bindings.openssl.binding import Binding
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1191, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1161, in _load_backward_compatible
  File "C:\Users\jpu\AppData\Local\Continuum\Anaconda3\lib\site-packages\cryptog
raphy\hazmat\bindings\openssl\binding.py", line 60, in <module>
    class Binding(object):
  File "C:\Users\jpu\AppData\Local\Continuum\Anaconda3\lib\site-packages\cryptog
raphy\hazmat\bindings\openssl\binding.py", line 109, in Binding
    libraries=_get_libraries(sys.platform)
 File "C:\Users\jpu\AppData\Local\Continuum\Anaconda3\lib\site-packages\cryptog
raphy\hazmat\bindings\utils.py", line 68, in build_ffi_for_binding
    __import__(module_name)
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1191, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1161, in _load_backward_compatible
  File "C:\Users\jpu\AppData\Local\Continuum\Anaconda3\lib\site-packages\cryptog
raphy\hazmat\bindings\openssl\osrandom_engine.py", line 10, in <module>
    os.path.dirname(__file__), "src/osrandom_engine.h"
FileNotFoundError: [Errno 2] No such file or directory: 'c:\\test\\dist\\library
.zip\\cryptography\\hazmat\\bindings\\openssl\\src/osrandom_engine.h'

**Comment by Ayrx** [comment]
Ref #2039.

@reaperhulk

**Comment by alex** [comment]
Closing as a duplicate.
