### ISSUE TITLE
AssertionError when using PrivateKey.decrypt

### ISSUE THREAD

**Issue by ericwb** [pyca/cryptography#2261]
So in OpenStack we get the following traceback, but only on CentOS 7.1.  I'm not really sure what the root cause is and I don't have a simple way to recreate.  We are using cryptography 0.9.1. 
```
2015-08-10 13:28:50.928 ERROR oslo_messaging.rpc.dispatcher [req-d69573cb-5b99-405e-b58d-1624ba9e7e5a tempest-InstanceRunTest-1171165482 tempest-InstanceRunTest-459188910] Exception during message handling: 
2015-08-10 13:28:50.928 10391 ERROR oslo_messaging.rpc.dispatcher Traceback (most recent call last):
2015-08-10 13:28:50.928 10391 ERROR oslo_messaging.rpc.dispatcher   File "/usr/lib/python2.7/site-packages/oslo_messaging/rpc/dispatcher.py", line 142, in _dispatch_and_reply
2015-08-10 13:28:50.928 10391 ERROR oslo_messaging.rpc.dispatcher     executor_callback))
2015-08-10 13:28:50.928 10391 ERROR oslo_messaging.rpc.dispatcher   File "/usr/lib/python2.7/site-packages/oslo_messaging/rpc/dispatcher.py", line 186, in _dispatch
2015-08-10 13:28:50.928 10391 ERROR oslo_messaging.rpc.dispatcher     executor_callback)
2015-08-10 13:28:50.928 10391 ERROR oslo_messaging.rpc.dispatcher   File "/usr/lib/python2.7/site-packages/oslo_messaging/rpc/dispatcher.py", line 129, in _do_dispatch
2015-08-10 13:28:50.928 10391 ERROR oslo_messaging.rpc.dispatcher     result = func(ctxt, **new_args)
2015-08-10 13:28:50.928 10391 ERROR oslo_messaging.rpc.dispatcher   File "/opt/stack/nova/nova/cert/manager.py", line 70, in decrypt_text
2015-08-10 13:28:50.928 10391 ERROR oslo_messaging.rpc.dispatcher     return crypto.decrypt_text(project_id, base64.b64decode(text))
2015-08-10 13:28:50.928 10391 ERROR oslo_messaging.rpc.dispatcher   File "/opt/stack/nova/nova/crypto.py", line 200, in decrypt_text
2015-08-10 13:28:50.928 10391 ERROR oslo_messaging.rpc.dispatcher     return priv_key.decrypt(text, padding.PKCS1v15())
2015-08-10 13:28:50.928 10391 ERROR oslo_messaging.rpc.dispatcher   File "/usr/lib/python2.7/site-packages/cryptography/hazmat/backends/openssl/rsa.py", line 536, in decrypt
2015-08-10 13:28:50.928 10391 ERROR oslo_messaging.rpc.dispatcher     return _enc_dec_rsa(self._backend, self, ciphertext, padding)
2015-08-10 13:28:50.928 10391 ERROR oslo_messaging.rpc.dispatcher   File "/usr/lib/python2.7/site-packages/cryptography/hazmat/backends/openssl/rsa.py", line 76, in _enc_dec_rsa
2015-08-10 13:28:50.928 10391 ERROR oslo_messaging.rpc.dispatcher     return _enc_dec_rsa_pkey_ctx(backend, key, data, padding_enum)
2015-08-10 13:28:50.928 10391 ERROR oslo_messaging.rpc.dispatcher   File "/usr/lib/python2.7/site-packages/cryptography/hazmat/backends/openssl/rsa.py", line 105, in _enc_dec_rsa_pkey_ctx
2015-08-10 13:28:50.928 10391 ERROR oslo_messaging.rpc.dispatcher     _handle_rsa_enc_dec_error(backend, key)
2015-08-10 13:28:50.928 10391 ERROR oslo_messaging.rpc.dispatcher   File "/usr/lib/python2.7/site-packages/cryptography/hazmat/backends/openssl/rsa.py", line 145, in _handle_rsa_enc_dec_error
2015-08-10 13:28:50.928 10391 ERROR oslo_messaging.rpc.dispatcher     assert errors[0].reason in decoding_errors
2015-08-10 13:28:50.928 10391 ERROR oslo_messaging.rpc.dispatcher AssertionError
2015-08-10 13:28:50.928 10391 ERROR oslo_messaging.rpc.dispatcher 
2015-08-10 13:28:50.930 ERROR oslo_messaging._drivers.common [req-d69573cb-5b99-405e-b58d-1624ba9e7e5a tempest-InstanceRunTest-1171165482 tempest-I
```
Here's the openssl version info for a standard centos 7.1.

```
$ openssl version -a
OpenSSL 1.0.1e-fips 11 Feb 2013
built on: Mon Jun 29 12:45:07 UTC 2015
platform: linux-x86_64
options:  bn(64,64) md2(int) rc4(16x,int) des(idx,cisc,16,int) idea(int) blowfish(idx) 
compiler: gcc -fPIC -DOPENSSL_PIC -DZLIB -DOPENSSL_THREADS -D_REENTRANT -DDSO_DLFCN -DHAVE_DLFCN_H -DKRB5_MIT -m64 -DL_ENDIAN -DTERMIO -Wall -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches   -m64 -mtune=generic -Wa,--noexecstack -DPURIFY -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DMD5_ASM -DAES_ASM -DVPAES_ASM -DBSAES_ASM -DWHIRLPOOL_ASM -DGHASH_ASM
OPENSSLDIR: "/etc/pki/tls"
engines:  rdrand dynamic 
```
More references to the error:
http://openstack-ci.tintri.com/tintri/refs-changes-78-209578-8/logs/screen-n-api.log.txt
http://openstack-ci.tintri.com/tintri/refs-changes-78-209578-8/logs/screen-n-crt.log.txt

**Comment by alex** [comment]
Do you have a reproducer for this case that can be triggered with just cryptography?

**Comment by ericwb** [comment]
I wish I did.  I'll continue to try to get one.

**Comment by ericwb** [comment]
This is the code snippet.  I'll continue to work to get the private key and text used in this code.

```
def decrypt_text(project_id, text):
    private_key_file = key_path(project_id)
    if not os.path.exists(private_key_file):
        raise exception.ProjectNotFound(project_id=project_id)
    with open(private_key_file, 'rb') as f:
        data = f.read()
    try:
        priv_key = serialization.load_pem_private_key(
            data, None, backends.default_backend())
        return priv_key.decrypt(text, padding.PKCS1v15())
    except (ValueError, TypeError, exceptions.UnsupportedAlgorithm) as exc:
        raise exception.DecryptionFailure(reason=six.text_type(exc))
```

**Comment by reaperhulk** [comment]
@ericwb is this happening in a test case? If so, is it expecting a `DecryptionFailure`?

**Comment by ericwb** [comment]
According to another developer, this is the openssl version in use.  So exactly the same as what I reported before if it matters.

openssl-1.0.1e-42.el7_1.9.x86_64

**Comment by ericwb** [comment]
@reaperhulk its not expected to happen.  This is occurring during a run of tempest (OpenStack functional testing engine).  On other operating systems its not happening.

**Comment by reaperhulk** [comment]
@ericwb have you made any progress on getting a reproducer?

**Comment by ericwb** [comment]
It seems the original reporter of the openstack bug resolved the issue by installing M2Crypto.  So I think I can also close this now.
https://bugs.launchpad.net/nova/+bug/1483408
