### ISSUE TITLE
Does not install on CentOS6 (python 2.6)

### ISSUE THREAD

**Issue by srinathman** [pyca/cryptography#2289]
Hi,

I get the following error when installing on a CentOS 6 (python2.6.6) using pip (pip install cryptography).

Here is the error:

```bash
.
.
.
build/temp.linux-x86_64-2.6/_openssl.c:722: error: declaration for parameter ‘SSLeay_version’ but no such parameter

build/temp.linux-x86_64-2.6/_openssl.c:721: error: declaration for parameter ‘SSLeay’ but no such parameter

build/temp.linux-x86_64-2.6/_openssl.c:718: error: declaration for parameter ‘OPENSSL_no_config’ but no such parameter

build/temp.linux-x86_64-2.6/_openssl.c:717: error: declaration for parameter ‘OPENSSL_config’ but no such parameter

build/temp.linux-x86_64-2.6/_openssl.c:577: error: declaration for parameter ‘ASN1_STRING_to_UTF8’ but no such parameter

build/temp.linux-x86_64-2.6/_openssl.c:560: error: declaration for parameter ‘AES_set_decrypt_key’ but no such parameter

build/temp.linux-x86_64-2.6/_openssl.c:559: error: declaration for parameter ‘AES_set_encrypt_key’ but no such parameter

build/temp.linux-x86_64-2.6/_openssl.c:69881: error: expected ‘{’ at end of input

error: command 'gcc' failed with exit status 1

----------------------------------------
Cleaning up...
Command /home/smantripragada/redlabnet/bin/python -c "import setuptools;__file__='/home/smantripragada/redlabnet/build/cryptography/setup.py';exec(compile(open(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-yCUTY2-record/install-record.txt --single-version-externally-managed --install-headers /home/smantripragada/redlabnet/include/site/python2.6 failed with error code 1 in /home/smantripragada/redlabnet/build/cryptography
Traceback (most recent call last):
  File "/home/smantripragada/redlabnet/bin/pip", line 9, in <module>
    load_entry_point('pip==1.4.1', 'console_scripts', 'pip')()
  File "/home/smantripragada/redlabnet/lib/python2.6/site-packages/pip/__init__.py", line 148, in main
    return command.main(args[1:], options)
  File "/home/smantripragada/redlabnet/lib/python2.6/site-packages/pip/basecommand.py", line 169, in main
    text = '\n'.join(complete_log)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 84: ordinal not in range(128)

$ python
Python 2.6.6 (r266:84292, Jul 23 2015, 15:22:56) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-11)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> 
```

**Comment by alex** [comment]
What version of OpenSSL do you have installed?

**Comment by srinathman** [comment]
openssl-1.0.1e-30.el6.11.x86_64

**Comment by reaperhulk** [comment]
You forgot to install the development packages. `yum install openssl-devel`

**Comment by kellyseeme** [comment]
I use python 2.6 and python 2.7 got this error,the python-devel and openssl-devel is installed,how can i solve this problem?thanks.
```
  gcc -pthread -fno-strict-aliasing -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -DNDEBUG -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -fPIC -I/usr/include/python2.6 -c build/temp.linux-x86_64-2.6/_openssl.c -o build/temp.linux-x86_64-2.6/build/temp.linux-x86_64-2.6/_openssl.o
    build/temp.linux-x86_64-2.6/_openssl.c: In function ‘_cffi_const_CMS_DEBUG_DECRYPT’:
    build/temp.linux-x86_64-2.6/_openssl.c:8193: error: ‘CMS_DEBUG_DECRYPT’ undeclared (first use in this function)
    build/temp.linux-x86_64-2.6/_openssl.c:8193: error: (Each undeclared identifier is reported only once
    build/temp.linux-x86_64-2.6/_openssl.c:8193: error: for each function it appears in.)
    error: command 'gcc' failed with exit status 1
    
    ----------------------------------------
Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-oBhGVS/cryptography/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-sa8laz-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-oBhGVS/cryptography/
[root@Bserver ansible]# rpm -qa openssl
openssl-1.0.0-20.el6.x86_64
[root@Bserver ansible]# rpm -qa openssl-devel
openssl-devel-1.0.0-20.el6.x86_64
```

**Comment by kellyseeme** [comment]
```
OpenSSL> version
OpenSSL 1.1.0c  10 Nov 2016
```

OK，i rebuild the openssl ,then can install cryptography
but i dont know why openssl-1.0.0-20.el6.x86_64 can't do???

**Comment by reaperhulk** [comment]
OpenSSL 1.0.0 is unsupported by cryptography. 1.0.1+ is required.
