### ISSUE TITLE
Failed requirement on setupext-pip

### ISSUE THREAD

**Issue by jvehent** [pyca/cryptography#2348]
I ran into this error on Debian Testing:

```bash
$ sudo pip install --upgrade cryptography
Downloading/unpacking cryptography from https://pypi.python.org/packages/source/c/cryptography/cryptography-1.0.1.tar.gz#md5=437adf65ab9c0ec98b2a07dd425d239d
  Downloading cryptography-1.0.1.tar.gz (332kB): 332kB downloaded
  Running setup.py (path:/tmp/pip-build-3jxdN8/cryptography/setup.py) egg_info for package cryptography
    
    no previously-included directories found matching 'docs/_build'
    warning: no previously-included files matching '*' found under directory 'vectors'
Requirement already up-to-date: idna>=2.0 in /usr/lib/python2.7/dist-packages (from cryptography)
Requirement already up-to-date: pyasn1>=0.1.8 in /usr/lib/python2.7/dist-packages (from cryptography)
Requirement already up-to-date: six>=1.4.1 in /usr/lib/python2.7/dist-packages (from cryptography)
Requirement already up-to-date: setuptools in /usr/local/lib/python2.7/dist-packages (from cryptography)
Requirement already up-to-date: enum34 in /usr/lib/python2.7/dist-packages (from cryptography)
Requirement already up-to-date: ipaddress in /usr/lib/python2.7/dist-packages (from cryptography)
Downloading/unpacking cffi>=1.1.0 (from cryptography)
  Downloading cffi-1.2.1.tar.gz (335kB): 335kB downloaded
  Running setup.py (path:/tmp/pip-build-3jxdN8/cffi/setup.py) egg_info for package cffi
    
Requirement already up-to-date: pycparser in /usr/lib/python2.7/dist-packages (from cffi>=1.1.0->cryptography)
Installing collected packages: cryptography, cffi
  Found existing installation: cryptography 0.9.3
    Not uninstalling cryptography at /usr/lib/python2.7/dist-packages, owned by OS
  Running setup.py install for cryptography
    
    Installed /tmp/pip-build-3jxdN8/cryptography/.eggs/cffi-1.2.1-py2.7-linux-x86_64.egg
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-3jxdN8/cryptography/setup.py", line 313, in <module>
        **keywords_with_side_effects(sys.argv)
      File "/usr/lib/python2.7/distutils/core.py", line 111, in setup
        _setup_distribution = dist = klass(attrs)
      File "/usr/local/lib/python2.7/dist-packages/setuptools/dist.py", line 272, in __init__
        _Distribution.__init__(self,attrs)
      File "/usr/lib/python2.7/distutils/dist.py", line 287, in __init__
        self.finalize_options()
      File "/usr/local/lib/python2.7/dist-packages/setuptools/dist.py", line 327, in finalize_options
        ep.load()(self, ep.name, value)
      File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2355, in load
        return self.resolve()
      File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2361, in resolve
        module = __import__(self.module_name, fromlist=['__name__'], level=0)
    ImportError: No module named setuptools_ext
    Complete output from command /usr/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip-build-3jxdN8/cryptography/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-nVQQA6-record/install-record.txt --single-version-externally-managed --compile:
    

Installed /tmp/pip-build-3jxdN8/cryptography/.eggs/cffi-1.2.1-py2.7-linux-x86_64.egg

Traceback (most recent call last):

  File "<string>", line 1, in <module>

  File "/tmp/pip-build-3jxdN8/cryptography/setup.py", line 313, in <module>

    **keywords_with_side_effects(sys.argv)

  File "/usr/lib/python2.7/distutils/core.py", line 111, in setup

    _setup_distribution = dist = klass(attrs)

  File "/usr/local/lib/python2.7/dist-packages/setuptools/dist.py", line 272, in __init__

    _Distribution.__init__(self,attrs)

  File "/usr/lib/python2.7/distutils/dist.py", line 287, in __init__

    self.finalize_options()

  File "/usr/local/lib/python2.7/dist-packages/setuptools/dist.py", line 327, in finalize_options

    ep.load()(self, ep.name, value)

  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2355, in load

    return self.resolve()

  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2361, in resolve

    module = __import__(self.module_name, fromlist=['__name__'], level=0)

ImportError: No module named setuptools_ext

----------------------------------------
  Can't roll back cryptography; was not uninstalled
Cleaning up...
Command /usr/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip-build-3jxdN8/cryptography/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-nVQQA6-record/install-record.txt --single-version-externally-managed --compile failed with error code 1 in /tmp/pip-build-3jxdN8/cryptography
Storing debug log for failure in /root/.pip/pip.log
```

The issue was fixed by running `$ sudo pip install --upgrade setupext-pip`

**Comment by reaperhulk** [comment]
This issue is because the install didn't import cffi 1.x properly even though it had installed it as part of the requirements. There's a good chance this occurred because you appear to be mixing system and pip packages. There's unfortunately nothing cryptography can do to avoid conflicts of this nature. Glad you found a way to resolve your issue though!
