### ISSUE TITLE
Unknown OpenSSL Error (RSA_R_DIGEST_TOO_BIG_FOR_RSA_KEY) when using Cryptography within mod_wsgi

### ISSUE THREAD

**Issue by asayler** [pyca/cryptography#2669]
I have some code that takes and signs a CSR within a flask-based WSGI app. The code runs fine when tested outside of a WSGI environment, but crashes with the below error when builder.sign() us called within WSGI via Apache.

Even stranger, the code seems to crash every time when running WSGI with a single process and a single thread. But it only crashes intermittently when I run WSGI with a single process and multiple threads.

Versions:
```
Ubuntu 14.04.3
Apache 2.4.7
Python 3.4.3
mod_wsgi 4.4.21
cryptography 1.2.1
libssl-dev 1.0.1f-ubuntu2.16
libffi-dev 3.1~rc1+r3.0.13-12ubuntu0.1
```

Error:
```
[Wed Jan 13 11:42:00.231441 2016] [wsgi:error] [pid 7095:tid 140077770643200] DEBUG: crypto - csr_pem:
[Wed Jan 13 11:42:00.231492 2016] [wsgi:error] [pid 7095:tid 140077770643200] -----BEGIN CERTIFICATE REQUEST-----
[Wed Jan 13 11:42:00.231517 2016] [wsgi:error] [pid 7095:tid 140077770643200] MIIE5zCCAs8CAQAwgZAxGzAZBgNVBAMMEk5ldyBUdXRhbWVuIENsaWVudDELMAkG
[Wed Jan 13 11:42:00.231538 2016] [wsgi:error] [pid 7095:tid 140077770643200] A1UEBhMCVVMxETAPBgNVBAgMCENvbG9yYWRvMRAwDgYDVQQHDAdCb3VsZGVyMRAw
[Wed Jan 13 11:42:00.231559 2016] [wsgi:error] [pid 7095:tid 140077770643200] DgYDVQQKDAdUZXN0T3JnMQ8wDQYDVQQLDAZUZXN0T1UxHDAaBgkqhkiG9w0BCQEW
[Wed Jan 13 11:42:00.231579 2016] [wsgi:error] [pid 7095:tid 140077770643200] DXRlc3RAdGVzdC5jb20wggIiMA0GCSqGSIb3DQEBAQUAA4ICDwAwggIKAoICAQDq
[Wed Jan 13 11:42:00.231605 2016] [wsgi:error] [pid 7095:tid 140077770643200] sga064FlqOGEBzs9ELHvIYxvfeZ8pKj4HWKJzyN7AAIH+YrDkRwINaH+u5awAAN2
[Wed Jan 13 11:42:00.231618 2016] [wsgi:error] [pid 7095:tid 140077770643200] JbxkLloNwznIJJgc0OoJr8rA2XuyQqvToFRiXv/y+TgiN7PmBm/G3KxJ/mNsfcIS
[Wed Jan 13 11:42:00.231630 2016] [wsgi:error] [pid 7095:tid 140077770643200] uBcd+lVr8A4gT2NzcW5SEPYyygiditY5/1I7Qh77r3JUD1f+FblHyJjVYDKUXgWF
[Wed Jan 13 11:42:00.231642 2016] [wsgi:error] [pid 7095:tid 140077770643200] AMvvVzRH/wbGLO59vBMaQ19QZXgnMQOREbFEBK8ePWgvuuMkYjsXlIe8WvOgKY4h
[Wed Jan 13 11:42:00.231654 2016] [wsgi:error] [pid 7095:tid 140077770643200] Q7/mPCGPApWRYO2e/oHl02/fv+sLtcDDri0DbhM1s1198jU6Np2Rpr83BdY3koVy
[Wed Jan 13 11:42:00.231665 2016] [wsgi:error] [pid 7095:tid 140077770643200] Eahg+S2w65l5YySO/amzRSx02A4fLMfiKjFqnhPQw3awhhaJ/4TjbMPvaMDFs+PH
[Wed Jan 13 11:42:00.231677 2016] [wsgi:error] [pid 7095:tid 140077770643200] QP77O8oxBoFLUvsaj4aTDVYZQJBHcYsVkUhUtoQ2H2L6hWh9uo1ET6y/BCAanp5P
[Wed Jan 13 11:42:00.231689 2016] [wsgi:error] [pid 7095:tid 140077770643200] Qvfxh9ZqFZqS9/AxXgLRk/x+KDx6gwxIGwrT9284vx1/lc/MeR2kWcI5HQok3UbM
[Wed Jan 13 11:42:00.231701 2016] [wsgi:error] [pid 7095:tid 140077770643200] RMzOq/9R/9TW2W3pIfbi+Oqk6N8YLkHZLTuT+xlx0G0epaM4Oz9ecF8UFpiVqrFU
[Wed Jan 13 11:42:00.231713 2016] [wsgi:error] [pid 7095:tid 140077770643200] n1J20kjdhtrznRJ6GdI6nm21GH0ETPG9ZePhQloVuGkkK0sFq2lBzPyf8uXRE9y+
[Wed Jan 13 11:42:00.231725 2016] [wsgi:error] [pid 7095:tid 140077770643200] 3CQolWkfTh+Ku92M/l99rHeSEQsdx7PX6Ok5hIDQgwIDAQABoBEwDwYJKoZIhvcN
[Wed Jan 13 11:42:00.231737 2016] [wsgi:error] [pid 7095:tid 140077770643200] AQkOMQIwADANBgkqhkiG9w0BAQsFAAOCAgEAe0vB1qi5I3fz5MCWxYs9mmqkHqPU
[Wed Jan 13 11:42:00.231749 2016] [wsgi:error] [pid 7095:tid 140077770643200] x2dAb6oLAxiFUphLphRNNAbKQaQViABd/tJLISkrx80oa0zNpc7AnRoKBi0wuPjq
[Wed Jan 13 11:42:00.231761 2016] [wsgi:error] [pid 7095:tid 140077770643200] NNs/Yg7yhcbC+jFAiyeKswoy6QO4V+R1xwSESLXNAOJWhBAU2fAyYV71XM6zbr7V
[Wed Jan 13 11:42:00.231781 2016] [wsgi:error] [pid 7095:tid 140077770643200] So9TdxrvSAIPowpoCVBeWK2hRgs4AVP7WLT087vXAkBNRVglzIsprDo6jx2EzHFk
[Wed Jan 13 11:42:00.231794 2016] [wsgi:error] [pid 7095:tid 140077770643200] CZc4asEgE5YFuvtwXpPPqJzoh9jL3TdKFefn/cyj0T9Bk5C120IDDd394XB/39ZP
[Wed Jan 13 11:42:00.231806 2016] [wsgi:error] [pid 7095:tid 140077770643200] 2egyUGDBdXgaDtk03P8CzoK+/4J1LI93DlklWesNlmOcx5hSJhNwmyRjCdwq0cc0
[Wed Jan 13 11:42:00.231818 2016] [wsgi:error] [pid 7095:tid 140077770643200] hjAcxgZWNfnnCIocYpdB/mObd931hg1R77jOsEM1YTgUWYRw+xf/N+F1tsWNsdQJ
[Wed Jan 13 11:42:00.231830 2016] [wsgi:error] [pid 7095:tid 140077770643200] vUPYpF6uDIGPaDakWTtudcn5Kuwyel0KFhTVQlzxL9EdJSY1LfPXKe3sThUGQ0ai
[Wed Jan 13 11:42:00.231850 2016] [wsgi:error] [pid 7095:tid 140077770643200] f2qNbiphqtIMawmq93Phzw4OWfkgyMhaz0G8GyTg/z1BdtVsuQ/d+0zvx7vkYIHk
[Wed Jan 13 11:42:00.231863 2016] [wsgi:error] [pid 7095:tid 140077770643200] X18qZycWuytpyZep5ZsmbOdlGLm33y2PnBcPf72V0IjkQg19kfAPyJ8xQHrw0nxp
[Wed Jan 13 11:42:00.231880 2016] [wsgi:error] [pid 7095:tid 140077770643200] 9096huCdHynfH8CNjXeMSTD2YfyZ3FCOiXai0cgpr4ooaRjmDz5Qs3NdLeftbC3K
[Wed Jan 13 11:42:00.231892 2016] [wsgi:error] [pid 7095:tid 140077770643200] 2O7v6jxKNrnOgCY=
[Wed Jan 13 11:42:00.231904 2016] [wsgi:error] [pid 7095:tid 140077770643200] -----END CERTIFICATE REQUEST-----
[Wed Jan 13 11:42:00.231921 2016] [wsgi:error] [pid 7095:tid 140077770643200]
[Wed Jan 13 11:42:00.231986 2016] [wsgi:error] [pid 7095:tid 140077770643200] DEBUG: crypto - cn: 60691a2d-ca5d-4c74-94ed-6218085cad74
[Wed Jan 13 11:42:00.232070 2016] [wsgi:error] [pid 7095:tid 140077770643200] DEBUG: crypto - serial: 60691a2d-ca5d-4c74-94ed-6218085cad74
[Wed Jan 13 11:42:00.290508 2016] [wsgi:error] [pid 7095:tid 140077770643200] DEBUG: crypto - sub_attr: [<NameAttribute(oid=<ObjectIdentifier(oid=2.5.4.6, name=countryName)>, value='US')>, <NameAttribute(oid=<ObjectIdentifier(oid=2.5.4.7, name=localityName)>, value='Boulder')>, <NameAttribute(oid=<ObjectIdentifier(oid=2.5.4.8, name=stateOrProvinceName)>, value='Colorado')>, <NameAttribute(oid=<ObjectIdentifier(oid=2.5.4.10, name=organizationName)>, value='TestOrg')>, <NameAttribute(oid=<ObjectIdentifier(oid=2.5.4.11, name=organizationalUnitName)>, value='TestOU')>, <NameAttribute(oid=<ObjectIdentifier(oid=2.5.4.3, name=commonName)>, value='60691a2d-ca5d-4c74-94ed-6218085cad74')>]
[Wed Jan 13 11:42:00.294438 2016] [wsgi:error] [pid 7095:tid 140077770643200] ERROR: app - Exception on /bootstrap/accounts/ [POST]
[Wed Jan 13 11:42:00.294483 2016] [wsgi:error] [pid 7095:tid 140077770643200] Traceback (most recent call last):
[Wed Jan 13 11:42:00.294503 2016] [wsgi:error] [pid 7095:tid 140077770643200]   File "/usr/local/lib/python3.4/dist-packages/flask/app.py", line 1817, in wsgi_app
[Wed Jan 13 11:42:00.294520 2016] [wsgi:error] [pid 7095:tid 140077770643200]     response = self.full_dispatch_request()
[Wed Jan 13 11:42:00.294536 2016] [wsgi:error] [pid 7095:tid 140077770643200]   File "/usr/local/lib/python3.4/dist-packages/flask/app.py", line 1477, in full_dispatch_request
[Wed Jan 13 11:42:00.294552 2016] [wsgi:error] [pid 7095:tid 140077770643200]     rv = self.handle_user_exception(e)
[Wed Jan 13 11:42:00.294568 2016] [wsgi:error] [pid 7095:tid 140077770643200]   File "/usr/local/lib/python3.4/dist-packages/flask_cors/extension.py", line 188, in wrapped_function
[Wed Jan 13 11:42:00.294585 2016] [wsgi:error] [pid 7095:tid 140077770643200]     return cors_after_request(app.make_response(f(*args, **kwargs)))
[Wed Jan 13 11:42:00.294601 2016] [wsgi:error] [pid 7095:tid 140077770643200]   File "/usr/local/lib/python3.4/dist-packages/flask/app.py", line 1381, in handle_user_exception
[Wed Jan 13 11:42:00.294616 2016] [wsgi:error] [pid 7095:tid 140077770643200]     reraise(exc_type, exc_value, tb)
[Wed Jan 13 11:42:00.294632 2016] [wsgi:error] [pid 7095:tid 140077770643200]   File "/usr/local/lib/python3.4/dist-packages/flask/_compat.py", line 33, in reraise
[Wed Jan 13 11:42:00.294648 2016] [wsgi:error] [pid 7095:tid 140077770643200]     raise value
[Wed Jan 13 11:42:00.294664 2016] [wsgi:error] [pid 7095:tid 140077770643200]   File "/usr/local/lib/python3.4/dist-packages/flask/app.py", line 1475, in full_dispatch_request
[Wed Jan 13 11:42:00.294680 2016] [wsgi:error] [pid 7095:tid 140077770643200]     rv = self.dispatch_request()
[Wed Jan 13 11:42:00.294695 2016] [wsgi:error] [pid 7095:tid 140077770643200]   File "/usr/local/lib/python3.4/dist-packages/flask/app.py", line 1461, in dispatch_request
[Wed Jan 13 11:42:00.294712 2016] [wsgi:error] [pid 7095:tid 140077770643200]     return self.view_functions[rule.endpoint](**req.view_args)
[Wed Jan 13 11:42:00.294727 2016] [wsgi:error] [pid 7095:tid 140077770643200]   File "/srv/@tutamen-api-ac/src/api/v1/api_accesscontrol/api.py", line 201, in bootstrap_account_create
[Wed Jan 13 11:42:00.294743 2016] [wsgi:error] [pid 7095:tid 140077770643200]     csr_pem=client_csr)
[Wed Jan 13 11:42:00.294759 2016] [wsgi:error] [pid 7095:tid 140077770643200]   File "/srv/@tutamen-api-ac/src/api/v1/pytutamen_server/datatypes.py", line 393, in create
[Wed Jan 13 11:42:00.294785 2016] [wsgi:error] [pid 7095:tid 140077770643200]     return self.type_child(self.parent.pbackend, pindex=self, create=True, **kwargs)
[Wed Jan 13 11:42:00.294801 2016] [wsgi:error] [pid 7095:tid 140077770643200]   File "/srv/@tutamen-api-ac/src/api/v1/pytutamen_server/accesscontrol.py", line 399, in __init__
[Wed Jan 13 11:42:00.294817 2016] [wsgi:error] [pid 7095:tid 140077770643200]     cn=self.key, serial=self.uid)
[Wed Jan 13 11:42:00.294833 2016] [wsgi:error] [pid 7095:tid 140077770643200]   File "/srv/@tutamen-api-ac/src/api/v1/pytutamen_server/crypto.py", line 153, in csr_to_crt
[Wed Jan 13 11:42:00.294848 2016] [wsgi:error] [pid 7095:tid 140077770643200]     crt = builder.sign(private_key=ca_key, algorithm=hashes.SHA256(), backend=be)
[Wed Jan 13 11:42:00.294864 2016] [wsgi:error] [pid 7095:tid 140077770643200]   File "/usr/local/lib/python3.4/dist-packages/cryptography/x509/base.py", line 520, in sign
[Wed Jan 13 11:42:00.294880 2016] [wsgi:error] [pid 7095:tid 140077770643200]     return backend.create_x509_certificate(self, private_key, algorithm)
[Wed Jan 13 11:42:00.294895 2016] [wsgi:error] [pid 7095:tid 140077770643200]   File "/usr/local/lib/python3.4/dist-packages/cryptography/hazmat/backends/multibackend.py", line 381, in create_x509_certificate
[Wed Jan 13 11:42:00.294912 2016] [wsgi:error] [pid 7095:tid 140077770643200]     return b.create_x509_certificate(builder, private_key, algorithm)
[Wed Jan 13 11:42:00.294929 2016] [wsgi:error] [pid 7095:tid 140077770643200]   File "/usr/local/lib/python3.4/dist-packages/cryptography/hazmat/backends/openssl/backend.py", line 1454, in create_x509_certificate
[Wed Jan 13 11:42:00.294946 2016] [wsgi:error] [pid 7095:tid 140077770643200]     errors[0][3] == self._lib.RSA_R_DIGEST_TOO_BIG_FOR_RSA_KEY
[Wed Jan 13 11:42:00.294962 2016] [wsgi:error] [pid 7095:tid 140077770643200]   File "/usr/local/lib/python3.4/dist-packages/cryptography/hazmat/backends/openssl/backend.py", line 719, in openssl_assert
[Wed Jan 13 11:42:00.294978 2016] [wsgi:error] [pid 7095:tid 140077770643200]     return binding._openssl_assert(self._lib, ok)
[Wed Jan 13 11:42:00.294994 2016] [wsgi:error] [pid 7095:tid 140077770643200]   File "/usr/local/lib/python3.4/dist-packages/cryptography/hazmat/bindings/openssl/binding.py", line 43, in _openssl_assert
[Wed Jan 13 11:42:00.295010 2016] [wsgi:error] [pid 7095:tid 140077770643200]     errors
[Wed Jan 13 11:42:00.295028 2016] [wsgi:error] [pid 7095:tid 140077770643200] cryptography.exceptions.InternalError: Unknown OpenSSL error. Please file an issue at https://github.com/pyca/cryptography/issues with information on how to reproduce this. ([])
[Wed Jan 13 11:42:00.295051 2016] [wsgi:error] [pid 7095:tid 140077770643200] 
```

code:
```
import datetime
import uuid
import logging

DUR_ONE_DAY = datetime.timedelta(1, 0, 0)
DUR_ONE_MONTH = datetime.timedelta(28, 0, 0)
DUR_ONE_YEAR = datetime.timedelta(366, 0, 0)
DUR_TEN_YEAR = datetime.timedelta(3660, 0, 0)

TYPE_RSA = 'RSA'

SIG_SHA256 = 'SHA56'

_SUPPORTED_LENGTH = [2048, 4096]
_SUPPORTED_EXP = [3, 65537]

from cryptography import x509
from cryptography.hazmat.backends import default_backend
from cryptography.hazmat.primitives import hashes
from cryptography.hazmat.primitives import serialization
from cryptography.hazmat.primitives.asymmetric import rsa

logger = logging.getLogger(__name__)
logger.setLevel(logging.DEBUG)
logger.addHandler(logging.NullHandler())

def csr_to_crt(csr_pem, ca_crt_pem, ca_key_pem, password=None,
               cn=None, duration=None, serial=None):

    logger.debug("csr_pem:\n{}".format(csr_pem))
    logger.debug("cn: {}".format(cn))
    logger.debug("serial: {}".format(serial))

    if isinstance(csr_pem, str):
        csr_pem = csr_pem.encode()
    if isinstance(ca_key_pem, str):
        ca_key_pem = ca_key_pem.encode()
    if isinstance(ca_crt_pem, str):
        ca_crt_pem = ca_crt_pem.encode()
    if isinstance(password, str):
        password = password.encode()

    be = default_backend()
    csr = x509.load_pem_x509_csr(csr_pem, be)
    ca_crt = x509.load_pem_x509_certificate(ca_crt_pem, be)
    ca_key = serialization.load_pem_private_key(ca_key_pem, password, be)

    if not cn:
        cn = csr.subject.get_attributes_for_oid(x509.NameOID.COMMON_NAME)[0].value
    if not duration:
        duration = DUR_ONE_YEAR
    if not serial:
        serial = uuid.uuid4()

    sub_attr = []
    sub_attr += csr.subject.get_attributes_for_oid(x509.NameOID.COUNTRY_NAME)
    sub_attr += csr.subject.get_attributes_for_oid(x509.NameOID.LOCALITY_NAME)
    sub_attr += csr.subject.get_attributes_for_oid(x509.NameOID.STATE_OR_PROVINCE_NAME)
    sub_attr += csr.subject.get_attributes_for_oid(x509.NameOID.ORGANIZATION_NAME)
    sub_attr += csr.subject.get_attributes_for_oid(x509.NameOID.ORGANIZATIONAL_UNIT_NAME)
    sub_attr.append(x509.NameAttribute(x509.NameOID.COMMON_NAME, cn))

    logger.debug("sub_attr: {}".format(sub_attr))

    builder = x509.CertificateBuilder()
    builder = builder.issuer_name(ca_crt.subject)
    builder = builder.subject_name(x509.Name(sub_attr))
    builder = builder.not_valid_before(datetime.datetime.today() - DUR_ONE_DAY)
    builder = builder.not_valid_after(datetime.datetime.today() + duration)
    builder = builder.serial_number(int(serial))
    builder = builder.public_key(csr.public_key())

    extensions = []
    extensions.append(x509.BasicConstraints(ca=False, path_length=None))
    for ext in extensions:
        builder = builder.add_extension(ext, critical=True)

    crt = builder.sign(private_key=ca_key, algorithm=hashes.SHA256(), backend=be)
    crt_pem = crt.public_bytes(serialization.Encoding.PEM)

    return crt_pem.decode()
```

**Comment by reaperhulk** [comment]
`mod_wsgi` makes it likely this is related to subinterpreter race condition issues. I realize this is asking a lot, but would it be possible for you to build a docker container that can replicate this issue? That would greatly assist us in isolating it and maybe coming up with a reasonable fix.

**Comment by asayler** [comment]
I can probably do that, but it might be a little bit before I get to it. In the meantime, I'm going to try switching to using pyOpenSSL directly via the crypto interface to see if that makes any difference.

**Comment by asayler** [comment]
So more relevant info:

It turns out I had the `WSGIApplicationGroup` on this server set to `%{RESOURCE}`

As noted in the WSGI docs:

> Any WSGI applications in the global application group will always be executed within the context of the first interpreter created by Python when it is initialised. Forcing a WSGI application to run within the first interpreter can be necessary when a third party C extension module for Python has used the simplified threading API for manipulation of the Python GIL and thus will not run correctly within any additional sub interpreters created by Python.

I changed the application group to `%{GLOBAL}` and the issue disappeared.

So that would seem to confirm your sub-interpreter theory.

Do you expect pyOpenSSL/Cryptogrphy to work with sub-interpreters, or is using the `%{GLOBAL}` simply a requirement to using pyOpenSSL due to the nature of the threading API is uses?

I can still shoot to spin up a Docker container to further test this if non-`%{GLOBAL}` application groups is something you expect to be able to support.

**Comment by reaperhulk** [comment]
We may not be able to resolve the problem without `%{GLOBAL}` but I'd love to have an environment where I can experiment a bit more. The new cffi `init_once` feature might give us a bit more ability to support the more typical subinterpreter implementation.

**Comment by asayler** [comment]
Sounds good. I'll see what I can do about getting your a reproducible docker setup.

Is this really a pyOpenSSL bug then? Or is this specific to Cryptography?

**Comment by reaperhulk** [comment]
This bug is cryptography's issue.

**Comment by reaperhulk** [comment]
Documenting %{GLOBAL} is now a task in #2816.

**Comment by alex** [comment]
This is documented now, nothing else for us to do.
