### ISSUE TITLE
Cryptography 1.2.2 on OS X (at least 10.10) causes the Twisted test suite to fail

### ISSUE THREAD

**Issue by hawkowl** [pyca/cryptography#2719]
Here's something that maybe gives a clue?

```
[ERROR]
Traceback (most recent call last):
  File "/Users/red/code/twgit/twisted/test/test_sslverify.py", line 1820, in test_surpriseFromInfoCallback
    buggyInfoCallback=True,
  File "/Users/red/code/twgit/twisted/test/test_sslverify.py", line 1579, in serviceIdentitySetup
    lambda: clientFactory.buildProtocol(None),
  File "/Users/red/code/twgit/twisted/test/iosim.py", line 429, in connectedServerAndClient
    return c, s, connect(s, sio, c, cio, debug)
  File "/Users/red/code/twgit/twisted/test/iosim.py", line 382, in connect
    clientProtocol.makeConnection(clientTransport)
  File "/Users/red/code/twgit/twisted/protocols/tls.py", line 322, in makeConnection
    self._tlsConnection.do_handshake()
  File "/Users/red/venvs/commands/lib/python2.7/site-packages/OpenSSL/SSL.py", line 1442, in do_handshake
    self._raise_ssl_error(self._ssl, result)
  File "/Users/red/venvs/commands/lib/python2.7/site-packages/OpenSSL/SSL.py", line 1187, in _raise_ssl_error
    _raise_current_error()
  File "/Users/red/venvs/commands/lib/python2.7/site-packages/OpenSSL/_util.py", line 48, in exception_from_error_queue
    raise exception_type(errors)
OpenSSL.SSL.Error: [('SSL routines', 'ssl_undefined_function', 'called a function you should not call')]

twisted.test.test_sslverify.ServiceIdentityTests.test_surpriseFromInfoCallback
===============================================================================
```

**Comment by reaperhulk** [comment]
In IRC it was determined that this is a 1.0.2f related issue and not specifically cryptography. I'm closing this but if you feel it shouldn't be closed feel free to comment/reopen!
