### ISSUE TITLE
OpenSSL and cryptography binding error in OSX

### ISSUE THREAD

**Issue by hitalex** [pyca/cryptography#2746]
I use `pip` to install `scrapy` and Homebrew to install OpenSSL on my mac.

Importing `scrapy` in Python and run `scrapy --version` are fine, but running the scrapy project causes the following error:

    Traceback (most recent call last):
      File "search.py", line 94, in <module>
        setup_crawler(spider_name, 0, keywords)
      File "search.py", line 58, in setup_crawler
        crawler = Crawler(MySpider, settings)
      File "/Library/Python/2.7/site-packages/scrapy/crawler.py", line 46, in __init__
        self.extensions = ExtensionManager.from_crawler(self)
      File "/Library/Python/2.7/site-packages/scrapy/middleware.py", line 56, in from_crawler
        return cls.from_settings(crawler.settings, crawler)
      File "/Library/Python/2.7/site-packages/scrapy/middleware.py", line 32, in from_settings
        mwcls = load_object(clspath)
      File "/Library/Python/2.7/site-packages/scrapy/utils/misc.py", line 44, in load_object
        mod = import_module(module)
      File "/usr/local/Cellar/python/2.7.8_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
        __import__(name)
      File "/Library/Python/2.7/site-packages/scrapy/extensions/memusage.py", line 16, in <module>
        from scrapy.mail import MailSender
      File "/Library/Python/2.7/site-packages/scrapy/mail.py", line 22, in <module>
        from twisted.internet import defer, reactor, ssl
      File "/Library/Python/2.7/site-packages/twisted/internet/ssl.py", line 59, in <module>
        from OpenSSL import SSL
      File "/Library/Python/2.7/site-packages/OpenSSL/__init__.py", line 8, in <module>
        from OpenSSL import rand, crypto, SSL
      File "/Library/Python/2.7/site-packages/OpenSSL/rand.py", line 11, in <module>
        from OpenSSL._util import (
      File "/Library/Python/2.7/site-packages/OpenSSL/_util.py", line 6, in <module>
        from cryptography.hazmat.bindings.openssl.binding import Binding
      File "/Library/Python/2.7/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 205, in <module>
        Binding.init_static_locks()
      File "/Library/Python/2.7/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 172, in init_static_locks
        __import__("_ssl")
    ImportError: No module named _ssl

I have run `brew link openssl`, so why is this error?

I have checked the code of the `/Library/Python/2.7/site-packages/cryptography/hazmat/bindings/openssl/binding.py`:

    # Use Python's implementation if available, importing _ssl triggers
    # the setup for this.
    __import__("_ssl")
    
I don't what these lines of code mean. In fact, importing `ssl` and `_ssl` are OK in python.

OS: Mac OSX 10.11 El Captian

scrapy version: 1.0.5

pip version: 8.0.3

python version: 2.7

**Comment by alex** [comment]
I have no idea what's going on here, if `import _ssl` works for you, then `__import__("_ssl")` should succeed, because they're the same. I strongly suspect there's some difference between the two environments you're using.

**Comment by hitalex** [comment]
I have re-installed python using `brew reinstall python` and update `pip` and `scrapy`, and it works fine now. This is probably due to the new protection mechanism in Mac OX.
