### ISSUE TITLE
Bug: Crashes when calling default_backend()

### ISSUE THREAD

**Issue by hagbarddenstore** [pyca/cryptography#2873]
Using Python 2.7.10 and cryptography 1.31.

```
>>> from cryptography.hazmat.backends import default_backend
>>> default_backend()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/user/Library/Python/2.7/lib/python/site-packages/cryptography/hazmat/backends/__init__.py", line 35, in default_backend
    _default_backend = MultiBackend(_available_backends())
  File "/Users/user/Library/Python/2.7/lib/python/site-packages/cryptography/hazmat/backends/__init__.py", line 22, in _available_backends
    "cryptography.backends"
AttributeError: 'EntryPoint' object has no attribute 'resolve'
```

I found the issue by running Ansible Vault 2.0.1.0.

**Comment by reaperhulk** [comment]
Your setuptools is out of date and needs to be updated to 11.3 or better. `pip install -U setuptools` will fix this.
