### ISSUE TITLE
Unable to install cryptography python package on ubuntu 16.04 LTS don't solve

### ISSUE THREAD

**Issue by Battant** [pyca/cryptography#2910]
Hello,

Sorry it's don't work

https://github.com/pyca/cryptography/issues/2909

I have purge python-cffi package with this line

sudo apt-get purge python-cffi

but I have this python exception when I try to reinstall openssl with this line.
pip install cryptography
Traceback (most recent call last):
File "/usr/bin/pip", line 9, in
from pip import main
File "/home/mparchet/.local/lib/python2.7/site-packages/pip/init.py", line 16, in
from pip.vcs import git, mercurial, subversion, bazaar # noqa
File "/home/mparchet/.local/lib/python2.7/site-packages/pip/vcs/mercurial.py", line 9, in
from pip.download import path_to_url
File "/home/mparchet/.local/lib/python2.7/site-packages/pip/download.py", line 39, in
from pip.vendor import requests, six
File "/home/mparchet/.local/lib/python2.7/site-packages/pip/vendor/requests/__init.py", line 53, in
from .packages.urllib3.contrib import pyopenssl
File "/home/mparchet/.local/lib/python2.7/site-packages/pip/vendor/requests/packages/urllib3/contrib/pyopenssl.py", line 54, in
import OpenSSL.SSL
File "/usr/lib/python2.7/dist-packages/OpenSSL/__init_.py", line 8, in
from OpenSSL import rand, crypto, SSL
File "/usr/lib/python2.7/dist-packages/OpenSSL/rand.py", line 11, in
from OpenSSL._util import (
File "/usr/lib/python2.7/dist-packages/OpenSSL/_util.py", line 6, in
from cryptography.hazmat.bindings.openssl.binding import Binding
File "/usr/lib/python2.7/dist-packages/cryptography/hazmat/bindings/openssl/binding.py", line 68, in
error=-1)
File "/usr/lib/python2.7/dist-packages/cryptography/hazmat/bindings/openssl/binding.py", line 57, in wrapper
ffi.def_extern(name=name, **kwargs)(func)
AttributeError: 'CompiledFFI' object has no attribute 'def_extern'

Could you help me please to fix this bug ?

Best regards

Battant

**Comment by reaperhulk** [comment]
This looks like an error during pip invocation and related to the way your packages are set up with the distribution-supplied version of `cryptography`. Since this is specific to your environment and not a general bug in cryptography I'm going to close this. I'd recommend building a new 16.04 VM to confirm it works that way.
