### ISSUE TITLE
Open SSL issue on local machine

### ISSUE THREAD

**Issue by rvaibhav** [pyca/cryptography#2916]
Hi,

I encountered a strange OpenSSL issue on my local machine.
I recently upgraded my mac to El Capitan 10.11.5 and started encountering punjab connection manager issues. The connection manager has been written in Python. The stacktrace directed me to log the issue here.

Here is the stacktrace.

Starting punjab connection manager now
```
Unhandled Error
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/Twisted-15.4.0-py2.7-macosx-10.10-intel.egg/twisted/application/app.py", line 617, in run
    runApp(config)
  File "/Library/Python/2.7/site-packages/Twisted-15.4.0-py2.7-macosx-10.10-intel.egg/twisted/scripts/twistd.py", line 25, in runApp
    _SomeApplicationRunner(config).run()
  File "/Library/Python/2.7/site-packages/Twisted-15.4.0-py2.7-macosx-10.10-intel.egg/twisted/application/app.py", line 348, in run
    self.application = self.createOrGetApplication()
  File "/Library/Python/2.7/site-packages/Twisted-15.4.0-py2.7-macosx-10.10-intel.egg/twisted/application/app.py", line 413, in createOrGetApplication
    application = getApplication(self.config, passphrase)
--- <exception caught here> ---
  File "/Library/Python/2.7/site-packages/Twisted-15.4.0-py2.7-macosx-10.10-intel.egg/twisted/application/app.py", line 424, in getApplication
    application = service.loadApplication(filename, style, passphrase)
  File "/Library/Python/2.7/site-packages/Twisted-15.4.0-py2.7-macosx-10.10-intel.egg/twisted/application/service.py", line 411, in loadApplication
    passphrase)
  File "/Library/Python/2.7/site-packages/Twisted-15.4.0-py2.7-macosx-10.10-intel.egg/twisted/persisted/sob.py", line 207, in loadValueFromFile
    eval(codeObj, d, d)
  File "punjab.tac", line 4, in <module>
    from twisted.web import server, resource, static
  File "/Library/Python/2.7/site-packages/Twisted-15.4.0-py2.7-macosx-10.10-intel.egg/twisted/web/server.py", line 36, in <module>
    from twisted.web import iweb, http, util
  File "/Library/Python/2.7/site-packages/Twisted-15.4.0-py2.7-macosx-10.10-intel.egg/twisted/web/http.py", line 92, in <module>
    from twisted.internet import interfaces, reactor, protocol, address
  File "/Library/Python/2.7/site-packages/Twisted-15.4.0-py2.7-macosx-10.10-intel.egg/twisted/internet/reactor.py", line 38, in <module>
    from twisted.internet import default
  File "/Library/Python/2.7/site-packages/Twisted-15.4.0-py2.7-macosx-10.10-intel.egg/twisted/internet/default.py", line 56, in <module>
    install = _getInstallFunction(platform)
  File "/Library/Python/2.7/site-packages/Twisted-15.4.0-py2.7-macosx-10.10-intel.egg/twisted/internet/default.py", line 50, in _getInstallFunction
    from twisted.internet.selectreactor import install
  File "/Library/Python/2.7/site-packages/Twisted-15.4.0-py2.7-macosx-10.10-intel.egg/twisted/internet/selectreactor.py", line 18, in <module>
    from twisted.internet import posixbase
  File "/Library/Python/2.7/site-packages/Twisted-15.4.0-py2.7-macosx-10.10-intel.egg/twisted/internet/posixbase.py", line 18, in <module>
    from twisted.internet import error, udp, tcp
  File "/Library/Python/2.7/site-packages/Twisted-15.4.0-py2.7-macosx-10.10-intel.egg/twisted/internet/tcp.py", line 29, in <module>
    from twisted.internet._newtls import (
  File "/Library/Python/2.7/site-packages/Twisted-15.4.0-py2.7-macosx-10.10-intel.egg/twisted/internet/_newtls.py", line 21, in <module>
    from twisted.protocols.tls import TLSMemoryBIOFactory, TLSMemoryBIOProtocol
  File "/Library/Python/2.7/site-packages/Twisted-15.4.0-py2.7-macosx-10.10-intel.egg/twisted/protocols/tls.py", line 41, in <module>
    from OpenSSL.SSL import Error, ZeroReturnError, WantReadError
  File "/Users/vaibhavr/environment/pyOpenSSL-0.15.1/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import rand, crypto, SSL
  File "/Users/vaibhavr/environment/pyOpenSSL-0.15.1/OpenSSL/rand.py", line 11, in <module>
    from OpenSSL._util import (
  File "/Users/vaibhavr/environment/pyOpenSSL-0.15.1/OpenSSL/_util.py", line 6, in <module>
    from cryptography.hazmat.bindings.openssl.binding import Binding
  File "/Library/Python/2.7/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 182, in <module>
    Binding.init_static_locks()
  File "/Library/Python/2.7/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 139, in init_static_locks
    cls._ensure_ffi_initialized()
  File "/Library/Python/2.7/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 134, in _ensure_ffi_initialized
    cls._register_osrandom_engine()
  File "/Library/Python/2.7/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 99, in _register_osrandom_engine
    _openssl_assert(cls.lib, cls.lib.ERR_peek_error() == 0)
  File "/Library/Python/2.7/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 43, in _openssl_assert
    errors
cryptography.exceptions.InternalError: Unknown OpenSSL error. Please file an issue at https://github.com/pyca/cryptography/issues with information on how to reproduce this.


Failed to load application: Unknown OpenSSL error. Please file an issue at https://github.com/pyca/cryptography/issues with information on how to reproduce this.
```

**Comment by reaperhulk** [comment]
Are you running your application within mod_wsgi? If so: https://cryptography.io/en/latest/faq/#starting-cryptography-using-mod-wsgi-produces-an-internalerror-during-a-call-in-register-osrandom-engine

**Comment by alex** [comment]
No response, closing for now. Will reopen if there's more info.

**Comment by rvaibhav** [comment]
@reaperhulk Nope the mod_wsgi is not used to run the application.
