### ISSUE TITLE
OpenSSL version detected is incorrect

### ISSUE THREAD

**Issue by dundeemt** [pyca/cryptography#3043]
Python 2.7.12
FreeBSD 9.3
installed openssl: openssl-1.0.2_14
```
$ python
Python 2.7.12 (default, Jul 14 2016, 12:45:50) 
[GCC 4.2.1 20070831 patched [FreeBSD]] on freebsd9
Type "help", "copyright", "credits" or "license" for more information.
>>> import ssl
>>> ssl.OPENSSL_VERSION
'OpenSSL 1.0.2h  3 May 2016'
>>> ssl.OPENSSL_VERSION_INFO
(1, 0, 2, 8, 15)
>>> import cryptography
>>> cryptography.__version__
'1.4'
>>> import OPENSSL.SSL 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named OPENSSL.SSL
>>> import OpenSSL.SSL
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/home/jlh/projects/junk/lib/python2.7/site-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import rand, crypto, SSL
  File "/usr/home/jlh/projects/junk/lib/python2.7/site-packages/OpenSSL/rand.py", line 12, in <module>
    from OpenSSL._util import (
  File "/usr/home/jlh/projects/junk/lib/python2.7/site-packages/OpenSSL/_util.py", line 6, in <module>
    from cryptography.hazmat.bindings.openssl.binding import Binding
  File "/usr/home/jlh/projects/junk/lib/python2.7/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 250, in <module>
    _verify_openssl_version(Binding.lib.SSLeay())
  File "/usr/home/jlh/projects/junk/lib/python2.7/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 230, in _verify_openssl_version
    "You are linking against OpenSSL 0.9.8, which is no longer "
RuntimeError: You are linking against OpenSSL 0.9.8, which is no longer support by the OpenSSL project. You need to upgrade to a newer version of OpenSSL.
```
Python is linked against a newer version of OpenSSL, I've rebuilt everything python related against this  version.  But cryptography is saying not true.   

I'm at a loss, what am I missing?
I've looked at the setup and there doesn't seem to be anything to configure -- however that must be true.

**Comment by reaperhulk** [comment]
You've probably got older OpenSSL installations in your path and cryptography is picking them up when you try to install. You'll need to explicitly pass CFLAGS/LDFLAGS to point it at the correct 1.0.2 version.

**Comment by airdissy** [comment]
Hello, 
I got similar problem. 
Could you explain me how to use CFLAGS/LDFLAGS when re-installing with `pip cryptography` ?
I guess I should uninstall it before? however it warn me I don't have permission to delete those files whereas I'am already after sudo.

Thanks !

**Comment by airdissy** [comment]
Is-it possible to re-open this subject? Thanks

**Comment by jbrockmendel** [comment]
I'm seeing this on an as-updated-as-I-can-make it raspberrypi.

```
$ pip --version
/home/pi/.local/lib/python2.7/site-packages/cryptography/hazmat/bindings/openssl/binding.py:163: CryptographyDeprecationWarning: OpenSSL version 1.0.1 is no longer supported by the OpenSSL project, please upgrade. A future version of cryptography will drop support for it.
  utils.CryptographyDeprecationWarning
pip 19.0.3 from /usr/local/lib/python2.7/dist-packages/pip (python 2.7)

$ python
>>> import cryptography
>>> cryptography.__version__
'2.6.1'
>>>
>>> import ssl
>>> ssl.OPENSSL_VERSION
'OpenSSL 1.1.0j  20 Nov 2018'
```

**Comment by reaperhulk** [comment]
@jbrockmendel please open a new issue providing the error and stack trace, what distro you're running on your rpi, etc.
