### ISSUE TITLE
Python 3.3 / OSX - Symbol Not Found error from cryptography-1.4-cp33-cp33m-macosx_10_10_x86_64.whl

### ISSUE THREAD

**Issue by radssh** [pyca/cryptography#3065]
Testing on Mac OS X 10.10 with Python 3.3.5 virtualenv (latest binary release of 3.3 from python.org). Unable to create default_backend() due to undefined symbol. Tests pass on 3.4 and 3.5 environments, only 3.3 presents this error.

```
  Successfully uninstalled cryptography-1.4
(3.3)unknown60c5478ec49e:radtest paul$ python -V
Python 3.3.5

(3.3)unknown60c5478ec49e:radtest paul$ pip install cryptography
Collecting cryptography
  Using cached cryptography-1.4-cp33-cp33m-macosx_10_10_x86_64.whl
Requirement already satisfied (use --upgrade to upgrade): setuptools>=11.3 in ./venv/3.3/lib/python3.3/site-packages (from cryptography)
Requirement already satisfied (use --upgrade to upgrade): idna>=2.0 in ./venv/3.3/lib/python3.3/site-packages (from cryptography)
Requirement already satisfied (use --upgrade to upgrade): six>=1.4.1 in ./venv/3.3/lib/python3.3/site-packages (from cryptography)
Requirement already satisfied (use --upgrade to upgrade): pyasn1>=0.1.8 in ./venv/3.3/lib/python3.3/site-packages (from cryptography)
Requirement already satisfied (use --upgrade to upgrade): cffi>=1.4.1 in ./venv/3.3/lib/python3.3/site-packages (from cryptography)
Requirement already satisfied (use --upgrade to upgrade): enum34 in ./venv/3.3/lib/python3.3/site-packages (from cryptography)
Requirement already satisfied (use --upgrade to upgrade): pycparser in ./venv/3.3/lib/python3.3/site-packages (from cffi>=1.4.1->cryptography)
Installing collected packages: cryptography
Successfully installed cryptography-1.4

(3.3)unknown60c5478ec49e:radtest paul$ uname -a
Darwin unknown60c5478ec49e.attlocal.net 15.6.0 Darwin Kernel Version 15.6.0: Thu Jun 23 18:25:34 PDT 2016; root:xnu-3248.60.10~1/RELEASE_X86_64 x86_64

(3.3)unknown60c5478ec49e:radtest paul$ python
Python 3.3.5 (v3.3.5:62cf4e77f785, Mar  9 2014, 01:12:57) 
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import cryptography.hazmat.backends
>>> be = cryptography.hazmat.backends.default_backend()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/paul/radtest/venv/3.3/lib/python3.3/site-packages/cryptography/hazmat/backends/__init__.py", line 35, in default_backend
    _default_backend = MultiBackend(_available_backends())
  File "/Users/paul/radtest/venv/3.3/lib/python3.3/site-packages/cryptography/hazmat/backends/__init__.py", line 22, in _available_backends
    "cryptography.backends"
  File "/Users/paul/radtest/venv/3.3/lib/python3.3/site-packages/cryptography/hazmat/backends/__init__.py", line 21, in <listcomp>
    for ep in pkg_resources.iter_entry_points(
  File "/Users/paul/radtest/venv/3.3/lib/python3.3/site-packages/pkg_resources/__init__.py", line 2235, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/Users/paul/radtest/venv/3.3/lib/python3.3/site-packages/cryptography/hazmat/backends/openssl/__init__.py", line 7, in <module>
    from cryptography.hazmat.backends.openssl.backend import backend
  File "/Users/paul/radtest/venv/3.3/lib/python3.3/site-packages/cryptography/hazmat/backends/openssl/backend.py", line 15, in <module>
    from cryptography import utils, x509
  File "/Users/paul/radtest/venv/3.3/lib/python3.3/site-packages/cryptography/x509/__init__.py", line 7, in <module>
    from cryptography.x509.base import (
  File "/Users/paul/radtest/venv/3.3/lib/python3.3/site-packages/cryptography/x509/base.py", line 15, in <module>
    from cryptography.x509.extensions import Extension, ExtensionType
  File "/Users/paul/radtest/venv/3.3/lib/python3.3/site-packages/cryptography/x509/extensions.py", line 19, in <module>
    from cryptography.hazmat.primitives import constant_time, serialization
  File "/Users/paul/radtest/venv/3.3/lib/python3.3/site-packages/cryptography/hazmat/primitives/constant_time.py", line 9, in <module>
    from cryptography.hazmat.bindings._constant_time import lib
ImportError: dlopen(/Users/paul/radtest/venv/3.3/lib/python3.3/site-packages/cryptography/hazmat/bindings/_constant_time.so, 2): Symbol not found: _PyExc_TypeError
  Referenced from: /Users/paul/radtest/venv/3.3/lib/python3.3/site-packages/cryptography/hazmat/bindings/_constant_time.so
  Expected in: /Users/paul/radtest/venv/3.3/bin/python
 in /Users/paul/radtest/venv/3.3/lib/python3.3/site-packages/cryptography/hazmat/bindings/_constant_time.so
```

**Comment by reaperhulk** [comment]
Hmm, I'm surprised the python.org python is pulling `cryptography-1.4-cp33-cp33m-macosx_10_10_x86_64.whl` as its wheel. If you download [cryptography-1.4-cp33-cp33m-macosx_10_6_intel.whl ](https://pypi.python.org/packages/21/1c/c6626d92de1119709920890e615eefa9001e252d876e9acd68efc27971cf/cryptography-1.4-cp33-cp33m-macosx_10_6_intel.whl#md5=7d2771e0d40ea3cb3849ea97b2951974) and install it directly do you see the same error?

**Comment by radssh** [comment]
Surprised? The system is 10.10, which does have 3.5.0 as its python3 default, but for testing purposes I have python.org packages (binary, not source) installed to test for 3.3 and 3.4 using virtualenv, so matching 3.3 and macos_10_10 in this case seems correct, although I'm still coming up to speed on wheels.

The 3.4 wheel for macos_10_10 did not have any ImportError; just the 3.3

As far as forcing the macos_10_6 wheel into place, there is still a dlopen() error, but now from cffi_backend on a different symbol:

```
  File "/Users/paul/radtest/venv/3.3/test/lib/python3.3/site-packages/cryptography/hazmat/primitives/constant_time.py", line 9, in <module>
    from cryptography.hazmat.bindings._constant_time import lib
ImportError: dlopen(/Users/paul/radtest/venv/3.3/test/lib/python3.3/site-packages/_cffi_backend.so, 2): Symbol not found: _PyByteArray_Type
  Referenced from: /Users/paul/radtest/venv/3.3/test/lib/python3.3/site-packages/_cffi_backend.so
  Expected in: /Users/paul/radtest/venv/3.3/test/bin/python
 in /Users/paul/radtest/venv/3.3/test/lib/python3.3/site-packages/_cffi_backend.so
```

Did a pip (8.1.2) install with --no-cache-dir to double check, and indeed it is pulling down cryptography-1.4-cp33-cp33m-macosx_10_10_x86_64.whl. System is 10.10 so Python 3.5.1 is the system default, but I have packages for 3.3 and 3.4 for testing in virtualenvs, and

**Comment by reaperhulk** [comment]
The surprising component of that is that the python.org releases are universal binaries and I thought they ignored the x86_64 only builds. Clearly that isn't the case though! I'm very much unsure what's going on here as `PyExc_TypeError` is provided by Python itself so that symbol should definitely be available...

**Comment by alex** [comment]
No movement in several months, closing.
