### ISSUE TITLE
Creating self-signed cert, tutorial doesn't work?

### ISSUE THREAD

**Issue by Safihre** [pyca/cryptography#3143]
Trying to create a self-signed certificate, but the tutorial in the docs doesn't work (https://cryptography.io/en/latest/x509/tutorial/).

It's missing the import of ```datetime``` and declaration of ```private_key```, so I assume  
```python
private_key = key
```
Is this correct?
If I use that, in the end it tells me this:
```
Traceback (most recent call last):
  File "TEST3.py", line 46, in <module>
    ).sign(private_key, hashes.SHA256(), default_backend())
  File "C:\Python27\Lib\site-packages\cryptography\x509\base.py", line 534, in sign
    raise ValueError("A certificate must have a serial number")
ValueError: A certificate must have a serial number
```
I have no clue what this means? Google isn't helping me either.
This is how I combined the examples on the docs:
```python
from cryptography.hazmat.backends import default_backend
from cryptography.hazmat.primitives import serialization, hashes
from cryptography.hazmat.primitives.asymmetric import rsa
from cryptography import x509
from cryptography.x509.oid import NameOID
import datetime

# Generate our key
key = rsa.generate_private_key(
    public_exponent=65537,
    key_size=2048,
    backend=default_backend()
)
# Write our key to disk for safe keeping
with open("key.pem", "wb") as f:
    f.write(key.private_bytes(
        encoding=serialization.Encoding.PEM,
        format=serialization.PrivateFormat.TraditionalOpenSSL,
        encryption_algorithm=serialization.BestAvailableEncryption(b"passprferferferferfhrase"),
    ))
# Various details about who we are. For a self-signed certificate the
# subject and issuer are always the same.
subject = issuer = x509.Name([
    x509.NameAttribute(NameOID.COUNTRY_NAME, u"US"),
    x509.NameAttribute(NameOID.STATE_OR_PROVINCE_NAME, u"CA"),
    x509.NameAttribute(NameOID.LOCALITY_NAME, u"San Francisco"),
    x509.NameAttribute(NameOID.ORGANIZATION_NAME, u"My Company"),
    x509.NameAttribute(NameOID.COMMON_NAME, u"mysite.com"),
])
cert = x509.CertificateBuilder().subject_name(
    subject
).issuer_name(
    issuer
).public_key(
    private_key.public_key()
).not_valid_before(
    datetime.datetime.utcnow()
).not_valid_after(
    # Our certificate will be valid for 10 days
    datetime.datetime.utcnow() + datetime.timedelta(days=10)
).add_extension(
    x509.SubjectAlternativeName([x509.DNSName(u"localhost")]),
    critical=False,
# Sign our certificate with our private key
).sign(private_key, hashes.SHA256(), default_backend())

# Write our certificate out to disk.
with open("cert.cert", "wb") as f:
    f.write(cert.public_bytes(serialization.Encoding.PEM))
```

**Comment by Safihre** [comment]
Figured it out, added
```
.serial_number(
    random_serial_number()
)
```
And now it works.
