### ISSUE TITLE
ImportError: undefined symbol: EC_KEY_get_flags

### ISSUE THREAD

**Issue by Siecje** [pyca/cryptography#3147]
I am trying to make a SSH connection with paramiko but I'm getting the following error

``` Python
#$ python
#Python 2.7.9 (default, Jan 27 2015, 01:27:20) 
#[GCC 4.9.1] on linux2
#Type "help", "copyright", "credits" or "license" for more information.
>>> import paramiko
>>> client = paramiko.SSHClient()
>>> client.connect(host, port, login, password)
No handlers could be found for logger "paramiko.transport"
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/path/python/lib/python2.7/site-packages/paramiko/client.py", line 338, in connect
    t.start_client()
  File "/path/python/lib/python2.7/site-packages/paramiko/transport.py", line 493, in start_client
    raise e
ImportError: /path/python/lib/python2.7/site-packages/cryptography/hazmat/bindings/_openssl.so: undefined symbol: EC_KEY_get_flags
>>> 
```

Paramiko version 2.0.2
Cryptography version 1.5

I have installed `openssl` and `openssl-dev` for my platform.

**Comment by alex** [comment]
What OS are you on, how did you install cryptography?

**Comment by reaperhulk** [comment]
You mentioned in IRC that you were running tinycore linux, but let's track the bug here. What version of OpenSSL do you have?

**Comment by alex** [comment]
No response in >1 month. Will reopen if there are more details.
