### ISSUE TITLE
Issue with local git-hub repository setup with reviewboard

### ISSUE THREAD

**Issue by gobindpraharaj** [pyca/cryptography#3174]
Hi folks,

**I have setup a local git repository in a fedora machine.**
## Details are as follows:

nms-repo@10.0.7.20:/home/nms-repo/webnms-main.git
with git user uid and password.

If i do clone the repository using git-bash it clones successfully.

But same thing If I do from reviewboard, I get an error as below:

2016-09-26 11:32:38,969 - ERROR -  - Exception thrown for user gobind at http://10.0.4.173/admin/db/scmtools/repository/add/

```
Unknown OpenSSL error. This error is commonly encountered when another library is not cleaning up the OpenSSL error stack. If you are using cryptography with another library that uses OpenSSL try disabling it before reporting a bug. Otherwise please file an issue at https://github.com/pyca/cryptography/issues with information on how to reproduce this. ([_OpenSSLErrorWithText(code=151441516L, lib=9, func=109, reason=108, reason_text='error:0906D06C:PEM routines:PEM_read_bio:no start line'), _OpenSSLErrorWithText(code=151441516L, lib=9, func=109, reason=108, reason_text='error:0906D06C:PEM routines:PEM_read_bio:no start line')])
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/Django-1.6.11-py2.6.egg/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/lib/python2.6/site-packages/Django-1.6.11-py2.6.egg/django/contrib/admin/options.py", line 465, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/usr/lib/python2.6/site-packages/Django-1.6.11-py2.6.egg/django/utils/decorators.py", line 99, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/usr/lib/python2.6/site-packages/Django-1.6.11-py2.6.egg/django/views/decorators/cache.py", line 52, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/usr/lib/python2.6/site-packages/Django-1.6.11-py2.6.egg/django/contrib/admin/sites.py", line 198, in inner
    return view(request, *args, **kwargs)
  File "/usr/lib/python2.6/site-packages/Django-1.6.11-py2.6.egg/django/utils/decorators.py", line 29, in _wrapper
    return bound_func(*args, **kwargs)
  File "/usr/lib/python2.6/site-packages/Django-1.6.11-py2.6.egg/django/utils/decorators.py", line 99, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/usr/lib/python2.6/site-packages/Django-1.6.11-py2.6.egg/django/utils/decorators.py", line 25, in bound_func
    return func(self, *args2, **kwargs2)
  File "/usr/lib/python2.6/site-packages/Django-1.6.11-py2.6.egg/django/db/transaction.py", line 371, in inner
    return func(*args, **kwargs)
  File "/usr/lib/python2.6/site-packages/Django-1.6.11-py2.6.egg/django/contrib/admin/options.py", line 1145, in add_view
    form = ModelForm(request.POST, request.FILES)
  File "/usr/lib/python2.6/site-packages/ReviewBoard-2.5.6.1-py2.6.egg/reviewboard/scmtools/forms.py", line 356, in __init__
    self.ssh_client = SSHClient(namespace=self.local_site_name)
  File "/usr/lib/python2.6/site-packages/ReviewBoard-2.5.6.1-py2.6.egg/reviewboard/ssh/client.py", line 65, in __init__
    self.load_host_keys('')
  File "/usr/lib/python2.6/site-packages/paramiko-2.0.2-py2.6.egg/paramiko/client.py", line 124, in load_host_keys
    self._host_keys.load(filename)
  File "/usr/lib/python2.6/site-packages/ReviewBoard-2.5.6.1-py2.6.egg/reviewboard/ssh/client.py", line 31, in load
    entry = HostKeyEntry.from_line(line)
  File "/usr/lib/python2.6/site-packages/paramiko-2.0.2-py2.6.egg/paramiko/hostkeys.py", line 331, in from_line
    key = RSAKey(data=decodebytes(key))
  File "/usr/lib/python2.6/site-packages/paramiko-2.0.2-py2.6.egg/paramiko/rsakey.py", line 58, in __init__
    ).public_key(default_backend())
  File "/usr/lib/python2.6/site-packages/cryptography-1.5-py2.6-linux-x86_64.egg/cryptography/hazmat/backends/__init__.py", line 35, in default_backend
    _default_backend = MultiBackend(_available_backends())
  File "/usr/lib/python2.6/site-packages/cryptography-1.5-py2.6-linux-x86_64.egg/cryptography/hazmat/backends/__init__.py", line 22, in _available_backends
    "cryptography.backends"
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 2264, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python2.6/site-packages/cryptography-1.5-py2.6-linux-x86_64.egg/cryptography/hazmat/backends/openssl/__init__.py", line 7, in <module>
    from cryptography.hazmat.backends.openssl.backend import backend
  File "/usr/lib/python2.6/site-packages/cryptography-1.5-py2.6-linux-x86_64.egg/cryptography/hazmat/backends/openssl/backend.py", line 47, in <module>
    from cryptography.hazmat.bindings.openssl import binding
  File "/usr/lib/python2.6/site-packages/cryptography-1.5-py2.6-linux-x86_64.egg/cryptography/hazmat/bindings/openssl/binding.py", line 234, in <module>
    Binding.init_static_locks()
  File "/usr/lib/python2.6/site-packages/cryptography-1.5-py2.6-linux-x86_64.egg/cryptography/hazmat/bindings/openssl/binding.py", line 180, in init_static_locks
    cls._ensure_ffi_initialized()
  File "/usr/lib/python2.6/site-packages/cryptography-1.5-py2.6-linux-x86_64.egg/cryptography/hazmat/bindings/openssl/binding.py", line 175, in _ensure_ffi_initialized
    cls._register_osrandom_engine()
  File "/usr/lib/python2.6/site-packages/cryptography-1.5-py2.6-linux-x86_64.egg/cryptography/hazmat/bindings/openssl/binding.py", line 140, in _register_osrandom_engine
    _openssl_assert(cls.lib, cls.lib.ERR_peek_error() == 0)
  File "/usr/lib/python2.6/site-packages/cryptography-1.5-py2.6-linux-x86_64.egg/cryptography/hazmat/bindings/openssl/binding.py", line 62, in _openssl_assert
    errors_with_text
InternalError: Unknown OpenSSL error. This error is commonly encountered when another library is not cleaning up the OpenSSL error stack. If you are using cryptography with another library that uses OpenSSL try disabling it before reporting a bug. Otherwise please file an issue at https://github.com/pyca/cryptography/issues with information on how to reproduce this. ([_OpenSSLErrorWithText(code=151441516L, lib=9, func=109, reason=108, reason_text='error:0906D06C:PEM routines:PEM_read_bio:no start line'), _OpenSSLErrorWithText(code=151441516L, lib=9, func=109, reason=108, reason_text='error:0906D06C:PEM routines:PEM_read_bio:no start line')])
2016-09-26 11:32:53,299 - ERROR -  - Git: Failed to find valid repository ssh://nms-repo@10.0.7.20/home/nms-repo/webnms-main.git: /usr/lib/python2.6/site-packages/cryptography-1.5-py2.6-linux-x86_64.egg/cryptography/__init__.py:26: DeprecationWarning: Python 2.6 is no longer supported by the Python core team, please upgrade your Python. A future version of cryptography will drop support for Python 2.6
  DeprecationWarning
Error connecting to server: No authentication methods available
fatal: The remote end hung up unexpectedly
```

Please do help me get this issue resolved.

Thank you,
Gobind

**Comment by pgobind** [comment]
Hi Guys,

Please do help me with this issue.

Thanks.

**Comment by reaperhulk** [comment]
Does this use `mod_wsgi`?

**Comment by gobindpraharaj** [comment]
Yes, it does use mod_wsgi...

**Comment by reaperhulk** [comment]
Okay, there are two ways to resolve this bug for now. You can either [modify your mod_wsgi config](https://cryptography.io/en/latest/faq/#starting-cryptography-using-mod-wsgi-produces-an-internalerror-during-a-call-in-register-osrandom-engine) or downgrade pyopenssl to 16.0 from 16.1. That should resolve the issue for now.

**Comment by gobindpraharaj** [comment]
Hi @reaperhulk ,

Sorry for the delay in the communication.

OpenSSL version is OpenSSL 1.0.1e-fips 11 Feb 2013

Could you please elaborate.

**Comment by reaperhulk** [comment]
Sorry I mixed up errors here. The issue is that something else in your process is not cleaning the OpenSSL error queue and when cryptography starts up it detects that situation and refuses to initialize. I think we've discussed this exact scenario in a previous issue but I don't have time to search through them right now.

**Comment by gobindpraharaj** [comment]
Hi @reaperhulk 

Please find the recent stack trace after I fixed the openSSL cleaning issue.

2016-10-14 11:23:52,461 - DEBUG -  - Cache miss for key jsi18n-djangojs-reviewboard_djblets-en-1474460254.
2016-10-14 11:29:06,525 - INFO -  - Reloading logging settings
2016-10-14 11:29:06,576 - DEBUG -  - GitTool: Attempting ssh connection with host: 10.0.7.20, username: nms-repo
2016-10-14 11:29:06,579 - DEBUG -  - starting thread (client mode): 0xa4d8be50L
2016-10-14 11:29:06,579 - DEBUG -  - Local version/idstring: SSH-2.0-paramiko_2.0.2
2016-10-14 11:29:06,597 - DEBUG -  - Remote version/idstring: SSH-2.0-OpenSSH_6.6.1p1 Ubuntu-2ubuntu2.8
2016-10-14 11:29:06,598 - INFO -  - Connected (version 2.0, client OpenSSH_6.6.1p1)
2016-10-14 11:29:06,600 - DEBUG -  - kex algos:[u'curve25519-sha256@libssh.org', u'ecdh-sha2-nistp256', u'ecdh-sha2-nistp384', u'ecdh-sha2-nistp521', u'diffie-hellman-group-exchange-sha256', u'diffie-hellman-group-exchange-sha1', u'diffie-hellman-group14-sha1', u'diffie-hellman-group1-sha1'] server key:[u'ssh-rsa', u'ssh-dss', u'ecdsa-sha2-nistp256', u'ssh-ed25519'] client encrypt:[u'aes128-ctr', u'aes192-ctr', u'aes256-ctr', u'arcfour256', u'arcfour128', u'aes128-gcm@openssh.com', u'aes256-gcm@openssh.com', u'chacha20-poly1305@openssh.com', u'aes128-cbc', u'3des-cbc', u'blowfish-cbc', u'cast128-cbc', u'aes192-cbc', u'aes256-cbc', u'arcfour', u'rijndael-cbc@lysator.liu.se'] server encrypt:[u'aes128-ctr', u'aes192-ctr', u'aes256-ctr', u'arcfour256', u'arcfour128', u'aes128-gcm@openssh.com', u'aes256-gcm@openssh.com', u'chacha20-poly1305@openssh.com', u'aes128-cbc', u'3des-cbc', u'blowfish-cbc', u'cast128-cbc', u'aes192-cbc', u'aes256-cbc', u'arcfour', u'rijndael-cbc@lysator.liu.se'] client mac:[u'hmac-md5-etm@openssh.com', u'hmac-sha1-etm@openssh.com', u'umac-64-etm@openssh.com', u'umac-128-etm@openssh.com', u'hmac-sha2-256-etm@openssh.com', u'hmac-sha2-512-etm@openssh.com', u'hmac-ripemd160-etm@openssh.com', u'hmac-sha1-96-etm@openssh.com', u'hmac-md5-96-etm@openssh.com', u'hmac-md5', u'hmac-sha1', u'umac-64@openssh.com', u'umac-128@openssh.com', u'hmac-sha2-256', u'hmac-sha2-512', u'hmac-ripemd160', u'hmac-ripemd160@openssh.com', u'hmac-sha1-96', u'hmac-md5-96'] server mac:[u'hmac-md5-etm@openssh.com', u'hmac-sha1-etm@openssh.com', u'umac-64-etm@openssh.com', u'umac-128-etm@openssh.com', u'hmac-sha2-256-etm@openssh.com', u'hmac-sha2-512-etm@openssh.com', u'hmac-ripemd160-etm@openssh.com', u'hmac-sha1-96-etm@openssh.com', u'hmac-md5-96-etm@openssh.com', u'hmac-md5', u'hmac-sha1', u'umac-64@openssh.com', u'umac-128@openssh.com', u'hmac-sha2-256', u'hmac-sha2-512', u'hmac-ripemd160', u'hmac-ripemd160@openssh.com', u'hmac-sha1-96', u'hmac-md5-96'] client compress:[u'none', u'zlib@openssh.com'] server compress:[u'none', u'zlib@openssh.com'] client lang:[u''] server lang:[u''] kex follows?False
2016-10-14 11:29:06,600 - DEBUG -  - Kex agreed: diffie-hellman-group1-sha1
2016-10-14 11:29:06,600 - DEBUG -  - Cipher agreed: aes128-ctr
2016-10-14 11:29:06,601 - DEBUG -  - MAC agreed: hmac-sha2-256
2016-10-14 11:29:06,601 - DEBUG -  - Compression agreed: none
2016-10-14 11:29:06,676 - DEBUG -  - kex engine KexGroup1 specified hash_algo <built-in function openssl_sha1>
2016-10-14 11:29:06,676 - DEBUG -  - Switch to new keys ...
2016-10-14 11:29:06,715 - DEBUG -  - userauth is OK
2016-10-14 11:29:06,820 - INFO -  - Authentication (password) successful!
2016-10-14 11:29:06,921 - DEBUG -  - EOF in transport thread
2016-10-14 11:29:08,577 - ERROR -  - Git: Failed to find valid repository ssh://nms-repo@**.**.*.***/home/nms-repo/webnms-main.git: /usr/lib/python2.6/site-packages/cryptography-1.5-py2.6-linux-x86_64.egg/cryptography/__init__.py:26: DeprecationWarning: Python 2.6 is no longer supported by the Python core team, please upgrade your Python. A future version of cryptography will drop support for Python 2.6
  DeprecationWarning
Error connecting to server: No authentication methods available
fatal: The remote end hung up unexpectedly

**Comment by reaperhulk** [comment]
Closing since there's no activity and the latest comment indicates an issue unrelated to cryptography. If there's new information please reopen as needed.
