### ISSUE TITLE
Deadlock involving RSA PKeys

### ISSUE THREAD

**Issue by aglasgall** [pyca/cryptography#3195]
Test case:

```
from OpenSSL.crypto import FILETYPE_PEM, load_privatekey, sign
import threading
import time
import sys
import traceback

def start_workers(N, key):

    for n in range(N):
        new_thread = threading.Thread(
            target=worker,
            name="daemon-worker-thread-{}".format(n),
            args=(n, key, ))
        new_thread.daemon = True
        print('start {}'.format(n))
        new_thread.start()


def worker(idx, key):
    try:
        while True:
            pkey = load_privatekey(FILETYPE_PEM, key)
            sign(pkey, 'some message that doesnt really matter', "sha256")
            print('worker {} did something!'.format(idx))
    except:
        traceback.print_exc()


if __name__ == '__main__':
    kfile = sys.argv[1]
    with open(kfile, 'rb') as fh:
        key = fh.read()

    start_workers(8, key)

    time.sleep(60)
    print('I am done')
```

Run with the path to a PEM-encoded RSA private key as an argument. It doesn't deadlock every time., but it definitely does at least a third to half of the time.

The cryptography locking callback is installed because python and cryptography are separately statically linked against openssl

**Comment by aglasgall** [comment]
This may be caused by GC being triggered from the locking callback, resulting eventually in a finalizer for a PKey calling the locking callback.

**Comment by aglasgall** [comment]
update: okay, I know that this case uses pyopenssl instead of just cryptography, but it the hang is definitely in cryptography's openssl lock callback, so...

**Comment by reaperhulk** [comment]
Yep, this is cryptography's problem. What version of Python are you seeing this on? I've been unable to replicate so far on 2.7.10 on macOS, but that doesn't mean much.

**Comment by aglasgall** [comment]
3.5.either 1 or 2 on Linux (built from source) against OpenSSL 1.0.2, uh, g, I think.

**Comment by aglasgall** [comment]
Stack traces for the deadlock that we saw with 1.2.2 (possibly _not_ the same as the deadlock exhibited by this test case) follow:

py-bt:

```
Thread 18 (LWP 11012):
Traceback (most recent call first):
  <built-in method acquire of _thread.lock object at remote 0x7f2fb5935b98>
  File "[redacted]/lib/cryptography/hazmat/bindings/openssl/binding.py", line 189, in _lock_cb
    lock.acquire()
  <built-in method EVP_SignFinal of CompiledLib object at remote 0x7f2fb62cb848>
  File "[redacted]/lib/OpenSSL/crypto.py", line 2413, in sign
    md_ctx, signature_buffer, signature_length, pkey._pkey)
  File "[redacted]/app/[redacted].py", line 50, in sign_message
    message.security_data.signature = sign(pkey, message.payload, "sha256")
  File "[redacted]/app/[redacted].py", line 37, in _make_publish_message
    sign_message(message)
[...unrelated frames...]

[several other threads with the same stack...]
Thread 13 (LWP 11007):
Traceback (most recent call first):
  <built-in method acquire of _thread.lock object at remote 0x7f2fb5935b98>
  File "[redacted]/lib/cryptography/hazmat/bindings/openssl/binding.py", line 189, in _lock_cb
    lock.acquire()
  <built-in method EVP_PKEY_free of CompiledLib object at remote 0x7f2fb62cb848>
  Garbage-collecting
  File "[redacted]/lib/cryptography/hazmat/bindings/openssl/binding.py", line 189, in _lock_cb
    lock.acquire()
  <built-in method EVP_SignFinal of CompiledLib object at remote 0x7f2fb62cb848>
  File "[redacted]/lib/OpenSSL/crypto.py", line 2413, in sign
    md_ctx, signature_buffer, signature_length, pkey._pkey)
  File "[redacted]/app/[redacted].py", line 50, in sign_message
    message.security_data.signature = sign(pkey, message.payload, "sha256")
  File "[redacted]/app/[redacted].py", line 37, in _make_publish_message
    sign_message(message)
[...unrelated frames...]
```

C backtraces coming shortly. Thread 13 is the interesting one. I know 1.2.2 is old, but a quick inspection of the relevant code shows no obvious reason to believe that 1.5.2 does not also have this issue (and even if it doesn't, it certainly has the issue exhibited by the test case in the issue proper)

**Comment by alex** [comment]
Note to self: these stacks are upside down relative to the usual python formatting

**Comment by aglasgall** [comment]
C backtraces:

```
Thread 18 (LWP 11012):
Thread 18 (LWP 11012):
#0  0x00007f2fba693fd0 in sem_wait () from /lib/x86_64-linux-gnu/libpthread.so.0
#1  0x00000000004fd2f5 in PyThread_acquire_lock_timed (lock=0x2c3c680, microseconds=-1000000, intr_flag=1)
    at Python/thread_pthread.h:352
#2  0x0000000000500c14 in acquire_timed (lock=0x2c3c680, timeout=-1000000000) at ./Modules/_threadmodule.c:68
#3  0x0000000000500c7d in lock_PyThread_acquire_lock (self=0x7f2fb5935b98, args=<optimized out>, 
    kwds=<optimized out>) at ./Modules/_threadmodule.c:151
#4  0x000000000054d8a6 in PyCFunction_Call (func=
    <built-in method acquire of _thread.lock object at remote 0x7f2fb5935b98>, args=<optimized out>, 
    kwds=<optimized out>) at Objects/methodobject.c:98
#5  0x00000000004c8de4 in call_function (oparg=<optimized out>, pp_stack=0x7f2f6effb1f8) at Python/ceval.c:4655
#6  PyEval_EvalFrameEx (f=<optimized out>, throwflag=<optimized out>) at Python/ceval.c:3185
#7  0x00000000004cab2c in _PyEval_EvalCodeWithName (_co=<optimized out>, globals=<optimized out>, 
    locals=<optimized out>, args=<optimized out>, argcount=5, kws=0x0, kwcount=0, defs=0x0, defcount=0, kwdefs=0x0, 
    closure=0x0, name=0x0, qualname=0x0) at Python/ceval.c:3966
#8  0x00000000004cac38 in PyEval_EvalCodeEx (_co=<optimized out>, globals=<optimized out>, locals=<optimized out>, 
    args=<optimized out>, argcount=<optimized out>, kws=<optimized out>, kwcount=0, defs=0x0, defcount=0, kwdefs=
    0x0, closure=0x0) at Python/ceval.c:3987
#9  0x0000000000549b85 in function_call (func=<function at remote 0x7f2fb62db0d0>, arg=
    (<type at remote 0x2c0ab18>, 5, 9, <_cffi_backend.CData at remote 0x7f2f8c20f8a0>, 262), kw=0x0)
    at Objects/funcobject.c:632
#10 0x00000000004322c7 in PyObject_Call (func=<function at remote 0x7f2fb62db0d0>, arg=<optimized out>, 
    kw=<optimized out>) at Objects/abstract.c:2165
#11 0x00000000005404ff in method_call (func=<function at remote 0x7f2fb62db0d0>, arg=
    (<type at remote 0x2c0ab18>, 5, 9, <_cffi_backend.CData at remote 0x7f2f8c20f8a0>, 262), kw=<optimized out>)
    at Objects/classobject.c:330
#12 0x00000000004322c7 in PyObject_Call (func=<method at remote 0x7f2fb6b94b08>, arg=<optimized out>, 
    kw=<optimized out>) at Objects/abstract.c:2165
#13 0x00007f2fb5b6fba7 in general_invoke_callback (decode_args_from_libffi=0, result=0x7f2f6effb570, 
    args=<optimized out>, userdata=0x7f2fb62f67c8) at c/_cffi_backend.c:5030
#14 0x00007f2fb5b745f4 in cffi_call_python (externpy=0x7f2fb62b13a0, args=0x7f2f6effb570 "\005")
    at c/call_python.c:211
#15 0x00007f2fb5e34154 in Cryptography_locking_cb (a0=<optimized out>, a1=<optimized out>, a2=<optimized out>, 
    a3=<optimized out>) at build/temp.linux-x86_64-3.5/_openssl.c:11817
#16 0x00007f2fb5fb1da4 in rsa_get_blinding (rsa=0x7f2eb5c90ed0, local=0x7f2f6effb640, ctx=0x7f2eb5c76100)
    at rsa_eay.c:262
#17 0x00007f2fb5fb2bd0 in RSA_eay_private_encrypt (flen=<optimized out>, from=0x0, to=0x7f2eb5c91150 "", rsa=
    0x7f2eb5c90ed0, padding=1) at rsa_eay.c:405
#18 0x00007f2fb5f091d2 in RSA_sign (type=672, m=<optimized out>, m_len=<optimized out>, sigret=0x7f2eb5c91150 "", 
    siglen=0x7f2f6effb770, rsa=0x7f2eb5c90ed0) at rsa_sign.c:135
#19 0x00007f2fb5fb6835 in pkey_rsa_sign (ctx=0x7f2eb5c8eee0, sig=0x7f2eb5c91150 "", siglen=0x7f2f6effb7f0, tbs=
    0x7f2f6effb800 "[redacted]", tbslen=32) at rsa_pmeth.c:271
#20 0x00007f2fb5f297d4 in EVP_SignFinal (ctx=0x7f2ea25f4ba0, sigret=0x7f2eb5c91150 "", siglen=0x7f2ea288a3e0, pkey=
    0x7f2eb5c8ca80) at p_sign.c:104
#21 0x00007f2fb5e72fee in _cffi_f_EVP_SignFinal (self=<optimized out>, args=<optimized out>)
    at build/temp.linux-x86_64-3.5/_openssl.c:39341
#22 0x000000000054d879 in PyCFunction_Call (func=
    <built-in method EVP_SignFinal of CompiledLib object at remote 0x7f2fb62cb848>, args=<optimized out>, 
    kwds=<optimized out>) at Objects/methodobject.c:121
#23 0x00000000004c8de4 in call_function (oparg=<optimized out>, pp_stack=0x7f2f6effba38) at Python/ceval.c:4655
#24 PyEval_EvalFrameEx (f=<optimized out>, throwflag=<optimized out>) at Python/ceval.c:3185
#25 0x00000000004ca153 in fast_function (nk=<optimized out>, na=<optimized out>, n=3, pp_stack=0x7f2f6effbb88, func=
    <function at remote 0x7f2fb58e4840>) at Python/ceval.c:4754
[...uninteresting frames...]
[...several other threads with the same stack...]

Thread 13 (LWP 11007):
#0  0x00007f2fba693fd0 in sem_wait () from /lib/x86_64-linux-gnu/libpthread.so.0
#1  0x00000000004fd2f5 in PyThread_acquire_lock_timed (lock=0x2c3c680, microseconds=-1000000, intr_flag=1)
    at Python/thread_pthread.h:352
#2  0x0000000000500c14 in acquire_timed (lock=0x2c3c680, timeout=-1000000000) at ./Modules/_threadmodule.c:68
#3  0x0000000000500c7d in lock_PyThread_acquire_lock (self=0x7f2fb5935b98, args=<optimized out>, 
    kwds=<optimized out>) at ./Modules/_threadmodule.c:151
#4  0x000000000054d8a6 in PyCFunction_Call (func=
    <built-in method acquire of _thread.lock object at remote 0x7f2fb5935b98>, args=<optimized out>, 
    kwds=<optimized out>) at Objects/methodobject.c:98
#5  0x00000000004c8de4 in call_function (oparg=<optimized out>, pp_stack=0x7f2f8dddc6c8) at Python/ceval.c:4655
#6  PyEval_EvalFrameEx (f=<optimized out>, throwflag=<optimized out>) at Python/ceval.c:3185
#7  0x00000000004cab2c in _PyEval_EvalCodeWithName (_co=<optimized out>, globals=<optimized out>, 
    locals=<optimized out>, args=<optimized out>, argcount=5, kws=0x0, kwcount=0, defs=0x0, defcount=0, kwdefs=0x0, 
    closure=0x0, name=0x0, qualname=0x0) at Python/ceval.c:3966
#8  0x00000000004cac38 in PyEval_EvalCodeEx (_co=<optimized out>, globals=<optimized out>, locals=<optimized out>, 
    args=<optimized out>, argcount=<optimized out>, kws=<optimized out>, kwcount=0, defs=0x0, defcount=0, kwdefs=
    0x0, closure=0x0) at Python/ceval.c:3987
#9  0x0000000000549b85 in function_call (func=<function at remote 0x7f2fb62db0d0>, arg=
    (<type at remote 0x2c0ab18>, 9, 9, <_cffi_backend.CData at remote 0x7f2f8c20f2b0>, 215), kw=0x0)
    at Objects/funcobject.c:632
#10 0x00000000004322c7 in PyObject_Call (func=<function at remote 0x7f2fb62db0d0>, arg=<optimized out>, 
    kw=<optimized out>) at Objects/abstract.c:2165
#11 0x00000000005404ff in method_call (func=<function at remote 0x7f2fb62db0d0>, arg=
    (<type at remote 0x2c0ab18>, 9, 9, <_cffi_backend.CData at remote 0x7f2f8c20f2b0>, 215), kw=<optimized out>)
    at Objects/classobject.c:330
#12 0x00000000004322c7 in PyObject_Call (func=<method at remote 0x7f2fb6b94b08>, arg=<optimized out>, 
    kw=<optimized out>) at Objects/abstract.c:2165
#13 0x00007f2fb5b6fba7 in general_invoke_callback (decode_args_from_libffi=0, result=0x7f2f8dddca40, 
    args=<optimized out>, userdata=0x7f2fb62f67c8) at c/_cffi_backend.c:5030
#14 0x00007f2fb5b745f4 in cffi_call_python (externpy=0x7f2fb62b13a0, args=0x7f2f8dddca40 "\t")
    at c/call_python.c:211
#15 0x00007f2fb5e34154 in Cryptography_locking_cb (a0=<optimized out>, a1=<optimized out>, a2=<optimized out>, 
    a3=<optimized out>) at build/temp.linux-x86_64-3.5/_openssl.c:11817
#16 0x00007f2fb5ec9997 in CRYPTO_add_lock (pointer=0x7f2f781f6720, amount=-1, type=9, file=
    0x7f2fb601402a "rsa_lib.c", line=<optimized out>) at cryptlib.c:627
#17 0x00007f2fb5f08bc9 in RSA_free (r=0x7f2f781f66b0) at rsa_lib.c:215
#18 0x00007f2fb5f2a23a in EVP_PKEY_free_it (x=0x7f2f78296260) at p_lib.c:419
#19 EVP_PKEY_free (x=0x7f2f78296260) at p_lib.c:410
#20 0x00007f2fb5e42b48 in _cffi_f_EVP_PKEY_free (self=<optimized out>, arg0=
    <_cffi_backend.CData at remote 0x7f2f8c20fd28>) at build/temp.linux-x86_64-3.5/_openssl.c:38303
#21 0x000000000054d85c in PyCFunction_Call (func=
    <built-in method EVP_PKEY_free of CompiledLib object at remote 0x7f2fb62cb848>, args=<optimized out>, 
    kwds=<optimized out>) at Objects/methodobject.c:134
#22 0x00000000004322c7 in PyObject_Call (func=
    <built-in method EVP_PKEY_free of CompiledLib object at remote 0x7f2fb62cb848>, arg=<optimized out>, 
    kw=<optimized out>) at Objects/abstract.c:2165
#23 0x0000000000432cd0 in PyObject_CallFunctionObjArgs (callable=
    <built-in method EVP_PKEY_free of CompiledLib object at remote 0x7f2fb62cb848>) at Objects/abstract.c:2445
#24 0x00007f2fb5b69614 in gcp_finalize (destructor=
    <built-in method EVP_PKEY_free of CompiledLib object at remote 0x7f2fb62cb848>, origobj=
    <_cffi_backend.CData at remote 0x7f2f8c20fd28>) at c/_cffi_backend.c:1681
#25 0x00000000004ff34b in finalize_garbage (collectable=0x7f2f8dddcd20) at Modules/gcmodule.c:808
#26 collect (generation=0, n_collected=0x7f2f8dddcdf0, n_uncollectable=0x7f2f8dddcdf8, nofail=0)
    at Modules/gcmodule.c:1003
#27 0x00000000004ffc9c in collect_with_callback (generation=0) at Modules/gcmodule.c:1119
#28 0x00000000004ffdcf in collect_generations () at Modules/gcmodule.c:1142
#29 _PyObject_GC_Alloc (use_calloc=<optimized out>, basicsize=<optimized out>) at Modules/gcmodule.c:1708
#30 0x00000000005004dd in _PyObject_GC_New (tp=0x846dc0) at Modules/gcmodule.c:1730
#31 0x000000000054dccd in PyCFunction_NewEx (ml=0x823cc0, self=<optimized out>, module=<optimized out>)
    at Objects/methodobject.c:36
#32 0x0000000000545c86 in method_get (obj=<_thread.lock at remote 0x7f2fb5935d00>, descr=0x7f2fbaa61318, 
    type=<optimized out>) at Objects/descrobject.c:128
#33 method_get (descr=0x7f2fbaa61318, obj=<_thread.lock at remote 0x7f2fb5935d00>, type=<optimized out>)
    at Objects/descrobject.c:122
#34 0x000000000046ca1a in _PyObject_GenericGetAttrWithDict (obj=<_thread.lock at remote 0x7f2fb5935d00>, name=
    'acquire', dict=0x0) at Objects/object.c:1097
#35 0x00000000004c362b in PyEval_EvalFrameEx (f=<optimized out>, throwflag=<optimized out>) at Python/ceval.c:2692
#36 0x00000000004cab2c in _PyEval_EvalCodeWithName (_co=<optimized out>, globals=<optimized out>, 
    locals=<optimized out>, args=<optimized out>, argcount=5, kws=0x0, kwcount=0, defs=0x0, defcount=0, kwdefs=0x0, 
    closure=0x0, name=0x0, qualname=0x0) at Python/ceval.c:3966
#37 0x00000000004cac38 in PyEval_EvalCodeEx (_co=<optimized out>, globals=<optimized out>, locals=<optimized out>, 
    args=<optimized out>, argcount=<optimized out>, kws=<optimized out>, kwcount=0, defs=0x0, defcount=0, kwdefs=0x0, closure=0x0) at Python/ceval.c:3987
#38 0x0000000000549b85 in function_call (func=<function at remote 0x7f2fb62db0d0>, arg=
    (<type at remote 0x2c0ab18>, 9, 18, <_cffi_backend.CData at remote 0x7f2f8c20fee0>, 230), kw=0x0)
    at Objects/funcobject.c:632
#39 0x00000000004322c7 in PyObject_Call (func=<function at remote 0x7f2fb62db0d0>, arg=<optimized out>, 
    kw=<optimized out>) at Objects/abstract.c:2165
#40 0x00000000005404ff in method_call (func=<function at remote 0x7f2fb62db0d0>, arg=
    (<type at remote 0x2c0ab18>, 9, 18, <_cffi_backend.CData at remote 0x7f2f8c20fee0>, 230), kw=<optimized out>)
    at Objects/classobject.c:330
#41 0x00000000004322c7 in PyObject_Call (func=<method at remote 0x7f2fb6b94b08>, arg=<optimized out>, 
    kw=<optimized out>) at Objects/abstract.c:2165
#42 0x00007f2fb5b6fba7 in general_invoke_callback (decode_args_from_libffi=0, result=0x7f2f8dddd330, 
    args=<optimized out>, userdata=0x7f2fb62f67c8) at c/_cffi_backend.c:5030
#43 0x00007f2fb5b745f4 in cffi_call_python (externpy=0x7f2fb62b13a0, args=0x7f2f8dddd330 "\t")
    at c/call_python.c:211
#44 0x00007f2fb5e34154 in Cryptography_locking_cb (a0=<optimized out>, a1=<optimized out>, a2=<optimized out>, 
    a3=<optimized out>) at build/temp.linux-x86_64-3.5/_openssl.c:11817
#45 0x00007f2fb5f1e6ce in ssleay_rand_add (buf=0x7f2f8dddd468, num=8, add=0) at md_rand.c:230
#46 0x00007f2fb5fa629f in bnrand (pseudorand=0, rnd=0x7f2f7c2be700, bits=2048, top=-1, bottom=0) at bn_rand.c:146
#47 0x00007f2fb5fa6108 in bn_rand_range (pseudo=<optimized out>, r=0x7f2f7c2be700, range=0x7f2f7d08fc90)
    at bn_rand.c:272
#48 0x00007f2fb5fa6951 in BN_BLINDING_create_param (b=0x0, e=<optimized out>, m=<optimized out>, ctx=
    0x7f2f7f008ce0, bn_mod_exp=0x7f2fb5ee6ae0 <BN_mod_exp_mont>, m_ctx=0x0) at bn_blind.c:348
#49 0x00007f2fb5f0b7e9 in RSA_setup_blinding (rsa=0x7f2f7f175dc0, in_ctx=0x7f2f7f008ce0) at rsa_crpt.c:232
#50 0x00007f2fb5fb1eb4 in rsa_get_blinding (rsa=0x7f2f7f175dc0, local=0x7f2f8dddd640, ctx=0x7f2f7f008ce0)
    at rsa_eay.c:270
#51 0x00007f2fb5fb2bd0 in RSA_eay_private_encrypt (flen=<optimized out>, from=0x0, to=0x7f2f7f335450 "", rsa=
    0x7f2f7f175dc0, padding=1) at rsa_eay.c:405
#52 0x00007f2fb5f091d2 in RSA_sign (type=672, m=<optimized out>, m_len=<optimized out>, sigret=0x7f2f7f335450 "", 
    siglen=0x7f2f8dddd770, rsa=0x7f2f7f175dc0) at rsa_sign.c:135
#53 0x00007f2fb5fb6835 in pkey_rsa_sign (ctx=0x7f2f7f0a6bb0, sig=0x7f2f7f335450 "", siglen=0x7f2f8dddd7f0, tbs=
    "[redacted]", tbslen=32) at rsa_pmeth.c:271
#54 0x00007f2fb5f297d4 in EVP_SignFinal (ctx=0x7f2f8c1988a0, sigret=0x7f2f7f335450 "", siglen=0x7f2fac026840, pkey=
    0x7f2f7f20cec0) at p_sign.c:104
#55 0x00007f2fb5e72fee in _cffi_f_EVP_SignFinal (self=<optimized out>, args=<optimized out>)
    at build/temp.linux-x86_64-3.5/_openssl.c:39341
#56 0x000000000054d879 in PyCFunction_Call (func=
    <built-in method EVP_SignFinal of CompiledLib object at remote 0x7f2fb62cb848>, args=<optimized out>, 
    kwds=<optimized out>) at Objects/methodobject.c:121
#57 0x00000000004c8de4 in call_function (oparg=<optimized out>, pp_stack=0x7f2f8dddda38) at Python/ceval.c:4655
#58 PyEval_EvalFrameEx (f=<optimized out>, throwflag=<optimized out>) at Python/ceval.c:3185
#59 0x00000000004ca153 in fast_function (nk=<optimized out>, na=<optimized out>, n=3, pp_stack=0x7f2f8ddddb88, func=
    <function at remote 0x7f2fb58e4840>) at Python/ceval.c:4754
#60 call_function (oparg=<optimized out>, pp_stack=0x7f2f8ddddb88) at Python/ceval.c:4681
#61 PyEval_EvalFrameEx (f=<optimized out>, throwflag=<optimized out>) at Python/ceval.c:3185
[...uninteresting frames...]
```

**Comment by aglasgall** [comment]
These stack traces were on python 3.5.1, cryptography 1.2.2, and openssl 1.0.2e. We're upgrading to newer versions of cryptography and openssl in the medium future.

**Comment by aglasgall** [comment]
py-bt-full of thread 13 is a bit more informative than py-bt:

```
#3 <built-in method acquire of _thread.lock object at remote 0x7f2fb5935b98>
#6 Frame 0x7f2fba937438, for file [redacted]/lib/cryptography/hazmat/bindings/openssl/binding.py, line 189, in _lock_cb (cls=<type at remote 0x2c0ab18>, mode=9, n=9, file=<_cffi_backend.CData at remote 0x7f2f8c20f2b0>, line=215, lock=<_thread.lock at remote 0x7f2fb5935b98>)
    lock.acquire()
#20 <built-in method EVP_PKEY_free of CompiledLib object at remote 0x7f2fb62cb848>
#26 Garbage-collecting
#35 Frame 0x7f2f680060c8, for file [redacted]/lib/cryptography/hazmat/bindings/openssl/binding.py, line 189, in _lock_cb (cls=<type at remote 0x2c0ab18>, mode=9, n=18, file=<_cffi_backend.CData at remote 0x7f2f8c20fee0>, line=230, lock=<_thread.lock at remote 0x7f2fb5935d00>)
    lock.acquire()
#55 <built-in method EVP_SignFinal of CompiledLib object at remote 0x7f2fb62cb848>
[...]
```

So it's not trivially trying to acquire the same lock twice. But there's nothing that says that it doesn't already have the lock (via a call that's not on this stack) that it's now waiting on...

**Comment by reaperhulk** [comment]
#3226 should fix this (just linking the two together since we closed the previous PR in favor of that one)

**Comment by alex** [comment]
Merged.
