### ISSUE TITLE
Cannot install whl on OSX 10.11 due to setuptools

### ISSUE THREAD

**Issue by Safihre** [pyca/cryptography#3326]
Trying to install Cryptography on our completely fresh El Capitan VM (which we use to create App's for all OSX versions) fails because cryptography requires a newer version of `setuptools` which `pip` can't install because it's shared with the OS.
`pip` v9.0.2
```
Collecting cryptography>1.5
  Downloading cryptography-1.7.1-cp27-cp27m-macosx_10_10_intel.whl (2.4MB)
    100% |████████████████████████████████| 2.4MB 288kB/s 
Requirement already satisfied: cffi>=1.4.1 in /Library/Python/2.7/site-packages (from cryptography>1.5)
Requirement already satisfied: pyasn1>=0.1.8 in /Library/Python/2.7/site-packages (from cryptography>1.5)
Collecting setuptools>=11.3 (from cryptography>1.5)
  Downloading setuptools-32.1.0-py2.py3-none-any.whl (477kB)
    100% |████████████████████████████████| 481kB 1.2MB/s 
Requirement already satisfied: six>=1.4.1 in /System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python (from cryptography>1.5)
Requirement already satisfied: idna>=2.0 in /Library/Python/2.7/site-packages (from cryptography>1.5)
Requirement already satisfied: ipaddress in /Library/Python/2.7/site-packages (from cryptography>1.5)
Requirement already satisfied: enum34 in /Library/Python/2.7/site-packages (from cryptography>1.5)
Requirement already satisfied: pycparser in /Library/Python/2.7/site-packages (from cffi>=1.4.1->cryptography>1.5)
Installing collected packages: setuptools, cryptography
  Found existing installation: setuptools 1.1.6
    Uninstalling setuptools-1.1.6:
Exception:
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/commands/install.py", line 342, in run
    prefix=options.prefix_path,
  File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/req/req_set.py", line 778, in install
    requirement.uninstall(auto_confirm=True)
  File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/req/req_install.py", line 754, in uninstall
    paths_to_remove.remove(auto_confirm)
  File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/req/req_uninstall.py", line 115, in remove
    renames(path, new_path)
  File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/utils/__init__.py", line 267, in renames
    shutil.move(old, new)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 299, in move
    copytree(src, real_dst, symlinks=True)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 208, in copytree
    raise Error, errors
Error: [('/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/_markerlib/__init__.py', '/tmp/pip-Ornnwd-uninstall/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/_markerlib/__init__.py', "[Errno 1] Operation not permitted: '/tmp/pip-Ornnwd-uninstall/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/_markerlib/__init__.py'"), ('/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/_markerlib/__init__.pyc', '/tmp/pip-Ornnwd-uninstall/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/_markerlib/__init__.pyc', "[Errno 1] Operation not permitted: '/tmp/pip-Ornnwd-uninstall/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/_markerlib/__init__.pyc'"), ('/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/_markerlib/markers.py', '/tmp/pip-Ornnwd-uninstall/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/_markerlib/markers.py', "[Errno 1] Operation not permitted: '/tmp/pip-Ornnwd-uninstall/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/_markerlib/markers.py'"), ('/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/_markerlib/markers.pyc', '/tmp/pip-Ornnwd-uninstall/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/_markerlib/markers.pyc', "[Errno 1] Operation not permitted: '/tmp/pip-Ornnwd-uninstall/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/_markerlib/markers.pyc'"), ('/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/_markerlib', '/tmp/pip-Ornnwd-uninstall/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/_markerlib', "[Errno 1] Operation not permitted: '/tmp/pip-Ornnwd-uninstall/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/_markerlib'")]
```

**Comment by Safihre** [comment]
Note: I tried to install older versions, but only `pip install cryptography==1.2` works.

**Comment by reaperhulk** [comment]
As a general rule it is extremely unwise to install anything into the system Python global package space. cryptography uses features present in setuptools 11.x and above, (although we actually do have workarounds for environments where setuptools versions don't properly update, that doesn't help if it's properly refusing to install).

Could you tell me a bit more about your requirements here? Could you bundle a newer setuptools with your package? I'm guessing this is for sabnzbd?

**Comment by Safihre** [comment]
Indeed it's for sabnzbd :)  Cryptography 1.2 will do all the functionality we need, absolutely. 
Just wanted to make sure I wasn't doing something wrong and wanted to make sure you were aware since it mentions El Captain support on the documentation :) 
With ApplePyton you have no choice where to install the packages and it will fail, also on official python 2.7.12 it shares global package space and it won't work with `pip`. 
The new python 2.7.13rc1 does have its own package space, but that's still very new..

**Comment by reaperhulk** [comment]
@Safihre Try this workaround for cryptography:

```
pip install idna>=2.0 pyasn1>=0.1.8 six>=1.4.1 enum34 ipaddress cffi>=1.4.1
pip install cryptography --no-deps
```

That should bypass the setuptools version requirement for your particular use case. Of course, this means the first install command is installing every dep (outside of setuptools) and if those requirements change you'll need to update the command.

**Comment by Safihre** [comment]
Thanks! With Python 2.7.13 officially released, everybody should just upgrade to that in case they want to use Cryptography since it uses it's own package space 👍

@reaperhulk saw your PyCon talk on Youtube about packaging and all the steps involved. Very interesting!
