### ISSUE TITLE
import stripe fails - openSSL error

### ISSUE THREAD

**Issue by mhunterak** [pyca/cryptography#3333]
trying to use stripe (https://stripe.com/docs/api/python#authentication) with Python/Flask, with pysqlcipher, and something with my openSSL doesn't want to cooperate. error message below:
```
>>> import stripe
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Python/2.7/site-packages/stripe/__init__.py", line 22, in <module>
    from stripe.resource import (  # noqa
  File "/Library/Python/2.7/site-packages/stripe/resource.py", line 6, in <module>
    from stripe import api_requestor, error, util, upload_api_base
  File "/Library/Python/2.7/site-packages/stripe/api_requestor.py", line 10, in <module>
    from stripe import error, http_client, version, util
  File "/Library/Python/2.7/site-packages/stripe/http_client.py", line 26, in <module>
    import requests
  File "/Library/Python/2.7/site-packages/requests/__init__.py", line 52, in <module>
    from .packages.urllib3.contrib import pyopenssl
  File "/Library/Python/2.7/site-packages/requests/packages/urllib3/contrib/pyopenssl.py", line 49, in <module>
    from cryptography.hazmat.backends.openssl import backend as openssl_backend
  File "/Library/Python/2.7/site-packages/cryptography/hazmat/backends/openssl/__init__.py", line 7, in <module>
    from cryptography.hazmat.backends.openssl.backend import backend
  File "/Library/Python/2.7/site-packages/cryptography/hazmat/backends/openssl/backend.py", line 43, in <module>
    from cryptography.hazmat.bindings.openssl import binding
  File "/Library/Python/2.7/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 182, in <module>
    Binding.init_static_locks()
  File "/Library/Python/2.7/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 139, in init_static_locks
    cls._ensure_ffi_initialized()
  File "/Library/Python/2.7/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 134, in _ensure_ffi_initialized
    cls._register_osrandom_engine()
  File "/Library/Python/2.7/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 99, in _register_osrandom_engine
    _openssl_assert(cls.lib, cls.lib.ERR_peek_error() == 0)
  File "/Library/Python/2.7/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 43, in _openssl_assert
    errors
cryptography.exceptions.InternalError: Unknown OpenSSL error. Please file an issue at https://github.com/pyca/cryptography/issues with information on how to reproduce this.
```

**Comment by reaperhulk** [comment]
The error msg here appears to be missing some detail, are you running the latest cryptography?

Typically this issue is caused by something else failing to clear the OpenSSL error stack in the same process you're running. During initialization if we run into any errors we deliberately halt because we can't guarantee that it's safe to proceed. In your case I'd be suspicious that sqlcipher (which links against OpenSSL) is failing to clear the error stack properly.

**Comment by mhunterak** [comment]
I believe the problem came from when I was trying to upgrade setuptools.
this command worked for me:
`sudo pip install --upgrade --ignore-installed cryptography`
