### ISSUE TITLE
Error on install with pip3 (python-3 and ubuntu-14.04)

### ISSUE THREAD

**Issue by fabriciorsf** [pyca/cryptography#3376]
I follow this installation guide:
https://cryptography.io/en/latest/installation/

And on install with pip3 (`sudo pip3 install cryptography -U`), I get this error:

```
Collecting cryptography
  Downloading cryptography-1.7.2.tar.gz (420kB)
    100% |████████████████████████████████| 430kB 2.9MB/s
Exception:
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/local/lib/python3.4/dist-packages/pip/commands/install.py", line 324, in run
    requirement_set.prepare_files(finder)
  File "/usr/local/lib/python3.4/dist-packages/pip/req/req_set.py", line 380, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "/usr/local/lib/python3.4/dist-packages/pip/req/req_set.py", line 634, in _prepare_file
    abstract_dist.prep_for_dist()
  File "/usr/local/lib/python3.4/dist-packages/pip/req/req_set.py", line 129, in prep_for_dist
    self.req_to_install.run_egg_info()
  File "/usr/local/lib/python3.4/dist-packages/pip/req/req_install.py", line 412, in run_egg_info
    self.setup_py, self.name,
  File "/usr/local/lib/python3.4/dist-packages/pip/req/req_install.py", line 387, in setup_py
    import setuptools  # noqa
  File "/usr/local/lib/python3.4/dist-packages/setuptools/__init__.py", line 12, in <module>
    import setuptools.version
  File "/usr/local/lib/python3.4/dist-packages/setuptools/version.py", line 1, in <module>
    import pkg_resources
  File "/usr/local/lib/python3.4/dist-packages/pkg_resources/__init__.py", line 72, in <module>
    import packaging.requirements
  File "/usr/local/lib/python3.4/dist-packages/packaging/requirements.py", line 59, in <module>
    MARKER_EXPR = originalTextFor(MARKER_EXPR())("marker")
TypeError: __call__() missing 1 required positional argument: 'name'
```

**Comment by alex** [comment]
I'm unable to reproduce this, can you provide instructions for doing so from a fresh OS?

**Comment by rcrehuet** [comment]
I have come across the same issue with a different python package. Apparently the problem is caused by outdated version of pyparsing (2.0.1). See [here](http://stackoverflow.com/questions/41829550/how-to-fix-pip-being-proken-after-installing-line-profiler) and [here](https://github.com/pypa/packaging/issues/91). Update to >=2.0.2
