### ISSUE TITLE
"pip install cryptography" fails due to six dependency

### ISSUE THREAD

**Issue by rectalogic** [pyca/cryptography#3412]
"pip install cryptography" into a new virtualenv fails on Ubuntu 14.04 with "ImportError: No module named six.moves"

```
test@test-vm /tmp> python --version
Python 2.7.6
test@test-vm /tmp> virtualenv --version
1.10.1
test@test-vm /tmp> virtualenv env
New python executable in env/bin/python
Installing Setuptools..............................................................................................................................................................................................................................done.
Installing Pip.....................................................................................................................................................................................................................................................................................................................................done.
test@test-vm /tmp> env/bin/pip install cryptography
Downloading/unpacking cryptography
  Downloading cryptography-1.7.2.tar.gz (420kB): 420kB downloaded
  Running setup.py egg_info for package cryptography

    no previously-included directories found matching 'docs/_build'
    warning: no previously-included files matching '*' found under directory 'vectors'
Downloading/unpacking idna>=2.0 (from cryptography)
  Downloading idna-2.2.tar.gz (130kB): 130kB downloaded
  Running setup.py egg_info for package idna

    warning: no previously-included files matching '*.pyc' found under directory 'tools'
    warning: no previously-included files matching '*.pyc' found under directory 'tests'
Downloading/unpacking pyasn1>=0.1.8 (from cryptography)
  Downloading pyasn1-0.2.2.tar.gz (90kB): 90kB downloaded
  Running setup.py egg_info for package pyasn1

    no previously-included directories found matching 'doc/build'
    no previously-included directories found matching 'doc/source/.templates'
Downloading/unpacking six>=1.4.1 (from cryptography)
  Downloading six-1.10.0.tar.gz
  Running setup.py egg_info for package six

    no previously-included directories found matching 'documentation/_build'
Downloading/unpacking setuptools>=11.3 (from cryptography)
  Downloading setuptools-34.2.0.zip (621kB): 621kB downloaded
  Running setup.py egg_info for package setuptools
    Traceback (most recent call last):
      File "<string>", line 3, in <module>
      File "setuptools/__init__.py", line 10, in <module>
        from six.moves import filter, map
    ImportError: No module named six.moves
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 3, in <module>

  File "setuptools/__init__.py", line 10, in <module>

    from six.moves import filter, map

ImportError: No module named six.moves

----------------------------------------
Cleaning up...
Command python setup.py egg_info failed with error code 1 in /tmp/env/build/setuptools
Storing complete log in /tmp/tmpzwGYBO
```

**Comment by alex** [comment]
Interesting. On a totally fresh Ubuntu 14.04, I hit a different error: https://gist.github.com/alex/aaecbb52419d02d404fbfc08a2688a37

**Comment by alex** [comment]
@rectalogic I recommend upgrading the `pip` in your `virtualenv`, that appears to fix it for me:

```
root@1c5ae440220a:/# virtualenv venv2
New python executable in venv2/bin/python
Installing setuptools, pip...done.
root@1c5ae440220a:/# ./venv2/bin/pip install -U pip
Downloading/unpacking pip from https://pypi.python.org/packages/b6/ac/7015eb97dc749283ffdec1c3a88ddb8ae03b8fad0f0e611408f196358da3/pip-9.0.1-py2.py3-none-any.whl#md5=297dbd16ef53bcef0447d245815f5144
  Downloading pip-9.0.1-py2.py3-none-any.whl (1.3MB): 1.3MB downloaded
Installing collected packages: pip
  Found existing installation: pip 1.5.4
    Uninstalling pip:
      Successfully uninstalled pip
Successfully installed pip
Cleaning up...
root@1c5ae440220a:/# ./venv2/bin/pip install cryptography
Collecting cryptography
/venv2/local/lib/python2.7/site-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:318: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/security.html#snimissingwarning.
  SNIMissingWarning
/venv2/local/lib/python2.7/site-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:122: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
  Downloading cryptography-1.7.2.tar.gz (420kB)
    100% |################################| 430kB 2.2MB/s
Collecting idna>=2.0 (from cryptography)
  Downloading idna-2.2-py2.py3-none-any.whl (55kB)
    100% |################################| 61kB 5.5MB/s
Collecting pyasn1>=0.1.8 (from cryptography)
  Downloading pyasn1-0.2.2-py2.py3-none-any.whl (51kB)
    100% |################################| 61kB 6.4MB/s
Collecting six>=1.4.1 (from cryptography)
  Downloading six-1.10.0-py2.py3-none-any.whl
Collecting setuptools>=11.3 (from cryptography)
  Downloading setuptools-34.2.0-py2.py3-none-any.whl (389kB)
    100% |################################| 399kB 1.6MB/s
Collecting enum34 (from cryptography)
  Downloading enum34-1.1.6-py2-none-any.whl
Collecting ipaddress (from cryptography)
  Downloading ipaddress-1.0.18-py2-none-any.whl
Collecting cffi>=1.4.1 (from cryptography)
  Downloading cffi-1.9.1-cp27-cp27mu-manylinux1_x86_64.whl (387kB)
    100% |################################| 389kB 2.0MB/s
Collecting appdirs>=1.4.0 (from setuptools>=11.3->cryptography)
  Downloading appdirs-1.4.0-py2.py3-none-any.whl
Collecting packaging>=16.8 (from setuptools>=11.3->cryptography)
  Downloading packaging-16.8-py2.py3-none-any.whl
Collecting pycparser (from cffi>=1.4.1->cryptography)
  Downloading pycparser-2.17.tar.gz (231kB)
    100% |################################| 235kB 2.4MB/s
Collecting pyparsing (from packaging>=16.8->setuptools>=11.3->cryptography)
  Downloading pyparsing-2.1.10-py2.py3-none-any.whl (56kB)
    100% |################################| 61kB 2.9MB/s
Installing collected packages: idna, pyasn1, six, appdirs, pyparsing, packaging, setuptools, enum34, ipaddress, pycparser, cffi, cryptography
  Found existing installation: setuptools 2.2
    Uninstalling setuptools-2.2:
      Successfully uninstalled setuptools-2.2
  Running setup.py install for pycparser ... done
  Running setup.py install for cryptography ... done
Successfully installed appdirs-1.4.0 cffi-1.9.1 cryptography-1.7.2 enum34-1.1.6 idna-2.2 ipaddress-1.0.18 packaging-16.8 pyasn1-0.2.2 pycparser-2.17 pyparsing-2.1.10 setuptools-34.2.0 six-1.10.0
/venv2/local/lib/python2.7/site-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:122: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
```

**Comment by alex** [comment]
On further review, this isn't really a cryptography bug at all. Since it's fixed by upgrading pip, I think that's the right way to go, but if you'd like to file a bug, I think it belongs in setuptools, the traceback doesn't actually come from cryptography.
