### ISSUE TITLE
cryptography should be able to avoid pycparser in case it can't be properly loaded and used

### ISSUE THREAD

**Issue by alxchk** [pyca/cryptography#3775]
https://github.com/eliben/pycparser/pull/198

```
> export PYTHONOPTIMIZE=2                  
> pip install --user --upgrade cryptography
Collecting cryptography
  Using cached cryptography-1.9.tar.gz
Requirement already up-to-date: idna>=2.1 in ./.local/lib64/python2.7/site-packages (from cryptography)
Requirement already up-to-date: asn1crypto>=0.21.0 in ./.local/lib64/python2.7/site-packages (from cryptography)
Requirement already up-to-date: six>=1.4.1 in ./.local/lib64/python2.7/site-packages (from cryptography)
Requirement already up-to-date: enum34 in ./.local/lib64/python2.7/site-packages (from cryptography)
Requirement already up-to-date: ipaddress in ./.local/lib64/python2.7/site-packages (from cryptography)
Requirement already up-to-date: cffi>=1.7 in ./.local/lib64/python2.7/site-packages (from cryptography)
Requirement already up-to-date: pycparser in ./.local/lib64/python2.7/site-packages (from cffi>=1.7->cryptography)
Installing collected packages: cryptography
  Found existing installation: cryptography 1.8.1
    Uninstalling cryptography-1.8.1:
      Successfully uninstalled cryptography-1.8.1
  Running setup.py install for cryptography ... error
    Complete output from command /usr/bin/python2.7 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-VQOhCT/cryptography/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-pNpCC7-record/install-record.txt --single-version-externally-managed --compile --user --prefix=:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-VQOhCT/cryptography/setup.py", line 321, in <module>
        **keywords_with_side_effects(sys.argv)
      File "/usr/lib64/python2.7/distutils/core.py", line 111, in setup
        _setup_distribution = dist = klass(attrs)
      File "/home/user/.local/lib64/python2.7/site-packages/setuptools/dist.py", line 320, in __init__
        _Distribution.__init__(self, attrs)
      File "/usr/lib64/python2.7/distutils/dist.py", line 287, in __init__
        self.finalize_options()
      File "/home/user/.local/lib64/python2.7/site-packages/setuptools/dist.py", line 387, in finalize_options
        ep.load()(self, ep.name, value)
      File "/home/user/.local/lib64/python2.7/site-packages/cffi/setuptools_ext.py", line 188, in cffi_modules
        add_cffi_module(dist, cffi_module)
      File "/home/user/.local/lib64/python2.7/site-packages/cffi/setuptools_ext.py", line 49, in add_cffi_module
        execfile(build_file_name, mod_vars)
      File "/home/user/.local/lib64/python2.7/site-packages/cffi/setuptools_ext.py", line 25, in execfile
        exec(code, glob, glob)
      File "src/_cffi_src/build_openssl.py", line 82, in <module>
        extra_link_args=extra_link_args(compiler_type()),
      File "/tmp/pip-build-VQOhCT/cryptography/src/_cffi_src/utils.py", line 61, in build_ffi_for_binding
        extra_link_args=extra_link_args,
      File "/tmp/pip-build-VQOhCT/cryptography/src/_cffi_src/utils.py", line 69, in build_ffi
        ffi = FFI()
      File "/home/user/.local/lib64/python2.7/site-packages/cffi/api.py", line 63, in __init__
        from . import cparser
      File "/home/user/.local/lib64/python2.7/site-packages/cffi/cparser.py", line 7, in <module>
        import pycparser
      File "/home/user/.local/lib64/python2.7/site-packages/pycparser/__init__.py", line 14, in <module>
        from .c_parser import CParser
      File "/home/user/.local/lib64/python2.7/site-packages/pycparser/c_parser.py", line 20, in <module>
        class CParser(PLYParser):
      File "/home/user/.local/lib64/python2.7/site-packages/pycparser/plyparser.py", line 95, in template
        _create_param_rules(cls, method)
      File "/home/user/.local/lib64/python2.7/site-packages/pycparser/plyparser.py", line 112, in _create_param_rules
        param_rule.__doc__ = func.__doc__.replace('xxx', xxx).replace('yyy', yyy)
    AttributeError: 'NoneType' object has no attribute 'replace'

    ----------------------------------------
  Rolling back uninstall of cryptography
Command "/usr/bin/python2.7 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-VQOhCT/cryptography/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-pNpCC7-record/install-record.txt --single-version-externally-managed --compile --user --prefix=" failed with error code 1 in /tmp/pip-build-VQOhCT/cryptography/```

**Comment by alex** [comment]
This is not a cryptography bug -- this appears to be a pycparser bug, combined with the fact that `setup_requiers` does not work with normal pip dependency resolution (fixed in the upcoming ppi 10).
