### ISSUE TITLE
Cryptography does not work with debug build of python 

### ISSUE THREAD

**Issue by binrush** [pyca/cryptography#3879]
I'm trying to debug application that uses cryptography using gdb. For this, I'm trying to use debug build of cpython (`python3-dbg` package on Debian).
However, I get error when calling `default_backend()`:

```
$ python3.5-dbg
Python 3.5.3 (default, Jan 19 2017, 14:11:04)
[GCC 6.3.0 20170118] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from cryptography.hazmat.backends import default_backend
>>> b = default_backend()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3/dist-packages/cryptography/hazmat/backends/__init__.py", line 71, in default_backend
    _default_backend = MultiBackend(_available_backends())
  File "/usr/lib/python3/dist-packages/cryptography/hazmat/backends/__init__.py", line 28, in _available_backends
    "cryptography.backends"
  File "/usr/lib/python3/dist-packages/cryptography/hazmat/backends/__init__.py", line 27, in <listcomp>
    for ep in pkg_resources.iter_entry_points(
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2297, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python3/dist-packages/cryptography/hazmat/backends/openssl/__init__.py", line 7, in <module>
    from cryptography.hazmat.backends.openssl.backend import backend
  File "/usr/lib/python3/dist-packages/cryptography/hazmat/backends/openssl/backend.py", line 17, in <module>
    from cryptography import utils, x509
  File "/usr/lib/python3/dist-packages/cryptography/x509/__init__.py", line 7, in <module>
    from cryptography.x509.base import (
  File "/usr/lib/python3/dist-packages/cryptography/x509/base.py", line 16, in <module>
    from cryptography.x509.extensions import Extension, ExtensionType
  File "/usr/lib/python3/dist-packages/cryptography/x509/extensions.py", line 20, in <module>
    from cryptography.hazmat.primitives import constant_time, serialization
  File "/usr/lib/python3/dist-packages/cryptography/hazmat/primitives/constant_time.py", line 9, in <module>
    from cryptography.hazmat.bindings._constant_time import lib
ImportError: No module named '_cffi_backend'
```

Normal cpython build works fine:
```
$ python3.5
Python 3.5.3 (default, Jan 19 2017, 14:11:04)
[GCC 6.3.0 20170118] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from cryptography.hazmat.backends import default_backend
>>> b = default_backend()
>>> b
<cryptography.hazmat.backends.multibackend.MultiBackend object at 0x7f52a5b395c0>
```

Cryptography version - `1.7.1-3` (installed using `apt-get install python35-cryptography`)
cffi version - `1.9.1-2`
pip version - `9.0.1-2`
setuptools version - `33.1.1-1`

Similar issue, but with different error reproduced on Centos7 with custom build of python 3.5:
```
# /opt/alt/python35/bin/python3-debug
Python 3.5.3 (default, Jan 21 2017, 07:13:48)
[GCC 4.8.5 20150623 (Red Hat 4.8.5-11)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from cryptography.hazmat.backends import default_backend
>>> b = default_backend()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/alt/python35/lib64/python3.5/site-packages/cryptography/hazmat/backends/__init__.py", line 74, in default_backend
    _default_backend = MultiBackend(_available_backends())
  File "/opt/alt/python35/lib64/python3.5/site-packages/cryptography/hazmat/backends/__init__.py", line 31, in _available_backends
    "cryptography.backends"
  File "/opt/alt/python35/lib64/python3.5/site-packages/cryptography/hazmat/backends/__init__.py", line 30, in <listcomp>
    for ep in pkg_resources.iter_entry_points(
  File "/opt/alt/python35/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2386, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/opt/alt/python35/lib64/python3.5/site-packages/cryptography/hazmat/backends/openssl/__init__.py", line 7, in <module>
    from cryptography.hazmat.backends.openssl.backend import backend
  File "/opt/alt/python35/lib64/python3.5/site-packages/cryptography/hazmat/backends/openssl/backend.py", line 16, in <module>
    from cryptography import utils, x509
  File "/opt/alt/python35/lib64/python3.5/site-packages/cryptography/x509/__init__.py", line 7, in <module>
    from cryptography.x509.base import (
  File "/opt/alt/python35/lib64/python3.5/site-packages/cryptography/x509/base.py", line 16, in <module>
    from cryptography.x509.extensions import Extension, ExtensionType
  File "/opt/alt/python35/lib64/python3.5/site-packages/cryptography/x509/extensions.py", line 19, in <module>
    from cryptography.hazmat.primitives import constant_time, serialization
  File "/opt/alt/python35/lib64/python3.5/site-packages/cryptography/hazmat/primitives/constant_time.py", line 9, in <module>
    from cryptography.hazmat.bindings._constant_time import lib
ImportError: No module named 'cryptography.hazmat.bindings._constant_time'
```

**Comment by alex** [comment]
Both the tracebacks you provided show `ImportError`s rying to import cffi-compiled modules.

I strongly suspect the bug here is in cffi, and not cryptography -- are you able to use other cffi modules, such as `bcrypt`?

**Comment by binrush** [comment]
Thank you for reply @alex 

Yes, seems like this is cffi problem:

```
# python3.5-dbg
Python 3.5.3 (default, Jan 19 2017, 14:11:04)
[GCC 6.3.0 20170118] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import bcrypt
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3/dist-packages/bcrypt/__init__.py", line 24, in <module>
    from bcrypt import _bcrypt
ImportError: cannot import name '_bcrypt'
```

**Comment by tdsmith** [comment]
I think this isn't a bug, though Python's error message here isn't super clear. Debug and non-debug builds aren't ABI-compatible, so binary packages intended for use with the normal python build won't work with the debug builds; you won't be able to use e.g. your distribution's cryptography package with the debug build.

You can install cryptography using the debug build with e.g. `python3.5-dbg -m pip install --no-binary :all: cryptography`. (I'm not sure the --no-binary flag is necessary; it asks pip not to use a prebuilt wheel, but maybe it's already smart enough to detect the ABI mismatch.)

**Comment by reaperhulk** [comment]
`pip` should be capable of detecting the debug ABI, yes. But it can't hurt to --no-binary it

**Comment by reaperhulk** [comment]
I'm going to go ahead and close this on the assumption that cffi & cryptography need to be compiled directly against the debug build since the ABI is different. If new information comes up feel free to reply to this and we can potentially reopen.
