### ISSUE TITLE
I encountered some errors when I installed the latest version.

### ISSUE THREAD

**Issue by zixiliuyue** [pyca/cryptography#4025]
```
/home/genius/cryptography-2.1.3]#/home/genius/python27/bin/python setup.py install
Traceback (most recent call last):
  File "setup.py", line 307, in <module>
    **keywords_with_side_effects(sys.argv)
  File "/home/genius/python27/lib/python2.7/distutils/core.py", line 111, in setup
    _setup_distribution = dist = klass(attrs)
  File "build/bdist.linux-x86_64/egg/setuptools/dist.py", line 320, in __init__
  File "/home/genius/python27/lib/python2.7/distutils/dist.py", line 287, in __init__
    self.finalize_options()
  File "build/bdist.linux-x86_64/egg/setuptools/dist.py", line 387, in finalize_options
  File "/home/genius/python27/lib/python2.7/site-packages/cffi-1.8.3-py2.7-linux-x86_64.egg/cffi/setuptools_ext.py", line 181, in cffi_modules
    add_cffi_module(dist, cffi_module)
  File "/home/genius/python27/lib/python2.7/site-packages/cffi-1.8.3-py2.7-linux-x86_64.egg/cffi/setuptools_ext.py", line 48, in add_cffi_module
    execfile(build_file_name, mod_vars)
  File "/home/genius/python27/lib/python2.7/site-packages/cffi-1.8.3-py2.7-linux-x86_64.egg/cffi/setuptools_ext.py", line 24, in execfile
    exec(code, glob, glob)
  File "src/_cffi_src/build_openssl.py", line 107, in <module>
    extra_link_args=extra_link_args(compiler_type()),
  File "src/_cffi_src/utils.py", line 49, in build_ffi_for_binding
    extra_link_args=extra_link_args,
  File "src/_cffi_src/utils.py", line 58, in build_ffi
    ffi.cdef(cdef_source)
  File "/home/genius/python27/lib/python2.7/site-packages/cffi-1.8.3-py2.7-linux-x86_64.egg/cffi/api.py", line 105, in cdef
    self._cdef(csource, override=override, packed=packed)
  File "/home/genius/python27/lib/python2.7/site-packages/cffi-1.8.3-py2.7-linux-x86_64.egg/cffi/api.py", line 119, in _cdef
    self._parser.parse(csource, override=override, **options)
  File "/home/genius/python27/lib/python2.7/site-packages/cffi-1.8.3-py2.7-linux-x86_64.egg/cffi/cparser.py", line 299, in parse
    self._internal_parse(csource)
  File "/home/genius/python27/lib/python2.7/site-packages/cffi-1.8.3-py2.7-linux-x86_64.egg/cffi/cparser.py", line 304, in _internal_parse
    ast, macros, csource = self._parse(csource)
  File "/home/genius/python27/lib/python2.7/site-packages/cffi-1.8.3-py2.7-linux-x86_64.egg/cffi/cparser.py", line 262, in _parse
    self.convert_pycparser_error(e, csource)
  File "/home/genius/python27/lib/python2.7/site-packages/cffi-1.8.3-py2.7-linux-x86_64.egg/cffi/cparser.py", line 291, in convert_pycparser_error
    raise api.CDefError(msg)
cffi.api.CDefError: cannot parse "typedef int __dotdotdot__  time_t;"
:24:28: before: time_t
```

Here are some of my system information:
```
[root@JTZDFB244054-DT/home/genius]#./python27/bin/pip show cffi
Name: cffi
Version: 1.8.3
Summary: Foreign Function Interface for Python calling C code.
Home-page: http://cffi.readthedocs.org
Author: Armin Rigo, Maciej Fijalkowski
Author-email: python-cffi@googlegroups.com
License: MIT
Location: /home/genius/python27/lib/python2.7/site-packages/cffi-1.8.3-py2.7-linux-x86_64.egg
Requires: pycparser


[root@JTZDFB244054-DT/home/genius]#./python27/bin/pip show setuptools
Name: setuptools
Version: 32.3.0
Summary: Easily download, build, install, upgrade, and uninstall Python packages
Home-page: https://github.com/pypa/setuptools
Author: Python Packaging Authority
Author-email: distutils-sig@python.org
License: UNKNOWN
Location: /home/genius/python27/lib/python2.7/site-packages/setuptools-32.3.0-py2.7.egg
Requires

[root@JTZDFB244054-DT/home/genius]#openssl
OpenSSL> version
OpenSSL 1.0.0-fips 29 Mar 2010


[root@JTZDFB244054-DT/home/genius]#whereis libffi.so
libffi: /usr/local/lib/libffi.la /usr/local/lib/libffi.a /usr/local/lib/libffi.so
[root@JTZDFB244054-DT/home/genius]#ls -la /usr/local/lib/libffi.so
lrwxrwxrwx. 1 root root 15 Nov 23 14:36 /usr/local/lib/libffi.so -> libffi.so.6.0.0
[root@JTZDFB244054-DT/home/genius]#ls -la /usr/local/lib/libffi.so.6.0.0
-rwxr-xr-x. 1 root root 100163 Nov 23 14:36 /usr/local/lib/libffi.so.6.0.0
```

**Comment by alex** [comment]
We do not support OpenSSL 1.0.0: https://cryptography.io/en/latest/faq/#installing-cryptography-with-openssl-0-9-8-or-1-0-0-fails

Please either upgrade to a newer version of OpenSSL, or install a newer version of pip so that you obtain a wheel.
