### ISSUE TITLE
load_ssh_public_key does not work with RSABackend

### ISSUE THREAD

**Issue by rmb938** [pyca/cryptography#4041]
* Versions of Python, ``cryptography``, ``cffi``, ``pip``, and ``setuptools``
  you're using

```
Python 3.6.3
```
```
Name: cryptography
Version: 2.1.4
```
```
Name: cffi
Version: 1.11.2
```
```
pip 9.0.1 (python 3.6)
```
```
Name: setuptools
Version: 36.7.2
```

* How you installed ``cryptography``

```
pip install cryptography
```

* Clear steps for reproducing your bug

See code and stack trace bellow:

```
from cryptography.hazmat.backends.interfaces import RSABackend
from cryptography.hazmat.primitives.serialization import load_ssh_public_key

load_ssh_public_key(b"rsa public key here", RSABackend)
```

```
Traceback (most recent call last):
  File "/home/rbelgrave/python-venvs/sandwich/lib/python3.6/site-packages/CherryPy-11.0.0-py3.6.egg/cherrypy/_cprequest.py", line 663, in respond
    self.body.process()
  File "/home/rbelgrave/python-venvs/sandwich/lib/python3.6/site-packages/CherryPy-11.0.0-py3.6.egg/cherrypy/_cpreqbody.py", line 982, in process
    super(RequestBody, self).process()
  File "/home/rbelgrave/python-venvs/sandwich/lib/python3.6/site-packages/CherryPy-11.0.0-py3.6.egg/cherrypy/_cpreqbody.py", line 561, in process
    proc(self)
  File "/mnt/e/Google Drive/IntelliJ Projects/Sandwich/ingredients.http/ingredients_http/tools/model.py", line 23, in model_processor
    model.validate()
  File "/home/rbelgrave/python-venvs/sandwich/lib/python3.6/site-packages/schematics/models.py", line 254, in validate
    partial=partial, convert=convert, app_data=app_data, **kwargs)
  File "/home/rbelgrave/python-venvs/sandwich/lib/python3.6/site-packages/schematics/models.py", line 295, in _convert
    return func(self._schema, self, raw_data=raw_data, oo=True, context=context, **kwargs)
  File "/home/rbelgrave/python-venvs/sandwich/lib/python3.6/site-packages/schematics/validate.py", line 62, in validate
    errors.update(_validate_model(schema, mutable, data, context))
  File "/home/rbelgrave/python-venvs/sandwich/lib/python3.6/site-packages/schematics/validate.py", line 90, in _validate_model
    schema._validator_functions[field_name](mutable, data, value, context)
  File "/home/rbelgrave/python-venvs/sandwich/lib/python3.6/site-packages/schematics/validate.py", line 123, in newfunc
    return func(*args, **kwargs)
  File "./deli_counter/http/mounts/root/routes/v1/validation_models/keypairs.py", line 26, in validate_public_key
    load_ssh_public_key(value.encode(), RSABackend)
  File "/home/rbelgrave/python-venvs/sandwich/lib/python3.6/site-packages/cryptography/hazmat/primitives/serialization.py", line 77, in load_ssh_public_key
    return loader(key_type, rest, backend)
  File "/home/rbelgrave/python-venvs/sandwich/lib/python3.6/site-packages/cryptography/hazmat/primitives/serialization.py", line 87, in _load_ssh_rsa_public_key
    return rsa.RSAPublicNumbers(e, n).public_key(backend)
  File "/home/rbelgrave/python-venvs/sandwich/lib/python3.6/site-packages/cryptography/hazmat/primitives/asymmetric/rsa.py", line 353, in public_key
    return backend.load_rsa_public_numbers(self)
TypeError: load_rsa_public_numbers() missing 1 required positional argument: 'numbers'
```

**Comment by alex** [comment]
`load_ssh_public_key` takes an instance of `RSABackend`, not the `RSABackend` type itself.

The correct way to use this API is `load_ssh_public_key(data, default_backend())`

**Comment by rmb938** [comment]
Ah ok. Probably should mention that in the docs somewhere since `backend – A backend which implements RSABackend, DSABackend, or EllipticCurveBackend depending on the key’s type.` doesn't really explain that it needs an instance vs just the type and doesn't mention anything about the default backend.
