### ISSUE TITLE
Debugging `ValueError: Unable to load certificate` error

### ISSUE THREAD

**Issue by dbinetti** [pyca/cryptography#4085]
I'm getting a `ValueError: Unable to load certificate` when trying to read a PEM cert.  However, after reading and searching in vain I'm unable to determine why I'm getting the error or how to debug.  The certificate appears valid, but I don't know how to check that.  Any guidance would be appreciated.

On MacOS High Sierra 10.13.2, Python 3.6.4, cryptography 2.1.4 and everything else up-to-date.

```
>>> from cryptography import x509
>>> from cryptography.hazmat.backends import default_backend
cert = x509.load_pem_x509_certificate(open('barberscore.pem', 'rb').read(), default_backend())
>>> cert = x509.load_pem_x509_certificate(open('barberscore.pem', 'rb').read(), default_backend())
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/dbinetti/Repos/pycryptography-test-load-x509/.venv/lib/python3.6/site-packages/cryptography/x509/base.py", line 43, in load_pem_x509_certificate
    return backend.load_pem_x509_certificate(data)
  File "/Users/dbinetti/Repos/pycryptography-test-load-x509/.venv/lib/python3.6/site-packages/cryptography/hazmat/backends/openssl/backend.py", line 1139, in load_pem_x509_certificate
    raise ValueError("Unable to load certificate")
ValueError: Unable to load certificate
```

**Comment by reaperhulk** [comment]
If you can't parse it with the command line (`openssl x509 -noout -text -in <file.pem>`) then it's in an invalid format. If the certificate contains no details you consider sensitive feel free to post it here as well.

**Comment by dbinetti** [comment]
seems to parse.

```
(pycryptography-test-load-x509)$ openssl x509 -noout -text -in 'barberscore.pem'
Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number: 1357196715954533991 (0x12d5bb38f0cbf667)
    Signature Algorithm: sha1WithRSAEncryption
        Issuer: CN=barberscore.auth0.com
        Validity
            Not Before: Feb  2 20:43:29 2016 GMT
            Not After : Oct 11 20:43:29 2029 GMT
        Subject: CN=barberscore.auth0.com
        Subject Public Key Info:
            Public Key Algorithm: rsaEncryption
                Public-Key: (2048 bit)
                Modulus:
                    00:d0:51:b2:c1:ee:3c:10:da:b1:a3:95:68:72:19:
                    f8:06:f7:96:c3:2f:9b:39:49:10:d8:0c:97:64:1b:
                    5c:12:2e:79:1d:7f:ff:b9:c3:0e:0f:3a:cb:f0:69:
                    c6:42:ef:c1:e5:1a:1c:16:88:5c:88:1e:a7:8b:cd:
                    69:1d:68:28:db:4c:de:ef:e2:ba:6c:44:dd:31:87:
                    89:bd:9a:99:62:7a:2a:17:ca:8f:d9:b1:e5:3a:f9:
                    8b:43:75:78:e4:dd:44:06:6c:7b:97:04:e6:c5:cb:
                    9d:d7:ec:55:af:1b:9c:fa:ae:cc:2b:3d:14:8d:49:
                    b8:3d:58:4b:7c:5c:c9:ad:53:19:a8:60:19:c7:65:
                    bc:2a:c9:f1:fa:68:a9:93:98:0d:f4:0d:a5:4e:fa:
                    67:36:e0:b5:ec:6d:95:0c:74:2e:3f:bb:10:d3:61:
                    a2:3d:88:31:60:50:1e:7e:33:88:10:67:d0:bf:11:
                    5c:da:36:69:26:dd:fd:72:fb:2b:af:b2:59:6a:d7:
                    96:9c:e7:99:e0:fa:15:34:24:dd:c8:b4:ee:15:5a:
                    c7:c2:46:71:9f:b2:ef:99:ca:47:bc:82:28:c0:ec:
                    7b:01:7f:80:73:e5:9a:e2:4d:0d:b9:7b:12:7c:a8:
                    62:33:c3:c0:5f:9b:2e:26:62:85:7a:fe:2b:5d:e9:
                    93:55
                Exponent: 65537 (0x10001)
        X509v3 extensions:
            X509v3 Basic Constraints: 
                CA:TRUE
            X509v3 Subject Key Identifier: 
                F9:37:29:44:DD:02:1A:4A:DE:05:0D:50:0B:C7:52:2B:0A:88:04:93
    Signature Algorithm: sha1WithRSAEncryption
         50:9e:35:6d:ae:63:53:31:00:98:53:f8:39:67:f5:5e:df:3a:
         a3:3a:60:2b:b4:76:94:93:62:f6:83:cc:a1:6a:2e:7a:c5:52:
         65:62:79:8e:3c:d8:4e:7a:d6:5e:8b:d7:c2:27:54:fd:ce:51:
         1b:f5:dc:b3:cf:a8:00:00:fd:de:ed:63:96:96:66:0f:68:42:
         b7:e0:2a:5e:03:30:af:45:d1:61:3a:cc:a5:8b:55:83:ff:56:
         f9:28:7d:3f:13:21:a9:3d:41:d8:43:56:6b:cb:71:ea:2a:11:
         49:15:8e:da:fc:2f:d9:8f:19:3f:9b:5b:75:30:e5:20:0e:b5:
         f8:a7:8a:e0:5d:c5:ab:58:51:30:26:c5:c3:d7:35:ae:fe:e8:
         50:5c:43:31:5b:06:04:82:60:b7:62:7b:b5:6b:19:96:6c:00:
         27:7c:87:8d:84:5c:cd:2f:26:a9:19:ce:ef:e8:5f:36:b8:56:
         b8:17:28:b4:3d:d6:5c:ba:e1:12:ef:a5:a4:be:f8:e4:23:c5:
         d8:5b:ee:20:4f:d9:34:a6:3a:2c:2a:3b:bd:34:3c:d8:44:52:
         e6:42:c9:87:b5:4e:86:bc:fb:10:77:30:30:4f:bd:12:df:63:
         4b:6e:45:b8:21:02:31:d2:63:c6:8c:d6:b3:dc:16:ce:78:58:
         ea:63:9d:99
(pycryptography-test-load-x509)$ 
```

And here's a quick test repo (with the non-sensitive PEM in question.)

https://github.com/barberscore/pycryptography-test-load-x509

THanks!

**Comment by reaperhulk** [comment]
Thanks for the example. Turns out OpenSSL 1.1.0 refuses to load while older versions (including LibreSSL 2.2.7, which is what High Sierra ships with for the CLI openssl client) will load it. However, we link 1.1.0 in the wheel which you are using so that's why you're seeing this error.

```
140736103023424:error:0D0E20DD:asn1 encoding routines:c2i_ibuf:illegal padding:crypto/asn1/a_int.c:187:
140736103023424:error:0D08303A:asn1 encoding routines:asn1_template_noexp_d2i:nested asn1 error:crypto/asn1/tasn_dec.c:609:Field=serialNumber, Type=X509_CINF
140736103023424:error:0D08303A:asn1 encoding routines:asn1_template_noexp_d2i:nested asn1 error:crypto/asn1/tasn_dec.c:609:Field=cert_info, Type=X509
140736103023424:error:0906700D:PEM routines:PEM_ASN1_read_bio:ASN1 lib:crypto/pem/pem_oth.c:33:
```

I'd suggest reporting this certificate as malformed to auth0. You can reproduce the error easily with just the OpenSSL CLI if you boot a Debian stretch container, `apt install openssl`, and parse it there.

**Comment by dbinetti** [comment]
Thanks for tracking it down!  I'll follow up as you suggested.

**Comment by wooly** [comment]
@dbinetti did you get anywhere with auth0? We're having similar issues.

**Comment by dbinetti** [comment]
yes, they corrected the problem.  but it did require them to re-issue the
certificate, so you need to co-ordinate with them (for timing).

**Comment by wooly** [comment]
Thanks!
