### ISSUE TITLE
AttributeError: module 'OpenSSL.SSL' has no attribute 'SSL_ST_INIT'

### ISSUE THREAD

**Issue by anthraxx** [pyca/cryptography#4092]
I have a regression when trying to import all symbols from OpenSSL.SSL

Python 3.6.4
cryptography: 2.1.4-1
cffi: 1.11.4-1
OpenSSL 1.1.0.g-1

```python
>>> from OpenSSL.SSL import *

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.6/site-packages/cryptography/utils.py", line 124, in __getattr__
    obj = getattr(self._module, attr)
AttributeError: module 'OpenSSL.SSL' has no attribute 'SSL_ST_INIT'

```

**Comment by alex** [comment]
What version of PyOpenSSL are you using?

**Comment by anthraxx** [comment]
latest 17.5.0

**Comment by anthraxx** [comment]
bump. any news? any ideas, fixes?

**Comment by reaperhulk** [comment]
Can you replicate this in a new virtualenv?

**Comment by reaperhulk** [comment]
(Closing so this can be resolved on the pyopenssl side)

**Comment by anthraxx** [comment]
@reaperhulk yep. thanks :smile_cat:
