### ISSUE TITLE
Inconsistency of loading keys versus loading certificates

### ISSUE THREAD

**Issue by ericwb** [pyca/cryptography#4186]
When loading a certificate with an unsupported public key type, there is no error until the method public_keys() is called. 

Whereas loading a public via load_ssh_public_key() will throw an UnsupportedAlgorithm('Key type is not supported.') on loading.

To be consistent, I feel the loading of the certificate should also throw an UnsupportedAlgorithm on load. 

To recreate:
```
>>> from cryptography import x509
>>> from cryptography.hazmat.backends import default_backend
>>> from cryptography.hazmat.primitives import serialization

>>> pem_data = '-----BEGIN CERTIFICATE-----\nMIIDiDCCAnCgAwIBAgIJAMCjVO7bK6nVMA0GCSqGSIb3DQEBBQUAMFUxUzAfBgNV\nBAMTGE51dm90b24gVFBNIFJvb3QgQ0EgMTAxMzAlBgNVBAoTHk51dm90b24gVGVj\naG5vbG9neSBDb3Jwb3JhdGlvbjAJBgNVBAYTAlRXMB4XDTE2MDMwNjAwNTAwNloX\nDTM2MDMwMjAwNTAwNlowADCCAV8wSgYJKoZIhvcNAQEHMD2gCzAJBgUrDgMCGgUA\noRgwFgYJKoZIhvcNAQEIMAkGBSsOAwIaBQCiFDASBgkqhkiG9w0BAQkEBVRDUEEA\nA4IBDwAwggEKAoIBAQC21/uLETx8WPbFwPOTuwD7N4Nd5Y86qyHfJGsvzldvSbMI\ncF/vvqa2BbqCSt4VcpPeY+L5UWDOy84xS9E73Z3gpK2w3AgpmBRGuiW8o52BXfq8\nxnHw+1RAOcqa7JR8+L5jd999/UIYQtjpYuNkRnHEOAtn6LEw0n/S9qQb1jW/LV66\n9hf6kKWtuexxVtZN0FYGkYPlIYkTRyNCBvKOFAqPHbJ4JqZFkTlo3lwcH8ipAqlL\nPKHwGG8qxBDT6N3SWzCNilMv6AMEssU3T6pucX7Aesa/pphNblUoihUU0XG3aW31\nKpjrPV1zvOw3YQCDlrDEzsXt0/scLzZ+FqBp0JuVAgMBAAGjczBxMEwGA1UdEQEB\n/wRCMECkPjA8MTowFAYFZ4EFAgETC2lkOjRFNTQ0MzAwMBAGBWeBBQICEwdOUENU\nNnh4MBAGBWeBBQIDEwdpZDowNTgxMAwGA1UdEwEB/wQCMAAwEwYDVR0lAQH/BAkw\nBwYFZ4EFCAEwDQYJKoZIhvcNAQEFBQADggEBACjUmbtaPx9T/YUHvGMfEgXAwJ6z\n5O0mAqP4inFQuaZWEfZsEtTJNZRtqVMy7B1U8SwB9bDbB7UCePjDv87Y9oRZB3aL\nenn7otgzj4RmQj3m0GrIMuNiOf/7x6+CSRt9W2YjXtQAP6G3F19VRbQnmmIB82tu\nPGYhBPGGSlQNXdHxiMc7iMPmTW0vXvEwTntG96KNHK7A9AdJ6xYBO/VKEfZcZEbb\nItwJU+GPsxWEik8BlfBTAuVv1BWPzHvdQV/byWj/F2UTUZHsRG6TmUF+XJ9iXqWy\n6CzedSuY54QfOiwd2eJzcCfBEBVdsiX6dPoTPdCXdS1N6xlkZDWpD5vF1hU=\n-----END CERTIFICATE-----\n'
>>> cert = x509.load_pem_x509_certificate(pem_data, default_backend())
>>> cert.serial_number
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: '_Certificate' object has no attribute 'serial_number'

>>> cert.public_key()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/dist-packages/cryptography/hazmat/backends/openssl/x509.py", line 298, in public_key
    raise ValueError("Certificate public key is of an unknown type")
ValueError: Certificate public key is of an unknown type

>>> serialization.load_ssh_public_key(pem_data, default_backend())
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/dist-packages/cryptography/hazmat/primitives/serialization.py", line 53, in load_ssh_public_key
    raise UnsupportedAlgorithm('Key type is not supported.')
```

Python 2.7.12
cffi (1.10.0)
cryptography (2.1.4)
pip 9.0.1
setuptools (20.7.0)
OpenSSL 1.0.2g  1 Mar 2016

**Comment by reaperhulk** [comment]
Hmm, this is a bit tricky since in some ways it's useful to be able to parse part of the certificate even if the public key is of an unknown type. That said, this is definitely not ideal so I'm adding it to our next release milestone so we can discuss what makes sense.

The cert in the example uses an rsaesOaep SPKI, which no released version of OpenSSL properly supports. Unsure if 1.1.1 handles it.

**Comment by reaperhulk** [comment]
Thinking about this more I think we're doing the right thing. Certificates are parseable but the public key is not a type that we understand so when trying to fetch it we (correctly) raise an exception. Loading the public key directly immediately raises that exception since the resulting object would be the key it can't load.
