### ISSUE TITLE
Question: How choose a curve and generate key, then gene shared key?

### ISSUE THREAD

**Issue by Yensan** [pyca/cryptography#4190]
I read the Doc, https://cryptography.io/en/latest/hazmat/primitives/asymmetric/dh/

I want choosing a curve，then generate public-key / private-key
     then use server-key & private-key generate shared key.
curve SECP224R1, algorithm MD5
```python
import cryptography.hazmat.primitives.asymmetric.ec as ec
import cryptography.hazmat.backends.openssl.backend as bk
from cryptography.hazmat.primitives import hashes
curve = ec.SECP224R1()
pri_obj = bk.generate_elliptic_curve_private_key(curve)
pub_obj = pri_obj.public_key()
from cryptography.hazmat.primitives import hashes
algorithm = hashes.MD5
serverkey = b"\x04\x07cX,\x118\xe4\xff]^\x0c\xc6P'W\x81@\x99@\xb6ow7E[\xc0\x7fJ\xb9\xa1\xef\xa3\xf5\xc8\\A\x86\xfb\xde\x12\x04\xda\xdc\xa1\xd0\x96\xe7\x1f2\x11\x94\x84+#+\xc6"
shared_key = pri_obj.exchange(algorithm, serverkey)
```
**Did I  wrong?**

> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "C:\Python36-64\lib\site-packages\cryptography\hazmat\backends\openssl\ec.py", line 159, in exchange
>     _Reasons.UNSUPPORTED_EXCHANGE_ALGORITHM
> cryptography.exceptions.UnsupportedAlgorithm: This backend does not support the ECDH algorithm.
>

**Comment by reaperhulk** [comment]
You're doing ECDH, not DH, so the actual docs you want are (https://cryptography.io/en/latest/hazmat/primitives/asymmetric/ec/#elliptic-curve-key-exchange-algorithm). In that example you can see that the `algorithm` arg to `exchange` must be `ec.ECDH()` and not a hash algorithm.

However, this is an ugly error message so we should probably make it more clear.

**Comment by Yensan** [comment]
ECDHClientKeyExchange, just as an Android mobile phone:

1.  choose curve, generate public-key / private-key
```python
curve = ec.SECP224R1()
private_key = ec.generate_private_key(curve, default_backend())
peer_public_key = ec.generate_private_key(curve, default_backend()).public_key()
```
2. sent public-key to sever:

```python
shared_key = private_key.exchange(ec.ECDH(), peer_public_key)
```
3. recieve server's key: 
```python
serverkey = b"\x04\x07cX,\x118\xe4\xff]^\x0c\xc6P'W\x81@\x99@\xb6ow7E[\xc0\x7fJ\xb9\xa1\xef\xa3\xf5\xc8\\A\x86\xfb\xde\x12\x04\xda\xdc\xa1\xd0\x96\xe7\x1f2\x11\x94\x84+#+\xc6"
```
4. use 【 client's private-key  + server's public key 】to generate shared-key, or  hand-shake
```python 
derived_key = HKDF(
         algorithm=hashes.MD5(),
         length=16,
         salt=None,
         info=serverkey,
         backend=default_backend()
     ).derive(shared_key)
```

Did I right?  I am driven to crazy by this ECDH thing... 😆

**Comment by Yensan** [comment]
sure, can't use MD5. 😄 
This is not my solution，I just write a python app to login to a server, just as a mobile phone.  And this login process is very complex, ecdh key is just the start ! (How tough that things ...) So, MD5 is short and simple algorithm, and enough for it.
OK, Thank you very much. @reaperhulk  I will try it again, if any question I will push something to here.

**Comment by Yensan** [comment]
hi, @reaperhulk  I think I was wrong. because I paste this pice into project, it doesn't work.
I give you the C++ code that other people use. You see: 
-  they use OpenSSL lib, 
- GenEcdh function is for generating private-key / public-key,  
- DoEcdh function accept private-key / server-pub-key to generate hand-shake-key

When I compile it in Linux with gcc, the result is wrong. So I want use cryptography, Python can cross platforms easily.

```c++
#include "stdafx.h"
#include "openssl/aes.h"
#include "openssl/rsa.h"
#include "openssl/ec.h"
#include "openssl/ecdh.h"
#include "openssl/md5.h"

extern "C" bool GenEcdh(int nid, unsigned char *szPriKey, int *pLenPri, unsigned char *szPubKey, int *pLenPub);
extern "C" bool DoEcdh(int nid, unsigned char * szServerPubKey, int nLenServerPub, unsigned char * szLocalPriKey, int nLenLocalPri, unsigned char * szShareKey, int *pLenShareKey);

#define MD5_DIGEST_LENGTH 16

extern "C" bool GenEcdh(int nid, unsigned char *szPriKey, int *pLenPri, unsigned char *szPubKey, int *pLenPub)
{
	if (!szPriKey || !pLenPri || !szPubKey || !pLenPub)		return FALSE;
	
	EC_KEY *ec_key = EC_KEY_new_by_curve_name(nid);
	if (!ec_key) return FALSE;

	int ret = EC_KEY_generate_key(ec_key);
	if (1 != ret)
	{
		EC_KEY_free(ec_key);
		ec_key = NULL;
		return FALSE;
	}
	int nLenPub = i2o_ECPublicKey(ec_key, NULL);
	unsigned char *pub_key_buf = NULL;
	ret = i2o_ECPublicKey(ec_key, &pub_key_buf);
	if (!ret)
	{
		EC_KEY_free(ec_key);
		ec_key = NULL;
		return FALSE;
	}
	memcpy(szPubKey, pub_key_buf, nLenPub);
	*pLenPub = nLenPub;

	int nLenPri = i2d_ECPrivateKey(ec_key, NULL);
	unsigned char *pri_key_buf = NULL;
	ret = i2d_ECPrivateKey(ec_key, &pri_key_buf);
	if (!ret)
	{
		EC_KEY_free(ec_key);
		ec_key = NULL;
		return FALSE;
	}
	memcpy(szPriKey, pri_key_buf, nLenPri);
	*pLenPri = nLenPri;

	if (ec_key)
	{
		EC_KEY_free(ec_key);
		ec_key = NULL;
	}
	if (pub_key_buf)
	{
		OPENSSL_free(pub_key_buf);
	}
	if (pri_key_buf)
	{
		OPENSSL_free(pri_key_buf);
	}


	return TRUE;
}


void *KDF_MD5(const void *in, size_t inlen, void *out, size_t *outlen)
{
	MD5_CTX ctx;
	MD5_Init(&ctx);
	MD5_Update(&ctx, in, inlen);
	MD5_Final((unsigned char*)out, &ctx);

	*outlen = MD5_DIGEST_LENGTH;

	return out;
}

extern "C" bool DoEcdh(int nid, unsigned char * szServerPubKey, int nLenServerPub, unsigned char * szLocalPriKey, int nLenLocalPri, unsigned char * szShareKey, int *pLenShareKey)
{
	const unsigned char *public_material = (const unsigned char *)szServerPubKey;
	const unsigned char *private_material = (const unsigned char *)szLocalPriKey;

	EC_KEY *pub_ec_key = EC_KEY_new_by_curve_name(nid);
	if (!pub_ec_key)	return FALSE;
	pub_ec_key = o2i_ECPublicKey(&pub_ec_key, &public_material, nLenServerPub);
	if (!pub_ec_key)	return FALSE;

	EC_KEY *pri_ec_key = EC_KEY_new_by_curve_name(nid);
	if (!pri_ec_key)	return FALSE;
	pri_ec_key = d2i_ECPrivateKey(&pri_ec_key, &private_material, nLenLocalPri);
	if (!pri_ec_key) return FALSE;

	if (MD5_DIGEST_LENGTH != ECDH_compute_key((void *)szShareKey, MD5_DIGEST_LENGTH, EC_KEY_get0_public_key(pub_ec_key), pri_ec_key, KDF_MD5))
	{
		EC_KEY_free(pub_ec_key);
		EC_KEY_free(pri_ec_key);

		return FALSE;
	}

	*pLenShareKey = MD5_DIGEST_LENGTH;

	if (pub_ec_key)
	{
		EC_KEY_free(pub_ec_key);
		pub_ec_key = NULL;
	}
	
	if (pri_ec_key)
	{
		EC_KEY_free(pri_ec_key);
		pri_ec_key = NULL;
	}
	
	return TRUE;
}
```

**Comment by Yensan** [comment]
Well。。。In finally, I made some ctypes wrapper just for this ECDH
https://github.com/Yensan/ecdh/tree/master
