### ISSUE TITLE
data size limits are not documented for encrypt method on AESGCM

### ISSUE THREAD

**Issue by vEpiphyte** [pyca/cryptography#4303]
Using the AESGCM primitive, a OverflowError can occur.

Steps to reproduce:

```
import os
from cryptography.hazmat.backends import default_backend
from cryptography.hazmat.primitives.ciphers.aead import AESGCM
buf = b'x' * (2**32 + 1)
lend = default_backend()
iv = os.urandom(16)
key = os.urandom(32)
encryptor = AESGCM(key)
byts = encryptor.encrypt(iv, buf, None)
```
Results in the following exception:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user/.pyenv/versions/somepyenv/lib/python3.6/site-packages/cryptography/hazmat/primitives/ciphers/aead.py", line 147, in encrypt
    backend, self, nonce, data, associated_data, 16
  File "/home/user/.pyenv/versions/somepyenv/lib/python3.6/site-packages/cryptography/hazmat/backends/openssl/aead.py", line 109, in _encrypt
    processed_data = _process_data(backend, ctx, data)
  File "/home/user/.pyenv/versions/somepyenv/lib/python3.6/site-packages/cryptography/hazmat/backends/openssl/aead.py", line 92, in _process_data
    res = backend._lib.EVP_CipherUpdate(ctx, buf, outlen, data, len(data))
OverflowError: integer 4294967297 does not fit '32-bit int'
```

Test environment:
Using Python 3.6.1, cryptography 2.2.2, cffi 1.11.5. Cryptography was installed using pip install onto a venv managed by pyenv.

Suggested course of action:
Update documentation to reflect that the amount of data that can be pushed through `encrypt()` is limited.  This should probably be documented wherever user data could be encrypted and potentially cause a failure for data to cross the cffi interface.

**Comment by vEpiphyte** [comment]
@reaperhulk My use case doesn't need streaming AEAD, and in fact we're moving away from using the primitives entirely.  I think it would be best to document the limits so that no one else ends up in the boat I found myself in accidentally.
