### ISSUE TITLE
NameError: name 'EllipticCurvePublicKeyWithSerialization' is not defined

### ISSUE THREAD

**Issue by wdx7266** [pyca/cryptography#4343]
When I run the following code:

```
from cryptography.hazmat.backends import default_backend
from cryptography.hazmat.primitives.asymmetric import ec

class Signature(object):
    @staticmethod
    def ec_get_pubkey_by_prikey(privateKey:
            private_key = ec.derive_private_key(privateKey, ec.SECP256R1(), default_backend())
            public_key = private_key.public_key()
        return public_key

pri_key = 0x15746f42ec429ce1c20647e92150099b644a00644649f03868a2a5962bd2f9af
pub_key = Signature.ec_get_pubkey_by_prikey(pri_key)

```
I got a mistake:

```
Traceback (most recent call last):
  File "/Crypto/Signature.py", line 5, in <module>
    from cryptography.hazmat.primitives.asymmetric import ec
  File "Python37-32\lib\site-packages\cryptography\hazmat\primitives\asymmetric\ec.py", line 131, in <module>
    EllipticCurvePublicKeyWithSerialization
NameError: name 'EllipticCurvePublicKeyWithSerialization' is not defined

Process finished with exit code 1
```
The version I use is: 

```
>pip list
Package      Version
------------ -------
asn1crypto   0.24.0
cffi         1.11.5
cryptography 2.2.2
```

**Comment by reaperhulk** [comment]
This works fine for me -- if you create a new virtualenv and run this script inside it do you still see the issue?

**Comment by wdx7266** [comment]
OK, you're right. When I run in a new virtualenv, the script run without error. Thanks for your help!
