### ISSUE TITLE
No module named '_cffi_backend' error

### ISSUE THREAD

**Issue by akshaybabloo** [pyca/cryptography#4403]
For some reason I am getting the following error:

```
Traceback (most recent call last):
  File "C:/Users/aksha/Documents/GitHub/neucube-cloud-api/temp.py", line 2, in <module>
    from azure.keyvault import KeyVaultClient, KeyVaultAuthentication
  File "C:\Users\aksha\Miniconda3\envs\neucube\lib\site-packages\azure\keyvault\__init__.py", line 15, in <module>
    from .key_vault_authentication import KeyVaultAuthentication, KeyVaultAuthBase, AccessToken
  File "C:\Users\aksha\Miniconda3\envs\neucube\lib\site-packages\azure\keyvault\key_vault_authentication.py", line 13, in <module>
    from azure.keyvault.http_message_security import HttpMessageSecurity
  File "C:\Users\aksha\Miniconda3\envs\neucube\lib\site-packages\azure\keyvault\http_message_security.py", line 9, in <module>
    from ._internal import _a128cbc_hs256_encrypt, _a128cbc_hs256_decrypt, _JwsHeader, _JwsObject, \
  File "C:\Users\aksha\Miniconda3\envs\neucube\lib\site-packages\azure\keyvault\_internal.py", line 16, in <module>
    from cryptography.hazmat.primitives import hashes, constant_time, padding, hmac
  File "C:\Users\aksha\Miniconda3\envs\neucube\lib\site-packages\cryptography\hazmat\primitives\constant_time.py", line 11, in <module>
    from cryptography.hazmat.bindings._constant_time import lib
ModuleNotFoundError: No module named '_cffi_backend'
```

This never happened, I am not sure what the problem is.

**Versions**

Python: `3.7`
cryptography: `2.3.1`
ciffi: `1.11.5`
pip: `10.0.1`
setuptools: `40.0.0`

**Comment by orihomie** [comment]
> 
> 
> True. My bad. Seems to be a problem when upgrading python 3.6 to 3.7.

So, how did u resolved this problem?

**Comment by akshaybabloo** [comment]
Downgrade to 3.6 for now. Till they add support for 3.7

**Comment by reaperhulk** [comment]
We support Python 3.7 (and indeed test against it in numerous configurations on 3 different OSes). This issue is not caused by a bug in cryptography or cffi and is almost always a problem with the environment on the user's machine. For instance, keeping the same packages while upgrading from 3.6 to 3.7 would break cffi (and any other C package that depends on version specific interfaces). You need to install cffi again with a 3.7 compatible version (which can be accomplished with `pip install -U cffi`).
