### ISSUE TITLE
AssertionError when running script on RPi Zero W, goes away after a few minutes

### ISSUE THREAD

**Issue by charliesneath** [pyca/cryptography#4635]
I get the following error after running my script on my Raspberry Pi Zero W. The error stops after a few minutes and I'm able to run the script as expected without error.

This is problematic because it prevents the script from successfully running right when the Pi has connected to internet.

- Python 2.7, cryptography 2.4.2, cffi 1.11.5, pip 18.1, setuptools 40.6.2
- Cryptography installed using `sudo pip install cryptography --no-binary cryptography`

```
Traceback (most recent call last):
  File "/home/pi/weatherbox/48_hour_forecast.py", line 136, in <module>
    render_forecast(args.location)
  File "/home/pi/weatherbox/48_hour_forecast.py", line 88, in render_forecast
    forecast_data_48_hours.append(darksky.get_time_machine_forecast(location, timestamp_today))
  File "/home/pi/weatherbox/darksky.py", line 83, in get_time_machine_forecast
    coordinates = get_lat_long(location_search)
  File "/home/pi/weatherbox/darksky.py", line 16, in get_lat_long
    saved_location = saved_location_ref.get()
  File "/usr/local/lib/python2.7/dist-packages/firebase_admin/db.py", line 219, in get
    return self._client.body('get', self._add_suffix(), params=params)
  File "/usr/local/lib/python2.7/dist-packages/firebase_admin/_http_client.py", line 93, in body
    resp = self.request(method, url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/firebase_admin/db.py", line 882, in request
    return super(_Client, self).request(method, url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/firebase_admin/_http_client.py", line 84, in request
    resp = self._session.request(method, self._base_url + url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/google/auth/transport/requests.py", line 198, in request
    self._auth_request, method, url, request_headers)
  File "/usr/local/lib/python2.7/dist-packages/google/auth/credentials.py", line 122, in before_request
    self.refresh(request)
  File "/usr/local/lib/python2.7/dist-packages/google/oauth2/service_account.py", line 320, in refresh
    assertion = self._make_authorization_grant_assertion()
  File "/usr/local/lib/python2.7/dist-packages/google/oauth2/service_account.py", line 314, in _make_authorization_grant_assertion
    token = jwt.encode(self._signer, payload)
  File "/usr/local/lib/python2.7/dist-packages/google/auth/jwt.py", line 94, in encode
    signature = signer.sign(signing_input)
  File "/usr/local/lib/python2.7/dist-packages/google/auth/crypt/_cryptography_rsa.py", line 126, in sign
    message, _PADDING, _SHA256)
  File "/usr/lib/python2.7/dist-packages/cryptography/hazmat/backends/openssl/rsa.py", line 463, in sign
    algorithm, self, data
  File "/usr/lib/python2.7/dist-packages/cryptography/hazmat/backends/openssl/rsa.py", line 241, in _rsa_sig_sign
    assert errors[0].lib == backend._lib.ERR_LIB_RSA
AssertionError
```

**Comment by charliesneath** [comment]
My issues seems to be the same as (or very similar) to what's reported in #2933.

**Comment by reaperhulk** [comment]
@charliesneath looks like we're failing an assertion on the type of error it's seeing. I have a suspect in my mind, but would you mind installing the current cryptography master branch and then run your code after a reboot to see what happens?

**Comment by charliesneath** [comment]
@reaperhulk Installed master via `sudo pip install git+https://github.com/pyca/cryptography.git@master`

When I run the script, it hangs and I get the following output when doing a keyboard interrupt. I'll let it run for a little long since the Pi can take a while to chew on bigger jobs, but let me know if there's something else to try.

```
^CTraceback (most recent call last):
  File "weatherbox/48_hour_forecast.py", line 12, in <module>
    import darksky
  File "/home/pi/weatherbox/darksky.py", line 5, in <module>
    import firebase_admin
  File "/usr/local/lib/python2.7/dist-packages/firebase_admin/__init__.py", line 23, in <module>
    from firebase_admin import credentials
  File "/usr/local/lib/python2.7/dist-packages/firebase_admin/credentials.py", line 22, in <module>
    from google.oauth2 import credentials
  File "/usr/local/lib/python2.7/dist-packages/google/oauth2/credentials.py", line 42, in <module>
    from google.oauth2 import _client
  File "/usr/local/lib/python2.7/dist-packages/google/oauth2/_client.py", line 35, in <module>
    from google.auth import jwt
  File "/usr/local/lib/python2.7/dist-packages/google/auth/jwt.py", line 54, in <module>
    from google.auth import _service_account_info
  File "/usr/local/lib/python2.7/dist-packages/google/auth/_service_account_info.py", line 22, in <module>
    from google.auth import crypt
  File "/usr/local/lib/python2.7/dist-packages/google/auth/crypt/__init__.py", line 39, in <module>
    from google.auth.crypt import rsa
  File "/usr/local/lib/python2.7/dist-packages/google/auth/crypt/rsa.py", line 20, in <module>
    from google.auth.crypt import _cryptography_rsa
  File "/usr/local/lib/python2.7/dist-packages/google/auth/crypt/_cryptography_rsa.py", line 46, in <module>
    _BACKEND = backends.default_backend()
  File "/usr/local/lib/python2.7/dist-packages/cryptography/hazmat/backends/__init__.py", line 15, in default_backend
    from cryptography.hazmat.backends.openssl.backend import backend
  File "/usr/local/lib/python2.7/dist-packages/cryptography/hazmat/backends/openssl/__init__.py", line 7, in <module>
    from cryptography.hazmat.backends.openssl.backend import backend
  File "/usr/local/lib/python2.7/dist-packages/cryptography/hazmat/backends/openssl/backend.py", line 2208, in <module>
    backend = Backend()
  File "/usr/local/lib/python2.7/dist-packages/cryptography/hazmat/backends/openssl/backend.py", line 113, in __init__
    self.activate_osrandom_engine()
  File "/usr/local/lib/python2.7/dist-packages/cryptography/hazmat/backends/openssl/backend.py", line 155, in activate_osrandom_engine
    with self._get_osurandom_engine() as e:
  File "/usr/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/usr/local/lib/python2.7/dist-packages/cryptography/hazmat/backends/openssl/backend.py", line 139, in _get_osurandom_engine
    res = self._lib.ENGINE_init(e)
KeyboardInterrupt
```

**Comment by charliesneath** [comment]
@reaperhulk I've run this a few times and even though it takes a while (5min!), it does eventually work and the script runs as expected. After running it the first time, subsequent runs don't take as long.

Out of curiosity: why does this delay only happen on the first time? Is something being compiled each time there's a fresh reboot of the system?

**Comment by charliesneath** [comment]
This is great, and thanks for the thorough explanation.

As long as it will eventually work, then I can manage for now. 

When do you think this change will this be available via `pip install `cryptography`?

**Comment by reaperhulk** [comment]
We'll probably be releasing 2.5 in the next ~month.

**Comment by mattdodge** [comment]
I'm sporadically seeing what I think may be the same thing on an Ubuntu box running our unit test suite.
* OpenSSL 1.1.0h  27 Mar 2018
* Python 3.5.2
* cryptography 2.4.2

It only seems to happen about ~10% of the time and it started happening when we upgraded cryptography from 1.5.x to 2.4.2.

```
env/python3.5/site-packages/jwt/api_jwt.py:56: in encode
    json_payload, key, algorithm, headers, json_encoder
env/python3.5/site-packages/jwt/api_jws.py:99: in encode
    signature = alg_obj.sign(signing_input, key)
env/python3.5/site-packages/jwt/algorithms.py:182: in sign
    return signer.finalize()
env/python3.5/site-packages/cryptography/hazmat/backends/openssl/rsa.py:295: in finalize
    self._hash_ctx.finalize()
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

backend = <cryptography.hazmat.backends.openssl.backend.Backend object at 0x7f4ca4d1ff60>
padding = <cryptography.hazmat.primitives.asymmetric.padding.PKCS1v15 object at 0x7f4ca377d128>
algorithm = <cryptography.hazmat.primitives.hashes.SHA256 object at 0x7f4ca377d160>
private_key = <cryptography.hazmat.backends.openssl.rsa._RSAPrivateKey object at 0x7f4ca37b1ba8>
data = b'\xbeYc\xc1?\xc97\x9fd\xb8\xd2a~N\x86C\xd9\xc0<\xc1\xda\xcf/\x93)\xf3\xfd\x9d\xf2\xa1\xd7\xe1'

    def _rsa_sig_sign(backend, padding, algorithm, private_key, data):
        pkey_ctx = _rsa_sig_setup(
            backend, padding, algorithm, private_key, data,
            backend._lib.EVP_PKEY_sign_init
        )
        buflen = backend._ffi.new("size_t *")
        res = backend._lib.EVP_PKEY_sign(
            pkey_ctx,
            backend._ffi.NULL,
            buflen,
            data,
            len(data)
        )
        backend.openssl_assert(res == 1)
        buf = backend._ffi.new("unsigned char[]", buflen[0])
        res = backend._lib.EVP_PKEY_sign(
            pkey_ctx, buf, buflen, data, len(data))
        if res != 1:
            errors = backend._consume_errors()
>           assert errors[0].lib == backend._lib.ERR_LIB_RSA
E           AssertionError

env/python3.5/site-packages/cryptography/hazmat/backends/openssl/rsa.py:239: AssertionError
```

Happens when calling `jwt.encode` (PyJWT 1.4.2):
```python
jwt.encode(_data, _priv_key_bytes, algorithm='RS256')
```
Do you think this is the same problem? Is there a way to more reliably reproduce it so I can confirm that cryptography master is indeed going to fix it? Also, any ETA on 2.5 release? Thanks a bunch!

**Comment by mattdodge** [comment]
I was able to launch a pdb shell on the fail which let me inspect the `errors` variable. That seemed to be the easiest way unless there's some other kind of debug flag.

Here's what errors looks like, expanded for helpfulness (I hope)
```
(pdb) [e.__dict__ for e in errors]
[{'_code': 50901100, '_func': 139, '_lib': 3, '_reason': 108},
 {'_code': 67665923, '_func': 136, '_lib': 4, '_reason': 3},
 {'_code': 67526724, '_func': 102, '_lib': 4, '_reason': 68}]
```

I'm happy to open up a new issue for this too if it seems unrelated

**Comment by alex** [comment]
Looks like `errors[0]` is `(ERR_LIB_BN, BN_F_BN_MOD_INVERSE_NO_BRANCH, BN_R_NO_INVERSE)`. No idea what to make of that, a corrupt key of some sort?

**Comment by mattdodge** [comment]
Ahh...that's a good hint actually. I have a feeling this is completely unrelated and very much my fault. This particular unit test is testing a bad JWT (signed by a corrupt or invalid private key). We have applied a very advanced "corruption algorithm" to the private key which converts all `a` bytes to `b` bytes. I'm guessing for some private keys this causes this type of error to be thrown but not all keys. Interestingly we never saw this over thousands of runs with the old cryptography but I can certainly understand how this would be happening now and it also explains the "it only happens sometimes" behavior. I will fix the test and exception handling on our end, apologies for cluttering up this issue but I appreciate the help!

**Comment by reaperhulk** [comment]
@mattdodge Could you open a new issue with a key that exhibits this? We generally consider any InternalError to be exposing implementation that should not be visible to the end user, so we'd like to add a test that can catch this type of failure.
