### ISSUE TITLE
SystemError: unexpected internal exception (please report a bug) installing with PyPy 3.5 on Windows 10

### ISSUE THREAD

**Issue by Altirix** [pyca/cryptography#4641]
Using PyPy3.5 Stable
pip        18.1
setuptools 40.6.3
Windows 10  Build 17134 (1803)

Unable to install, feel like I've tried everything and can't seem to find anything on the problem I'm getting.

```
C:\Users\Michael>pip install cryptography
Collecting cryptography
  Using cached https://files.pythonhosted.org/packages/f3/39/d3904df7c56f8654691c4ae1bdb270c1c9220d6da79bd3b1fbad91afd0e1/cryptography-2.4.2.tar.gz
  Installing build dependencies ... error
  Complete output from command c:\users\michael\appdata\local\programs\python\pypy3\pypy3.exe -m pip install --ignore-installed --no-user --prefix C:\Users\Michael\AppData\Local\Temp\pip-build-env-jkco8raq --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- setuptools>=18.5 wheel "cffi>=1.7,!=1.11.3; python_implementation != 'PyPy'":
  RPython traceback:
    File "pypy_interpreter.c", line 42299, in BuiltinCode1_fastcall_1
    File "pypy_module_posix.c", line 4913, in get_terminal_size
  Traceback (most recent call last):
    File "c:\users\michael\appdata\local\programs\python\pypy3\lib-python\3\runpy.py", line 193, in _run_module_as_main
      "__main__", mod_spec)
    File "c:\users\michael\appdata\local\programs\python\pypy3\lib-python\3\runpy.py", line 85, in _run_code
      exec(code, run_globals)
    File "c:\users\michael\appdata\local\programs\python\pypy3\site-packages\pip\__main__.py", line 19, in <module>
      sys.exit(_main())
    File "c:\users\michael\appdata\local\programs\python\pypy3\site-packages\pip\_internal\__init__.py", line 64, in main
      cmd_name, cmd_args = parse_command(args)
    File "c:\users\michael\appdata\local\programs\python\pypy3\site-packages\pip\_internal\cli\main_parser.py", line 58, in parse_command
      parser = create_main_parser()
    File "c:\users\michael\appdata\local\programs\python\pypy3\site-packages\pip\_internal\cli\main_parser.py", line 28, in create_main_parser
      'formatter': UpdatingDefaultsHelpFormatter(),
    File "c:\users\michael\appdata\local\programs\python\pypy3\site-packages\pip\_internal\cli\parser.py", line 26, in __init__
      kwargs['width'] = get_terminal_size()[0] - 2
    File "c:\users\michael\appdata\local\programs\python\pypy3\site-packages\pip\_internal\utils\compat.py", line 217, in get_terminal_size
      return tuple(shutil.get_terminal_size())
    File "c:\users\michael\appdata\local\programs\python\pypy3\lib-python\3\shutil.py", line 1078, in get_terminal_size
      size = os.get_terminal_size(sys.__stdout__.fileno())
  SystemError: unexpected internal exception (please report a bug): <WindowsError object at 0x4899b20>; internal traceback was dumped to stderr

  ----------------------------------------
Command "c:\users\michael\appdata\local\programs\python\pypy3\pypy3.exe -m pip install --ignore-installed --no-user --prefix C:\Users\Michael\AppData\Local\Temp\pip-build-env-jkco8raq --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- setuptools>=18.5 wheel "cffi>=1.7,!=1.11.3; python_implementation != 'PyPy'"" failed with error code 1 in None
```

**Comment by alex** [comment]
This looks like a PyPy bug, not a cryptography bug.

**Comment by Altirix** [comment]
thanks, ill switch over to python and stuff should hopefully run smoothly. no surprise its the cause.

Even tho this is a PyPy problem would you know any workarounds? or if the nightly builds might have fixed this?

**Comment by alex** [comment]
I can't say I've seen this before, no.

Based on the traceback, I expected you'd get this installing _any_ package on PyPy, so please file this bug with them! I'm closing this for us though.

**Comment by Altirix** [comment]
Thanks, you pointed me in the right direction.

If anyone else has this issue. it is for PyPy, os.get_terminal_size causes it and it was fixed in a recent nightly. Wouldnt have expected that from a "stable" build.
