### ISSUE TITLE
Exception when getting public_bytes of Ed25519PublicKey

### ISSUE THREAD

**Issue by richardmss** [pyca/cryptography#4808]
I created an ed25519 key with: `ssh-keygen -t ed25519`.
This one I loaded successfully with cryptography 2.6.1. Dumping the loaded key however creates the following exception:

```
>>> print(key.__class__)
<class 'cryptography.hazmat.backends.openssl.ed25519._Ed25519PublicKey'>

>>> key.public_bytes(Encoding.OpenSSH, PublicFormat.OpenSSH)
Traceback (most recent call last):
  File "/usr/lib/python3.6/code.py", line 91, in runcode
    exec(code, self.locals)
  File "<console>", line 1, in <module>
  File "/home/richard/.local/lib/python3.6/site-packages/cryptography/hazmat/backends/openssl/ed25519.py", line 45, in public_bytes
    encoding, format, self, self._evp_pkey, None
  File "/home/richard/.local/lib/python3.6/site-packages/cryptography/hazmat/backends/openssl/backend.py", line 1838, in _public_key_bytes
    return self._openssh_public_key_bytes(key)
  File "/home/richard/.local/lib/python3.6/site-packages/cryptography/hazmat/backends/openssl/backend.py", line 1886, in _openssh_public_key_bytes
    assert isinstance(key, ec.EllipticCurvePublicKey)
AssertionError
```

**Comment by richardmss** [comment]
This behavior seems to be in accordance with the doc found here: 
https://cryptography.io/en/latest/hazmat/primitives/asymmetric/ed25519/#cryptography.hazmat.primitives.asymmetric.ed25519.Ed25519PublicKey.public_bytes

To provide a bit more context: I'd like to compute the ssh fingerprint of the key, hence the `Encoding.OpenSSH`. This works for all other ssh keys, except for this one.

**Comment by alex** [comment]
There's really two bugs here:

a) If `OpenSSH` isn't support it should give a proper error, not an `assert` failure.

b) We should support OpenSSH!

**Comment by alex** [comment]
are you by chance interested in implementing this? you'd need to add the implementation here https://github.com/pyca/cryptography/blob/master/src/cryptography/hazmat/backends/openssl/backend.py#L1870 and then add tests

**Comment by richardmss** [comment]
I'll look into it.
