### ISSUE TITLE
AttributeError: module 'cryptography' has no attribute '__version__'

### ISSUE THREAD

**Issue by mengguiyouziyi** [pyca/cryptography#4852]
Python 3.6.6 |Anaconda 4.3.0 (64-bit)| (default, Jun 28 2018, 11:27:44) [MSC v.1900 64 bit (AMD64)]
Type "copyright", "credits" or "license" for more information.
IPython 5.5.0 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.
PyDev console: using IPython 5.5.0
Python 3.6.6 |Anaconda 4.3.0 (64-bit)| (default, Jun 28 2018, 11:27:44) [MSC v.1900 64 bit (AMD64)] on win32

->import cryptography
->cryptography.__version__
Traceback (most recent call last):
  File "C:\Users\sunlijian\AppData\Local\Continuum\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 2882, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-3-a9cc0815f168>", line 1, in <module>
    cryptography.__version__
AttributeError: module 'cryptography' has no attribute '__version__'

I reinstall it, but the error still heppen.
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
C:\Users\xxx\AppData\Local\Continuum\Anaconda3\python.exe "mypath/scrapyProject/cmd_test.py"

2492
2019-04-19 16:18:42 [scrapy.utils.log] INFO: Scrapy 1.5.2 started (bot: scrapyProject)
Traceback (most recent call last):
  File "D:/My Package/My project/sogou-spider/sogouTrans/scrapyProject/cmd_test.py", line 21, in <module>
    execute(cmd_list)
  File "C:\Users\sunlijian\AppData\Local\Continuum\Anaconda3\lib\site-packages\scrapy\cmdline.py", line 149, in execute
    cmd.crawler_process = CrawlerProcess(settings)
  File "C:\Users\sunlijian\AppData\Local\Continuum\Anaconda3\lib\site-packages\scrapy\crawler.py", line 252, in __init__
    log_scrapy_info(self.settings)
  File "C:\Users\sunlijian\AppData\Local\Continuum\Anaconda3\lib\site-packages\scrapy\utils\log.py", line 149, in log_scrapy_info
    for name, version in scrapy_components_versions()
  File "C:\Users\sunlijian\AppData\Local\Continuum\Anaconda3\lib\site-packages\scrapy\utils\versions.py", line 22, in scrapy_components_versions
    cryptography_version = cryptography.__version__
AttributeError: module 'cryptography' has no attribute '__version__'

when i run my scrapy project, i get this error.
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
how can i do? thank you!!!

**Comment by alex** [comment]
Sorry for the slow response. Unfortunately there's not enough information to debug this. Unless you can provide steps for us reproduce this, there's not much we can do.
