### ISSUE TITLE
derive_private_key raises TypeError with correct EllipticCurve interface

### ISSUE THREAD

**Issue by samuelcolvin** [pyca/cryptography#4928]
* Python: **3.7.2**
* cryptography: **2.7**

The following

```py
from cryptography.hazmat.backends import default_backend
from cryptography.hazmat.primitives.asymmetric import ec

key = ec.derive_private_key(1, ec.SECP256R1, default_backend())
```

Fails with

```py
Traceback (most recent call last):
  File "crypt.py", line 4, in <module>
    key = ec.derive_private_key(1, ec.SECP256R1, default_backend())
  File "/home/samuel/code/em2/env/lib/python3.7/site-packages/cryptography/hazmat/primitives/asymmetric/ec.py", line 338, in derive_private_key
    raise TypeError("curve must provide the EllipticCurve interface.")
TypeError: curve must provide the EllipticCurve interface.
```

However calling what this uses internally `default_backend().derive_elliptic_curve_private_key(1, ec.SECP256R1)` works fine.

The problem seems to be with:

https://github.com/pyca/cryptography/blob/fadd16d10246e2e2a59c54d32abef5301d5e5708/src/cryptography/hazmat/primitives/asymmetric/ec.py#L337-L338

**Comment by alex** [comment]
You need to pass an instance of `EllipticCurve`, not the class. You should be passing `ec.SECP256R1()`. Note the parens.

**Comment by samuelcolvin** [comment]
Thanks, sorry. 

Just odd that `generate_private_key` works with the class, not just an instance eg. `ec.generate_private_key(ec.SECP256R1, default_backend())` while its companion method `ec.generate_private_key` does not.
