### ISSUE TITLE
x509.Certificate.not_valid_before raises error on year 0

### ISSUE THREAD

**Issue by dagheyman** [pyca/cryptography#4949]
I'm not sure this is a bug, but I recently ran into this so I thought I'd report it. [This](https://lapo.it/asn1js/#MIIBbjCB2AIBADANBgkqhkiG9w0BAQUFADAAMB4YDTAwMDAwMTAxMDAwMFoYDTAwMDAwMTAxMDAwMFowADCBnzANBgkqhkiG9w0BAQEFAAOBjQAwgYkCgYEApsqeY0hZANCKohjl6QOoiAT9Iw3OsM_GfjBeA8wZkaUrJWgnFbP_t56eVYfXeQwe-b2Hu_fIORV1QDgNj_eiVeHWuo2VJKe_9CB5FkWx7XwbwIwAVKxbaock7S7DQK97OqVJs0Ik-tyqA3A7t5OEAHtgVVH0Hvp7rDsVx-42R8kCAwEAATANBgkqhkiG9w0BAQUFAAOBgQArj7uYaX_3Luu07soESV8D3KDA8l3TMWoE9RIvB3YoIvkANkAD5XAjI5HwLQRYXmXBu12tQTaD7E3k34CAiK440gRjr_zfnlwVmiHi1QzSc8c-m92omtrJXA12p-9AiEitxOMYSAmRS12LaElNoea6Vt11iVfK0Z634JjAWt5r2Q)  certificate, with validity set to year 0, raises error when **not_valid_before** is called.

**To reproduce:**
`$ python script.py`

**script.py**
```
from cryptography.hazmat.backends import default_backend
from cryptography import x509

pem = b"""
-----BEGIN CERTIFICATE-----
MIIBbjCB2AIBADANBgkqhkiG9w0BAQUFADAAMB4YDTAwMDAwMTAxMDAwMFoYDTAw
MDAwMTAxMDAwMFowADCBnzANBgkqhkiG9w0BAQEFAAOBjQAwgYkCgYEApsqeY0hZ
ANCKohjl6QOoiAT9Iw3OsM/GfjBeA8wZkaUrJWgnFbP/t56eVYfXeQwe+b2Hu/fI
ORV1QDgNj/eiVeHWuo2VJKe/9CB5FkWx7XwbwIwAVKxbaock7S7DQK97OqVJs0Ik
+tyqA3A7t5OEAHtgVVH0Hvp7rDsVx+42R8kCAwEAATANBgkqhkiG9w0BAQUFAAOB
gQArj7uYaX/3Luu07soESV8D3KDA8l3TMWoE9RIvB3YoIvkANkAD5XAjI5HwLQRY
XmXBu12tQTaD7E3k34CAiK440gRjr/zfnlwVmiHi1QzSc8c+m92omtrJXA12p+9A
iEitxOMYSAmRS12LaElNoea6Vt11iVfK0Z634JjAWt5r2Q==
-----END CERTIFICATE-----
"""

cert = x509.load_pem_x509_certificate(pem, default_backend())
print(cert.not_valid_before)
```
```
Traceback (most recent call last):
  File "script.py", line 18, in <module>
    print(cert.not_valid_before)
  File "/usr/lib/python3.7/site-packages/cryptography/hazmat/backends/openssl/x509.py", line 84, in not_valid_before
    return _parse_asn1_time(self._backend, asn1_time)
  File "/usr/lib/python3.7/site-packages/cryptography/hazmat/backends/openssl/decode_asn1.py", line 793, in _parse_asn1_time
    return _parse_asn1_generalized_time(backend, generalized_time)
  File "/usr/lib/python3.7/site-packages/cryptography/hazmat/backends/openssl/decode_asn1.py", line 800, in _parse_asn1_generalized_time
    return datetime.datetime.strptime(time, "%Y%m%d%H%M%SZ")
  File "/usr/lib/python3.7/_strptime.py", line 577, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
  File "/usr/lib/python3.7/_strptime.py", line 544, in _strptime
    datetime_date(year, 1, 1).toordinal() + 1
ValueError: year 0 is out of range
```
Tested with Python 3.7.3, Cryptography 2.7, Arch Linux.

**openssl parses the cert fine:**
```
$ openssl x509 -in cert.crt -text -noout                                                                                                                                                                                                    
Certificate:
    Data:
        Version: 1 (0x0)
        Serial Number: 0 (0x0)
        Signature Algorithm: sha1WithRSAEncryption
        Issuer: 
        Validity
            Not Before: Jan  1 00:00:00 0 GMT
            Not After : Jan  1 00:00:00 0 GMT
        Subject: 
        Subject Public Key Info:
            Public Key Algorithm: rsaEncryption
                RSA Public-Key: (1024 bit)
                Modulus:
                    00:a6:ca:9e:63:48:59:00:d0:8a:a2:18:e5:e9:03:
                    a8:88:04:fd:23:0d:ce:b0:cf:c6:7e:30:5e:03:cc:
                    19:91:a5:2b:25:68:27:15:b3:ff:b7:9e:9e:55:87:
                    d7:79:0c:1e:f9:bd:87:bb:f7:c8:39:15:75:40:38:
                    0d:8f:f7:a2:55:e1:d6:ba:8d:95:24:a7:bf:f4:20:
                    79:16:45:b1:ed:7c:1b:c0:8c:00:54:ac:5b:6a:87:
                    24:ed:2e:c3:40:af:7b:3a:a5:49:b3:42:24:fa:dc:
                    aa:03:70:3b:b7:93:84:00:7b:60:55:51:f4:1e:fa:
                    7b:ac:3b:15:c7:ee:36:47:c9
                Exponent: 65537 (0x10001)
    Signature Algorithm: sha1WithRSAEncryption
         2b:8f:bb:98:69:7f:f7:2e:eb:b4:ee:ca:04:49:5f:03:dc:a0:
         c0:f2:5d:d3:31:6a:04:f5:12:2f:07:76:28:22:f9:00:36:40:
         03:e5:70:23:23:91:f0:2d:04:58:5e:65:c1:bb:5d:ad:41:36:
         83:ec:4d:e4:df:80:80:88:ae:38:d2:04:63:af:fc:df:9e:5c:
         15:9a:21:e2:d5:0c:d2:73:c7:3e:9b:dd:a8:9a:da:c9:5c:0d:
         76:a7:ef:40:88:48:ad:c4:e3:18:48:09:91:4b:5d:8b:68:49:
         4d:a1:e6:ba:56:dd:75:89:57:ca:d1:9e:b7:e0:98:c0:5a:de:
         6b:d9
```

**Comment by reaperhulk** [comment]
This is unfortunate, but a consequence of datetimes wanting real values and X509 ASN.1 encoded values being capable of holding an unbounded quantity of garbage. We could try compensate for this by just setting it to `datetime.MINYEAR`, but then we would be showing a value that was no longer a bijective mapping between the ASN.1 raw value and the datetime object. I think we're stuck erroring like this in the (extremely rare and very broken) cases where the value is not representable. If you need to parse super broken things you sadly need a pure ASN.1 parser. Sorry!
