### ISSUE TITLE
RSA public key verify 

### ISSUE THREAD

**Issue by lud4ik** [pyca/cryptography#5044]
I need to use SmileID API. Requests are signed with signature by public key, and response signature must be verified.
The algorithm for calculate outgoing signature
```

1. Create a timestamp
2. Join the integer value of your int Partner ID to the timestamp using a semi-colon in the format 5:[timestamp]
3. Create a SHA256 hash of the string created in Step 2
4. Public Key encrypt the hash using your Base 64 decoded API key. We encourage that you utilise the base 64 encoded version and then decode the api key on your server to public encrypt the hash, however, should you choose to use the the decoded version of your api key, you will also find it here
5. Base64 encode the encrypted hash
6. Finally join the the encrypted hash to  the unencrypted hash using the "|" character
```

Public key is used to verify the signature of response coming from smileid server. I have problems with it. I tried to use:
```
public_key.verify(
    base64.b64decode(encrypted),
    hashed.encode('ascii'),
    padding.PKCS1v15(),
    # hashes.SHA256(), not sure but its positional argument
)
```
It mismatch by such calculation. Maybe I am just using wrong your function? Can you help please?
Code from Ruby that should work (from documentation):
```
> Calculating an incoming signature:

api_key = "TgorWTFHTG5NL2hEUU5aM3M2ZWJCUndWZGR1aTRLejNCTGZ2RkJwWis1Myty="
partner_id = "001"
timestamp = body["timestamp"]
hash = Digest::SHA256.hexdigest([partner_id.to_i, timestamp].join(":"))
encrypted, hashed = body["sec_key"].split("|")
success = OpenSSL::PKey::RSA.new(Base64.decode64(api_key)).public_decrypt(Base64.decode64(encrypted)) == hash && hash == hashed
## success should equal true
```
Is there a way for public_decrypt?

**Comment by reaperhulk** [comment]
You probably need Prehashed (search the docs). Right now it will hash your incoming msg, but that’s already hashed.

**Comment by lud4ik** [comment]
I tried code
```
    def verify_response(self, signature, timestamp):
        encrypted, hashed = signature.split("|")
        hash_ = hashlib.sha256(
            '{}:{}'.format(self._partner_id, timestamp).encode('ascii')
        ).hexdigest()
        return hash_ == hashed and self._public_key.verify(
            base64.b64decode(encrypted),
            hashed.encode('ascii'),
            padding.PKCS1v15(),
            utils.Prehashed(hashes.SHA256()),
        )
```
and get the exception:
```
Traceback (most recent call last):
  File "../smile.py", line 120, in <module>
    valid = smile_id.verify_response(resp['sec_key'], resp['timestamp'])
  File "../smile.py", line 71, in verify_response
    utils.Prehashed(hashes.SHA256()),
  File ".../site-packages/cryptography/hazmat/backends/openssl/rsa.py", line 474, in verify
    self._backend, data, algorithm
  File ".../site-packages/cryptography/hazmat/backends/openssl/utils.py", line 48, in _calculate_digest_and_algorithm
    "The provided data must be the same length as the hash "
```
