### ISSUE TITLE
internal error  with X25519 in FIPS mode (RHEL 8)

### ISSUE THREAD

**Issue by wenottingham** [pyca/cryptography#5082]
```
[cloud-user@fipsy-fu ~]$ pip3 freeze | egrep "(cryptography|cffi)"
cffi==1.13.2
cryptography==2.8
```
Non-wheel install. wheel works, which is an interesting data point.

Platform: RHEL 8.1

```
[cloud-user@fipsy-fu ~]$ python3
Python 3.6.8 (default, Oct 11 2019, 15:04:54) 
[GCC 8.3.1 20190507 (Red Hat 8.3.1-4)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import cryptography
>>> from cryptography.hazmat.primitives.asymmetric.x25519 import (X25519PrivateKey,X25519PrivateKey)
>>> print(X25519PrivateKey.generate())
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/cloud-user/.local/lib/python3.6/site-packages/cryptography/hazmat/primitives/asymmetric/x25519.py", line 44, in generate
    return backend.x25519_generate_key()
  File "/home/cloud-user/.local/lib/python3.6/site-packages/cryptography/hazmat/backends/openssl/backend.py", line 2227, in x25519_generate_key
    evp_pkey = self._evp_pkey_keygen_gc(self._lib.NID_X25519)
  File "/home/cloud-user/.local/lib/python3.6/site-packages/cryptography/hazmat/backends/openssl/backend.py", line 2215, in _evp_pkey_keygen_gc
    self.openssl_assert(evp_pkey_ctx != self._ffi.NULL)
  File "/home/cloud-user/.local/lib/python3.6/site-packages/cryptography/hazmat/backends/openssl/backend.py", line 131, in openssl_assert
    return binding._openssl_assert(self._lib, ok)
  File "/home/cloud-user/.local/lib/python3.6/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 78, in _openssl_assert
    errors_with_text
cryptography.exceptions.InternalError: Unknown OpenSSL error. This error is commonly encountered when another library is not cleaning up the OpenSSL error stack. If you are using cryptography with another library that uses OpenSSL try disabling it before reporting a bug. Otherwise please file an issue at https://github.com/pyca/cryptography/issues with information on how to reproduce this. ([_OpenSSLErrorWithText(code=101306568, lib=6, func=157, reason=200, reason_text=b'error:0609D0C8:digital envelope routines:int_ctx_new:disabled for FIPS')])
```

**Comment by tiran** [comment]
X25519 is prohibited by RHEL's downstream FIPS patch. I have been working on a PR and tests for FIPS based on @reaperhulk's first attempt, see https://github.com/pyca/cryptography/pull/5024

**Comment by alex** [comment]
Worth noting that FIPS 180-3 will allow x25519, so I assume rhel will
update their patches shortly

**Comment by wenottingham** [comment]
> X25519 is prohibited by RHEL's downstream FIPS patch. I have been working on a PR and tests for FIPS based on @reaperhulk's first attempt, see #5024

Right, but in that case, we should in theory get something like what we get on EL7:
```
>>> import cryptography
>>> print(cryptography)
<module 'cryptography' from '/home/user/.local/lib/python2.7/site-packages/cryptography/__init__.pyc'>
>>> from cryptography.hazmat.primitives.asymmetric.x25519 import (X25519PrivateKey,X25519PrivateKey)
>>> print(X25519PrivateKey.generate())
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user/.local/lib/python2.7/site-packages/cryptography/hazmat/primitives/asymmetric/x25519.py", line 42, in generate
    _Reasons.UNSUPPORTED_EXCHANGE_ALGORITHM
cryptography.exceptions.UnsupportedAlgorithm: X25519 is not supported by this version of OpenSSL.
```
That I can handle - InternalError not so much.

**Comment by reaperhulk** [comment]
Yeah this is a bug, but it should be resolved by landing a FIPS patch. Incidentally, FIPS disabling this is a wonderful example of how FIPS harms security far more than it helps, haha.

**Comment by wenottingham** [comment]
Ah, OK, now I see that the only reason the "right" thing happens on EL7 is because OpenSSL is so old the algorithm is disabled that way... and the wheel works because it statically brings in its own OpenSSL.

Closing, downstream problem.
