### ISSUE TITLE
No module named '_cffi_backend'

### ISSUE THREAD

**Issue by build-agent** [pyca/cryptography#5122]
When I am running an exe built using py2exe, the exe is throwing ImportError as shown below. I am running Python 3.7.6 on Windows with pip 20.0.2, and these modules:
cffi (1.14.0)
cryptography (2.8)
setuptools (45.2.0)
py2exe (0.9.3.2)

I understand there was an old issue #4403 , but I don't see how the issue was resolved. I tried re-installing cffi as suggested in #4403 , but doesn't help. Any idea how to resolve this issue?

```
Traceback (most recent call last):
  File "boot_service.py", line 22, in <module>
  File "ksproxyservice.pyc", line 21, in <module>
  File "ksproxy.pyc", line 24, in <module>
  File "cryptography\x509\__init__.pyc", line 8, in <module>
  File "cryptography\x509\base.pyc", line 18, in <module>
  File "cryptography\x509\extensions.pyc", line 20, in <module>
  File "cryptography\hazmat\primitives\constant_time.pyc", line 11, in <module>
  File "<loader>", line 10, in <module>
  File "<loader>", line 8, in __load
ImportError: (No module named '_cffi_backend') 'C:\\Users\\Administrator\\Desktop\\ks\\dist\\cryptography.hazmat.bindings._constant_time.pyd'
```

**Comment by Legorooj** [comment]
@build-agent I'd suggest you use PyInstaller - it includes default support for this lib. Otherwise, you'll need a hidden import or similar.

**Comment by alex** [comment]
Apologies for the slow response -- we're not able to provide support for py2exe. We ship a fairly standard python package with c extensions.
