### ISSUE TITLE
Add library cryptography_vectors to test in setup.py 

### ISSUE THREAD

**Issue by honglei** [pyca/cryptography#5133]
/opt/python38/bin/python3.8 setup.py  test
```text

======================================================================
ERROR: tests.x509.test_x509 (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: tests.x509.test_x509
Traceback (most recent call last):
  File "/opt/python38/lib/python3.8/unittest/loader.py", line 436, in _find_test_path
    module = self._get_module_from_name(name)
  File "/opt/python38/lib/python3.8/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/home/lccy/Python/cryptography-2.8/tests/x509/test_x509.py", line 45, in <module>
    from ..hazmat.primitives.test_ec import _skip_curve_unsupported
  File "/home/lccy/Python/cryptography-2.8/tests/hazmat/primitives/test_ec.py", line 27, in <module>
    from ...utils import (
  File "/home/lccy/Python/cryptography-2.8/tests/utils.py", line 21, in <module>
    import cryptography_vectors
ModuleNotFoundError: No module named 'cryptography_vectors'


======================================================================
ERROR: tests.x509.test_x509_crlbuilder (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: tests.x509.test_x509_crlbuilder
Traceback (most recent call last):
  File "/opt/python38/lib/python3.8/unittest/loader.py", line 436, in _find_test_path
    module = self._get_module_from_name(name)
  File "/opt/python38/lib/python3.8/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/home/lccy/Python/cryptography-2.8/tests/x509/test_x509_crlbuilder.py", line 26, in <module>
    from ..hazmat.primitives.test_ec import _skip_curve_unsupported
  File "/home/lccy/Python/cryptography-2.8/tests/hazmat/primitives/test_ec.py", line 27, in <module>
    from ...utils import (
  File "/home/lccy/Python/cryptography-2.8/tests/utils.py", line 21, in <module>
    import cryptography_vectors
ModuleNotFoundError: No module named 'cryptography_vectors'


======================================================================
ERROR: tests.x509.test_x509_ext (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: tests.x509.test_x509_ext
Traceback (most recent call last):
  File "/opt/python38/lib/python3.8/unittest/loader.py", line 436, in _find_test_path
    module = self._get_module_from_name(name)
  File "/opt/python38/lib/python3.8/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/home/lccy/Python/cryptography-2.8/tests/x509/test_x509_ext.py", line 32, in <module>
    from .test_x509 import _load_cert
  File "/home/lccy/Python/cryptography-2.8/tests/x509/test_x509.py", line 45, in <module>
    from ..hazmat.primitives.test_ec import _skip_curve_unsupported
  File "/home/lccy/Python/cryptography-2.8/tests/hazmat/primitives/test_ec.py", line 27, in <module>
    from ...utils import (
  File "/home/lccy/Python/cryptography-2.8/tests/utils.py", line 21, in <module>
    import cryptography_vectors
ModuleNotFoundError: No module named 'cryptography_vectors'


----------------------------------------------------------------------
Ran 107 tests in 0.054s

FAILED (errors=107)
Test failed: <unittest.runner.TextTestResult run=107 errors=107 failures=0>
error: Test failed: <unittest.runner.TextTestResult run=107 errors=107 failures=0>


```

**Comment by reaperhulk** [comment]
We don't support `python setup.py test` as a test workflow any more (and haven't since May 7, 2019). https://cryptography.io/en/latest/development/getting-started/#running-tests describes the recommended way of building and running tests (`tox`).

**Comment by reaperhulk** [comment]
https://github.com/pyca/cryptography/pull/4879 is the PR that did this btw
