### ISSUE TITLE
Unknown OpenSSL error by _register_osrandom_engine

### ISSUE THREAD

**Issue by jeremyw2019** [pyca/cryptography#5134]
We use authlib as OAuth2 client. Everything works fine when running from source code, but after we freeze it with py2exe, the following error is raised when running from binary. Unfortunately the errors_with_text is empty. Please help to figure out what's missing.

cryptography is installed by pip.

python 3.7.2 x86
cryptography 2.7 / 2.8 (tried both)
OpenSSL 1.1.1d  10 Sep 2019
cffi 1.12.3
pip 20.0.2
setuptools 41.6.0
Authlib 0.13 / 0.14.1 (tried both)

```
Traceback (most recent call last):
  File "OAuth2Client.pyc", line 393, in LogIn
  File "authlib\jose\rfc7519\jwt.pyc", line 121, in decode
  File "authlib\jose\rfc7515\jws.pyc", line 115, in deserialize_compact
  File "authlib\jose\util.pyc", line 8, in prepare_algorithm_key
  File "authlib\jose\jwk.pyc", line 27, in key_func
  File "authlib\jose\jwk.pyc", line 22, in load_key
  File "authlib\jose\jwk.pyc", line 12, in _load_jwk
  File "authlib\jose\rfc7517\jwk.pyc", line 80, in loads
  File "authlib\jose\rfc7517\jwk.pyc", line 62, in _load_jwk_set
  File "authlib\jose\rfc7517\jwk.pyc", line 50, in _load_obj
  File "authlib\jose\rfc7518\_backends\_jwk_cryptography.pyc", line 97, in loads
  File "authlib\jose\rfc7518\_backends\_jwk_cryptography.pyc", line 91, in loads_public_key
  File "cryptography\hazmat\backends\__init__.pyc", line 15, in default_backend
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 668, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 638, in _load_backward_compatible
  File "zipextimporter.pyc", line 87, in load_module
  File "cryptography\hazmat\backends\openssl\__init__.pyc", line 7, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 668, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 638, in _load_backward_compatible
  File "zipextimporter.pyc", line 87, in load_module
  File "cryptography\hazmat\backends\openssl\backend.pyc", line 74, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 668, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 638, in _load_backward_compatible
  File "zipextimporter.pyc", line 87, in load_module
  File "cryptography\hazmat\bindings\openssl\binding.pyc", line 195, in <module>
  File "cryptography\hazmat\bindings\openssl\binding.pyc", line 139, in init_static_locks
  File "cryptography\hazmat\bindings\openssl\binding.pyc", line 134, in _ensure_ffi_initialized
  File "cryptography\hazmat\bindings\openssl\binding.pyc", line 120, in _register_osrandom_engine
  File "cryptography\hazmat\bindings\openssl\binding.pyc", line 78, in _openssl_assert
cryptography.exceptions.InternalError: Unknown OpenSSL error. This error is commonly encountered when another library is not cleaning up the OpenSSL error stack. If you are using cryptography with another library that uses OpenSSL try disabling it before reporting a bug. Otherwise please file an issue at https://github.com/pyca/cryptography/issues with information 
on how to reproduce this. ([])

```

**Comment by alex** [comment]
Can you please provide us some instructions on how to reproduce this? We're not familiar with py2exec

**Comment by jeremyw2019** [comment]
Hi Alex,

Thank you for your reply. py2exe is similar to PyInstaller. We had to tweak
it to make it work for python 3.7. I'll try to reproduce it with a simple
script and provide you with the working py2exe package.

Regards,
Jeremy

**Comment by jeremyw2019** [comment]
@alex, please find attached scripts to reproduce the error.

I believe it is the issue of relative path to the libraries, because when dlls are bundled to library.zip by py2exe, the path will be different.

[ReproduceCryptographyError.zip](https://github.com/pyca/cryptography/files/4313940/ReproduceCryptographyError.zip)

**Comment by reaperhulk** [comment]
Is this still seen in 3.0? When compiling against 1.1.1d+ we no longer use the osrandom engine, although we still leave some symbols there so it may not have helped.

That said, this sounds like a py2exe problem and nothing related to our project.
