### ISSUE TITLE
TypeError while using load_ssh_public_key

### ISSUE THREAD

**Issue by irwincong** [pyca/cryptography#5266]
# Env
Installed with `pip3 install -U cryptography`.  pip installed with `python3 get-pip.py`

```bash
vagrant@kali:~$ openssl version
OpenSSL 1.1.1g  21 Apr 2020
vagrant@kali:~$ python -V
Python 2.7.18
```

```bash
vagrant@kali:~$ pip3 list | egrep "(cffi|pip|cryptography)"
cffi                         1.14.0
cryptography                 2.9.2
pip                          20.1.1
```

# Steps
## Generate pub/private RSA key
```
vagrant@kali:~$ ssh-keygen -t rsa -f /home/vagrant/.ssh/id_rsa
Generating public/private rsa key pair.
Enter passphrase (empty for no passphrase):
Enter same passphrase again:
Your identification has been saved in /home/vagrant/.ssh/id_rsa
Your public key has been saved in /home/vagrant/.ssh/id_rsa.pub
The key fingerprint is:
SHA256:sHmv0lysi6wgTJTtkuBpvmGtO+pnKb5bZyU3fYth7Xc vagrant@kali
The key's randomart image is:
+---[RSA 3072]----+
|                 |
|  o              |
|.o .  .          |
|+ +    +. .      |
| B . .o+S= o     |
|= o   +.o.B .    |
|.=.o.o o +.o . E |
|.+==o...+.  . .  |
|=OO ..o.o.       |
+----[SHA256]-----+
```
```
vagrant@kali:~$ xxd /home/vagrant/.ssh/id_rsa.pub
00000000: 7373 682d 7273 6120 4141 4141 4233 4e7a  ssh-rsa AAAAB3Nz
00000010: 6143 3179 6332 4541 4141 4144 4151 4142  aC1yc2EAAAADAQAB
00000020: 4141 4142 6751 4445 4e66 7567 5a70 5369  AAABgQDENfugZpSi
00000030: 716a 4638 686c 5839 584e 3352 4c58 614b  qjF8hlX9XN3RLXaK
00000040: 4a62 5371 762f 4930 7779 6369 4e61 6d4b  JbSqv/I0wyciNamK
00000050: 4d32 4755 7553 6946 7545 4459 3837 4b64  M2GUuSiFuEDY87Kd
00000060: 795a 4670 6576 7142 6866 4a63 794c 656a  yZFpevqBhfJcyLej
00000070: 6351 4f34 365a 5161 796b 7166 4f78 4244  cQO46ZQaykqfOxBD
00000080: 744f 4e4e 772b 6c37 346b 6366 4a30 482b  tONNw+l74kcfJ0H+
00000090: 4736 4355 4b35 5554 7344 737a 316f 444f  G6CUK5UTsDsz1oDO
000000a0: 6443 4e38 466a 5047 4f55 7a35 5a48 4c63  dCN8FjPGOUz5ZHLc
000000b0: 344b 754e 5537 5243 644f 4f43 4237 4c4b  4KuNU7RCdOOCB7LK
000000c0: 6b6b 424a 7947 6652 2b62 5135 7472 6639  kkBJyGfR+bQ5trf9
000000d0: 6243 6771 4c39 6253 7030 4879 6e48 4152  bCgqL9bSp0HynHAR
000000e0: 4b62 4544 6e79 3843 546a 796e 6a36 776a  KbEDny8CTjynj6wj
000000f0: 6c2b 6848 6433 6c34 3135 7376 7344 6546  l+hHd3l415svsDeF
00000100: 6641 6459 6f6e 5077 4454 3774 7741 6832  fAdYonPwDT7twAh2
00000110: 695a 3453 3557 4f64 4d4a 5937 6d4b 4569  iZ4S5WOdMJY7mKEi
00000120: 3434 332f 7558 7152 6352 3765 4474 3168  443/uXqRcR7eDt1h
00000130: 646b 476f 6339 3570 6631 6639 4d7a 566f  dkGoc95pf1f9MzVo
00000140: 4578 4f63 304b 546f 336a 7244 4648 7835  ExOc0KTo3jrDFHx5
00000150: 304c 2f74 696f 6b70 3673 4341 2b4a 6b2b  0L/tiokp6sCA+Jk+
00000160: 6f33 6b30 7371 6477 686f 4430 616d 5461  o3k0sqdwhoD0amTa
00000170: 6e71 4f58 3952 5767 6578 6556 6e41 5243  nqOX9RWgexeVnARC
00000180: 6d37 6e46 5831 346b 3255 537a 3639 7146  m7nFX14k2USz69qF
00000190: 6879 387a 7853 4b34 4374 6d72 4338 4231  hy8zxSK4CtmrC8B1
000001a0: 4f48 745a 6d72 3351 4c56 4c78 4363 6149  OHtZmr3QLVLxCcaI
000001b0: 7343 6357 454d 5a69 4e59 4766 3032 5769  sCcWEMZiNYGf02Wi
000001c0: 6d75 3651 424d 3769 6c4f 6c70 2f62 6838  mu6QBM7ilOlp/bh8
000001d0: 3034 6332 434f 6273 496e 2f44 4646 6a4e  04c2CObsIn/DFFjN
000001e0: 4e38 6848 6364 364c 3630 5272 6d68 484f  N8hHcd6L60RrmhHO
000001f0: 484e 4a6f 5146 3543 666e 5659 396e 727a  HNJoQF5CfnVY9nrz
00000200: 746f 3031 6d61 6642 3670 4975 7946 7145  to01mafB6pIuyFqE
00000210: 594c 4779 686b 3735 6355 3279 3051 3474  YLGyhk75cU2y0Q4t
00000220: 565a 5a58 6659 383d 2076 6167 7261 6e74  VZZXfY8= vagrant
00000230: 406b 616c 690a                           @kali.
```
## load_ssh_public_key
```python
from cryptography.hazmat.backends import default_backend
from cryptography.hazmat.primitives.serialization import load_ssh_public_key

key=open("/home/vagrant/.ssh/id_rsa.pub")
keyval=key.read();
print(type(keyval))
print(keyval)
load_ssh_public_key(keyval, default_backend());
```

### Output
```
<class 'str'>
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDENfugZpSiqjF8hlX9XN3RLXaKJbSqv/I0wyciNamKM2GUuSiFuEDY87KdyZFpevqBhfJcyLejcQO46ZQaykqfOxBDtONNw+l74kcfJ0H+G6CUK5UTsDsz1oDOdCN8FjPGOUz5ZHLc4KuNU7RCdOOCB7LKkkBJyGfR+bQ5trf9bCgqL9bSp0HynHARKbEDny8CTjynj6wjl+hHd3l415svsDeFfAdYonPwDT7twAh2iZ4S5WOdMJY7mKEi443/uXqRcR7eDt1hdkGoc95pf1f9MzVoExOc0KTo3jrDFHx50L/tiokp6sCA+Jk+o3k0sqdwhoD0amTanqOX9RWgexeVnARCm7nFX14k2USz69qFhy8zxSK4CtmrC8B1OHtZmr3QLVLxCcaIsCcWEMZiNYGf02Wimu6QBM7ilOlp/bh804c2CObsIn/DFFjNN8hHcd6L60RrmhHOHNJoQF5CfnVY9nrzto01mafB6pIuyFqEYLGyhk75cU2y0Q4tVZZXfY8= vagrant@kali

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python3/dist-packages/cryptography/hazmat/primitives/serialization/ssh.py", line 18, in load_ssh_public_key
    key_parts = data.split(b' ', 2)
TypeError: must be str or None, not bytes
```

Thought tests added for https://github.com/pyca/cryptography/issues/2199 would have caught this, so this could very well be a problem between the keyboard and chair.

**Comment by alex** [comment]
You are passing a a `str` instance, but you are supposed to pass a `bytes` instance.
