### ISSUE TITLE
ModuleNotFoundError: No module named 'cryptography.hazmat.bindings._constant_time'

### ISSUE THREAD

**Issue by KiteFlyKid** [pyca/cryptography#5273]
I've got no problems when I run my crawler like 
```python
scrapy crawl my_crawler
```
It goes wrong when I am trying to debuging scrapy.
My code for debugging is 
```python
from scrapy import cmdline
name = 'movie_subject'
cmd = 'scrapy crawl {0}'.format(name)
cmdline.execute(cmd.split())
```

```shell
D:\Anaconda\Lib\site-packages\numpy\__init__.py:140: UserWarning: mkl-service package failed to import, therefore Intel(R) MKL initialization ensuring its correct out-of-the box operation under condition when Gnu OpenMP had already been loaded by Python process is not assured. Please install mkl-service package, see http://github.com/IntelPython/mkl-service
  from . import _distributor_init
Traceback (most recent call last):
  File "C:/Users/ms396/Desktop/AntSpider-master/scrapy/debug.py", line 1, in <module>
    from scrapy import cmdline
  File "D:\Anaconda\Lib\site-packages\scrapy\cmdline.py", line 9, in <module>
    from scrapy.crawler import CrawlerProcess
  File "D:\Anaconda\Lib\site-packages\scrapy\crawler.py", line 18, in <module>
    from scrapy.core.engine import ExecutionEngine
  File "D:\Anaconda\Lib\site-packages\scrapy\core\engine.py", line 14, in <module>
    from scrapy.core.scraper import Scraper
  File "D:\Anaconda\Lib\site-packages\scrapy\core\scraper.py", line 13, in <module>
    from scrapy.utils.log import logformatter_adapter, failure_to_exc_info
  File "D:\Anaconda\Lib\site-packages\scrapy\utils\log.py", line 14, in <module>
    from scrapy.utils.versions import scrapy_components_versions
  File "D:\Anaconda\Lib\site-packages\scrapy\utils\versions.py", line 12, in <module>
    from scrapy.utils.ssl import get_openssl_version
  File "D:\Anaconda\Lib\site-packages\scrapy\utils\ssl.py", line 3, in <module>
    import OpenSSL
  File "D:\Anaconda\Lib\site-packages\OpenSSL\__init__.py", line 8, in <module>
    from OpenSSL import crypto, SSL
  File "D:\Anaconda\Lib\site-packages\OpenSSL\crypto.py", line 12, in <module>
    from cryptography import x509
  File "D:\Anaconda\Lib\site-packages\cryptography\x509\__init__.py", line 8, in <module>
    from cryptography.x509.base import (
  File "D:\Anaconda\Lib\site-packages\cryptography\x509\base.py", line 18, in <module>
    from cryptography.x509.extensions import Extension, ExtensionType
  File "D:\Anaconda\Lib\site-packages\cryptography\x509\extensions.py", line 20, in <module>
    from cryptography.hazmat.primitives import constant_time, serialization
  File "D:\Anaconda\Lib\site-packages\cryptography\hazmat\primitives\constant_time.py", line 11, in <module>
    from cryptography.hazmat.bindings._constant_time import lib
ModuleNotFoundError: No module named 'cryptography.hazmat.bindings._constant_time'

Process finished with exit code 1
```
So I suppose it is because  Cryptography 
Here is what is in my cryptography.hazmat.bindings:
![image](https://user-images.githubusercontent.com/45324156/84564796-20ca0980-ad97-11ea-8617-f487a19ee3ae.png)

**Comment by reaperhulk** [comment]
This is almost certainly something related to environment, which makes it very difficult for us to help since there are an infinity of ways Python environments can be configured. Two things to check:
* Is this actually a debug Python or just you are debugging? Debug versions of Python themselves (prior to 3.8) have a different ABI so cryptography's precompiled code won't work without recompilation. 
* When you debug are you still using Python 3.7 or is it some other version? On Windows compiled modules in Python are specific to Python versions, so the cp37 installed code will not load or run on 3.6, 3.8, etc.

**Comment by KiteFlyKid** [comment]
Thx, Python 3.7 works well.
I just used python 3.8 no wonder it went wrong.
