### ISSUE TITLE
3.1: unable to load RSA private key with paramiko

### ISSUE THREAD

**Issue by pavelrad** [pyca/cryptography#5434]
I understand that this repo might not be the right place for this problem, but it appeared only after update to cryptography 3.1 and doesn't manifest in 3.0.
**Steps to reproduce:**
```
$ ssh-keygen -t rsa -N '' -f /tmp/key
Generating public/private rsa key pair.
Your identification has been saved in /tmp/key.
Your public key has been saved in /tmp/key.pub.
The key fingerprint is:
SHA256:j1LzYNciubjL4FtMcSbDLhFdNgmbJJWBVfh8v0RwXGE pavel@lambda
The key's randomart image is:
+---[RSA 2048]----+
|    o=*B=. . .E. |
|    .=++... o.   |
|    . Boo  o     |
|     o *o....    |
|    . o S.oo.    |
|     + + X .o    |
|    . = o o. .   |
|   . + o    .    |
|    o.+.         |
+----[SHA256]-----+
$ pip install paramiko 'cryptography==3.1'
Collecting paramiko
  Using cached paramiko-2.7.1-py2.py3-none-any.whl (206 kB)
Collecting cryptography==3.1
  Using cached cryptography-3.1-cp35-abi3-macosx_10_10_x86_64.whl (1.8 MB)
Collecting bcrypt>=3.1.3
  Using cached bcrypt-3.2.0-cp36-abi3-macosx_10_9_x86_64.whl (31 kB)
Collecting pynacl>=1.0.1
  Using cached PyNaCl-1.4.0-cp35-abi3-macosx_10_10_x86_64.whl (380 kB)
Collecting six>=1.4.1
  Using cached six-1.15.0-py2.py3-none-any.whl (10 kB)
Collecting cffi!=1.11.3,>=1.8
  Using cached cffi-1.14.2-cp38-cp38-macosx_10_9_x86_64.whl (176 kB)
Collecting pycparser
  Using cached pycparser-2.20-py2.py3-none-any.whl (112 kB)
Installing collected packages: six, pycparser, cffi, cryptography, bcrypt, pynacl, paramiko
Successfully installed bcrypt-3.2.0 cffi-1.14.2 cryptography-3.1 paramiko-2.7.1 pycparser-2.20 pynacl-1.4.0 six-1.15.0
$ python -c "import paramiko; paramiko.RSAKey.from_private_key_file('/tmp/key')"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/pavel/.virtualenvs/tmp-ae15bf6ad17b2a5/lib/python3.8/site-packages/paramiko/pkey.py", line 235, in from_private_key_file
    key = cls(filename=filename, password=password)
  File "/Users/pavel/.virtualenvs/tmp-ae15bf6ad17b2a5/lib/python3.8/site-packages/paramiko/rsakey.py", line 55, in __init__
    self._from_private_key_file(filename, password)
  File "/Users/pavel/.virtualenvs/tmp-ae15bf6ad17b2a5/lib/python3.8/site-packages/paramiko/rsakey.py", line 176, in _from_private_key_file
    self._decode_key(data)
  File "/Users/pavel/.virtualenvs/tmp-ae15bf6ad17b2a5/lib/python3.8/site-packages/paramiko/rsakey.py", line 194, in _decode_key
    key = rsa.RSAPrivateNumbers(
  File "/Users/pavel/.virtualenvs/tmp-ae15bf6ad17b2a5/lib/python3.8/site-packages/cryptography/hazmat/primitives/asymmetric/rsa.py", line 311, in private_key
    return backend.load_rsa_private_numbers(self)
  File "/Users/pavel/.virtualenvs/tmp-ae15bf6ad17b2a5/lib/python3.8/site-packages/cryptography/hazmat/backends/openssl/backend.py", line 630, in load_rsa_private_numbers
    return _RSAPrivateKey(self, rsa_cdata, evp_pkey)
  File "/Users/pavel/.virtualenvs/tmp-ae15bf6ad17b2a5/lib/python3.8/site-packages/cryptography/hazmat/backends/openssl/rsa.py", line 320, in __init__
    raise ValueError("Invalid private key", errors)
ValueError: ('Invalid private key', [_OpenSSLErrorWithText(code=67764350, lib=4, func=160, reason=126, reason_text=b'error:040A007E:rsa routines:RSA_check_key_ex:iqmp not inverse of q')])
```
The same works just fine with cryptography 3.0:
```
$ pip install 'cryptography==3.0'
Collecting cryptography==3.0
  Using cached cryptography-3.0-cp35-abi3-macosx_10_10_x86_64.whl (1.8 MB)
Requirement already satisfied: six>=1.4.1 in /Users/pavel/.virtualenvs/tmp-ae15bf6ad17b2a5/lib/python3.8/site-packages (from cryptography==3.0) (1.15.0)
Requirement already satisfied: cffi!=1.11.3,>=1.8 in /Users/pavel/.virtualenvs/tmp-ae15bf6ad17b2a5/lib/python3.8/site-packages (from cryptography==3.0) (1.14.2)
Requirement already satisfied: pycparser in /Users/pavel/.virtualenvs/tmp-ae15bf6ad17b2a5/lib/python3.8/site-packages (from cffi!=1.11.3,>=1.8->cryptography==3.0) (2.20)
Installing collected packages: cryptography
  Attempting uninstall: cryptography
    Found existing installation: cryptography 3.1
    Uninstalling cryptography-3.1:
      Successfully uninstalled cryptography-3.1
Successfully installed cryptography-3.0
$ python -c "import paramiko; paramiko.RSAKey.from_private_key_file('/tmp/key')"
$
```
The issue is reproduced with python3.7 & python3.8 on MacOS and Raspbian.

**Comment by reaperhulk** [comment]
This is because we started enforcing stricter requirements on our RSA keys on load in https://github.com/pyca/cryptography/pull/5307. The bug in paramiko is here: https://github.com/paramiko/paramiko/pull/1723

**Comment by pavelrad** [comment]
Thank you for your reply.
