### ISSUE TITLE
Since v3.1 'pip install' produces: TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'

### ISSUE THREAD

**Issue by caronc** [pyca/cryptography#5446]
Hi,

I can't seem to install cryptography since the release of v3.1 on my test runners for Python v3.5. see [here](https://travis-ci.org/github/caronc/apprise/jobs/722568697#L163).

Environment details are:
   * **OS**: Ubuntu 16.04
   * **Cryptography**: 3.1
   * **Python**:  3.5.3 (fdd60ed87e94, Apr 24 2018, 06:10:04)
   * **pip**: 18.1

TravisCI Full output and reproducing steps can be found [here](https://travis-ci.org/github/caronc/apprise/jobs/722568697#L163)
**The full traceback:**
```python
Collecting cryptography (from -r dev-requirements.txt (line 8))
  Downloading https://files.pythonhosted.org/packages/12/be/c9cc7d7ab71dbcc9e4e517ead0cdd48e8c9a48d7b8bdddb738e90d08279a/cryptography-3.1.tar.gz (534kB)
  Installing build dependencies ... -\|/done
    Complete output from command python setup.py egg_info:

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-kkhh_z5u/cryptography/setup.py", line 122, in <module>
        "src/_cffi_src/build_padding.py:ffi",
      File "/tmp/pip-build-env-eyekjjp_/site-packages/setuptools/__init__.py", line 153, in setup
        return distutils.core.setup(**attrs)
      File "/tmp/pip-build-env-eyekjjp_/site-packages/setuptools/_distutils/core.py", line 108, in setup
        _setup_distribution = dist = klass(attrs)
      File "/tmp/pip-build-env-eyekjjp_/site-packages/setuptools/dist.py", line 424, in __init__
        k: v for k, v in attrs.items()
      File "/tmp/pip-build-env-eyekjjp_/site-packages/setuptools/_distutils/dist.py", line 293, in __init__
        self.finalize_options()
      File "/tmp/pip-build-env-eyekjjp_/site-packages/setuptools/dist.py", line 695, in finalize_options
        ep(self)
      File "/tmp/pip-build-env-eyekjjp_/site-packages/setuptools/dist.py", line 702, in _finalize_setup_keywords
        ep.load()(self, ep.name, value)
      File "/opt/python/pypy3.5-6.0.0/lib_pypy/cffi/setuptools_ext.py", line 204, in cffi_modules
        add_cffi_module(dist, cffi_module)
      File "/opt/python/pypy3.5-6.0.0/lib_pypy/cffi/setuptools_ext.py", line 49, in add_cffi_module
        execfile(build_file_name, mod_vars)
      File "/opt/python/pypy3.5-6.0.0/lib_pypy/cffi/setuptools_ext.py", line 25, in execfile
        exec(code, glob, glob)
      File "src/_cffi_src/build_openssl.py", line 129, in <module>
        extra_compile_args=_extra_compile_args(sys.platform),
      File "src/_cffi_src/build_openssl.py", line 66, in _extra_compile_args
        cmd._check_compiler()
      File "/tmp/pip-build-env-eyekjjp_/site-packages/setuptools/_distutils/command/config.py", line 99, in _check_compiler
        customize_compiler(self.compiler)
      File "/tmp/pip-build-env-eyekjjp_/site-packages/setuptools/_distutils/sysconfig.py", line 228, in customize_compiler
        cpp = cc + " -E"           # not always
    TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'
```

**Comment by alex** [comment]
A quick note: You're compiling for PyPy, but your issue doesn't mention that. You're using PyPy3 6.0, but we test against 7.3.1.

Can you confirm if this still reproduces with the latest versions of: 1) pip, 2) setuptools, 3) pypy?

**Comment by caronc** [comment]
>You're using PyPy3 6.0, but we test against 7.3.1

Thanks for pointing that out! :slightly_smiling_face:  It's worth pointing out that PyPy2 6.0 works great [see here](https://travis-ci.org/github/caronc/apprise/jobs/722568696) with your newest build too though.

That all said, I updated my `.travis.xml` file to reference newer builds and that appears to have fixed it ([ref](https://travis-ci.org/github/caronc/apprise/jobs/722813603))! Thank you so much for your fast response! :+1: 

I'll close off this issue.
