### ISSUE TITLE
Error installing on macOS Big Sur 11.0 on arm64 

### ISSUE THREAD

**Issue by hmrbarros** [pyca/cryptography#5641]
OpenSSL: 1.1.1i
macOS 11.0
Python 3.9.1

```
$ pip3 install cryptography
Collecting cryptography
  Using cached cryptography-3.3.1.tar.gz (539 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... error
    ERROR: Command errored out with exit status 1:
     command: /opt/homebrew/opt/python@3.9/bin/python3.9 /opt/homebrew/lib/python3.9/site-packages/pip/_vendor/pep517/_in_process.py prepare_metadata_for_build_wheel /var/folders/h7/rp8ld5_n2ld57w78vzqvcrx40000gp/T/tmpeboyguj2
         cwd: /private/var/folders/h7/rp8ld5_n2ld57w78vzqvcrx40000gp/T/pip-install-szr955_e/cryptography_c73bf1e46f3b4e1f964c8f8abccc845b
    Complete output (54 lines):

        =============================DEBUG ASSISTANCE=============================
        If you are seeing a compilation error please try the following steps to
        successfully install cryptography:
        1) Upgrade to the latest pip and try again. This will fix errors for most
           users. See: https://pip.pypa.io/en/stable/installing/#upgrading-pip
        2) Read https://cryptography.io/en/latest/installation.html for specific
           instructions for your platform.
        3) Check our frequently asked questions for more information:
           https://cryptography.io/en/latest/faq.html
        =============================DEBUG ASSISTANCE=============================

    Traceback (most recent call last):
      File "/opt/homebrew/lib/python3.9/site-packages/pip/_vendor/pep517/_in_process.py", line 280, in <module>
        main()
      File "/opt/homebrew/lib/python3.9/site-packages/pip/_vendor/pep517/_in_process.py", line 263, in main
        json_out['return_val'] = hook(**hook_input['kwargs'])
      File "/opt/homebrew/lib/python3.9/site-packages/pip/_vendor/pep517/_in_process.py", line 133, in prepare_metadata_for_build_wheel
        return hook(metadata_directory, config_settings)
      File "/private/var/folders/h7/rp8ld5_n2ld57w78vzqvcrx40000gp/T/pip-build-env-69a73sea/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 161, in prepare_metadata_for_build_wheel
        self.run_setup()
      File "/private/var/folders/h7/rp8ld5_n2ld57w78vzqvcrx40000gp/T/pip-build-env-69a73sea/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 145, in run_setup
        exec(compile(code, __file__, 'exec'), locals())
      File "setup.py", line 44, in <module>
        setup(
      File "/private/var/folders/h7/rp8ld5_n2ld57w78vzqvcrx40000gp/T/pip-build-env-69a73sea/overlay/lib/python3.9/site-packages/setuptools/__init__.py", line 153, in setup
        return distutils.core.setup(**attrs)
      File "/opt/homebrew/Cellar/python@3.9/3.9.1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/core.py", line 108, in setup
        _setup_distribution = dist = klass(attrs)
      File "/private/var/folders/h7/rp8ld5_n2ld57w78vzqvcrx40000gp/T/pip-build-env-69a73sea/overlay/lib/python3.9/site-packages/setuptools/dist.py", line 423, in __init__
        _Distribution.__init__(self, {
      File "/opt/homebrew/Cellar/python@3.9/3.9.1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/dist.py", line 292, in __init__
        self.finalize_options()
      File "/private/var/folders/h7/rp8ld5_n2ld57w78vzqvcrx40000gp/T/pip-build-env-69a73sea/overlay/lib/python3.9/site-packages/setuptools/dist.py", line 695, in finalize_options
        ep(self)
      File "/private/var/folders/h7/rp8ld5_n2ld57w78vzqvcrx40000gp/T/pip-build-env-69a73sea/overlay/lib/python3.9/site-packages/setuptools/dist.py", line 702, in _finalize_setup_keywords
        ep.load()(self, ep.name, value)
      File "/private/var/folders/h7/rp8ld5_n2ld57w78vzqvcrx40000gp/T/pip-build-env-69a73sea/overlay/lib/python3.9/site-packages/cffi/setuptools_ext.py", line 219, in cffi_modules
        add_cffi_module(dist, cffi_module)
      File "/private/var/folders/h7/rp8ld5_n2ld57w78vzqvcrx40000gp/T/pip-build-env-69a73sea/overlay/lib/python3.9/site-packages/cffi/setuptools_ext.py", line 49, in add_cffi_module
        execfile(build_file_name, mod_vars)
      File "/private/var/folders/h7/rp8ld5_n2ld57w78vzqvcrx40000gp/T/pip-build-env-69a73sea/overlay/lib/python3.9/site-packages/cffi/setuptools_ext.py", line 25, in execfile
        exec(code, glob, glob)
      File "src/_cffi_src/build_openssl.py", line 77, in <module>
        ffi = build_ffi_for_binding(
      File "src/_cffi_src/utils.py", line 54, in build_ffi_for_binding
        ffi = build_ffi(
      File "src/_cffi_src/utils.py", line 74, in build_ffi
        ffi = FFI()
      File "/private/var/folders/h7/rp8ld5_n2ld57w78vzqvcrx40000gp/T/pip-build-env-69a73sea/overlay/lib/python3.9/site-packages/cffi/api.py", line 48, in __init__
        import _cffi_backend as backend
    ImportError: dlopen(/private/var/folders/h7/rp8ld5_n2ld57w78vzqvcrx40000gp/T/pip-build-env-69a73sea/overlay/lib/python3.9/site-packages/_cffi_backend.cpython-39-darwin.so, 2): no suitable image found.  Did find:
        /private/var/folders/h7/rp8ld5_n2ld57w78vzqvcrx40000gp/T/pip-build-env-69a73sea/overlay/lib/python3.9/site-packages/_cffi_backend.cpython-39-darwin.so: mach-o, but wrong architecture
        /private/var/folders/h7/rp8ld5_n2ld57w78vzqvcrx40000gp/T/pip-build-env-69a73sea/overlay/lib/python3.9/site-packages/_cffi_backend.cpython-39-darwin.so: mach-o, but wrong architecture
    ----------------------------------------
ERROR: Command errored out with exit status 1: /opt/homebrew/opt/python@3.9/bin/python3.9 /opt/homebrew/lib/python3.9/site-packages/pip/_vendor/pep517/_in_process.py prepare_metadata_for_build_wheel /var/folders/h7/rp8ld5_n2ld57w78vzqvcrx40000gp/T/tmpeboyguj2 Check the logs for full command output.
```

**Comment by reaperhulk** [comment]
`_cffi_backend.cpython-39-darwin.so, 2): no suitable image found`

It appears you somehow have an x86_64 cffi installed that you're trying to load via arm64 Python. You'll need to fix that, then follow the instructions for compiling cryptography in our docs since we do not provide arm64 wheels on macOS at this time.

**Comment by hmrbarros** [comment]
Thanks for the clarification, cffi doesn't have a arm64 version at the moment and the x86_64 is being download which produces this error. 
For those that find this issue my workaround was to have a complete virtualenv with x86_64 Python for the time being.
