### ISSUE TITLE
Unable to use: [cryptography.hazmat.primitives.serialization.NoEncryption] while serilize RSA or EllipticCurve private-key

### ISSUE THREAD

**Issue by EliasGabrielsson** [pyca/cryptography#5671]
## Expectation

The code below should return an unencrypted private key saved in variable `pem`.

```
from cryptography.hazmat.primitives.asymmetric import rsa
from cryptography.hazmat.primitives import serialization

private_key = rsa.generate_private_key(
    public_exponent=65537,
    key_size=2048,
    )

pem = private_key.private_bytes(
    encoding=serialization.Encoding.PEM,
    format=serialization.PrivateFormat.PKCS8,
    encryption_algorithm=serialization.NoEncryption)
```

## Result:

Got this result:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/username/.local/share/virtualenvs/projectname-bBdz6gnv/lib/python3.8/site-packages/cryptography/hazmat/backends/openssl/rsa.py", line 439, in private_bytes
    return self._backend._private_key_bytes(
  File "/Users/username/.local/share/virtualenvs/projectname-bBdz6gnv/lib/python3.8/site-packages/cryptography/hazmat/backends/openssl/backend.py", line 1901, in _private_key_bytes
    raise TypeError(
TypeError: Encryption algorithm must be a KeySerializationEncryption instance
```

## Versions:

* MacOS BigSur 11.1
* Python 3.8.2 (default, Nov  4 2020, 21:23:28)  [Clang 12.0.0 (clang-1200.0.32.28)] on darwin
* Cryptography 3.3.1
* OpenSSL 1.1.1i

**Comment by alex** [comment]
`NoEncryption()` needs to be instantiated, as per the example: https://cryptography.io/en/latest/hazmat/primitives/asymmetric/rsa.html#key-serialization

**Comment by EliasGabrielsson** [comment]
Oh, aha, what I feel stupid right now. Sorry for bothering you and stealing your time. Take care // EG
