### ISSUE TITLE
Cryptography fails when fresh installed (3.3.1) but works when updated from previous version (3.3.0)

### ISSUE THREAD

**Issue by dciborow** [pyca/cryptography#5694]
If you're filing a bug (as opposed to a feature request), please try the
following things:

* Upgrade to the latest version of ``setuptools`` and ``pip``
* Make sure you're on a supported version of OpenSSL
* Try with the latest version of ``cryptography``

If none of that works, please make sure to include the following information in
your bug report:

* Versions of Python, ``cryptography``, ``cffi``, ``pip``, and ``setuptools``
  you're using

cryptography=3.3.1
cffi==1.14.4
pip==20.3.3, 
setuptools==51.1.1

* How you installed ``cryptography``

pip download \
        --no-binary :all: \
        -d "/source/packages/pywheel" \
        cryptography==3.3.1

pip install \
      --no-binary :all: \
      --upgrade \
        cryptography==3.3.1

* Clear steps for reproducing your bug
I am using the, azure-storage-blob==12.6.0. Trying to create a mini repo of this issue now.

```
2021-01-12T18:57:49.8275844Z [WARN] [2460] ImportError while loading conftest '/source/src/azureiai-managed-apps/tests/conftest.py'.
2021-01-12T18:57:49.8278524Z [WARN] [2461] tests/conftest.py:10: in <module>
2021-01-12T18:57:49.8278987Z [WARN] [2462]     from azureiai.managed_apps import ManagedApplication
2021-01-12T18:57:49.8280937Z [WARN] [2463] azureiai/managed_apps/__init__.py:9: in <module>
2021-01-12T18:57:49.8283003Z [WARN] [2464]     from azureiai.managed_apps.managed_app import ManagedApplication
2021-01-12T18:57:49.8285032Z [WARN] [2465] azureiai/managed_apps/managed_app.py:16: in <module>
2021-01-12T18:57:49.8286587Z [WARN] [2466]     from azureiai.managed_apps.confs import (
2021-01-12T18:57:49.8287998Z [WARN] [2467] azureiai/managed_apps/confs/__init__.py:5: in <module>
2021-01-12T18:57:49.8289489Z [WARN] [2468]     from azureiai.managed_apps.confs.listing import Listing
2021-01-12T18:57:49.8290930Z [WARN] [2469] azureiai/managed_apps/confs/listing.py:10: in <module>
2021-01-12T18:57:49.8292903Z [WARN] [2470]     from azureiai.managed_apps.confs.offer_configurations import OfferConfigurations
2021-01-12T18:57:49.8294478Z [WARN] [2471] azureiai/managed_apps/confs/offer_configurations.py:9: in <module>
2021-01-12T18:57:49.8295984Z [WARN] [2472]     from azure.storage.blob import ContentSettings  # noqa
2021-01-12T18:57:49.8298148Z [WARN] [2473] /devopsVirtualEnv/lib/python3.7/site-packages/azure/storage/blob/__init__.py:10: in <module>
2021-01-12T18:57:49.8299766Z [WARN] [2474]     from ._blob_client import BlobClient
2021-01-12T18:57:49.8301824Z [WARN] [2475] /devopsVirtualEnv/lib/python3.7/site-packages/azure/storage/blob/_blob_client.py:25: in <module>
2021-01-12T18:57:49.8303730Z [WARN] [2476]     from ._shared.encryption import generate_blob_encryption_data
2021-01-12T18:57:49.8305897Z [WARN] [2477] /devopsVirtualEnv/lib/python3.7/site-packages/azure/storage/blob/_shared/encryption.py:19: in <module>
2021-01-12T18:57:49.8307455Z [WARN] [2478]     from cryptography.hazmat.primitives.padding import PKCS7
2021-01-12T18:57:49.8309550Z [WARN] [2479] /devopsVirtualEnv/lib/python3.7/site-packages/cryptography/hazmat/primitives/padding.py:13: in <module>
2021-01-12T18:57:49.8311065Z [WARN] [2480]     from cryptography.hazmat.bindings._padding import lib
2021-01-12T18:57:49.8313069Z [WARN] [2481] E   ModuleNotFoundError: No module named 'cryptography.hazmat.bindings._padding'
```

Please do not report security issues on Github! Follow the instructions in our
documentation for reporting security issues:
https://cryptography.io/en/latest/security/

**Comment by alex** [comment]
Your message does not include what error you're getting.

**Comment by dciborow** [comment]
@alex sorry, fixed that. Working on a repo in code right now.

**Comment by alex** [comment]
Based on this error, we'll really need instructions for reproducing, it looks like you somehow half-installed cryptography.

**Comment by dciborow** [comment]
pip install azure
python3.7

>>> from azure.storage.blob import ContentSettings

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/devopsVirtualEnv/lib/python3.7/site-packages/azure/storage/blob/__init__.py", line 10, in <module>
    from ._blob_client import BlobClient
  File "/devopsVirtualEnv/lib/python3.7/site-packages/azure/storage/blob/_blob_client.py", line 25, in <module>
    from ._shared.encryption import generate_blob_encryption_data
  File "/devopsVirtualEnv/lib/python3.7/site-packages/azure/storage/blob/_shared/encryption.py", line 19, in <module>
    from cryptography.hazmat.primitives.padding import PKCS7
  File "/devopsVirtualEnv/lib/python3.7/site-packages/cryptography/hazmat/primitives/padding.py", line 13, in <module>
    from cryptography.hazmat.bindings._padding import lib
ModuleNotFoundError: No module named 'cryptography.hazmat.bindings._padding'

**Comment by reaperhulk** [comment]
Installing `azure-storage-blob` and importing in a new virtualenv does not cause the error you're describing in my tests. Can you reproduce this in a fresh virtualenv?

**Comment by mkreim** [comment]
I am also failing to install cryptography 3.3.1 (in my case on Windows 10 with Python 3.7):
```
pip.exe install cryptography
Collecting cryptography
  Using cached https://files.pythonhosted.org/packages/b7/82/f7a4ddc1af185936c1e4fa000942ffa8fb2d98cff26b75afa7b3c63391c4/cryptography-3.3.1.tar.gz
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Collecting six>=1.4.1 (from cryptography)
  Using cached https://files.pythonhosted.org/packages/ee/ff/48bde5c0f013094d729fe4b0316ba2a24774b3ff1c52d924a8a4cb04078a/six-1.15.0-py2.py3-none-any.whl
Collecting cffi>=1.12 (from cryptography)
  Using cached https://files.pythonhosted.org/packages/65/7b/cf83e7da59967d7f8599ac27338d570af4d770791b1ea744677b27aafcb4/cffi-1.14.4-cp37-cp37m-win_amd64.whl
Collecting pycparser (from cffi>=1.12->cryptography)
  Using cached https://files.pythonhosted.org/packages/ae/e7/d9c3a176ca4b02024debf82342dab36efadfc5776f9c8db077e8f6e71821/pycparser-2.20-py2.py3-none-any.whl
Building wheels for collected packages: cryptography
  Building wheel for cryptography (PEP 517) ... error
  ERROR: Command errored out with exit status 1:
   command: 'c:\netsyno\tlw\tlwvenv\scripts\python.exe' 'c:\netsyno\tlw\tlwvenv\lib\site-packages\pip\_vendor\pep517\_in_process.py' build_wheel 'C:\Users\mk\AppData\Local\Temp\tmprru9eq3e'
       cwd: C:\Users\mk\AppData\Local\Temp\pip-install-pm0d36wv\cryptography
  Complete output (141 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-3.7
  creating build\lib.win-amd64-3.7\cryptography
  copying src\cryptography\exceptions.py -> build\lib.win-amd64-3.7\cryptography
  copying src\cryptography\fernet.py -> build\lib.win-amd64-3.7\cryptography
  copying src\cryptography\utils.py -> build\lib.win-amd64-3.7\cryptography
  copying src\cryptography\__about__.py -> build\lib.win-amd64-3.7\cryptography
  copying src\cryptography\__init__.py -> build\lib.win-amd64-3.7\cryptography
  creating build\lib.win-amd64-3.7\cryptography\hazmat
  copying src\cryptography\hazmat\_der.py -> build\lib.win-amd64-3.7\cryptography\hazmat
  copying src\cryptography\hazmat\_oid.py -> build\lib.win-amd64-3.7\cryptography\hazmat
  copying src\cryptography\hazmat\__init__.py -> build\lib.win-amd64-3.7\cryptography\hazmat
  creating build\lib.win-amd64-3.7\cryptography\x509
  copying src\cryptography\x509\base.py -> build\lib.win-amd64-3.7\cryptography\x509
  copying src\cryptography\x509\certificate_transparency.py -> build\lib.win-amd64-3.7\cryptography\x509
  copying src\cryptography\x509\extensions.py -> build\lib.win-amd64-3.7\cryptography\x509
  copying src\cryptography\x509\general_name.py -> build\lib.win-amd64-3.7\cryptography\x509
  copying src\cryptography\x509\name.py -> build\lib.win-amd64-3.7\cryptography\x509
  copying src\cryptography\x509\ocsp.py -> build\lib.win-amd64-3.7\cryptography\x509
  copying src\cryptography\x509\oid.py -> build\lib.win-amd64-3.7\cryptography\x509
  copying src\cryptography\x509\__init__.py -> build\lib.win-amd64-3.7\cryptography\x509
  creating build\lib.win-amd64-3.7\cryptography\hazmat\backends
  copying src\cryptography\hazmat\backends\interfaces.py -> build\lib.win-amd64-3.7\cryptography\hazmat\backends
  copying src\cryptography\hazmat\backends\__init__.py -> build\lib.win-amd64-3.7\cryptography\hazmat\backends
  creating build\lib.win-amd64-3.7\cryptography\hazmat\bindings
  copying src\cryptography\hazmat\bindings\__init__.py -> build\lib.win-amd64-3.7\cryptography\hazmat\bindings
  creating build\lib.win-amd64-3.7\cryptography\hazmat\primitives
  copying src\cryptography\hazmat\primitives\cmac.py -> build\lib.win-amd64-3.7\cryptography\hazmat\primitives
  copying src\cryptography\hazmat\primitives\constant_time.py -> build\lib.win-amd64-3.7\cryptography\hazmat\primitives
  copying src\cryptography\hazmat\primitives\hashes.py -> build\lib.win-amd64-3.7\cryptography\hazmat\primitives
  copying src\cryptography\hazmat\primitives\hmac.py -> build\lib.win-amd64-3.7\cryptography\hazmat\primitives
  copying src\cryptography\hazmat\primitives\keywrap.py -> build\lib.win-amd64-3.7\cryptography\hazmat\primitives
  copying src\cryptography\hazmat\primitives\padding.py -> build\lib.win-amd64-3.7\cryptography\hazmat\primitives
  copying src\cryptography\hazmat\primitives\poly1305.py -> build\lib.win-amd64-3.7\cryptography\hazmat\primitives
  copying src\cryptography\hazmat\primitives\__init__.py -> build\lib.win-amd64-3.7\cryptography\hazmat\primitives
  creating build\lib.win-amd64-3.7\cryptography\hazmat\backends\openssl
  copying src\cryptography\hazmat\backends\openssl\aead.py -> build\lib.win-amd64-3.7\cryptography\hazmat\backends\openssl
  copying src\cryptography\hazmat\backends\openssl\backend.py -> build\lib.win-amd64-3.7\cryptography\hazmat\backends\openssl
  copying src\cryptography\hazmat\backends\openssl\ciphers.py -> build\lib.win-amd64-3.7\cryptography\hazmat\backends\openssl
  copying src\cryptography\hazmat\backends\openssl\cmac.py -> build\lib.win-amd64-3.7\cryptography\hazmat\backends\openssl
  copying src\cryptography\hazmat\backends\openssl\decode_asn1.py -> build\lib.win-amd64-3.7\cryptography\hazmat\backends\openssl
  copying src\cryptography\hazmat\backends\openssl\dh.py -> build\lib.win-amd64-3.7\cryptography\hazmat\backends\openssl
  copying src\cryptography\hazmat\backends\openssl\dsa.py -> build\lib.win-amd64-3.7\cryptography\hazmat\backends\openssl
  copying src\cryptography\hazmat\backends\openssl\ec.py -> build\lib.win-amd64-3.7\cryptography\hazmat\backends\openssl
  copying src\cryptography\hazmat\backends\openssl\ed25519.py -> build\lib.win-amd64-3.7\cryptography\hazmat\backends\openssl
  copying src\cryptography\hazmat\backends\openssl\ed448.py -> build\lib.win-amd64-3.7\cryptography\hazmat\backends\openssl
  copying src\cryptography\hazmat\backends\openssl\encode_asn1.py -> build\lib.win-amd64-3.7\cryptography\hazmat\backends\openssl
  copying src\cryptography\hazmat\backends\openssl\hashes.py -> build\lib.win-amd64-3.7\cryptography\hazmat\backends\openssl
  copying src\cryptography\hazmat\backends\openssl\hmac.py -> build\lib.win-amd64-3.7\cryptography\hazmat\backends\openssl
  copying src\cryptography\hazmat\backends\openssl\ocsp.py -> build\lib.win-amd64-3.7\cryptography\hazmat\backends\openssl
  copying src\cryptography\hazmat\backends\openssl\poly1305.py -> build\lib.win-amd64-3.7\cryptography\hazmat\backends\openssl
  copying src\cryptography\hazmat\backends\openssl\rsa.py -> build\lib.win-amd64-3.7\cryptography\hazmat\backends\openssl
  copying src\cryptography\hazmat\backends\openssl\utils.py -> build\lib.win-amd64-3.7\cryptography\hazmat\backends\openssl
  copying src\cryptography\hazmat\backends\openssl\x25519.py -> build\lib.win-amd64-3.7\cryptography\hazmat\backends\openssl
  copying src\cryptography\hazmat\backends\openssl\x448.py -> build\lib.win-amd64-3.7\cryptography\hazmat\backends\openssl
  copying src\cryptography\hazmat\backends\openssl\x509.py -> build\lib.win-amd64-3.7\cryptography\hazmat\backends\openssl
  copying src\cryptography\hazmat\backends\openssl\__init__.py -> build\lib.win-amd64-3.7\cryptography\hazmat\backends\openssl
  creating build\lib.win-amd64-3.7\cryptography\hazmat\bindings\openssl
  copying src\cryptography\hazmat\bindings\openssl\binding.py -> build\lib.win-amd64-3.7\cryptography\hazmat\bindings\openssl
  copying src\cryptography\hazmat\bindings\openssl\_conditional.py -> build\lib.win-amd64-3.7\cryptography\hazmat\bindings\openssl
  copying src\cryptography\hazmat\bindings\openssl\__init__.py -> build\lib.win-amd64-3.7\cryptography\hazmat\bindings\openssl
  creating build\lib.win-amd64-3.7\cryptography\hazmat\primitives\asymmetric
  copying src\cryptography\hazmat\primitives\asymmetric\dh.py -> build\lib.win-amd64-3.7\cryptography\hazmat\primitives\asymmetric
  copying src\cryptography\hazmat\primitives\asymmetric\dsa.py -> build\lib.win-amd64-3.7\cryptography\hazmat\primitives\asymmetric
  copying src\cryptography\hazmat\primitives\asymmetric\ec.py -> build\lib.win-amd64-3.7\cryptography\hazmat\primitives\asymmetric
  copying src\cryptography\hazmat\primitives\asymmetric\ed25519.py -> build\lib.win-amd64-3.7\cryptography\hazmat\primitives\asymmetric
  copying src\cryptography\hazmat\primitives\asymmetric\ed448.py -> build\lib.win-amd64-3.7\cryptography\hazmat\primitives\asymmetric
  copying src\cryptography\hazmat\primitives\asymmetric\padding.py -> build\lib.win-amd64-3.7\cryptography\hazmat\primitives\asymmetric
  copying src\cryptography\hazmat\primitives\asymmetric\rsa.py -> build\lib.win-amd64-3.7\cryptography\hazmat\primitives\asymmetric
  copying src\cryptography\hazmat\primitives\asymmetric\utils.py -> build\lib.win-amd64-3.7\cryptography\hazmat\primitives\asymmetric
  copying src\cryptography\hazmat\primitives\asymmetric\x25519.py -> build\lib.win-amd64-3.7\cryptography\hazmat\primitives\asymmetric
  copying src\cryptography\hazmat\primitives\asymmetric\x448.py -> build\lib.win-amd64-3.7\cryptography\hazmat\primitives\asymmetric
  copying src\cryptography\hazmat\primitives\asymmetric\__init__.py -> build\lib.win-amd64-3.7\cryptography\hazmat\primitives\asymmetric
  creating build\lib.win-amd64-3.7\cryptography\hazmat\primitives\ciphers
  copying src\cryptography\hazmat\primitives\ciphers\aead.py -> build\lib.win-amd64-3.7\cryptography\hazmat\primitives\ciphers
  copying src\cryptography\hazmat\primitives\ciphers\algorithms.py -> build\lib.win-amd64-3.7\cryptography\hazmat\primitives\ciphers
  copying src\cryptography\hazmat\primitives\ciphers\base.py -> build\lib.win-amd64-3.7\cryptography\hazmat\primitives\ciphers
  copying src\cryptography\hazmat\primitives\ciphers\modes.py -> build\lib.win-amd64-3.7\cryptography\hazmat\primitives\ciphers
  copying src\cryptography\hazmat\primitives\ciphers\__init__.py -> build\lib.win-amd64-3.7\cryptography\hazmat\primitives\ciphers
  creating build\lib.win-amd64-3.7\cryptography\hazmat\primitives\kdf
  copying src\cryptography\hazmat\primitives\kdf\concatkdf.py -> build\lib.win-amd64-3.7\cryptography\hazmat\primitives\kdf
  copying src\cryptography\hazmat\primitives\kdf\hkdf.py -> build\lib.win-amd64-3.7\cryptography\hazmat\primitives\kdf
  copying src\cryptography\hazmat\primitives\kdf\kbkdf.py -> build\lib.win-amd64-3.7\cryptography\hazmat\primitives\kdf
  copying src\cryptography\hazmat\primitives\kdf\pbkdf2.py -> build\lib.win-amd64-3.7\cryptography\hazmat\primitives\kdf
  copying src\cryptography\hazmat\primitives\kdf\scrypt.py -> build\lib.win-amd64-3.7\cryptography\hazmat\primitives\kdf
  copying src\cryptography\hazmat\primitives\kdf\x963kdf.py -> build\lib.win-amd64-3.7\cryptography\hazmat\primitives\kdf
  copying src\cryptography\hazmat\primitives\kdf\__init__.py -> build\lib.win-amd64-3.7\cryptography\hazmat\primitives\kdf
  creating build\lib.win-amd64-3.7\cryptography\hazmat\primitives\serialization
  copying src\cryptography\hazmat\primitives\serialization\base.py -> build\lib.win-amd64-3.7\cryptography\hazmat\primitives\serialization
  copying src\cryptography\hazmat\primitives\serialization\pkcs12.py -> build\lib.win-amd64-3.7\cryptography\hazmat\primitives\serialization
  copying src\cryptography\hazmat\primitives\serialization\pkcs7.py -> build\lib.win-amd64-3.7\cryptography\hazmat\primitives\serialization
  copying src\cryptography\hazmat\primitives\serialization\ssh.py -> build\lib.win-amd64-3.7\cryptography\hazmat\primitives\serialization
  copying src\cryptography\hazmat\primitives\serialization\__init__.py -> build\lib.win-amd64-3.7\cryptography\hazmat\primitives\serialization
  creating build\lib.win-amd64-3.7\cryptography\hazmat\primitives\twofactor
  copying src\cryptography\hazmat\primitives\twofactor\hotp.py -> build\lib.win-amd64-3.7\cryptography\hazmat\primitives\twofactor
  copying src\cryptography\hazmat\primitives\twofactor\totp.py -> build\lib.win-amd64-3.7\cryptography\hazmat\primitives\twofactor
  copying src\cryptography\hazmat\primitives\twofactor\utils.py -> build\lib.win-amd64-3.7\cryptography\hazmat\primitives\twofactor
  copying src\cryptography\hazmat\primitives\twofactor\__init__.py -> build\lib.win-amd64-3.7\cryptography\hazmat\primitives\twofactor
  running egg_info
  writing src\cryptography.egg-info\PKG-INFO
  writing dependency_links to src\cryptography.egg-info\dependency_links.txt
  writing requirements to src\cryptography.egg-info\requires.txt
  writing top-level names to src\cryptography.egg-info\top_level.txt
  reading manifest file 'src\cryptography.egg-info\SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  no previously-included directories found matching 'docs\_build'
  warning: no previously-included files found matching 'vectors'
  warning: no previously-included files matching '*' found under directory 'vectors'
  warning: no previously-included files matching '*' found under directory '.github'
  warning: no previously-included files found matching 'release.py'
  warning: no previously-included files found matching '.coveragerc'
  warning: no previously-included files found matching 'codecov.yml'
  warning: no previously-included files found matching '.readthedocs.yml'
  warning: no previously-included files found matching 'dev-requirements.txt'
  warning: no previously-included files found matching 'rtd-requirements.txt'
  warning: no previously-included files found matching 'tox.ini'
  warning: no previously-included files matching '*' found under directory '.zuul.d'
  warning: no previously-included files matching '*' found under directory '.zuul.playbooks'
  writing manifest file 'src\cryptography.egg-info\SOURCES.txt'
  running build_ext
  generating cffi module 'build\\temp.win-amd64-3.7\\Release\\_padding.c'
  creating build\temp.win-amd64-3.7
  creating build\temp.win-amd64-3.7\Release
  generating cffi module 'build\\temp.win-amd64-3.7\\Release\\_openssl.c'
  building '_openssl' extension

      =============================DEBUG ASSISTANCE=============================
      If you are seeing a compilation error please try the following steps to
      successfully install cryptography:
      1) Upgrade to the latest pip and try again. This will fix errors for most
         users. See: https://pip.pypa.io/en/stable/installing/#upgrading-pip
      2) Read https://cryptography.io/en/latest/installation.html for specific
         instructions for your platform.
      3) Check our frequently asked questions for more information:
         https://cryptography.io/en/latest/faq.html
      =============================DEBUG ASSISTANCE=============================

  error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
  ----------------------------------------
  ERROR: Failed building wheel for cryptography
  Running setup.py clean for cryptography
Failed to build cryptography
ERROR: Could not build wheels for cryptography which use PEP 517 and cannot be installed directly
```

**Comment by tiran** [comment]
Please update pip to latest version and try again. You might be running an outdated pip version that does not recognize precompiled binaries wheels for Windows.

**Comment by mkreim** [comment]
Oh thanks that solved it:
```PS C:\Users\mk> python -m pip install --upgrade pip
Collecting pip
  Using cached https://files.pythonhosted.org/packages/54/eb/4a3642e971f404d69d4f6fa3885559d67562801b99d7592487f1ecc4e017/pip-20.3.3-py2.py3-none-any.whl
Installing collected packages: pip
  Found existing installation: pip 19.2.3
    Uninstalling pip-19.2.3:
      Successfully uninstalled pip-19.2.3
Successfully installed pip-20.3.3
PS C:\Users\mk> pip install cryptography
Collecting cryptography
  Downloading cryptography-3.3.1-cp36-abi3-win_amd64.whl (1.5 MB)
     |████████████████████████████████| 1.5 MB 327 kB/s
Requirement already satisfied: six>=1.4.1 in c:\users\mk\appdata\local\programs\python\python37\lib\site-packages (from cryptography) (1.15.0)
Collecting cffi>=1.12
  Using cached cffi-1.14.4-cp37-cp37m-win_amd64.whl (178 kB)
Collecting pycparser
  Using cached pycparser-2.20-py2.py3-none-any.whl (112 kB)
Installing collected packages: pycparser, cffi, cryptography
Successfully installed cffi-1.14.4 cryptography-3.3.1 pycparser-2.20
```

No I just have to find out why my venv has an outdated pip. But I think that has nothing to do with cryptography. So thanks a lot for your help :-)

**Comment by boanergies** [comment]
> Please update pip to latest version and try again. You might be running an outdated pip version that does not recognize precompiled binaries wheels for Windows.

Why did this have to happen? I found today if I upgraded from pip 19.3.1 to the newest pip I suddenly could install cryptography-3.3.1  on windows 10 without it defaulting to the tar file. Did something change in pip I'm not aware of? I looked through pip's release notes and couldn't find a change.

**Comment by alex** [comment]
The thing that makes this work is support for the abi3 wheel tag for Windows in pip.

Since there doesn't appear to be a cryptography issue here, I'm going to close this.

**Comment by tiran** [comment]
AFAIK it's https://github.com/pypa/pip/issues/7327

> Use literal “abi3” for wheel tag on CPython 3.x, to align with PEP 384 which only defines it for this platform.
