### ISSUE TITLE
error: Can not find Rust compiler wtf?

### ISSUE THREAD

**Issue by gnauq3mg6m64rs2n** [pyca/cryptography#5755]
Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-acaqhqbi/cryptography/setup.py", line 13, in <module>
        from setuptools_rust import RustExtension
    ModuleNotFoundError: No module named 'setuptools_rust'

**Comment by alex** [comment]
See #5753.

And maybe don't ask "wtf" in your issue titles.
