### ISSUE TITLE
Runtime error on import on M1 Mac

### ISSUE THREAD

**Issue by bengolds** [pyca/cryptography#5843]
**Note**: I'm aware that there are a [few](https://github.com/pyca/cryptography/issues/5742) M1 installation errors. This has the same error message as the linked issue, but seems to be happening after install has already succeeded. If this is a dupe, please close this!

Cryptography throws a familiar cffi error when trying to import `cryptography.hazmat.bindings._padding`:
```
bash-3.2$ venv/bin/python -c "import cryptography.hazmat.bindings._padding"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: dlopen(/Users/bengold/Desktop/venv/lib/python3.9/site-packages/_cffi_backend.cpython-39-darwin.so, 2): Symbol not found: _ffi_prep_closure
  Referenced from: /Users/bengold/Desktop/venv/lib/python3.9/site-packages/_cffi_backend.cpython-39-darwin.so
  Expected in: flat namespace
 in /Users/bengold/Desktop/venv/lib/python3.9/site-packages/_cffi_backend.cpython-39-darwin.so
```

### Installation procedure
This is happening after successfully installing cryptography with the following commands:
```
python3 -m venv venv
LDFLAGS=-L$(brew --prefix libffi)/lib CFLAGS=-I$(brew --prefix libffi)/include venv/bin/pip install cffi --no-binary :all:
venv/bin/pip install cryptography
```

### Versions:
Python 3.9.1
cryptography 3.4.5
cffi 1.14.5

There is only the newest ARM version of Homebrew on this computer; the previous x86 Homebrew has been deleted.

I get these values from `pkg-config`:
```
$ pkg-config libffi --variable=pcfiledir                   
/opt/homebrew/Library/Homebrew/os/mac/pkgconfig/11

$ pkg-config libffi --cflags
-I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/ffi

$ pkg-config --variable pc_path pkg-config
/opt/homebrew/lib/pkgconfig:/opt/homebrew/share/pkgconfig:/usr/local/lib/pkgconfig:/usr/lib/pkgconfig:/opt/homebrew/Library/Homebrew/os/mac/pkgconfig/11
```

**Comment by reaperhulk** [comment]
Your environment appears to somehow still be installing a broken cffi. What happens if you do this after deleting your entire pip cache?

```python
python3 -m venv venv
venv/bin/pip install -U pip setuptools
LDFLAGS=-L$(brew --prefix libffi)/lib CFLAGS=-I$(brew --prefix libffi)/include venv/bin/pip install cffi --no-binary :all:
venv/bin/pip install cryptography
```

The pip/setuptools that come with 3.9.x's venv should be plenty new, but it's worth a shot. We've also now uploaded a cryptography wheel so it should pull that rather than attempting to compile itself.

If these steps don't work I'm afraid I'm out of ideas for now.

**Comment by alex** [comment]
Closing this -- if there's a response and we think there's an underlying issue we can reopen.

**Comment by bengolds** [comment]
I tried these commands out on a completely fresh partition of MacOS, and ran into the same error.

Interestingly enough, I then went back and tried something I hadn't for a while -- skipping the step that involves building `cffi` from scratch. So, I _just_ ran `pip install cryptography`, and it worked fine. This failed previously, when I had both the ARM and x86 versions of Homebrew on the machine.

**Comment by mathstuf** [comment]
I think this is the same as #5807.

**Comment by n8henrie** [comment]
I'm getting this same error and have been struggling with it for a few days, would be happy to open a new issue if more appropriate. Thanks for your efforts [trying to get this working](https://stackoverflow.com/a/66055389/1588795), but I'm not having much luck.

Same error using homebrew-installed python 3.9.2 and pyenv installed 3.9.1 (making sure to set CFLAGS and LDFLAGS for openssl, libffi, and readline in the latter).

```console
$ file /opt/homebrew/opt/python@3.9/bin/python3
/opt/homebrew/opt/python@3.9/bin/python3: Mach-O 64-bit executable arm64
$ file ~/.pyenv/versions/3.9.1/bin/python3
/Users/n8henrie/.pyenv/versions/3.9.1/bin/python3: Mach-O 64-bit executable arm64
$ arch
arm64
```

```console
$ pyenv which python3
/opt/homebrew/opt/python@3.9/bin/python3
$ python3 --version
Python 3.9.2
$ python3 -m venv .venv
$ ./.venv/bin/python -m pip install --upgrade pip setuptools
Requirement already satisfied: pip in ./.venv/lib/python3.9/site-packages (21.0.1)
Requirement already satisfied: setuptools in ./.venv/lib/python3.9/site-packages (53.0.0)
Collecting setuptools
  Using cached setuptools-54.1.1-py3-none-any.whl (784 kB)
Installing collected packages: setuptools
  Attempting uninstall: setuptools
    Found existing installation: setuptools 53.0.0
    Uninstalling setuptools-53.0.0:
      Successfully uninstalled setuptools-53.0.0
Successfully installed setuptools-54.1.1
$ LDFLAGS=-L$(brew --prefix libffi)/lib CFLAGS=-I$(brew --prefix libffi)/include ./.venv/bin/python -m pip install --no-cache-dir cffi --no-binary :all:
Collecting cffi
  Downloading cffi-1.14.5.tar.gz (475 kB)
     |████████████████████████████████| 475 kB 137 kB/s
Collecting pycparser
  Downloading pycparser-2.20.tar.gz (161 kB)
     |████████████████████████████████| 161 kB 133 kB/s
Skipping wheel build for cffi, due to binaries being disabled for it.
Skipping wheel build for pycparser, due to binaries being disabled for it.
Installing collected packages: pycparser, cffi
    Running setup.py install for pycparser ... done
    Running setup.py install for cffi ... done
Successfully installed cffi-1.14.5 pycparser-2.20
$ ./.venv/bin/python -m pip install --no-cache-dir cryptography
Collecting cryptography
  Downloading cryptography-3.4.6-cp36-abi3-macosx_11_0_arm64.whl (1.7 MB)
     |████████████████████████████████| 1.7 MB 153 kB/s
Requirement already satisfied: cffi>=1.12 in ./.venv/lib/python3.9/site-packages (from cryptography) (1.14.5)
Requirement already satisfied: pycparser in ./.venv/lib/python3.9/site-packages (from cffi>=1.12->cryptography) (2.20)
Installing collected packages: cryptography
Successfully installed cryptography-3.4.6
$ ./.venv/bin/python3 -c 'from cryptography.fernet import Fernet'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/private/var/folders/kb/tw_lp_xd2_bbv0hqk4m0bvt80000gn/T/tmp.AgNp3jrgmK/.venv/lib/python3.9/site-packages/cryptography/fernet.py", line 16, in <module>
    from cryptography.hazmat.primitives import hashes, padding
  File "/private/var/folders/kb/tw_lp_xd2_bbv0hqk4m0bvt80000gn/T/tmp.AgNp3jrgmK/.venv/lib/python3.9/site-packages/cryptography/hazmat/primitives/padding.py", line 11, in <module>
    from cryptography.hazmat.bindings._padding import lib
ImportError: dlopen(/private/var/folders/kb/tw_lp_xd2_bbv0hqk4m0bvt80000gn/T/tmp.AgNp3jrgmK/.venv/lib/python3.9/site-packages/_cffi_backend.cpython-39-darwin.so, 2): Symbol not found: _ffi_prep_closure
  Referenced from: /private/var/folders/kb/tw_lp_xd2_bbv0hqk4m0bvt80000gn/T/tmp.AgNp3jrgmK/.venv/lib/python3.9/site-packages/_cffi_backend.cpython-39-darwin.so
  Expected in: flat namespace
 in /private/var/folders/kb/tw_lp_xd2_bbv0hqk4m0bvt80000gn/T/tmp.AgNp3jrgmK/.venv/lib/python3.9/site-packages/_cffi_backend.cpython-39-darwin.so
```

Same error if I blow away the venv and install cryptography directly:

```console
$ rm -r .venv
$ python3 -m venv .venv
$ ./.venv/bin/python -m pip install --upgrade pip setuptools wheel
Requirement already satisfied: pip in ./.venv/lib/python3.9/site-packages (21.0.1)
Requirement already satisfied: setuptools in ./.venv/lib/python3.9/site-packages (53.0.0)
Collecting setuptools
  Using cached setuptools-54.1.1-py3-none-any.whl (784 kB)
Collecting wheel
  Downloading wheel-0.36.2-py2.py3-none-any.whl (35 kB)
Installing collected packages: wheel, setuptools
  Attempting uninstall: setuptools
    Found existing installation: setuptools 53.0.0
    Uninstalling setuptools-53.0.0:
      Successfully uninstalled setuptools-53.0.0
Successfully installed setuptools-54.1.1 wheel-0.36.2
$ ./.venv/bin/python -m pip install --no-cache-dir cryptography
Collecting cryptography
  Downloading cryptography-3.4.6-cp36-abi3-macosx_11_0_arm64.whl (1.7 MB)
     |████████████████████████████████| 1.7 MB 424 kB/s
Collecting cffi>=1.12
  Downloading cffi-1.14.5.tar.gz (475 kB)
     |████████████████████████████████| 475 kB 453 kB/s
Collecting pycparser
  Downloading pycparser-2.20-py2.py3-none-any.whl (112 kB)
     |████████████████████████████████| 112 kB 352 kB/s
Building wheels for collected packages: cffi
  Building wheel for cffi (setup.py) ... done
  Created wheel for cffi: filename=cffi-1.14.5-cp39-cp39-macosx_11_0_arm64.whl size=173730 sha256=e5dd1d296e4564180be5c3264c765bb273f8f5f8629fc645638e7cf7a8072b70
  Stored in directory: /private/var/folders/kb/tw_lp_xd2_bbv0hqk4m0bvt80000gn/T/pip-ephem-wheel-cache-09u10j81/wheels/9d/fd/b3/1c45c7d2a111aa5a29f24e12609ea5bc8a010d1b8351488796
Successfully built cffi
Installing collected packages: pycparser, cffi, cryptography
Successfully installed cffi-1.14.5 cryptography-3.4.6 pycparser-2.20
$ ./.venv/bin/python3 -c 'from cryptography.fernet import Fernet'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/private/var/folders/kb/tw_lp_xd2_bbv0hqk4m0bvt80000gn/T/tmp.AgNp3jrgmK/.venv/lib/python3.9/site-packages/cryptography/fernet.py", line 16, in <module>
    from cryptography.hazmat.primitives import hashes, padding
  File "/private/var/folders/kb/tw_lp_xd2_bbv0hqk4m0bvt80000gn/T/tmp.AgNp3jrgmK/.venv/lib/python3.9/site-packages/cryptography/hazmat/primitives/padding.py", line 11, in <module>
    from cryptography.hazmat.bindings._padding import lib
ImportError: dlopen(/private/var/folders/kb/tw_lp_xd2_bbv0hqk4m0bvt80000gn/T/tmp.AgNp3jrgmK/.venv/lib/python3.9/site-packages/_cffi_backend.cpython-39-darwin.so, 2): Symbol not found: _ffi_prep_closure
  Referenced from: /private/var/folders/kb/tw_lp_xd2_bbv0hqk4m0bvt80000gn/T/tmp.AgNp3jrgmK/.venv/lib/python3.9/site-packages/_cffi_backend.cpython-39-darwin.so
  Expected in: flat namespace
 in /private/var/folders/kb/tw_lp_xd2_bbv0hqk4m0bvt80000gn/T/tmp.AgNp3jrgmK/.venv/lib/python3.9/site-packages/_cffi_backend.cpython-39-darwin.so
```

I have uninstalled and reinstalled python, pyenv, cryptography, cffi, and libffi so many times and in so many different ways I'm going nuts.

**Comment by mathstuf** [comment]
Hmm. Looking again, maybe I was wrong in the similarity in the issue to #5807. Feel free to ignore my comments here :) .

**Comment by n8henrie** [comment]
I noted that homebrew updated `libffi` today; I blew away and rebuilt my virtualenv, installed dependencies with no special modifiers or flags, and things seem to work again.

```console
$ brew info libffi
libffi: stable 3.3 (bottled), HEAD [keg-only]
Portable Foreign Function Interface library
https://sourceware.org/libffi/
/opt/homebrew/Cellar/libffi/3.3_3 (17 files, 617.4KB)
  Poured from bottle on 2021-03-12 at 09:00:18
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/libffi.rb
License: MIT
==> Options
--HEAD
	Install HEAD version
==> Caveats
libffi is keg-only, which means it was not symlinked into /opt/homebrew,
because macOS already provides this software and installing another version in
parallel can cause all kinds of trouble.

For compilers to find libffi you may need to set:
  export LDFLAGS="-L/opt/homebrew/opt/libffi/lib"
  export CPPFLAGS="-I/opt/homebrew/opt/libffi/include"

For pkg-config to find libffi you may need to set:
  export PKG_CONFIG_PATH="/opt/homebrew/opt/libffi/lib/pkgconfig"

==> Analytics
install: 373,487 (30 days), 1,025,270 (90 days), 3,016,158 (365 days)
install-on-request: 17,796 (30 days), 55,403 (90 days), 135,582 (365 days)
build-error: 0 (30 days)
```
