### ISSUE TITLE
 [60] SSL peer certificate or SSH remote key was not OK

### ISSUE THREAD

**Issue by Walorda** [pyca/cryptography#6182]
Hi i am trying to install cryptography library with CKAN framework but i keep getting the error below which results in a build failure inside my docker alpine instance. i am running behind a proxy. 

How would i be able to bypass the 60 error for ssl certifcate? is their anyway i can manually download the rust and cargo ?

```
`#24 53.54   warning: no previously-included files found matching 'codecov.yml'
#24 53.54   warning: no previously-included files found matching '.readthedocs.yml'
#24 53.54   warning: no previously-included files found matching 'dev-requirements.txt'
#24 53.54   warning: no previously-included files found matching 'tox.ini'
#24 53.54   warning: no previously-included files found matching 'mypy.ini'
#24 53.54   warning: no previously-included files matching '*' found under directory '.zuul.d'
#24 53.54   warning: no previously-included files matching '*' found under directory '.zuul.playbooks'
#24 53.54   adding license file 'LICENSE'
#24 53.54   adding license file 'LICENSE.APACHE'
#24 53.54   adding license file 'LICENSE.BSD'
#24 53.54   adding license file 'LICENSE.PSF'
#24 53.54   writing manifest file 'src/cryptography.egg-info/SOURCES.txt'
#24 53.54   copying src/cryptography/py.typed -> build/lib.linux-x86_64-3.8/cryptography
#24 53.54   running build_ext
#24 53.54   generating cffi module 'build/temp.linux-x86_64-3.8/_padding.c'
#24 53.54   creating build/temp.linux-x86_64-3.8
#24 53.54   generating cffi module 'build/temp.linux-x86_64-3.8/_openssl.c'
#24 53.54   running build_rust
#24 53.54       Updating crates.io index
#24 53.54    Downloading crates ...
#24 53.54   error: failed to download from `https://crates.io/api/v1/crates/cfg-if/1.0.0/download`
#24 53.54
#24 53.54   Caused by:
#24 53.54     [60] SSL peer certificate or SSH remote key was not OK (SSL certificate problem: unable to get local issuer certificate)
#24 53.54
#24 53.54       =============================DEBUG ASSISTANCE=============================
#24 53.54       If you are seeing a compilation error please try the following steps to
#24 53.54       successfully install cryptography:
#24 53.54       1) Upgrade to the latest pip and try again. This will fix errors for most
#24 53.54          users. See: https://pip.pypa.io/en/stable/installing/#upgrading-pip
#24 53.54       2) Read https://cryptography.io/en/latest/installation.html for specific
#24 53.54          instructions for your platform.
#24 53.54       3) Check our frequently asked questions for more information:
#24 53.54          https://cryptography.io/en/latest/faq.html
#24 53.54       4) Ensure you have a recent Rust toolchain installed:
#24 53.54          https://cryptography.io/en/latest/installation.html#rust
#24 53.54       5) If you are experiencing issues with Rust for *this release only* you may
#24 53.54          set the environment variable `CRYPTOGRAPHY_DONT_BUILD_RUST=1`.
#24 53.54       =============================DEBUG ASSISTANCE=============================
#24 53.54
#24 53.54   Traceback (most recent call last):
#24 53.54     File "/usr/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 280, in <module>
#24 53.54       main()
#24 53.54     File "/usr/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 263, in main
#24 53.54       json_out['return_val'] = hook(**hook_input['kwargs'])
#24 53.54     File "/usr/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 204, in build_wheel
#24 53.54       return _build_backend().build_wheel(wheel_directory, config_settings,
#24 53.54     File "/tmp/pip-build-env-h4k24hls/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 221, in build_wheel
#24 53.54       return self._build_with_temp_dir(['bdist_wheel'], '.whl',
#24 53.54     File "/tmp/pip-build-env-h4k24hls/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 207, in _build_with_temp_dir
#24 53.54       self.run_setup()
#24 53.54     File "/tmp/pip-build-env-h4k24hls/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 150, in run_setup
#24 53.54       exec(compile(code, __file__, 'exec'), locals())
#24 53.54     File "setup.py", line 71, in <module>
#24 53.54       setup(
#24 53.54     File "/tmp/pip-build-env-h4k24hls/overlay/lib/python3.8/site-packages/setuptools/__init__.py", line 153, in setup
#24 53.54       return distutils.core.setup(**attrs)
#24 53.54     File "/usr/lib/python3.8/distutils/core.py", line 148, in setup
#24 53.54       dist.run_commands()
#24 53.54     File "/usr/lib/python3.8/distutils/dist.py", line 966, in run_commands
#24 53.54       self.run_command(cmd)
#24 53.54     File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
#24 53.54       cmd_obj.run()
#24 53.54     File "/tmp/pip-build-env-h4k24hls/overlay/lib/python3.8/site-packages/wheel/bdist_wheel.py", line 299, in run
#24 53.54       self.run_command('build')
#24 53.54     File "/usr/lib/python3.8/distutils/cmd.py", line 313, in run_command
#24 53.54       self.distribution.run_command(command)
#24 53.54     File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
#24 53.54       cmd_obj.run()
#24 53.54     File "/usr/lib/python3.8/distutils/command/build.py", line 135, in run
#24 53.54       self.run_command(cmd_name)
#24 53.54     File "/usr/lib/python3.8/distutils/cmd.py", line 313, in run_command
#24 53.54       self.distribution.run_command(command)
#24 53.54     File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
#24 53.54       cmd_obj.run()
#24 53.54     File "/tmp/pip-build-env-h4k24hls/overlay/lib/python3.8/site-packages/cffi/setuptools_ext.py", line 144, in run
#24 53.54       base_class.run(self)
#24 53.54     File "/tmp/pip-build-env-h4k24hls/overlay/lib/python3.8/site-packages/cffi/setuptools_ext.py", line 144, in run
#24 53.54       base_class.run(self)
#24 53.54     File "/tmp/pip-build-env-h4k24hls/overlay/lib/python3.8/site-packages/setuptools_rust/setuptools_ext.py", line 103, in run
#24 53.54       build_rust.run()
#24 53.54     File "/tmp/pip-build-env-h4k24hls/overlay/lib/python3.8/site-packages/setuptools_rust/command.py", line 52, in run
#24 53.54       self.run_for_extension(ext)
#24 53.54     File "/tmp/pip-build-env-h4k24hls/overlay/lib/python3.8/site-packages/setuptools_rust/build.py", line 92, in run_for_extension
#24 53.54       dylib_paths = self.build_extension(ext)
#24 53.54     File "/tmp/pip-build-env-h4k24hls/overlay/lib/python3.8/site-packages/setuptools_rust/build.py", line 131, in build_extension
#24 53.54       metadata = json.loads(check_output(metadata_command))
#24 53.54     File "/usr/lib/python3.8/subprocess.py", line 415, in check_output
#24 53.54       return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
#24 53.54     File "/usr/lib/python3.8/subprocess.py", line 516, in run
#24 53.54       raise CalledProcessError(retcode, process.args,
#24 53.54   subprocess.CalledProcessError: Command '['cargo', 'metadata', '--manifest-path', 'src/rust/Cargo.toml', '--format-version', '1']' returned non-zero 
exit status 101.
#24 53.54   ----------------------------------------
#24 53.54   ERROR: Failed building wheel for cryptography
#24 53.54 Failed to build cryptography
#24 53.54 ERROR: Could not build wheels for cryptography which use PEP 517 and cannot be installed directly`
```

**Comment by alex** [comment]
`cargo` will respect the `HTTPS_PROXY` env var, as well as a host of others: https://doc.rust-lang.org/cargo/reference/config.html#httpproxy

There's also a way to pre-download the rust dependencies, which is what linux distros use, but I don't know what it is off hand.

**Comment by Walorda** [comment]
Sadly enough i dont have access to the proxy details and an IT ticket will take weeks, so i was wondering if their was another solution.

**Comment by alex** [comment]
https://src.fedoraproject.org/rpms/python-cryptography/blob/rawhide/f/vendor_rust.py contains teh steps that Fedora uses to take a pyca/cryptography tarball and rebuild it with the cargo dependencies vendored.
