### ISSUE TITLE
isinstance fails to correctly identify types in derive_public_key

### ISSUE THREAD

**Issue by lemur117** [pyca/cryptography#6213]
While trying the following code:

```
from cryptography.hazmat.primitives import serialization
from cryptography.hazmat.primitives import asymmetric

priv_key = 'F1AB1074477EBCC7F554EA1C5FC368B1616730155E0041AC447D6301975FECDA'
privkey_int = int(priv_key, base=16)
privkey_ec = asymmetric.ec.derive_private_key(privkey_int, asymmetric.ec.SECP256R1)
```

I get a TypeError as follows:

```
>>> privkey_ec = asymmetric.ec.derive_private_key(privkey_int, asymmetric.ec.SECP256R1)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.8/dist-packages/cryptography/hazmat/primitives/asymmetric/ec.py", line 338, in derive_private_key
    raise TypeError("curve must provide the EllipticCurve interface.")
TypeError: curve must provide the EllipticCurve interface.
```

If I modify the ec.py file to print out the `type(curve)` and `type(EllipticCurve)`, then it shows:

```
type(curve): <class 'type'>
type(EllipticCurve): <class 'abc.ABCMeta'>
```

And if I comment out the `if not instance(curve, EllipticCurve):` line, then the function works perfectly.

Tested versions:
```
Python 3.8.5
pip 20.1.1
cffi==1.14.4
cryptography==3.3.1
```

**Comment by tiran** [comment]
You have to pass an instance of ``asymmetric.ec.SECP256R1``:

```
>>> privkey_ec = asymmetric.ec.derive_private_key(privkey_int, asymmetric.ec.SECP256R1())
>>> privkey_ec
<cryptography.hazmat.backends.openssl.ec._EllipticCurvePrivateKey object at 0x7fce1a1436a0>
```

**Comment by reaperhulk** [comment]
@tiran is correct. The documentation states that an instance (not the class itself) should be passed and the type error is due to that.

**Comment by lemur117** [comment]
You're right, fixing that in my code produces the correct result.  Thanks!
