### ISSUE TITLE
Need support for Private Enterprise Numbers in Extensions and Attributes

### ISSUE THREAD

**Issue by pprindeville** [pyca/cryptography#6235]
My employer has been allocated a Private Enterprise Number from which we're allocating OIDs as subtrees to use in X.509 Extensions in our CSR's.

However, when trying to add some trivial custom extensions to our CSR's with the `CertificateSigningRequestBuilder`, we see the following:

```
Traceback (most recent call last):
  File "./tests/device_enrollment.py", line 249, in <module>
    main(sys.argv)
  File "./tests/device_enrollment.py", line 205, in main
    csr = utility.generateCSR(
  File "./utility/utility.py", line 362, in generateCSR
    csr = builder.sign(sk, hashes.SHA256())
  File "/Library/Python/3.8/site-packages/cryptography/x509/base.py", line 494, in sign
    return backend.create_x509_csr(self, private_key, algorithm)
  File "/Library/Python/3.8/site-packages/cryptography/hazmat/backends/openssl/backend.py", line 961, in create_x509_csr
    self._create_x509_extensions(
  File "/Library/Python/3.8/site-packages/cryptography/hazmat/backends/openssl/backend.py", line 1141, in _create_x509_extensions
    x509_extension = self._create_x509_extension(handlers, extension)
  File "/Library/Python/3.8/site-packages/cryptography/hazmat/backends/openssl/backend.py", line 1178, in _create_x509_extension
    raise NotImplementedError(
NotImplementedError: Extension not supported: <ObjectIdentifier(oid=1.3.6.1.4.1.54807.1.1, name=Unknown OID)>
Error: offset out of range
```

Similarly, when trying to add custom attributes, we found that everything defaulted to `_ASN1Type.UTF8String` and there wasn't a way to specify other encodings like `_ASN1Type.IA5String` (there's no reason not to export this class, BTW).

I'd like to see support for dynamically adding custom OIDs (either as extensions or attributes).

This is on MacOS running 11.5.2.  It's the Python 3.8 that comes with MacOS.  And cryptography.io 3.4.7 that comes with MacOS.

**Comment by pprindeville** [comment]
Got an answer in IRC (on `#pyca`) on how to do this for Extensions:

```
>>>> acme_oids.py <<<<
#
# Acme oids taken from IANA PEN space
#

import typing

import pyasn1

from cryptography import x509
from cryptography.hazmat._oid import ObjectIdentifier

_AcmePENRoot = '1.3.6.1.4.1.123456'
_AcmeLensBase = _AcmePENRoot + '.1'

def _ia5string(b: bytes) -> bytes:
    ia5 = pyasn1.type.char.IA5String(value = b)
    return pyasn1.codec.ber.encoder.encode(ia5)

def _printablestring(b: bytes) -> bytes:
    ps = pyasn1.type.char.PrintableString(value = b)
    return pyasn1.codec.ber.encoder.encode(ps)

def _utf8string(s: str) -> bytes:
    utf = pyasn1.type.char.UTF8String(value = s)
    return pyasn1.codec.ber.encoder.encode(utf)

def _octetstring(b: bytes) -> bytes:
     os = pyasn1.type.char.OctetString(value = b)
     return pyasn1.codec.ber.encoder.encode(os)

class AcmeOID(object):
    MANUFACTURER_AND_MODEL = ObjectIdentifier(_AcmeLensBase + '.1')
    OPERATING_SYSTEM_AND_VERSION = ObjectIdentifier(_AcmeLensBase + '.2')

class ManufacturerAndModel(x509.UnrecognizedExtension):
    def __init__(
        self, value: bytes
    ):
        x509.UnrecognizedExtension.__init__(
            self,
            AcmeOID.MANUFACTURER_AND_MODEL,
            _ia5string(value),
        )

class OperatingSystemAndVersion(x509.UnrecognizedExtension):
    def __init__(
        self, value: bytes
    ):
        x509.UnrecognizedExtension.__init__(
            self,
            AcmeOID.OPERATING_SYSTEM_AND_VERSION,
            _ia5string(value),
        )

__all__ = [
    'AcmeOID',
    'ManufacturerAndModel',
    'OperatingSystemAndVersion',
]

_OID_NAMES = {
    AcmeOID.MANUFACTURER_AND_MODEL: 'ManufacturerAndModel',
    AcmeOID.OPERATING_SYSTEM_AND_VERSION: 'OperatingSystemAndVersion',
}
```

and then when generating CSR's, I do:

```
...
from acme_oids import OperatingSystemAndVersion
...
builder = x509.CertificateSigningRequestBuilder()
...
builder = builder.add_extension(
    OperatingSystemAndVersion('iOS 14.7.1'),
    critical = False
)
...
```
