### ISSUE TITLE
Unknown OpenSSL error with latest python docker image

### ISSUE THREAD

**Issue by ylogx** [pyca/cryptography#6244]
I'm seeing the following openssl error when I'm trying to use cryptography for aes-gcm. Attached are the detailed steps for repro and the results from my terminal. The outputs also contain the versions of python, openssl and cryptography.

# Repro

### Dockerfile
```dockerfile
FROM python:3.9

WORKDIR /app

RUN pip install --no-cache-dir cryptography
```

### Build and Run
```bash
docker build -f Dockerfile -t crypto-repro .
docker run --rm -it crypto-repro python3
```

### Code
```python
import cryptography
cryptography.__version__
from cryptography.hazmat.backends.openssl.backend import backend;print(backend.openssl_version_text())
from cryptography.hazmat.backends import default_backend
from cryptography.hazmat.primitives.ciphers import (Cipher, algorithms, modes)
Cipher(algorithms.AES('asdfasdfasdfasdfasdfasdfasdfasdf'.encode()), modes.GCM('asdasdfasdfasdfasdff'.encode(), 'asdfasdfaasdfasdfasdfsdf'.encode()), backend=default_backend()).decryptor()
```

##### Output
```python
Python 3.9.6 (default, Aug 17 2021, 15:37:33)
[GCC 10.2.1 20210110] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import cryptography
>>> cryptography.__version__
'3.4.8'
>>> from cryptography.hazmat.backends import default_backend
>>> from cryptography.hazmat.primitives.ciphers import (Cipher, algorithms, modes)
>>> from cryptography.hazmat.backends.openssl.backend import backend;print(backend.openssl_version_text())
OpenSSL 1.1.1l  24 Aug 2021
>>> Cipher(algorithms.AES('asdfasdfasdfasdfasdfasdfasdfasdf'.encode()), modes.GCM('asdasdfasdfasdfasdff'.encode(), 'asdfasdfaasdfasdfasdfsdf'.encode()), backend=default_backend()).decryptor()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.9/site-packages/cryptography/hazmat/primitives/ciphers/base.py", line 115, in decryptor
    ctx = self._backend.create_symmetric_decryption_ctx(
  File "/usr/local/lib/python3.9/site-packages/cryptography/hazmat/backends/openssl/backend.py", line 487, in create_symmetric_decryption_ctx
    return _CipherContext(self, cipher, mode, _CipherContext._DECRYPT)
  File "/usr/local/lib/python3.9/site-packages/cryptography/hazmat/backends/openssl/ciphers.py", line 103, in __init__
    self._backend.openssl_assert(res != 0)
  File "/usr/local/lib/python3.9/site-packages/cryptography/hazmat/backends/openssl/backend.py", line 241, in openssl_assert
    return binding._openssl_assert(self._lib, ok, errors=errors)
  File "/usr/local/lib/python3.9/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 80, in _openssl_assert
    raise InternalError(
cryptography.exceptions.InternalError: Unknown OpenSSL error. This error is commonly encountered when another library is not cleaning up the OpenSSL error stack. If you are using cryptography with another library that uses OpenSSL try disabling it before reporting a bug. Otherwise please file an issue at https://github.com/pyca/cryptography/issues with information on how to reproduce this. ([])
>>>
Please do not report security issues on Github! Follow the instructions in our
documentation for reporting security issues:
https://cryptography.io/en/latest/security.html
```

Please let me know if I'm using the library wrong, or if there's a missing dependency and how this can be fixed.

**Comment by reaperhulk** [comment]
Thanks for the bug report. The issue here is that you are passing a 24 byte tag. GCM tags are, at most, 16 bytes. This is still a bug in our library though because we should catch this and raise a `ValueError` instead.
