### ISSUE TITLE
Build failure

### ISSUE THREAD

**Issue by cemoktra** [pyca/cryptography#6485]
* Versions of Python, ``cryptography``, ``cffi``, ``pip``, and ``setuptools``
  you're using
* How you installed ``cryptography``
* Clear steps for reproducing your bug

We are setting up a python environment inside a debian buster container:

```
Collecting cryptography (from Authlib==0.11->-r /tmp/pip_requirements.txt (line 3))
  Downloading https://files.pythonhosted.org/packages/10/91/90b8d4cd611ac2aa526290ae4b4285aa5ea57ee191c63c2f3d04170d7683/cryptography-35.0.0.tar.gz (559kB)
```
- python 3.7.3
- libffi 3.2.1-9

```
Running setup.py bdist_wheel for cryptography: started
Running setup.py bdist_wheel for cryptography: finished with status 'error'
...
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-install-97xwe5pz/cryptography/setup.py", line 54, in <module>
      rust_version=">=1.41.0",
    File "/tmp/pip-build-env-dr0sapkh/lib/python3.7/site-packages/setuptools/__init__.py", line 159, in setup
      return distutils.core.setup(**attrs)
    File "/usr/lib/python3.7/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/usr/lib/python3.7/distutils/dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "/usr/lib/python3.7/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/tmp/pip-build-env-dr0sapkh/lib/python3.7/site-packages/wheel/bdist_wheel.py", line 299, in run
      self.run_command('build')
    File "/usr/lib/python3.7/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/lib/python3.7/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/usr/lib/python3.7/distutils/command/build.py", line 135, in run
      self.run_command(cmd_name)
    File "/usr/lib/python3.7/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/lib/python3.7/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/tmp/pip-build-env-dr0sapkh/lib/python3.7/site-packages/cffi/setuptools_ext.py", line 144, in run
      base_class.run(self)
    File "/tmp/pip-build-env-dr0sapkh/lib/python3.7/site-packages/setuptools_rust/setuptools_ext.py", line 103, in run
      build_rust.run()
    File "/tmp/pip-build-env-dr0sapkh/lib/python3.7/site-packages/setuptools_rust/command.py", line 52, in run
      self.run_for_extension(ext)
    File "/tmp/pip-build-env-dr0sapkh/lib/python3.7/site-packages/setuptools_rust/build.py", line 92, in run_for_extension
      dylib_paths = self.build_extension(ext)
    File "/tmp/pip-build-env-dr0sapkh/lib/python3.7/site-packages/setuptools_rust/build.py", line 131, in build_extension
      metadata = json.loads(check_output(metadata_command))
    File "/usr/lib/python3.7/subprocess.py", line 395, in check_output
      **kwargs).stdout
    File "/usr/lib/python3.7/subprocess.py", line 487, in run
      output=stdout, stderr=stderr)
  subprocess.CalledProcessError: Command '['cargo', 'metadata', '--manifest-path', 'src/rust/Cargo.toml', '--format-version', '1']' died with <Signals.SIGSEGV: 11>.
  
  ----------------------------------------
  Failed building wheel for cryptography
```

**Comment by alex** [comment]
Looks like someone reported this to debian: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=998232
