### ISSUE TITLE
CSR parsing error with >28 bits oids

### ISSUE THREAD

**Issue by vpelletier** [pyca/cryptography#6573]
`cryptography` is capable of producing PEM-encoded CSRs containing >28bits OIDs, but fails when parsing them with the error (here, the OID is in a policy identifier):
```
ValueError: error parsing asn1 value: ParseError { kind: InvalidValue, location: ["0", "PolicyInformation::policy_identifier"] }
```

This makes the UUID OID subtree (2.25) unusable, as it requires 128-bits OIDs.

Now, I guess this could be reasonably closed as wontfix because there are many other implementations out there which do not (and some will likely never) support >64bits OIDs (ex: golang's). This is a messy topic at he very least:
- because there are many implementations incomplete in such a way out there, relying on >64bits OIDs is a bad idea
- ...so fixing it here is unlikely to do much good
- ...except for existing implementations which were not aware of this lack of support, in which case propagating the lack of support (=breaking >64bits oids in `cryptography`) will complicate the upgrade path

For my personal use cases, I was kind of lucky that I discovered the issue before support was dropped in `cryptography`, and I believe all impacted certificates have been long migrated. It is my automated testing of this very migration codepath which detected the breakage in `cryptography`, so I guess I have to at least skip this test when parsing fails.

If this bug was at 63 or 64bits, I would sugest resolving it by just (retroactively ?) listing this breakage in the changelog. But seeing that this happens with OIDs well under 64bits makes me think a fix is needed.

Of course, if such fix can also add support for 128bits OIDs, it is even better, but I do not know if it is necessary.

Versions:
- Python: 3.9.2
- cryptography: 35.0.0 (installed with pip in a virtualenv)
- cffi: 1.15.0
- pip: 21.3.1
- setuptools: 58.5.3

Steps to reproduce:

```python
from cryptography import x509
from cryptography.hazmat.primitives.asymmetric import rsa
from cryptography.hazmat.primitives import serialization, hashes

LONG_UUID = 2**128 - 1
LONG_OID = '2.25.%i' % (LONG_UUID, )
SHORT_OID = '2.25.%i' % (LONG_UUID & (2**28 - 1), )
test_private_key = rsa.generate_private_key(public_exponent=65537, key_size=2048)
def makeAndLoadCSR(oid):
    extension = x509.CertificatePolicies([
        x509.PolicyInformation(x509.oid.ObjectIdentifier(oid), None),
    ])
    csr_pem = x509.CertificateSigningRequestBuilder(
        subject_name=x509.Name([x509.NameAttribute(oid=x509.oid.NameOID.COMMON_NAME, value='test')]),
    ).add_extension(extension, critical=False).sign(
        private_key=test_private_key,
        algorithm=hashes.SHA256(),
    ).public_bytes(encoding=serialization.Encoding.PEM)
    _ = x509.load_pem_x509_csr(csr_pem).extensions

# this succeeds
makeAndLoadCSR(SHORT_OID)
# this fails
makeAndLoadCSR(LONG_OID)
```

Output of the last statement above when the issue is present:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 14, in makeAndLoadCSR
ValueError: error parsing asn1 value: ParseError { kind: InvalidValue, location: ["0", "PolicyInformation::policy_identifier"] }
```

**Comment by reaperhulk** [comment]
Thanks for the report. The existence of a UUID arc is (unwelcome) news to me. 😄 This error occurs because we internally parse arcs as u32. We can make them wider (64-bits is easy). Should we widen even if we choose not to support 128-bit arc values?

I'm leaning towards aligning with Go here in rejecting >64-bit, as the existence of a very large ecosystem that doesn't support this means it's likely to die out.

**Comment by vpelletier** [comment]
I checked some more, and I'm afraid I am actually misremembering the golang limit and the RFC:

[rfc3280 appendix-B]https://datatracker.ietf.org/doc/html/rfc3280#appendix-B) says (my emphasis):

>    Object Identifiers (OIDs) are used throughout this specification to
>   identify certificate policies, public key and signature algorithms,
>   certificate extensions, etc.  There is no maximum size for OIDs.
>   This specification mandates support for OIDs which have **arc elements**
>   **with values that are less than 2^28**, that is, they MUST be between 0
>   and 268,435,455, inclusive.  This allows each arc element to be
>   represented within a single 32 bit word.  Implementations MUST also
>   support OIDs where the length of the dotted decimal (see [RFC 2252],
>   section 4.1) string representation can be up to 100 bytes
>   (inclusive).  Implementations MUST be able to handle OIDs with up to
>   20 elements (inclusive).  CAs SHOULD NOT issue certificates which
>   contain OIDs that exceed these requirements.  Likewise, CRL issuers
>   SHOULD NOT issue CRLs which contain OIDs that exceed these
>   requirements.

And golang is apparently limited to 28 bits as well: https://github.com/golang/go/issues/19933 .

So I was wrong in mentioning 64 bits as the golang limit and better cutoff, and 28bits seems to be the widespread implementation limit.

So I leave the decision of how this "regression" (it is technically a regression, but only for users in a very homogeneous environment, other will have had issues long ago anyway) should be handled.

**Comment by alex** [comment]
Based on the fact that other implementations enforce similar limitations, and this approach is condoned by the RFC, I think I'm going to wontfix this.

@reaperhulk if you disagree, feel free to re-open.

**Comment by vpelletier** [comment]
Update on this topic: as of 36.0.0, the error became (with `RUST_BACKTRACE=1`):

```
thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', src/x509/extensions.rs:238:18
stack backtrace:
   0: rust_begin_unwind
             at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/panicking.rs:517:5
   1: core::panicking::panic_fmt
             at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/core/src/panicking.rs:101:14
   2: core::panicking::panic
             at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/core/src/panicking.rs:50:5
   3: cryptography_rust::x509::extensions::encode_extension
   4: cryptography_rust::x509::common::encode_extensions
   5: cryptography_rust::x509::csr::create_x509_csr
   6: cryptography_rust::x509::csr::__pyo3_raw_create_x509_csr::{{closure}}
   7: cryptography_rust::x509::csr::__pyo3_raw_create_x509_csr
   8: cfunction_call
             at /build/python3.9-VBHEdK/python3.9-3.9.9/build-static/../Objects/methodobject.c:543:19
   9: _PyObject_MakeTpCall
             at /build/python3.9-VBHEdK/python3.9-3.9.9/build-static/../Objects/call.c:191:18
  10: _PyObject_VectorcallTstate
             at /build/python3.9-VBHEdK/python3.9-3.9.9/build-static/../Include/cpython/abstract.h:116:16
  11: _PyObject_VectorcallTstate
             at /build/python3.9-VBHEdK/python3.9-3.9.9/build-static/../Include/cpython/abstract.h:103:1
  12: PyObject_Vectorcall
             at /build/python3.9-VBHEdK/python3.9-3.9.9/build-static/../Include/cpython/abstract.h:127:12
  13: call_function
             at /build/python3.9-VBHEdK/python3.9-3.9.9/build-static/../Python/ceval.c:5075:13
  14: _PyEval_EvalFrameDefault
             at /build/python3.9-VBHEdK/python3.9-3.9.9/build-static/../Python/ceval.c:3487:23
  15: _PyEval_EvalFrame
             at /build/python3.9-VBHEdK/python3.9-3.9.9/build-static/../Include/internal/pycore_ceval.h:40:12
  16: _PyEval_EvalCode
             at /build/python3.9-VBHEdK/python3.9-3.9.9/build-static/../Python/ceval.c:4327:14
  17: _PyFunction_Vectorcall
             at /build/python3.9-VBHEdK/python3.9-3.9.9/build-static/../Objects/call.c:396:12
  18: _PyObject_VectorcallTstate
             at /build/python3.9-VBHEdK/python3.9-3.9.9/build-static/../Include/cpython/abstract.h:118:11
  19: method_vectorcall
             at /build/python3.9-VBHEdK/python3.9-3.9.9/build-static/../Objects/classobject.c:53:18
  20: _PyObject_VectorcallTstate
             at /build/python3.9-VBHEdK/python3.9-3.9.9/build-static/../Include/cpython/abstract.h:118:11
  21: PyObject_Vectorcall
             at /build/python3.9-VBHEdK/python3.9-3.9.9/build-static/../Include/cpython/abstract.h:127:12
  22: call_function
             at /build/python3.9-VBHEdK/python3.9-3.9.9/build-static/../Python/ceval.c:5075:13
  23: _PyEval_EvalFrameDefault
             at /build/python3.9-VBHEdK/python3.9-3.9.9/build-static/../Python/ceval.c:3535:19
  24: _PyEval_EvalFrame
             at /build/python3.9-VBHEdK/python3.9-3.9.9/build-static/../Include/internal/pycore_ceval.h:40:12
  25: _PyEval_EvalCode
             at /build/python3.9-VBHEdK/python3.9-3.9.9/build-static/../Python/ceval.c:4327:14
  26: _PyFunction_Vectorcall
             at /build/python3.9-VBHEdK/python3.9-3.9.9/build-static/../Objects/call.c:396:12
  27: _PyObject_VectorcallTstate
             at /build/python3.9-VBHEdK/python3.9-3.9.9/build-static/../Include/cpython/abstract.h:118:11
  28: PyObject_Vectorcall
             at /build/python3.9-VBHEdK/python3.9-3.9.9/build-static/../Include/cpython/abstract.h:127:12
  29: call_function
             at /build/python3.9-VBHEdK/python3.9-3.9.9/build-static/../Python/ceval.c:5075:13
  30: _PyEval_EvalFrameDefault
             at /build/python3.9-VBHEdK/python3.9-3.9.9/build-static/../Python/ceval.c:3518:19
  31: _PyEval_EvalFrame
             at /build/python3.9-VBHEdK/python3.9-3.9.9/build-static/../Include/internal/pycore_ceval.h:40:12
  32: _PyEval_EvalCode
             at /build/python3.9-VBHEdK/python3.9-3.9.9/build-static/../Python/ceval.c:4327:14
  33: _PyFunction_Vectorcall
             at /build/python3.9-VBHEdK/python3.9-3.9.9/build-static/../Objects/call.c:396:12
  34: _PyObject_VectorcallTstate
             at /build/python3.9-VBHEdK/python3.9-3.9.9/build-static/../Include/cpython/abstract.h:118:11
  35: PyObject_Vectorcall
             at /build/python3.9-VBHEdK/python3.9-3.9.9/build-static/../Include/cpython/abstract.h:127:12
  36: call_function
             at /build/python3.9-VBHEdK/python3.9-3.9.9/build-static/../Python/ceval.c:5075:13
  37: _PyEval_EvalFrameDefault
             at /build/python3.9-VBHEdK/python3.9-3.9.9/build-static/../Python/ceval.c:3518:19
  38: _PyEval_EvalFrame
             at /build/python3.9-VBHEdK/python3.9-3.9.9/build-static/../Include/internal/pycore_ceval.h:40:12
  39: _PyEval_EvalCode
             at /build/python3.9-VBHEdK/python3.9-3.9.9/build-static/../Python/ceval.c:4327:14
  40: _PyEval_EvalCodeWithName
             at /build/python3.9-VBHEdK/python3.9-3.9.9/build-static/../Python/ceval.c:4359:12
  41: PyEval_EvalCodeEx
             at /build/python3.9-VBHEdK/python3.9-3.9.9/build-static/../Python/ceval.c:4375:12
  42: PyEval_EvalCode
             at /build/python3.9-VBHEdK/python3.9-3.9.9/build-static/../Python/ceval.c:826:12
  43: builtin_exec_impl
             at /build/python3.9-VBHEdK/python3.9-3.9.9/build-static/../Python/bltinmodule.c:1026:13
  44: builtin_exec
             at /build/python3.9-VBHEdK/python3.9-3.9.9/build-static/../Python/clinic/bltinmodule.c.h:396:20
  45: cfunction_vectorcall_FASTCALL
             at /build/python3.9-VBHEdK/python3.9-3.9.9/build-static/../Objects/methodobject.c:430:24
  46: _PyObject_VectorcallTstate
             at /build/python3.9-VBHEdK/python3.9-3.9.9/build-static/../Include/cpython/abstract.h:118:11
  47: PyObject_Vectorcall
             at /build/python3.9-VBHEdK/python3.9-3.9.9/build-static/../Include/cpython/abstract.h:127:12
  48: call_function
             at /build/python3.9-VBHEdK/python3.9-3.9.9/build-static/../Python/ceval.c:5075:13
  49: _PyEval_EvalFrameDefault
             at /build/python3.9-VBHEdK/python3.9-3.9.9/build-static/../Python/ceval.c:3518:19
  50: _PyEval_EvalFrame
             at /build/python3.9-VBHEdK/python3.9-3.9.9/build-static/../Include/internal/pycore_ceval.h:40:12
  51: _PyEval_EvalCode
             at /build/python3.9-VBHEdK/python3.9-3.9.9/build-static/../Python/ceval.c:4327:14
  52: _PyFunction_Vectorcall
             at /build/python3.9-VBHEdK/python3.9-3.9.9/build-static/../Objects/call.c:396:12
  53: _PyObject_VectorcallTstate
             at /build/python3.9-VBHEdK/python3.9-3.9.9/build-static/../Include/cpython/abstract.h:118:11
  54: PyObject_Vectorcall
             at /build/python3.9-VBHEdK/python3.9-3.9.9/build-static/../Include/cpython/abstract.h:127:12
  55: call_function
             at /build/python3.9-VBHEdK/python3.9-3.9.9/build-static/../Python/ceval.c:5075:13
  56: _PyEval_EvalFrameDefault
             at /build/python3.9-VBHEdK/python3.9-3.9.9/build-static/../Python/ceval.c:3518:19
  57: _PyEval_EvalFrame
             at /build/python3.9-VBHEdK/python3.9-3.9.9/build-static/../Include/internal/pycore_ceval.h:40:12
  58: _PyEval_EvalCode
             at /build/python3.9-VBHEdK/python3.9-3.9.9/build-static/../Python/ceval.c:4327:14
  59: _PyFunction_Vectorcall
             at /build/python3.9-VBHEdK/python3.9-3.9.9/build-static/../Objects/call.c:396:12
  60: pymain_run_module
             at /build/python3.9-VBHEdK/python3.9-3.9.9/build-static/../Modules/main.c:291:14
  61: pymain_run_python
             at /build/python3.9-VBHEdK/python3.9-3.9.9/build-static/../Modules/main.c:592:21
  62: Py_RunMain
             at /build/python3.9-VBHEdK/python3.9-3.9.9/build-static/../Modules/main.c:677:5
  63: Py_BytesMain
             at /build/python3.9-VBHEdK/python3.9-3.9.9/build-static/../Modules/main.c:731:12
  64: __libc_start_main
             at ./csu/../csu/libc-start.c:332:16
  65: _start
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "caucase/test.py", line 145, in <module>
    ) = _getTestOID()
  File "caucase/test.py", line 136, in _getTestOID
    makeAndLoadCSR(LONG_OID)
  File "caucase/test.py", line 110, in makeAndLoadCSR
    x509.CertificateSigningRequestBuilder(
  File "vpy3/lib/python3.9/site-packages/cryptography/x509/base.py", line 644, in sign
    return rust_x509.create_x509_csr(self, private_key, algorithm)
pyo3_runtime.PanicException: called `Option::unwrap()` on a `None` value
```

(same happens on current release version, 36.0.1)

This is happening in code in my test suite, which is trying to detect if tested cryptography version has support for 128bits OIDs, and if the support is missing then I skip a test case (which is precisely testing the upgrade path out of 128 bits OIDs in my CA implementation). In 35.0.0 it was raising a `ValueError`, which seems a lot cleaner than such does-not-inherit-from-`Exception` class.

Is this error change intentional ?

What would be the recommended way of checking for 128bits OID support ? Maybe checking `cryptography.__version__` ?

**Comment by reaperhulk** [comment]
Reopening, as whatever we do we should have a better error than that.
