### ISSUE TITLE
35.0.0: documentation build fails

### ISSUE THREAD

**Issue by kloczek** [pyca/cryptography#6612]
* Versions of Python, ``cryptography``, ``cffi``, ``pip``, and ``setuptools``
  Python 2.8.12, cryptography 35.0.0, cffi 1.14.6, setuptools 59.1.0
* How you installed ``cryptography``
N/A
* Clear steps for reproducing your bug
After `setup.py build egg_info` execute `setup.py build_sphinx`

Here is the output with build fails:
```console
+ /usr/bin/python3 setup.py build_sphinx -b man --build-dir build/sphinx
running build_sphinx
Running Sphinx v4.2.0
making output directory... done
loading intersphinx inventory from https://docs.python.org/3/objects.inv...
building [mo]: targets for 0 po files that are out of date
building [man]: all manpages
updating environment: [new config] 58 added, 0 changed, 0 removed
reading sources... [100%] x509/tutorial
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
writing... python-cryptography.3 { fernet x509/index x509/tutorial x509/certificate-transparency x509/ocsp x509/reference hazmat/primitives/index hazmat/primitives/aead hazmat/primitives/asymmetric/index hazmat/primitives/asymmetric/ed25519 hazmat/primitives/asymmetric/x25519 hazmat/primitives/asymmetric/ed448 hazmat/primitives/asymmetric/x448 hazmat/primitives/asymmetric/ec hazmat/primitives/asymmetric/rsa hazmat/primitives/asymmetric/dh hazmat/primitives/asymmetric/dsa hazmat/primitives/asymmetric/serialization hazmat/primitives/asymmetric/utils hazmat/primitives/constant-time hazmat/primitives/key-derivation-functions hazmat/primitives/keywrap hazmat/primitives/mac/index hazmat/primitives/mac/cmac hazmat/primitives/mac/hmac hazmat/primitives/mac/poly1305 hazmat/primitives/cryptographic-hashes hazmat/primitives/symmetric-encryption hazmat/primitives/padding hazmat/primitives/twofactor exceptions random-numbers hazmat/backends/index hazmat/backends/openssl hazmat/backends/interfaces installation changelog faq development/index development/getting-started development/submitting-patches development/reviewing-patches development/test-vectors development/custom-vectors/secp256k1 development/custom-vectors/rsa-oaep-sha2 development/custom-vectors/arc4 development/custom-vectors/cast5 development/custom-vectors/idea development/custom-vectors/seed development/custom-vectors/hkdf development/c-bindings security limitations api-stability doing-a-release community glossary } failed

Exception occurred:
  File "/usr/lib/python3.8/site-packages/sphinx/writers/manpage.py", line 467, in unknown_visit
    raise NotImplementedError('Unknown node: ' + node.__class__.__name__)
NotImplementedError: Unknown node: Hazmat
The full traceback has been saved in /tmp/sphinx-err-jw5g176o.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!

    =============================DEBUG ASSISTANCE=============================
    If you are seeing a compilation error please try the following steps to
    successfully install cryptography:
    1) Upgrade to the latest pip and try again. This will fix errors for most
       users. See: https://pip.pypa.io/en/stable/installing/#upgrading-pip
    2) Read https://cryptography.io/en/latest/installation/ for specific
       instructions for your platform.
    3) Check our frequently asked questions for more information:
       https://cryptography.io/en/latest/faq/
    4) Ensure you have a recent Rust toolchain installed:
       https://cryptography.io/en/latest/installation/#rust

    Python: 3.8.12
    platform: Linux-5.14.17-301.fc35.x86_64-x86_64-with-glibc2.34
    pip: 21.3.1
    setuptools: 59.1.0.post20211115
    setuptools_rust: 0.12.1
    =============================DEBUG ASSISTANCE=============================
```
```console
[tkloczko@ss-desktop SPECS]$ cat /tmp/sphinx-err-jw5g176o.log
# Sphinx version: 4.2.0
# Python version: 3.8.12 (CPython)
# Docutils version: 0.17.1 release
# Jinja2 version: 3.0.1
# Last messages:
#   development/custom-vectors/hkdf
#   development/c-bindings
#   security
#   limitations
#   api-stability
#   doing-a-release
#   community
#   glossary
#   }
#   failed
# Loaded extensions:
#   sphinx.ext.mathjax (4.2.0) from /usr/lib/python3.8/site-packages/sphinx/ext/mathjax.py
#   sphinxcontrib.applehelp (1.0.2) from /usr/lib/python3.8/site-packages/sphinxcontrib/applehelp/__init__.py
#   sphinxcontrib.devhelp (1.0.2) from /usr/lib/python3.8/site-packages/sphinxcontrib/devhelp/__init__.py
#   sphinxcontrib.htmlhelp (2.0.0) from /usr/lib/python3.8/site-packages/sphinxcontrib/htmlhelp/__init__.py
#   sphinxcontrib.serializinghtml (1.1.5) from /usr/lib/python3.8/site-packages/sphinxcontrib/serializinghtml/__init__.py
#   sphinxcontrib.qthelp (1.0.3) from /usr/lib/python3.8/site-packages/sphinxcontrib/qthelp/__init__.py
#   alabaster (0.7.12) from /usr/lib/python3.8/site-packages/alabaster/__init__.py
#   sphinx.ext.autodoc.preserve_defaults (1.0) from /usr/lib/python3.8/site-packages/sphinx/ext/autodoc/preserve_defaults.py
#   sphinx.ext.autodoc.type_comment (4.2.0) from /usr/lib/python3.8/site-packages/sphinx/ext/autodoc/type_comment.py
#   sphinx.ext.autodoc (4.2.0) from /usr/lib/python3.8/site-packages/sphinx/ext/autodoc/__init__.py
#   sphinx.ext.doctest (4.2.0) from /usr/lib/python3.8/site-packages/sphinx/ext/doctest.py
#   sphinx.ext.intersphinx (4.2.0) from /usr/lib/python3.8/site-packages/sphinx/ext/intersphinx.py
#   sphinx.ext.viewcode (4.2.0) from /usr/lib/python3.8/site-packages/sphinx/ext/viewcode.py
#   cryptography-docs (unknown version) from /home/tkloczko/rpmbuild/BUILD/cryptography-35.0.0/docs/cryptography-docs.py
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/sphinx/setup_command.py", line 177, in run
    app.build(force_all=self.all_files)
  File "/usr/lib/python3.8/site-packages/sphinx/application.py", line 343, in build
    self.builder.build_update()
  File "/usr/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 290, in build_update
    self.build(['__all__'], to_build)
  File "/usr/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 357, in build
    self.write(docnames, list(updated_docnames), method)
  File "/usr/lib/python3.8/site-packages/sphinx/util/__init__.py", line 547, in wrapper
    return f(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/sphinx/builders/manpage.py", line 104, in write
    docwriter.write(largetree, destination)
  File "/usr/lib/python3.8/site-packages/docutils/writers/__init__.py", line 78, in write
    self.translate()
  File "/usr/lib/python3.8/site-packages/sphinx/writers/manpage.py", line 39, in translate
    self.document.walkabout(visitor)
  File "/usr/lib/python3.8/site-packages/docutils/nodes.py", line 227, in walkabout
    if child.walkabout(visitor):
  File "/usr/lib/python3.8/site-packages/docutils/nodes.py", line 227, in walkabout
    if child.walkabout(visitor):
  File "/usr/lib/python3.8/site-packages/docutils/nodes.py", line 227, in walkabout
    if child.walkabout(visitor):
  [Previous line repeated 2 more times]
  File "/usr/lib/python3.8/site-packages/docutils/nodes.py", line 219, in walkabout
    visitor.dispatch_visit(self)
  File "/usr/lib/python3.8/site-packages/sphinx/util/docutils.py", line 480, in dispatch_visit
    super().dispatch_visit(node)
  File "/usr/lib/python3.8/site-packages/docutils/nodes.py", line 2021, in dispatch_visit
    return method(node)
  File "/usr/lib/python3.8/site-packages/sphinx/writers/manpage.py", line 467, in unknown_visit
    raise NotImplementedError('Unknown node: ' + node.__class__.__name__)
NotImplementedError: Unknown node: Hazmat
```

**Comment by reaperhulk** [comment]
Building through setup.py is not a supported method of building our docs. See https://github.com/pyca/cryptography/blob/main/tox.ini#L33 for how we build in CI.

**Comment by kloczek** [comment]
It fails as well over tox.

**Comment by kloczek** [comment]
Other thing is that in tox are hardcoded output formats which I don't need.
I need man page.
