### ISSUE TITLE
36.0.0: cryptography sphinx ext do not support man output

### ISSUE THREAD

**Issue by kloczek** [pyca/cryptography#6680]
Looks like cryptography sphinx ext (docs/_ext)m do not support man output.
```console
[tkloczko@ss-desktop cryptography-36.0.0]$ sphinx-build -T -W -b man docs docs/_build/html
Running Sphinx v4.3.1
Initializing Spelling Checker 7.2.1
loading intersphinx inventory from https://docs.python.org/3/objects.inv...
building [mo]: targets for 0 po files that are out of date
building [man]: all manpages
updating environment: [new config] 56 added, 0 changed, 0 removed
reading sources... [100%] x509/tutorial
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
writing... python-cryptography.3 { fernet x509/index x509/tutorial x509/certificate-transparency x509/ocsp x509/reference hazmat/primitives/index hazmat/primitives/aead hazmat/primitives/asymmetric/index hazmat/primitives/asymmetric/ed25519 hazmat/primitives/asymmetric/x25519 hazmat/primitives/asymmetric/ed448 hazmat/primitives/asymmetric/x448 hazmat/primitives/asymmetric/ec hazmat/primitives/asymmetric/rsa hazmat/primitives/asymmetric/dh hazmat/primitives/asymmetric/dsa hazmat/primitives/asymmetric/serialization hazmat/primitives/asymmetric/utils hazmat/primitives/constant-time hazmat/primitives/key-derivation-functions hazmat/primitives/keywrap hazmat/primitives/mac/index hazmat/primitives/mac/cmac hazmat/primitives/mac/hmac hazmat/primitives/mac/poly1305 hazmat/primitives/cryptographic-hashes hazmat/primitives/symmetric-encryption hazmat/primitives/padding hazmat/primitives/twofactor exceptions random-numbers installation changelog faq development/index development/getting-started development/submitting-patches development/reviewing-patches development/test-vectors development/custom-vectors/secp256k1 development/custom-vectors/rsa-oaep-sha2 development/custom-vectors/arc4 development/custom-vectors/cast5 development/custom-vectors/idea development/custom-vectors/seed development/custom-vectors/hkdf development/c-bindings openssl security limitations api-stability doing-a-release community glossary } failed

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/sphinx/cmd/build.py", line 280, in build_main
    app.build(args.force_all, filenames)
  File "/usr/lib/python3.8/site-packages/sphinx/application.py", line 344, in build
    self.builder.build_update()
  File "/usr/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 291, in build_update
    self.build(['__all__'], to_build)
  File "/usr/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 358, in build
    self.write(docnames, list(updated_docnames), method)
  File "/usr/lib/python3.8/site-packages/sphinx/util/__init__.py", line 547, in wrapper
    return f(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/sphinx/builders/manpage.py", line 104, in write
    docwriter.write(largetree, destination)
  File "/usr/lib/python3.8/site-packages/docutils/writers/__init__.py", line 78, in write
    self.translate()
  File "/usr/lib/python3.8/site-packages/sphinx/writers/manpage.py", line 39, in translate
    self.document.walkabout(visitor)
  File "/usr/lib/python3.8/site-packages/docutils/nodes.py", line 227, in walkabout
    if child.walkabout(visitor):
  File "/usr/lib/python3.8/site-packages/docutils/nodes.py", line 227, in walkabout
    if child.walkabout(visitor):
  File "/usr/lib/python3.8/site-packages/docutils/nodes.py", line 227, in walkabout
    if child.walkabout(visitor):
  [Previous line repeated 2 more times]
  File "/usr/lib/python3.8/site-packages/docutils/nodes.py", line 219, in walkabout
    visitor.dispatch_visit(self)
  File "/usr/lib/python3.8/site-packages/sphinx/util/docutils.py", line 480, in dispatch_visit
    super().dispatch_visit(node)
  File "/usr/lib/python3.8/site-packages/docutils/nodes.py", line 2021, in dispatch_visit
    return method(node)
  File "/usr/lib/python3.8/site-packages/sphinx/writers/manpage.py", line 467, in unknown_visit
    raise NotImplementedError('Unknown node: ' + node.__class__.__name__)
NotImplementedError: Unknown node: Hazmat

Exception occurred:
  File "/usr/lib/python3.8/site-packages/sphinx/writers/manpage.py", line 467, in unknown_visit
    raise NotImplementedError('Unknown node: ' + node.__class__.__name__)
NotImplementedError: Unknown node: Hazmat
The full traceback has been saved in /tmp/sphinx-err-l3f_n7v5.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
```
```console
[tkloczko@ss-desktop cryptography-36.0.0]$ cat /tmp/sphinx-err-l3f_n7v5.log
# Sphinx version: 4.3.1
# Python version: 3.8.12 (CPython)
# Docutils version: 0.17.1 release
# Jinja2 version: 3.0.3
# Last messages:
#   development/c-bindings
#   openssl
#   security
#   limitations
#   api-stability
#   doing-a-release
#   community
#   glossary
#   }
#   failed
# Loaded extensions:
#   sphinx.ext.mathjax (4.3.1) from /usr/lib/python3.8/site-packages/sphinx/ext/mathjax.py
#   sphinxcontrib.applehelp (1.0.2) from /usr/lib/python3.8/site-packages/sphinxcontrib/applehelp/__init__.py
#   sphinxcontrib.devhelp (1.0.2) from /usr/lib/python3.8/site-packages/sphinxcontrib/devhelp/__init__.py
#   sphinxcontrib.htmlhelp (2.0.0) from /usr/lib/python3.8/site-packages/sphinxcontrib/htmlhelp/__init__.py
#   sphinxcontrib.serializinghtml (1.1.5) from /usr/lib/python3.8/site-packages/sphinxcontrib/serializinghtml/__init__.py
#   sphinxcontrib.qthelp (1.0.3) from /usr/lib/python3.8/site-packages/sphinxcontrib/qthelp/__init__.py
#   alabaster (0.7.12) from /usr/lib/python3.8/site-packages/alabaster/__init__.py
#   sphinx.ext.autodoc.preserve_defaults (1.0) from /usr/lib/python3.8/site-packages/sphinx/ext/autodoc/preserve_defaults.py
#   sphinx.ext.autodoc.type_comment (4.3.1) from /usr/lib/python3.8/site-packages/sphinx/ext/autodoc/type_comment.py
#   sphinx.ext.autodoc (4.3.1) from /usr/lib/python3.8/site-packages/sphinx/ext/autodoc/__init__.py
#   sphinx.ext.doctest (4.3.1) from /usr/lib/python3.8/site-packages/sphinx/ext/doctest.py
#   sphinx.ext.intersphinx (4.3.1) from /usr/lib/python3.8/site-packages/sphinx/ext/intersphinx.py
#   sphinx.ext.linkcode (4.3.1) from /usr/lib/python3.8/site-packages/sphinx/ext/linkcode.py
#   cryptography-docs (unknown version) from /home/tkloczko/rpmbuild/BUILD/cryptography-36.0.0/docs/_ext/cryptography-docs.py
#   sphinxcontrib.spelling (7.2.1) from /usr/lib/python3.8/site-packages/sphinxcontrib/spelling/__init__.py
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/sphinx/cmd/build.py", line 280, in build_main
    app.build(args.force_all, filenames)
  File "/usr/lib/python3.8/site-packages/sphinx/application.py", line 344, in build
    self.builder.build_update()
  File "/usr/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 291, in build_update
    self.build(['__all__'], to_build)
  File "/usr/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 358, in build
    self.write(docnames, list(updated_docnames), method)
  File "/usr/lib/python3.8/site-packages/sphinx/util/__init__.py", line 547, in wrapper
    return f(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/sphinx/builders/manpage.py", line 104, in write
    docwriter.write(largetree, destination)
  File "/usr/lib/python3.8/site-packages/docutils/writers/__init__.py", line 78, in write
    self.translate()
  File "/usr/lib/python3.8/site-packages/sphinx/writers/manpage.py", line 39, in translate
    self.document.walkabout(visitor)
  File "/usr/lib/python3.8/site-packages/docutils/nodes.py", line 227, in walkabout
    if child.walkabout(visitor):
  File "/usr/lib/python3.8/site-packages/docutils/nodes.py", line 227, in walkabout
    if child.walkabout(visitor):
  File "/usr/lib/python3.8/site-packages/docutils/nodes.py", line 227, in walkabout
    if child.walkabout(visitor):
  [Previous line repeated 2 more times]
  File "/usr/lib/python3.8/site-packages/docutils/nodes.py", line 219, in walkabout
    visitor.dispatch_visit(self)
  File "/usr/lib/python3.8/site-packages/sphinx/util/docutils.py", line 480, in dispatch_visit
    super().dispatch_visit(node)
  File "/usr/lib/python3.8/site-packages/docutils/nodes.py", line 2021, in dispatch_visit
    return method(node)
  File "/usr/lib/python3.8/site-packages/sphinx/writers/manpage.py", line 467, in unknown_visit
    raise NotImplementedError('Unknown node: ' + node.__class__.__name__)
NotImplementedError: Unknown node: Hazmat
```
At the same time for exemplerendering html output is fine
```console
[tkloczko@ss-desktop cryptography-36.0.0]$ sphinx-build -T -W -b html docs docs/_build/html
Running Sphinx v4.3.1
Initializing Spelling Checker 7.2.1
loading intersphinx inventory from https://docs.python.org/3/objects.inv...
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 56 source files that are out of date
updating environment: [new config] 56 added, 0 changed, 0 removed
reading sources... [100%] x509/tutorial
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
preparing documents... done
writing output... [100%] x509/tutorial
generating indices... genindex py-modindex done
writing additional pages... search done
copying downloadable files... [100%] development/custom-vectors/seed/verify_seed.py
copying static files... done
copying extra files... done
dumping search index in English (code: en)... done
dumping object inventory... done
build succeeded.

The HTML pages are in docs/_build/html.
```

**Comment by kloczek** [comment]
No it doesn't.
I've already reported that issue buit now I've spent a bit more time on diagnose that issue and looks cryptography sphinx ext uses `Hazmat` as keyword.
```console
[tkloczko@ss-desktop docs]$ grep -r Hazmat
_ext/cryptography-docs.py:class HazmatDirective(Directive):
_ext/cryptography-docs.py:        admonition_node = Hazmat("\n".join(content))
_ext/cryptography-docs.py:class Hazmat(nodes.Admonition, nodes.Element):
_ext/cryptography-docs.py:        Hazmat,
_ext/cryptography-docs.py:    app.add_directive("hazmat", HazmatDirective)
security.rst:* Offering ECB mode for symmetric encryption in the *Hazmat* layer. Though ECB
```

**Comment by alexdotgov** [comment]
(Commenting from my work account)

I assume this is a result of our usage of a sphinx extension. I don't know anything about the `man` builder or why I wouldn't support them.

We'd be happy to accept a patch to get `man` support working (assuming it's not too invasive/large), however we're not going to do the work ourselves, as none of us consume these docs in `man` format.

**Comment by reaperhulk** [comment]
No activity here for 4 months so closing. We're still happy to take a patch if someone wants to do the work! 😄
