### ISSUE TITLE
Failure parsing OCSP requests

### ISSUE THREAD

**Issue by pepone** [pyca/cryptography#6688]
The request comes from macOS SecureTransport SSL engine

```
DATA: ME4wTKADAgEAMEUwQzBBMAkGBSsOAwIaBQAEFP4rCoFXQt2cj3BLS7kzmybo6ooGBBT+K37KwbI8oa/jVsockF8ik3PMuwIId8nvsPlcQgc=
Traceback (most recent call last):
  File "/Users/vagrant/workspace/ice/3.7/scripts/tests/IceSSL/revocationutil.py", line 101, in validate
    request = ocsp.load_der_ocsp_request(data)
  File "/Users/vagrant/Library/Python/3.9/lib/python/site-packages/cryptography/x509/ocsp.py", line 479, in load_der_ocsp_request
    return ocsp.load_der_ocsp_request(data)
ValueError: error parsing asn1 value: ParseError { kind: EncodedDefault, location: ["RawOCSPRequest::tbs_request", "TBSRequest::version"] }
```
cffi               1.15.0
cryptography       36.0.0
pip                21.3.1
setuptools         59.0.1
Python 3.9.9 
macOS x86_64

**Comment by pepone** [comment]
You can reproduce with 

```
from cryptography.x509 import ocsp
import base64

data = base64.b64decode("ME4wTKADAgEAMEUwQzBBMAkGBSsOAwIaBQAEFP4rCoFXQt2cj3BLS7kzmybo6ooGBBT+K37KwbI8oa/jVsockF8ik3PMuwIId8nvsPlcQgc=")
ocsp.load_der_ocsp_request(data)
```

This fails with 35.0.0 and 36.0.0 but works with 3.4.8

**Comment by alex** [comment]
welp.

this doesn't conform to the RFC, because DER defaults are never supposed to be encoded.

What version of macOS produces these, we'll need to report to the Apple team, before we'd even consider working around it.

**Comment by sleevi** [comment]
The bug is in https://github.com/apple-oss-distributions/Security/blob/14c93f1a06247f59871ab1b9542d1e722f903abc/trust/trustd/SecOCSPRequest.c#L109 and it looks like it’s survived many refactorings, so effectively “all” releases.

The issue is it should be `nullptr`/`NULL` if the default value, as `SecASN` doesn’t know about defaults, or how to omit them.

Note, a similar issue exists around https://github.com/apple-oss-distributions/Security/blob/14c93f1a06247f59871ab1b9542d1e722f903abc/trust/trustd/SecOCSPRequest.c#L86-89 with respect to default params for SHA-1

**Comment by reaperhulk** [comment]
This has been reported through a few channels. Let's see what macOS 12.2 brings... 😄

**Comment by alex** [comment]
It's my understanding that macOS 12.4, released today should have fixed the OCSP requests generated. Is anyone able to confirm?

**Comment by alex** [comment]
err, 12.3

**Comment by reaperhulk** [comment]
No activity here and it's our understanding that macOS has fixed the bug going forward so closing for now. If someone runs into this with macOS 12.3+ or another fully patched tool please open a new issue.
