### ISSUE TITLE
ImportError: /usr/local/lib/python3.7/site-packages/cryptography/hazmat/bindings/_rust.abi3.so: undefined symbol: PyModule_Create2

### ISSUE THREAD

**Issue by kevin0107** [pyca/cryptography#6813]
compile python 3.7.9 --with-pydebug manual in Dockerfile.

`pip install pyopenssl`

test.py
`import OpenSSL
`
```
root@5f1fba5624a0:/# python test.py 
Traceback (most recent call last):
  File "test.py", line 1, in <module>
    import OpenSSL
  File "/usr/local/lib/python3.7/site-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import crypto, SSL
  File "/usr/local/lib/python3.7/site-packages/OpenSSL/crypto.py", line 14, in <module>
    from cryptography import utils, x509
  File "/usr/local/lib/python3.7/site-packages/cryptography/x509/__init__.py", line 6, in <module>
    from cryptography.x509 import certificate_transparency
  File "/usr/local/lib/python3.7/site-packages/cryptography/x509/certificate_transparency.py", line 10, in <module>
    from cryptography.hazmat.bindings._rust import x509 as rust_x509
ImportError: /usr/local/lib/python3.7/site-packages/cryptography/hazmat/bindings/_rust.abi3.so: undefined symbol: PyModule_Create2


```

**Comment by alex** [comment]
Please provide instructions for reproducing.

**Comment by alex** [comment]
It seems likely to me that your problem is that you're using a cryptography compiled for the system python and then trying to use it with the debug python you built.

**Comment by kevin0107** [comment]
i build cryptography 
`python setup.py build`

then, use gen _rust.abi3.so replace /usr/local/lib/python3.7/site-packages/cryptography/hazmat/bindings/_rust.abi3.so

get same error 

is there any build args should change ？

**Comment by alex** [comment]
These instructions are not complete. `python setup.py build` would not touch `/usr/local`. Please provide _complete_ instructions, starting from a fresh linux distribution.

**Comment by kevin0107** [comment]
Q：python multi-threads locked, use gdb debug threads, get "frame information optimized out"

i use gdb for detail frame

1：build python --with-pydebug from python3.7.9 Dockerfile
[Dockerfile.txt](https://github.com/pyca/cryptography/files/7946823/Dockerfile.txt)
```shell
make python-build
cd python-build
mv Dockerfile.txt Dockerfile
docker build  -t python-debug:1.0 .
```

2：run docker and install pyopenssl
```shell
docker run -it --rm python-debug:1.0 /bin/bash
pip install pyopenssl
```

3：run python and import OpenSSL
```python
import OpenSSL
```

4：ERROR message
```
oot@d1995b012961:/# python
Python 3.7.9 (default, Jan 19 2022, 08:51:32) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import OpenSSL
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/site-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import crypto, SSL
  File "/usr/local/lib/python3.7/site-packages/OpenSSL/crypto.py", line 14, in <module>
    from cryptography import utils, x509
  File "/usr/local/lib/python3.7/site-packages/cryptography/x509/__init__.py", line 6, in <module>
    from cryptography.x509 import certificate_transparency
  File "/usr/local/lib/python3.7/site-packages/cryptography/x509/certificate_transparency.py", line 10, in <module>
    from cryptography.hazmat.bindings._rust import x509 as rust_x509
ImportError: /usr/local/lib/python3.7/site-packages/cryptography/hazmat/bindings/_rust.abi3.so: undefined symbol: PyModule_Create2
>>> 
```

5：as you said，i build cryptography from source
```
git clone https://github.com/pyca/cryptography.git
cd cryptography
python setup.py build
```

6：use gen _rust.abi3.so replace /usr/local/lib/python3.7/site-packages/cryptography/hazmat/bindings/_rust.abi3.so
```
mv /usr/local/lib/python3.7/site-packages/cryptography/hazmat/bindings/_rust.abi3.so /usr/local/lib/python3.7/site-packages/cryptography/hazmat/bindings/_rust.abi3.so_bak
mv _rust.abi3.so /usr/local/lib/python3.7/site-packages/cryptography/hazmat/bindings/
```

7：ERROR message
```
root@965447fb4fd4:/# python
Python 3.7.9 (default, Jan 19 2022, 08:51:32) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import OpenSSL
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/site-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import crypto, SSL
  File "/usr/local/lib/python3.7/site-packages/OpenSSL/crypto.py", line 14, in <module>
    from cryptography import utils, x509
  File "/usr/local/lib/python3.7/site-packages/cryptography/x509/__init__.py", line 6, in <module>
    from cryptography.x509 import certificate_transparency
  File "/usr/local/lib/python3.7/site-packages/cryptography/x509/certificate_transparency.py", line 10, in <module>
    from cryptography.hazmat.bindings._rust import x509 as rust_x509
ImportError: /usr/local/lib/python3.7/site-packages/cryptography/hazmat/bindings/_rust.abi3.so: undefined symbol: PyModule_Create2
>>>
```

**Comment by tiran** [comment]
Python 3.7 debug builds have a different ABI than Python 3.7 standard builds. You cannot reuse a shared extension from a standard build in a 3.7 debug build. You have to recompile all extensions with your debug Python interpreter.

The problem has been fixed in Python 3.8 for debug builds without ref tracing, https://docs.python.org/3/whatsnew/3.8.html#debug-build-uses-the-same-abi-as-release-build

**Comment by tiran** [comment]
PS: A stable abi3 extension modules might not work in debug mode when the extension uses cp36 or cp37 ABI. It may only work for cp38-abi3 builds or newer.

**Comment by kevin0107** [comment]
Use python 3.9.2, get detail frame info
