### ISSUE TITLE
Parse Error in ASN1.value when attempting to access CertificateSigningRequest.extension. 

### ISSUE THREAD

**Issue by sanchayanghosh** [pyca/cryptography#6926]
If you're filing a bug (as opposed to a feature request), please try the
following things:

* Check the FAQ to see if your issue is covered there:
  https://cryptography.io/en/latest/faq.html
* Upgrade to the latest version of ``setuptools`` and ``pip``
* Make sure you're on a supported version of OpenSSL
* Try with the latest version of ``cryptography``
* Be sure you have the required compilers (both a C compiler and Rust)
  installed if you aren't using the binary wheels.

If none of that works, please make sure to include the following information in
your bug report:

* Versions of Python, ``cryptography``, ``cffi``, ``pip``, and ``setuptools``
  you're using
* How you installed ``cryptography``
* Clear steps for reproducing your bug

Please do not report security issues on Github! Follow the instructions in our
documentation for reporting security issues:
https://cryptography.io/en/latest/security.htm

Currently when attemtping to access certificatesigningrequest.extension, we get 

ParseError: Error in ASN.1 parsing {kind: ShortData}

However, according to documenation we expect to see - the Extensions in their entirety.

The reason for the fix here:

1. For a script/function that would vet the CSR's extensions to see which ones should be included and which ones should not, we would need to be able to parse the extensions. Eg. CSR has been signed requesting for ServerAuth KeyUsage, or data_encipherment. But the CA, would want to verify if that is truly needed or not, and would reject the CSR if not correct.
2. Also, to more align with the documenation that would return the extensions object.

Prior related issues; #6872 

In #6872 the Certificate.extensions was not accessible due to the parse error. However, in this case, we have a valid scenario where we may need to access the extensions for the CertificateSigningRequest, even if for tallying the extensions themselves. For example, when we get a csr from an external entity, and we would want to tally the extensions after loading it into the python program using load_csr

**Comment by reaperhulk** [comment]
Do you see this issue if you compile our `main` branch and test against that? Do you have an example CSR you can share that exhibits this problem?

**Comment by sanchayanghosh** [comment]
We have a concerning issue with cryptography. The project source is refactored (cryptography.hazmat.bindings._openssl) to another locaiton. So, after building the latest main branch of cryptography, I now get this problem:
```

[root@581cda299512 cryptopart]# python test_cert.py 
Traceback (most recent call last):
  File "/python-src/cryptopart/test_cert.py", line 13, in <module>
    key = generate_private_key(SECP384R1())
  File "/usr/lib/python3.10/site-packages/cryptography-37.0.0.dev1-py3.10-linux-x86_64.egg/cryptography/hazmat/primitives/asymmetric/ec.py", line 323, in generate_private_key
    from cryptography.hazmat.backends.openssl.backend import backend as ossl
  File "/usr/lib/python3.10/site-packages/cryptography-37.0.0.dev1-py3.10-linux-x86_64.egg/cryptography/hazmat/backends/openssl/__init__.py", line 6, in <module>
    from cryptography.hazmat.backends.openssl.backend import backend
  File "/usr/lib/python3.10/site-packages/cryptography-37.0.0.dev1-py3.10-linux-x86_64.egg/cryptography/hazmat/backends/openssl/backend.py", line 63, in <module>
    from cryptography.hazmat.bindings.openssl import binding
  File "/usr/lib/python3.10/site-packages/cryptography-37.0.0.dev1-py3.10-linux-x86_64.egg/cryptography/hazmat/bindings/openssl/binding.py", line 14, in <module>
    from cryptography.hazmat.bindings._openssl import ffi, lib
ModuleNotFoundError: No module named 'cryptography.hazmat.bindings._openssl'
[root@581cda299512 cryptopart]# 
```
The unit test file is - 
```

[root@581cda299512 cryptopart]# cat test_cert.py t
from cryptography.x509.oid import ExtendedKeyUsageOID
from cryptography.hazmat.primitives.asymmetric.rsa import generate_private_key, RSAPrivateKey

from cryptography.x509.base import CertificateBuilder, CertificateSigningRequest
from cryptography import x509
from cryptography.x509.oid import NameOID
import datetime
from cryptography.hazmat.primitives import hashes
from cryptography.hazmat.primitives.hashes import SHA256
from cryptography.hazmat.primitives.asymmetric.ec import generate_private_key, SECP384R1
from cryptography.hazmat.primitives.serialization import Encoding

key = generate_private_key(SECP384R1())


csr_b = x509.CertificateSigningRequestBuilder().subject_name(x509.Name([

    # Provide various details about who we are.

    x509.NameAttribute(NameOID.COUNTRY_NAME, u"US"),

    x509.NameAttribute(NameOID.STATE_OR_PROVINCE_NAME, u"California"),

    x509.NameAttribute(NameOID.LOCALITY_NAME, u"San Francisco"),

    x509.NameAttribute(NameOID.ORGANIZATION_NAME, u"My Company"),

    x509.NameAttribute(NameOID.COMMON_NAME, u"mysite.com"),

])).add_extension(

    x509.SubjectAlternativeName([

        # Describe what sites we want this certificate for.

        x509.DNSName(u"mysite.com"),

        x509.DNSName(u"www.mysite.com"),

        x509.DNSName(u"subdomain.mysite.com"),

    ]),

    critical=False,

# Sign the CSR with our private key.

).sign(key, hashes.SHA256())

csr_b.extensions()

# Write our CSR out to disk.

with open("csr.pem", "wb") as f:

    f.write(csr.public_bytes(serialization.Encoding.PEM))

```

I copied this unit test from the tutorial - [here](https://cryptography.io/en/latest/x509/tutorial/)

**Comment by alex** [comment]
This script doesn't actually run, it's got a number of issues. However, if I fix those then it runs to completion without error.

Are you saying that this script generates the `ValueError` you originally described?

**Comment by sanchayanghosh** [comment]
Sorry for the wrong snippet. I forgot to include a significant parameter I have set up.
```

[root@581cda299512 cryptopart]# vim test_cert.py 
[root@581cda299512 cryptopart]# python3.11 test_cert.py 
Traceback (most recent call last):
  File "/python-src/cryptopart/test_cert.py", line 66, in <module>
    print(csr_b.extensions)
          ^^^^^^^^^^^^^^^^
ValueError: error parsing asn1 value: ParseError { kind: ShortData }
[root@581cda299512 cryptopart]# vim test_cert.py 
[root@581cda299512 cryptopart]# vim test_cert.py 
[root@581cda299512 cryptopart]# python3.11 test_cert.py 
Traceback (most recent call last):
  File "/python-src/cryptopart/test_cert.py", line 66, in <module>
    print(csr_b.extensions)
          ^^^^^^^^^^^^^^^^
ValueError: error parsing asn1 value: ParseError { kind: ShortData }
[root@581cda299512 cryptopart]# cat test_cert.py 
from cryptography.x509.oid import ExtendedKeyUsageOID
from cryptography.hazmat.primitives.asymmetric.rsa import generate_private_key, RSAPrivateKey

from cryptography.x509.base import CertificateBuilder, CertificateSigningRequest
from cryptography import x509
from cryptography.x509.oid import NameOID
import datetime
from cryptography.hazmat.primitives import hashes
from cryptography.hazmat.primitives.hashes import SHA256
from cryptography.hazmat.primitives.asymmetric.ec import generate_private_key, SECP384R1
from cryptography.hazmat.primitives.serialization import Encoding
import ipaddress
from cryptography.hazmat.primitives import serialization

key = generate_private_key(SECP384R1())


csr_b = x509.CertificateSigningRequestBuilder().subject_name(x509.Name([

    # Provide various details about who we are.

    x509.NameAttribute(NameOID.COUNTRY_NAME, u"US"),

    x509.NameAttribute(NameOID.STATE_OR_PROVINCE_NAME, u"California"),

    x509.NameAttribute(NameOID.LOCALITY_NAME, u"San Francisco"),

    x509.NameAttribute(NameOID.ORGANIZATION_NAME, u"My Company"),

    x509.NameAttribute(NameOID.COMMON_NAME, u"mysite.com"),

])).add_extension(

    x509.SubjectAlternativeName([

        # Describe what sites we want this certificate for.

        x509.DNSName(u"mysite.com"),

        x509.DNSName(u"www.mysite.com"),

        x509.DNSName(u"subdomain.mysite.com"),

        x509.IPAddress(ipaddress.IPv4Address("10.220.224.47"))
    ]),

    critical=False,

# Sign the CSR with our private key.

).add_extension(

x509.ExtendedKeyUsage(
    [
        ExtendedKeyUsageOID.IPSEC_IKE
    ]

    ), critical=False

).add_extension(
        x509.KeyUsage(
            False,False,False,False,False,False,False,False,False
            ), critical=True
        ).sign(key, hashes.SHA256())

print(csr_b.extensions)

# Write our CSR out to disk.

with open("csr.pem", "wb") as f:

    f.write(csr_b.public_bytes(serialization.Encoding.PEM))


```

The KeyUsage parameter causes this.

**Comment by alex** [comment]
Minimized reproducer:

```
from cryptography import x509
from cryptography.hazmat.primitives import hashes
from cryptography.hazmat.primitives.asymmetric import ec

key = ec.generate_private_key(ec.SECP384R1())


csr_b = (
    x509.CertificateSigningRequestBuilder()
    .subject_name(x509.Name([]))
    .add_extension(
        x509.KeyUsage(
            False, False, False, False, False, False, False, False, False
        ),
        critical=True,
    )
    .sign(key, hashes.SHA256())
)

print(csr_b.extensions)
```

**Comment by alex** [comment]
ok, PR submitted to fix this. thanks for the clear report!

**Comment by sanchayanghosh** [comment]
@alex 
Thanks so much for the speedy fix! It works without errors now!
