### ISSUE TITLE
Cannot install on OS X (v0.2.1)

### ISSUE THREAD

**Issue by danielfrg** [pyca/cryptography#693]
Trying to install the last version of `pyOpesSSL v0.14` gives the error below when installing `cryptography==0.2.1`. Installing `pyOpenSSL==0.13` is working fine.

I followed instructions [here](https://cryptography.io/en/latest/installation/#using-your-own-openssl-on-os-x) without luck. Running: `env ARCHFLAGS="-arch x86_64" LDFLAGS="-L/usr/local/opt/openssl/lib" CFLAGS="-I/usr/local/opt/openssl/include" pip install cryptography` gives me this below.

More info: OS X mavericks - gcc version:

```
gcc --version
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 5.0 (clang-500.2.79) (based on LLVM 3.3svn)
Target: x86_64-apple-darwin13.0.0
Thread model: posix
```

Error:

```
Downloading/unpacking cryptography
  Downloading cryptography-0.2.1.tar.gz (13.8MB): 13.8MB downloaded
  Running setup.py (path:/private/var/folders/ds/qbtlskm523g_kmf8bzshxsgh0000gn/T/pip_build_danielfrg/cryptography/setup.py) egg_info for package cryptography
    Package libffi was not found in the pkg-config search path.
    Perhaps you should add the directory containing `libffi.pc'
    to the PKG_CONFIG_PATH environment variable
    No package 'libffi' found
    Package libffi was not found in the pkg-config search path.
    Perhaps you should add the directory containing `libffi.pc'
    to the PKG_CONFIG_PATH environment variable
    No package 'libffi' found
    Package libffi was not found in the pkg-config search path.
    Perhaps you should add the directory containing `libffi.pc'
    to the PKG_CONFIG_PATH environment variable
    No package 'libffi' found
    Package libffi was not found in the pkg-config search path.
    Perhaps you should add the directory containing `libffi.pc'
    to the PKG_CONFIG_PATH environment variable
    No package 'libffi' found
    Package libffi was not found in the pkg-config search path.
    Perhaps you should add the directory containing `libffi.pc'
    to the PKG_CONFIG_PATH environment variable
    No package 'libffi' found
    c/check__thread.c:1:1: error: thread-local storage is unsupported for the current target
    __thread int some_threadlocal_variable_42;
    ^
    1 error generated.
    the above error message can be safely ignored;
    will not use '__thread' in the C code

    Installed /private/var/folders/ds/qbtlskm523g_kmf8bzshxsgh0000gn/T/pip_build_danielfrg/cryptography/cffi-0.8.1-py2.7-macosx-10.5-x86_64.egg
    Searching for pycparser
    Reading https://pypi.python.org/simple/pycparser/
    Best match: pycparser 2.10
    Downloading https://pypi.python.org/packages/source/p/pycparser/pycparser-2.10.tar.gz#md5=d87aed98c8a9f386aa56d365fe4d515f
    Processing pycparser-2.10.tar.gz
    Writing /var/folders/ds/qbtlskm523g_kmf8bzshxsgh0000gn/T/easy_install-OuwG0l/pycparser-2.10/setup.cfg
    Running pycparser-2.10/setup.py -q bdist_egg --dist-dir /var/folders/ds/qbtlskm523g_kmf8bzshxsgh0000gn/T/easy_install-OuwG0l/pycparser-2.10/egg-dist-tmp-nTEnU9
    zip_safe flag not set; analyzing archive contents...

    Installed /private/var/folders/ds/qbtlskm523g_kmf8bzshxsgh0000gn/T/pip_build_danielfrg/cryptography/pycparser-2.10-py2.7.egg

    building '_cffi__xcfd0a060xfba2f231' extension
    gcc -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/usr/local/opt/openssl/include -arch x86_64 -I/Users/danielfrg/anaconda/envs/ocu-backend/include/python2.7 -c cryptography/hazmat/primitives/__pycache__/_cffi__xcfd0a060xfba2f231.c -o /private/var/folders/ds/qbtlskm523g_kmf8bzshxsgh0000gn/T/pip_build_danielfrg/cryptography/cryptography/hazmat/primitives/__pycache__/cryptography/hazmat/primitives/__pycache__/_cffi__xcfd0a060xfba2f231.o
    gcc -bundle -undefined dynamic_lookup -L/Users/danielfrg/anaconda/envs/ocu-backend/lib -L/usr/local/opt/openssl/lib -I/usr/local/opt/openssl/include -arch x86_64 -arch x86_64 /private/var/folders/ds/qbtlskm523g_kmf8bzshxsgh0000gn/T/pip_build_danielfrg/cryptography/cryptography/hazmat/primitives/__pycache__/cryptography/hazmat/primitives/__pycache__/_cffi__xcfd0a060xfba2f231.o -L/Users/danielfrg/anaconda/envs/ocu-backend/lib -o /private/var/folders/ds/qbtlskm523g_kmf8bzshxsgh0000gn/T/pip_build_danielfrg/cryptography/cryptography/hazmat/primitives/__pycache__/_cffi__xcfd0a060xfba2f231.so
    building '_cffi__x5fea2bacx4a8b9ec1' extension
    gcc -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/usr/local/opt/openssl/include -arch x86_64 -I/Users/danielfrg/anaconda/envs/ocu-backend/include/python2.7 -c cryptography/hazmat/primitives/__pycache__/_cffi__x5fea2bacx4a8b9ec1.c -o /private/var/folders/ds/qbtlskm523g_kmf8bzshxsgh0000gn/T/pip_build_danielfrg/cryptography/cryptography/hazmat/primitives/__pycache__/cryptography/hazmat/primitives/__pycache__/_cffi__x5fea2bacx4a8b9ec1.o
    gcc -bundle -undefined dynamic_lookup -L/Users/danielfrg/anaconda/envs/ocu-backend/lib -L/usr/local/opt/openssl/lib -I/usr/local/opt/openssl/include -arch x86_64 -arch x86_64 /private/var/folders/ds/qbtlskm523g_kmf8bzshxsgh0000gn/T/pip_build_danielfrg/cryptography/cryptography/hazmat/primitives/__pycache__/cryptography/hazmat/primitives/__pycache__/_cffi__x5fea2bacx4a8b9ec1.o -L/Users/danielfrg/anaconda/envs/ocu-backend/lib -o /private/var/folders/ds/qbtlskm523g_kmf8bzshxsgh0000gn/T/pip_build_danielfrg/cryptography/cryptography/hazmat/primitives/__pycache__/_cffi__x5fea2bacx4a8b9ec1.so
    building '_cffi__x9ee276ddxb4fc9075' extension
    gcc -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/usr/local/opt/openssl/include -arch x86_64 -I/Users/danielfrg/anaconda/envs/ocu-backend/include/python2.7 -c cryptography/hazmat/bindings/__pycache__/_cffi__x9ee276ddxb4fc9075.c -o /private/var/folders/ds/qbtlskm523g_kmf8bzshxsgh0000gn/T/pip_build_danielfrg/cryptography/cryptography/hazmat/bindings/__pycache__/cryptography/hazmat/bindings/__pycache__/_cffi__x9ee276ddxb4fc9075.o
    gcc -bundle -undefined dynamic_lookup -L/Users/danielfrg/anaconda/envs/ocu-backend/lib -L/usr/local/opt/openssl/lib -I/usr/local/opt/openssl/include -arch x86_64 -arch x86_64 /private/var/folders/ds/qbtlskm523g_kmf8bzshxsgh0000gn/T/pip_build_danielfrg/cryptography/cryptography/hazmat/bindings/__pycache__/cryptography/hazmat/bindings/__pycache__/_cffi__x9ee276ddxb4fc9075.o -L/Users/danielfrg/anaconda/envs/ocu-backend/lib -lcrypto -lssl -o /private/var/folders/ds/qbtlskm523g_kmf8bzshxsgh0000gn/T/pip_build_danielfrg/cryptography/cryptography/hazmat/bindings/__pycache__/_cffi__x9ee276ddxb4fc9075.so
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/private/var/folders/ds/qbtlskm523g_kmf8bzshxsgh0000gn/T/pip_build_danielfrg/cryptography/setup.py", line 113, in <module>
        "build": cffi_build,
      File "/Users/danielfrg/anaconda/envs/ocu-backend/lib/python2.7/distutils/core.py", line 152, in setup
        dist.run_commands()
      File "/Users/danielfrg/anaconda/envs/ocu-backend/lib/python2.7/distutils/dist.py", line 953, in run_commands
        self.run_command(cmd)
      File "/Users/danielfrg/anaconda/envs/ocu-backend/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "<string>", line 15, in replacement_run
      File "build/bdist.macosx-10.5-x86_64/egg/setuptools/command/egg_info.py", line 186, in find_sources
      File "build/bdist.macosx-10.5-x86_64/egg/setuptools/command/egg_info.py", line 246, in run
      File "build/bdist.macosx-10.5-x86_64/egg/setuptools/command/egg_info.py", line 282, in add_defaults
      File "build/bdist.macosx-10.5-x86_64/egg/setuptools/command/sdist.py", line 167, in add_defaults
      File "/Users/danielfrg/anaconda/envs/ocu-backend/lib/python2.7/distutils/cmd.py", line 312, in get_finalized_command
        cmd_obj.ensure_finalized()
      File "/Users/danielfrg/anaconda/envs/ocu-backend/lib/python2.7/distutils/cmd.py", line 109, in ensure_finalized
        self.finalize_options()
      File "build/bdist.macosx-10.5-x86_64/egg/setuptools/command/build_py.py", line 26, in finalize_options
      File "/Users/danielfrg/anaconda/envs/ocu-backend/lib/python2.7/distutils/command/build_py.py", line 46, in finalize_options
        ('force', 'force'))
      File "/Users/danielfrg/anaconda/envs/ocu-backend/lib/python2.7/distutils/cmd.py", line 298, in set_undefined_options
        src_cmd_obj.ensure_finalized()
      File "/Users/danielfrg/anaconda/envs/ocu-backend/lib/python2.7/distutils/cmd.py", line 109, in ensure_finalized
        self.finalize_options()
      File "/private/var/folders/ds/qbtlskm523g_kmf8bzshxsgh0000gn/T/pip_build_danielfrg/cryptography/setup.py", line 55, in finalize_options
        OpenSSLBinding().ffi.verifier.get_extension(),
      File "cryptography/hazmat/bindings/openssl/binding.py", line 83, in __init__
        self._ensure_ffi_initialized()
      File "cryptography/hazmat/bindings/openssl/binding.py", line 99, in _ensure_ffi_initialized
        libraries)
      File "cryptography/hazmat/bindings/utils.py", line 72, in build_ffi
        ext_package="cryptography",
      File "/private/var/folders/ds/qbtlskm523g_kmf8bzshxsgh0000gn/T/pip_build_danielfrg/cryptography/cffi-0.8.1-py2.7-macosx-10.5-x86_64.egg/cffi/api.py", line 339, in verify
        lib = self.verifier.load_library()
      File "/private/var/folders/ds/qbtlskm523g_kmf8bzshxsgh0000gn/T/pip_build_danielfrg/cryptography/cffi-0.8.1-py2.7-macosx-10.5-x86_64.egg/cffi/verifier.py", line 75, in load_library
        return self._load_library()
      File "/private/var/folders/ds/qbtlskm523g_kmf8bzshxsgh0000gn/T/pip_build_danielfrg/cryptography/cffi-0.8.1-py2.7-macosx-10.5-x86_64.egg/cffi/verifier.py", line 151, in _load_library
        return self._vengine.load_library()
      File "/private/var/folders/ds/qbtlskm523g_kmf8bzshxsgh0000gn/T/pip_build_danielfrg/cryptography/cffi-0.8.1-py2.7-macosx-10.5-x86_64.egg/cffi/vengine_cpy.py", line 138, in load_library
        raise ffiplatform.VerificationError(error)
    cffi.ffiplatform.VerificationError: importing '/private/var/folders/ds/qbtlskm523g_kmf8bzshxsgh0000gn/T/pip_build_danielfrg/cryptography/cryptography/hazmat/bindings/__pycache__/_cffi__x9ee276ddxb4fc9075.so': dlopen(/private/var/folders/ds/qbtlskm523g_kmf8bzshxsgh0000gn/T/pip_build_danielfrg/cryptography/cryptography/hazmat/bindings/__pycache__/_cffi__x9ee276ddxb4fc9075.so, 2): Library not loaded: libcrypto.1.0.0.dylib
      Referenced from: /private/var/folders/ds/qbtlskm523g_kmf8bzshxsgh0000gn/T/pip_build_danielfrg/cryptography/cryptography/hazmat/bindings/__pycache__/_cffi__x9ee276ddxb4fc9075.so
      Reason: image not found
    Complete output from command python setup.py egg_info:
    Package libffi was not found in the pkg-config search path.

Perhaps you should add the directory containing `libffi.pc'

to the PKG_CONFIG_PATH environment variable

No package 'libffi' found

Package libffi was not found in the pkg-config search path.

Perhaps you should add the directory containing `libffi.pc'

to the PKG_CONFIG_PATH environment variable

No package 'libffi' found

Package libffi was not found in the pkg-config search path.

Perhaps you should add the directory containing `libffi.pc'

to the PKG_CONFIG_PATH environment variable

No package 'libffi' found

Package libffi was not found in the pkg-config search path.

Perhaps you should add the directory containing `libffi.pc'

to the PKG_CONFIG_PATH environment variable

No package 'libffi' found

Package libffi was not found in the pkg-config search path.

Perhaps you should add the directory containing `libffi.pc'

to the PKG_CONFIG_PATH environment variable

No package 'libffi' found

c/check__thread.c:1:1: error: thread-local storage is unsupported for the current target

__thread int some_threadlocal_variable_42;

^

1 error generated.

the above error message can be safely ignored;

will not use '__thread' in the C code



Installed /private/var/folders/ds/qbtlskm523g_kmf8bzshxsgh0000gn/T/pip_build_danielfrg/cryptography/cffi-0.8.1-py2.7-macosx-10.5-x86_64.egg

Searching for pycparser

Reading https://pypi.python.org/simple/pycparser/

Best match: pycparser 2.10

Downloading https://pypi.python.org/packages/source/p/pycparser/pycparser-2.10.tar.gz#md5=d87aed98c8a9f386aa56d365fe4d515f

Processing pycparser-2.10.tar.gz

Writing /var/folders/ds/qbtlskm523g_kmf8bzshxsgh0000gn/T/easy_install-OuwG0l/pycparser-2.10/setup.cfg

Running pycparser-2.10/setup.py -q bdist_egg --dist-dir /var/folders/ds/qbtlskm523g_kmf8bzshxsgh0000gn/T/easy_install-OuwG0l/pycparser-2.10/egg-dist-tmp-nTEnU9

zip_safe flag not set; analyzing archive contents...



Installed /private/var/folders/ds/qbtlskm523g_kmf8bzshxsgh0000gn/T/pip_build_danielfrg/cryptography/pycparser-2.10-py2.7.egg

running egg_info

creating pip-egg-info/cryptography.egg-info

writing requirements to pip-egg-info/cryptography.egg-info/requires.txt

writing pip-egg-info/cryptography.egg-info/PKG-INFO

writing top-level names to pip-egg-info/cryptography.egg-info/top_level.txt

writing dependency_links to pip-egg-info/cryptography.egg-info/dependency_links.txt

writing manifest file 'pip-egg-info/cryptography.egg-info/SOURCES.txt'

warning: manifest_maker: standard file '-c' not found



running build_ext

building '_cffi__xcfd0a060xfba2f231' extension

creating /private/var/folders/ds/qbtlskm523g_kmf8bzshxsgh0000gn/T/pip_build_danielfrg/cryptography/cryptography/hazmat/primitives/__pycache__/cryptography

creating /private/var/folders/ds/qbtlskm523g_kmf8bzshxsgh0000gn/T/pip_build_danielfrg/cryptography/cryptography/hazmat/primitives/__pycache__/cryptography/hazmat

creating /private/var/folders/ds/qbtlskm523g_kmf8bzshxsgh0000gn/T/pip_build_danielfrg/cryptography/cryptography/hazmat/primitives/__pycache__/cryptography/hazmat/primitives

creating /private/var/folders/ds/qbtlskm523g_kmf8bzshxsgh0000gn/T/pip_build_danielfrg/cryptography/cryptography/hazmat/primitives/__pycache__/cryptography/hazmat/primitives/__pycache__

gcc -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/usr/local/opt/openssl/include -arch x86_64 -I/Users/danielfrg/anaconda/envs/ocu-backend/include/python2.7 -c cryptography/hazmat/primitives/__pycache__/_cffi__xcfd0a060xfba2f231.c -o /private/var/folders/ds/qbtlskm523g_kmf8bzshxsgh0000gn/T/pip_build_danielfrg/cryptography/cryptography/hazmat/primitives/__pycache__/cryptography/hazmat/primitives/__pycache__/_cffi__xcfd0a060xfba2f231.o

gcc -bundle -undefined dynamic_lookup -L/Users/danielfrg/anaconda/envs/ocu-backend/lib -L/usr/local/opt/openssl/lib -I/usr/local/opt/openssl/include -arch x86_64 -arch x86_64 /private/var/folders/ds/qbtlskm523g_kmf8bzshxsgh0000gn/T/pip_build_danielfrg/cryptography/cryptography/hazmat/primitives/__pycache__/cryptography/hazmat/primitives/__pycache__/_cffi__xcfd0a060xfba2f231.o -L/Users/danielfrg/anaconda/envs/ocu-backend/lib -o /private/var/folders/ds/qbtlskm523g_kmf8bzshxsgh0000gn/T/pip_build_danielfrg/cryptography/cryptography/hazmat/primitives/__pycache__/_cffi__xcfd0a060xfba2f231.so

running build_ext

building '_cffi__x5fea2bacx4a8b9ec1' extension

gcc -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/usr/local/opt/openssl/include -arch x86_64 -I/Users/danielfrg/anaconda/envs/ocu-backend/include/python2.7 -c cryptography/hazmat/primitives/__pycache__/_cffi__x5fea2bacx4a8b9ec1.c -o /private/var/folders/ds/qbtlskm523g_kmf8bzshxsgh0000gn/T/pip_build_danielfrg/cryptography/cryptography/hazmat/primitives/__pycache__/cryptography/hazmat/primitives/__pycache__/_cffi__x5fea2bacx4a8b9ec1.o

gcc -bundle -undefined dynamic_lookup -L/Users/danielfrg/anaconda/envs/ocu-backend/lib -L/usr/local/opt/openssl/lib -I/usr/local/opt/openssl/include -arch x86_64 -arch x86_64 /private/var/folders/ds/qbtlskm523g_kmf8bzshxsgh0000gn/T/pip_build_danielfrg/cryptography/cryptography/hazmat/primitives/__pycache__/cryptography/hazmat/primitives/__pycache__/_cffi__x5fea2bacx4a8b9ec1.o -L/Users/danielfrg/anaconda/envs/ocu-backend/lib -o /private/var/folders/ds/qbtlskm523g_kmf8bzshxsgh0000gn/T/pip_build_danielfrg/cryptography/cryptography/hazmat/primitives/__pycache__/_cffi__x5fea2bacx4a8b9ec1.so

running build_ext

building '_cffi__x9ee276ddxb4fc9075' extension

creating /private/var/folders/ds/qbtlskm523g_kmf8bzshxsgh0000gn/T/pip_build_danielfrg/cryptography/cryptography/hazmat/bindings/__pycache__/cryptography

creating /private/var/folders/ds/qbtlskm523g_kmf8bzshxsgh0000gn/T/pip_build_danielfrg/cryptography/cryptography/hazmat/bindings/__pycache__/cryptography/hazmat

creating /private/var/folders/ds/qbtlskm523g_kmf8bzshxsgh0000gn/T/pip_build_danielfrg/cryptography/cryptography/hazmat/bindings/__pycache__/cryptography/hazmat/bindings

creating /private/var/folders/ds/qbtlskm523g_kmf8bzshxsgh0000gn/T/pip_build_danielfrg/cryptography/cryptography/hazmat/bindings/__pycache__/cryptography/hazmat/bindings/__pycache__

gcc -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/usr/local/opt/openssl/include -arch x86_64 -I/Users/danielfrg/anaconda/envs/ocu-backend/include/python2.7 -c cryptography/hazmat/bindings/__pycache__/_cffi__x9ee276ddxb4fc9075.c -o /private/var/folders/ds/qbtlskm523g_kmf8bzshxsgh0000gn/T/pip_build_danielfrg/cryptography/cryptography/hazmat/bindings/__pycache__/cryptography/hazmat/bindings/__pycache__/_cffi__x9ee276ddxb4fc9075.o

gcc -bundle -undefined dynamic_lookup -L/Users/danielfrg/anaconda/envs/ocu-backend/lib -L/usr/local/opt/openssl/lib -I/usr/local/opt/openssl/include -arch x86_64 -arch x86_64 /private/var/folders/ds/qbtlskm523g_kmf8bzshxsgh0000gn/T/pip_build_danielfrg/cryptography/cryptography/hazmat/bindings/__pycache__/cryptography/hazmat/bindings/__pycache__/_cffi__x9ee276ddxb4fc9075.o -L/Users/danielfrg/anaconda/envs/ocu-backend/lib -lcrypto -lssl -o /private/var/folders/ds/qbtlskm523g_kmf8bzshxsgh0000gn/T/pip_build_danielfrg/cryptography/cryptography/hazmat/bindings/__pycache__/_cffi__x9ee276ddxb4fc9075.so

Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/private/var/folders/ds/qbtlskm523g_kmf8bzshxsgh0000gn/T/pip_build_danielfrg/cryptography/setup.py", line 113, in <module>

    "build": cffi_build,

  File "/Users/danielfrg/anaconda/envs/ocu-backend/lib/python2.7/distutils/core.py", line 152, in setup

    dist.run_commands()

  File "/Users/danielfrg/anaconda/envs/ocu-backend/lib/python2.7/distutils/dist.py", line 953, in run_commands

    self.run_command(cmd)

  File "/Users/danielfrg/anaconda/envs/ocu-backend/lib/python2.7/distutils/dist.py", line 972, in run_command

    cmd_obj.run()

  File "<string>", line 15, in replacement_run

  File "build/bdist.macosx-10.5-x86_64/egg/setuptools/command/egg_info.py", line 186, in find_sources

  File "build/bdist.macosx-10.5-x86_64/egg/setuptools/command/egg_info.py", line 246, in run

  File "build/bdist.macosx-10.5-x86_64/egg/setuptools/command/egg_info.py", line 282, in add_defaults

  File "build/bdist.macosx-10.5-x86_64/egg/setuptools/command/sdist.py", line 167, in add_defaults

  File "/Users/danielfrg/anaconda/envs/ocu-backend/lib/python2.7/distutils/cmd.py", line 312, in get_finalized_command

    cmd_obj.ensure_finalized()

  File "/Users/danielfrg/anaconda/envs/ocu-backend/lib/python2.7/distutils/cmd.py", line 109, in ensure_finalized

    self.finalize_options()

  File "build/bdist.macosx-10.5-x86_64/egg/setuptools/command/build_py.py", line 26, in finalize_options

  File "/Users/danielfrg/anaconda/envs/ocu-backend/lib/python2.7/distutils/command/build_py.py", line 46, in finalize_options

    ('force', 'force'))

  File "/Users/danielfrg/anaconda/envs/ocu-backend/lib/python2.7/distutils/cmd.py", line 298, in set_undefined_options

    src_cmd_obj.ensure_finalized()

  File "/Users/danielfrg/anaconda/envs/ocu-backend/lib/python2.7/distutils/cmd.py", line 109, in ensure_finalized

    self.finalize_options()

  File "/private/var/folders/ds/qbtlskm523g_kmf8bzshxsgh0000gn/T/pip_build_danielfrg/cryptography/setup.py", line 55, in finalize_options

    OpenSSLBinding().ffi.verifier.get_extension(),

  File "cryptography/hazmat/bindings/openssl/binding.py", line 83, in __init__

    self._ensure_ffi_initialized()

  File "cryptography/hazmat/bindings/openssl/binding.py", line 99, in _ensure_ffi_initialized

    libraries)

  File "cryptography/hazmat/bindings/utils.py", line 72, in build_ffi

    ext_package="cryptography",

  File "/private/var/folders/ds/qbtlskm523g_kmf8bzshxsgh0000gn/T/pip_build_danielfrg/cryptography/cffi-0.8.1-py2.7-macosx-10.5-x86_64.egg/cffi/api.py", line 339, in verify

    lib = self.verifier.load_library()

  File "/private/var/folders/ds/qbtlskm523g_kmf8bzshxsgh0000gn/T/pip_build_danielfrg/cryptography/cffi-0.8.1-py2.7-macosx-10.5-x86_64.egg/cffi/verifier.py", line 75, in load_library

    return self._load_library()

  File "/private/var/folders/ds/qbtlskm523g_kmf8bzshxsgh0000gn/T/pip_build_danielfrg/cryptography/cffi-0.8.1-py2.7-macosx-10.5-x86_64.egg/cffi/verifier.py", line 151, in _load_library

    return self._vengine.load_library()

  File "/private/var/folders/ds/qbtlskm523g_kmf8bzshxsgh0000gn/T/pip_build_danielfrg/cryptography/cffi-0.8.1-py2.7-macosx-10.5-x86_64.egg/cffi/vengine_cpy.py", line 138, in load_library

    raise ffiplatform.VerificationError(error)

cffi.ffiplatform.VerificationError: importing '/private/var/folders/ds/qbtlskm523g_kmf8bzshxsgh0000gn/T/pip_build_danielfrg/cryptography/cryptography/hazmat/bindings/__pycache__/_cffi__x9ee276ddxb4fc9075.so': dlopen(/private/var/folders/ds/qbtlskm523g_kmf8bzshxsgh0000gn/T/pip_build_danielfrg/cryptography/cryptography/hazmat/bindings/__pycache__/_cffi__x9ee276ddxb4fc9075.so, 2): Library not loaded: libcrypto.1.0.0.dylib

  Referenced from: /private/var/folders/ds/qbtlskm523g_kmf8bzshxsgh0000gn/T/pip_build_danielfrg/cryptography/cryptography/hazmat/bindings/__pycache__/_cffi__x9ee276ddxb4fc9075.so

  Reason: image not found

----------------------------------------
Cleaning up...
Command python setup.py egg_info failed with error code 1 in /private/var/folders/ds/qbtlskm523g_kmf8bzshxsgh0000gn/T/pip_build_danielfrg/cryptography
Storing debug log for failure in /Users/danielfrg/.pip/pip.log
```

**Comment by muxuezi** [comment]
It's awesome!

**Comment by ralfzen** [comment]
for el capitan:
```
brew install openssl
env ARCHFLAGS="-arch x86_64" LDFLAGS="-L/usr/local/opt/openssl/lib" CFLAGS="-I/usr/local/opt/openssl/include" pip install cryptography
```

**Comment by guihaojin** [comment]
OS X El Capitan and `env ARCHFLAGS="-arch x86_64" LDFLAGS="-L/usr/local/opt/openssl/lib" CFLAGS="-I/usr/local/opt/openssl/include" pip install cryptography` failed with output:

```
cffi.ffiplatform.VerificationError: CompileError: command 'cc' failed with exit status 1
```

**Comment by tcab** [comment]
Mac OS X El Capitan - simply do:
```
conda install cryptography
```

**Comment by Eimis** [comment]
I had a completely same error msg and @danielfrg's solution helped me, thx :)

```
➜  ~  env DYLD_LIBRARY_PATH=/usr/local/opt/openssl/lib/ ARCHFLAGS="-arch x86_64 -Wno-error=unused-command-line-argument-hard-error-in-future" LDFLAGS="-L/usr/local/opt/openssl/lib" CFLAGS="-I/usr/local/opt/openssl/include" pip install cryptography
```
