### ISSUE TITLE
Importerrer in the Spark

### ISSUE THREAD

**Issue by yang-shuaijun** [pyca/cryptography#6968]
Python: 3.7.10
pip: 20.2.2
cryptography: 36.0.2
Spark: 3.1.2-amzn-1

if I load the cryptography from --pyfiles, the error raised:

```text
[hadoop@ip-172-31-21-108 ~]$ pyspark --py-files dependencies.zip
Python 3.7.10 (default, Jun  3 2021, 00:02:01) 
[GCC 7.3.1 20180712 (Red Hat 7.3.1-13)] on linux
Type "help", "copyright", "credits" or "license" for more information.
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/usr/lib/spark/jars/slf4j-log4j12-1.7.30.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/usr/share/aws/emr/emrfs/lib/slf4j-log4j12-1.7.12.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/usr/share/aws/redshift/jdbc/redshift-jdbc42-1.2.37.1061.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.slf4j.impl.Log4jLoggerFactory]
Setting default log level to "WARN".
To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).
22/03/16 10:45:46 WARN Client: Neither spark.yarn.jars nor spark.yarn.archive is set, falling back to uploading libraries under SPARK_HOME.
Welcome to
      ____              __
     / __/__  ___ _____/ /__
    _\ \/ _ \/ _ `/ __/  '_/
   /__ / .__/\_,_/_/ /_/\_\   version 3.1.2-amzn-1
      /_/

Using Python version 3.7.10 (default, Jun  3 2021 00:02:01)
Spark context Web UI available at http://ip-172-31-21-108.cn-north-1.compute.internal:4040
Spark context available as 'sc' (master = yarn, app id = application_1647323952412_0011).
SparkSession available as 'spark'.
>>> from cryptography.hazmat.primitives import padding
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/mnt/tmp/spark-66e602ba-ad79-4dae-af55-76c7cc225c89/userFiles-80a59a58-1cd4-4962-8115-504c1bab5097/dependencies.zip/cryptography/hazmat/primitives/padding.py", line 11, in <module>
ImportError: cannot import name 'check_ansix923_padding' from 'cryptography.hazmat.bindings._rust' (unknown location)
```

The dependencies.zip was bundled from /home/hadoop/.local/lib/python3.7/site-packages/.

If I directly install cryptography in emr platform, it worked well.
```text
[hadoop@ip-172-31-21-108 site-packages]$ pyspark 
Python 3.7.10 (default, Jun  3 2021, 00:02:01) 
[GCC 7.3.1 20180712 (Red Hat 7.3.1-13)] on linux
Type "help", "copyright", "credits" or "license" for more information.
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/usr/lib/spark/jars/slf4j-log4j12-1.7.30.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/usr/share/aws/emr/emrfs/lib/slf4j-log4j12-1.7.12.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/usr/share/aws/redshift/jdbc/redshift-jdbc42-1.2.37.1061.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.slf4j.impl.Log4jLoggerFactory]
Setting default log level to "WARN".
To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).
22/03/16 11:25:17 WARN Client: Neither spark.yarn.jars nor spark.yarn.archive is set, falling back to uploading libraries under SPARK_HOME.
Welcome to
      ____              __
     / __/__  ___ _____/ /__
    _\ \/ _ \/ _ `/ __/  '_/
   /__ / .__/\_,_/_/ /_/\_\   version 3.1.2-amzn-1
      /_/

Using Python version 3.7.10 (default, Jun  3 2021 00:02:01)
Spark context Web UI available at http://ip-172-31-21-108.cn-north-1.compute.internal:4040
Spark context available as 'sc' (master = yarn, app id = application_1647323952412_0013).
SparkSession available as 'spark'.
>>> from cryptography.hazmat.primitives import padding
>>> 
```

**Comment by alex** [comment]
How is your `dependencies.zip` file built, does it contain the native code extension modules?

**Comment by yang-shuaijun** [comment]
I directly bundle the file in the /home/hadoop/.local/lib/python3.7/site-packages

**Comment by alex** [comment]
Looking closely at the exception message I see that the path contains: `/dependencies.zip/cryptography/hazmat/primitives/padding.py`. This tells me that spark directly loads python files out of the `.zip`.

Unfortunately extension modules cannot be loaded out of the `.zip` file, so this can't work. You'll need to find out if spark has some other way of specifying files that supports extension modules.

**Comment by yang-shuaijun** [comment]
> Looking closely at the exception message I see that the path contains: `/dependencies.zip/cryptography/hazmat/primitives/padding.py`. This tells me that spark directly loads python files out of the `.zip`.
> 
> Unfortunately extension modules cannot be loaded out of the `.zip` file, so this can't work. You'll need to find out if spark has some other way of specifying files that supports extension modules.

Spark will unzip the zip file and then load the python modules.

**Comment by yang-shuaijun** [comment]
Just like this:
```text
[hadoop@ip-172-31-21-108 ~]$ pyspark --py-files dependencies.zip 
Python 3.7.10 (default, Jun  3 2021, 00:02:01) 
[GCC 7.3.1 20180712 (Red Hat 7.3.1-13)] on linux
Type "help", "copyright", "credits" or "license" for more information.
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/usr/lib/spark/jars/slf4j-log4j12-1.7.30.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/usr/share/aws/emr/emrfs/lib/slf4j-log4j12-1.7.12.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/usr/share/aws/redshift/jdbc/redshift-jdbc42-1.2.37.1061.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.slf4j.impl.Log4jLoggerFactory]
Setting default log level to "WARN".
To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).
22/03/16 11:39:11 WARN Client: Neither spark.yarn.jars nor spark.yarn.archive is set, falling back to uploading libraries under SPARK_HOME.
Welcome to
      ____              __
     / __/__  ___ _____/ /__
    _\ \/ _ \/ _ `/ __/  '_/
   /__ / .__/\_,_/_/ /_/\_\   version 3.1.2-amzn-1
      /_/

Using Python version 3.7.10 (default, Jun  3 2021 00:02:01)
Spark context Web UI available at http://ip-172-31-21-108.cn-north-1.compute.internal:4040
Spark context available as 'sc' (master = yarn, app id = application_1647323952412_0014).
SparkSession available as 'spark'.
>>> from cryptography.hazmat.primitives.ciphers import Cipher, algorithms, modes
>>> 
```

**Comment by alex** [comment]
That import is pure python, pure python files can be imported directly from `.zip` files but extension modules cannot.

**Comment by yang-shuaijun** [comment]
> Cipher, algorithms, modes

Are Cipher, algorithms, modes pure python code? It doesn't call other extension modules.

**Comment by yang-shuaijun** [comment]
Thank your analysis in detail.
The cryptography is excellent. I use it to mask the sensitive data.
