### ISSUE TITLE
install fails on redhat ppc64le

### ISSUE THREAD

**Issue by flynn1973** [pyca/cryptography#7091]
installing cryptography in venv for ansible awx fails with the following error...

````
(aix-custom-venv) root@lpgaixmgmtlx01:/var/lib/awx/venv/aix-custom-venv>pip3  install cryptography
Collecting cryptography
  Using cached cryptography-36.0.2.tar.gz (572 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  ERROR: Command errored out with exit status 1:
   command: /var/lib/awx/venv/aix-custom-venv/bin/python /var/lib/awx/venv/aix-custom-venv/lib/python3.6/site-packages/pip/_vendor/pep517/in_process/_in_process.py get_requires_for_build_wheel /tmp/tmp8lcqu0wx
       cwd: /tmp/pip-install-zm43akdm/cryptography_7c5d4ca729b64738ad846779fd79bde9
  Complete output (62 lines):

      =============================DEBUG ASSISTANCE=============================
      If you are seeing a compilation error please try the following steps to
      successfully install cryptography:
      1) Upgrade to the latest pip and try again. This will fix errors for most
         users. See: https://pip.pypa.io/en/stable/installing/#upgrading-pip
      2) Read https://cryptography.io/en/latest/installation/ for specific
         instructions for your platform.
      3) Check our frequently asked questions for more information:
         https://cryptography.io/en/latest/faq/
      4) Ensure you have a recent Rust toolchain installed:
         https://cryptography.io/en/latest/installation/#rust

      Python: 3.6.8
      platform: Linux-3.10.0-1160.59.1.el7.ppc64le-ppc64le-with-redhat-7.9-Maipo
      pip: n/a
      setuptools: 59.6.0
      setuptools_rust: 1.1.2
      =============================DEBUG ASSISTANCE=============================

  Traceback (most recent call last):
    File "/var/lib/awx/venv/aix-custom-venv/lib/python3.6/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
      main()
    File "/var/lib/awx/venv/aix-custom-venv/lib/python3.6/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/var/lib/awx/venv/aix-custom-venv/lib/python3.6/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 130, in get_requires_for_build_wheel
      return hook(config_settings)
    File "/tmp/pip-build-env-98vn68ew/overlay/lib/python3.6/site-packages/setuptools/build_meta.py", line 163, in get_requires_for_build_wheel
      config_settings, requirements=['wheel'])
    File "/tmp/pip-build-env-98vn68ew/overlay/lib/python3.6/site-packages/setuptools/build_meta.py", line 143, in _get_build_requires
      self.run_setup()
    File "/tmp/pip-build-env-98vn68ew/overlay/lib/python3.6/site-packages/setuptools/build_meta.py", line 158, in run_setup
      exec(compile(code, __file__, 'exec'), locals())
    File "setup.py", line 54, in <module>
      rust_version=">=1.41.0",
    File "/tmp/pip-build-env-98vn68ew/overlay/lib/python3.6/site-packages/setuptools/__init__.py", line 153, in setup
      return distutils.core.setup(**attrs)
    File "/usr/lib64/python3.6/distutils/core.py", line 108, in setup
      _setup_distribution = dist = klass(attrs)
    File "/tmp/pip-build-env-98vn68ew/overlay/lib/python3.6/site-packages/setuptools/dist.py", line 463, in __init__
      for k, v in attrs.items()
    File "/usr/lib64/python3.6/distutils/dist.py", line 281, in __init__
      self.finalize_options()
    File "/tmp/pip-build-env-98vn68ew/overlay/lib/python3.6/site-packages/setuptools/dist.py", line 837, in finalize_options
      ep(self)
    File "/tmp/pip-build-env-98vn68ew/overlay/lib/python3.6/site-packages/setuptools/dist.py", line 858, in _finalize_setup_keywords
      ep.load()(self, ep.name, value)
    File "/tmp/pip-build-env-98vn68ew/overlay/lib64/python3.6/site-packages/cffi/setuptools_ext.py", line 219, in cffi_modules
      add_cffi_module(dist, cffi_module)
    File "/tmp/pip-build-env-98vn68ew/overlay/lib64/python3.6/site-packages/cffi/setuptools_ext.py", line 49, in add_cffi_module
      execfile(build_file_name, mod_vars)
    File "/tmp/pip-build-env-98vn68ew/overlay/lib64/python3.6/site-packages/cffi/setuptools_ext.py", line 25, in execfile
      exec(code, glob, glob)
    File "src/_cffi_src/build_openssl.py", line 118, in <module>
      extra_link_args=extra_link_args(compiler_type()),
    File "src/_cffi_src/utils.py", line 59, in build_ffi_for_binding
      extra_link_args=extra_link_args,
    File "src/_cffi_src/utils.py", line 73, in build_ffi
      ffi = FFI()
    File "/tmp/pip-build-env-98vn68ew/overlay/lib64/python3.6/site-packages/cffi/api.py", line 48, in __init__
      import _cffi_backend as backend
  ModuleNotFoundError: No module named '_cffi_backend'
  ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/10/a7/51953e73828deef2b58ba1604de9167843ee9cd4185d8aaffcb45dd1932d/cryptography-36.0.2.tar.gz#sha256=70f8f4f7bb2ac9f340655cbac89d68c527af5bb4387522a8413e841e3e6628c9 (from https://pypi.org/simple/cryptography/) (requires-python:>=3.6). Command errored out with exit status 1: /var/lib/awx/venv/aix-custom-venv/bin/python /var/lib/awx/venv/aix-custom-venv/lib/python3.6/site-packages/pip/_vendor/pep517/in_process/_in_process.py get_requires_for_build_wheel /tmp/tmp8lcqu0wx Check the logs for full command output.
````

how to proceed here?

**Comment by alex** [comment]
Is this the same issue as #7042?

Can you please provide instructions for reproducing this issue from a fresh machine/container?

**Comment by flynn1973** [comment]
ah..sorry, wrong project once again than...i cant get my head around all the different cryptography nonsens anymore.
