### ISSUE TITLE
Missing attribute in v37.0.0? 

### ISSUE THREAD

**Issue by arohm-ff** [pyca/cryptography#7134]
### Description
I am running into the following error with the latest version of `cryptography` on Ubuntu 20.04.4 with OpenSSL 1.1.1f:
```
AttributeError: module 'lib' has no attribute 'X509_V_FLAG_CB_ISSUER_CHECK'
```
This is for a CI job running in Github Actions on ubuntu. I get the error with the following job:
```
jobs:
  pre-build:
    name: Unit Tests and Linting
    runs-on: ubuntu-latest
    steps:
      - name: Install Unit Test & Linting Dependencies
        run: |
          pip install --upgrade pip
          pip3 cache purge
          pip3 --version
          pip3 install --upgrade setuptools
          pip3 install cryptography==37
          pip3 install pyOpenSSL
          openssl version
          pip3 list
          python3 -m OpenSSL.debug
```
### Version info
`ubuntu-latest` is 20.04.4 LTS [per here](https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu2004-Readme.md)
Python3 3.8.10
OpenSSL 1.1.1f 31 Mar 2020
pip 22.0.4
setuptools 62.1.0
cffi 1.15.0

### Full output
```
Run pip install --upgrade pip
  pip install --upgrade pip
  pip3 cache purge
  pip3 --version
  pip3 install --upgrade setuptools
  pip3 install cryptography==37
  pip3 install pyOpenSSL
  openssl version
  pip3 list
  python3 -m OpenSSL.debug
  shell: /usr/bin/bash -e {0}
Collecting pip
  Downloading pip-22.0.4-py3-none-any.whl (2.1 MB)
Installing collected packages: pip
Successfully installed pip-22.0.4
Files removed: 2
pip 22.0.4 from /home/runner/.local/lib/python3.8/site-packages/pip (python 3.8)
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: setuptools in /usr/lib/python3/dist-packages (45.2.0)
Collecting setuptools
  Downloading setuptools-62.1.0-py3-none-any.whl (1.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.1/1.1 MB 14.6 MB/s eta 0:00:00
Installing collected packages: setuptools
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
launchpadlib 1.10.13 requires testresources, which is not installed.
Successfully installed setuptools-62.1.0
Defaulting to user installation because normal site-packages is not writeable
Collecting cryptography==37
  Downloading cryptography-37.0.0-cp36-abi3-manylinux_2_24_x86_64.whl (4.0 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.0/4.0 MB 38.7 MB/s eta 0:00:00
Collecting cffi>=1.12
  Downloading cffi-1.15.0-cp38-cp38-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (446 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 446.7/446.7 KB 82.7 MB/s eta 0:00:00
Collecting pycparser
  Downloading pycparser-2.21-py2.py3-none-any.whl (118 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 118.7/118.7 KB 36.0 MB/s eta 0:00:00
Installing collected packages: pycparser, cffi, cryptography
Successfully installed cffi-1.15.0 cryptography-37.0.0 pycparser-2.21
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pyOpenSSL in /usr/lib/python3/dist-packages (19.0.0)
OpenSSL 1.1.1f  31 Mar 2020
Package                Version
---------------------- --------------------
argcomplete            2.0.0
attrs                  19.3.0
Automat                0.8.0
blinker                1.4
certifi                2019.11.28
cffi                   1.15.0
chardet                3.0.4
Click                  7.0
cloud-init             22.1
colorama               0.4.3
command-not-found      0.3
configobj              5.0.6
constantly             15.1.0
crcmod                 1.7
crit                   0.0.1
cryptography           37.0.0
dbus-python            1.2.16
distro                 1.4.0
distro-info            0.23ubuntu1
entrypoints            0.3
httplib2               0.14.0
hyperlink              19.0.0
idna                   2.8
importlib-metadata     1.5.0
incremental            16.10.1
Jinja2                 2.10.1
jsonpatch              1.22
jsonpointer            2.0
jsonschema             3.2.0
keyring                18.0.1
language-selector      0.1
launchpadlib           1.10.13
lazr.restfulclient     0.14.2
lazr.uri               1.0.3
MarkupSafe             1.1.0
more-itertools         4.2.0
netifaces              0.10.4
oauthlib               3.1.0
packaging              21.3
pexpect                4.6.0
pip                    22.0.4
pipx                   1.0.0
protobuf               3.6.1
pyasn1                 0.4.2
pyasn1-modules         0.2.1
pycparser              2.21
Pygments               2.3.1
PyGObject              3.36.0
PyHamcrest             1.9.0
PyJWT                  1.7.1
pymacaroons            0.13.0
PyNaCl                 1.3.0
pyOpenSSL              19.0.0
pyparsing              3.0.8
pyparted               3.11.2
pyrsistent             0.15.5
pyserial               3.4
python-apt             2.0.0+ubuntu0.20.4.7
python-debian          0.1.36ubuntu1
PyYAML                 5.3.1
requests               2.22.0
requests-unixsocket    0.2.0
SecretStorage          2.3.1
service-identity       18.1.0
setuptools             62.1.0
simplejson             3.16.0
six                    1.14.0
sos                    4.3
ssh-import-id          5.10
systemd-python         234
Twisted                18.9.0
ubuntu-advantage-tools 27.7
ufw                    0.36
urllib3                1.25.8
userpath               1.8.0
wadllib                1.3.3
WALinuxAgent           2.2.46
wheel                  0.34.2
zipp                   1.0.0
zope.interface         4.7.1
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 185, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.8/runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "/usr/lib/python3/dist-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import crypto, SSL
  File "/usr/lib/python3/dist-packages/OpenSSL/crypto.py", line 1553, in <module>
    class X509StoreFlags(object):
  File "/usr/lib/python3/dist-packages/OpenSSL/crypto.py", line 1573, in X509StoreFlags
    CB_ISSUER_CHECK = _lib.X509_V_FLAG_CB_ISSUER_CHECK
AttributeError: module 'lib' has no attribute 'X509_V_FLAG_CB_ISSUER_CHECK'
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 72, in apport_excepthook
    from apport.fileutils import likely_packaged, get_recent_crashes
  File "/usr/lib/python3/dist-packages/apport/__init__.py", line 5, in <module>
    from apport.report import Report
  File "/usr/lib/python3/dist-packages/apport/report.py", line 32, in <module>
    import apport.fileutils
  File "/usr/lib/python3/dist-packages/apport/fileutils.py", line 12, in <module>
    import os, glob, subprocess, os.path, time, pwd, sys, requests_unixsocket
  File "/usr/lib/python3/dist-packages/requests_unixsocket/__init__.py", line 1, in <module>
    import requests
  File "/usr/lib/python3/dist-packages/requests/__init__.py", line 95, in <module>
    from urllib3.contrib import pyopenssl
  File "/usr/lib/python3/dist-packages/urllib3/contrib/pyopenssl.py", line 46, in <module>
    import OpenSSL.SSL
  File "/usr/lib/python3/dist-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import crypto, SSL
  File "/usr/lib/python3/dist-packages/OpenSSL/crypto.py", line 1553, in <module>
    class X509StoreFlags(object):
  File "/usr/lib/python3/dist-packages/OpenSSL/crypto.py", line 1573, in X509StoreFlags
    CB_ISSUER_CHECK = _lib.X509_V_FLAG_CB_ISSUER_CHECK
AttributeError: module 'lib' has no attribute 'X509_V_FLAG_CB_ISSUER_CHECK'

Original exception was:
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 185, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.8/runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "/usr/lib/python3/dist-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import crypto, SSL
  File "/usr/lib/python3/dist-packages/OpenSSL/crypto.py", line 1553, in <module>
    class X509StoreFlags(object):
  File "/usr/lib/python3/dist-packages/OpenSSL/crypto.py", line 1573, in X509StoreFlags
    CB_ISSUER_CHECK = _lib.X509_V_FLAG_CB_ISSUER_CHECK
AttributeError: module 'lib' has no attribute 'X509_V_FLAG_CB_ISSUER_CHECK'
```

**Comment by alex** [comment]
See https://github.com/pyca/cryptography/issues/7126

**Comment by arohm-ff** [comment]
@alex Thanks for sharing that - couldn't find it when I started looking yesterday. 

I noticed that pyOpenSSL [specifies a minimum cryptography version of 35](https://github.com/pyca/pyopenssl/blob/99911f75f110409742eaf710a178ff0201f9b4a9/tox.ini#L13) but no upper limit - maybe adding that would help?

**Comment by alex** [comment]
Unfortunately we don't know what the upper limit will be in advance -- in this case the attribute was removed because OpenSSL itself was deprecating/removing it :-(

**Comment by arohm-ff** [comment]
Ah right. I see now that the pyOpenSSL version failing in my example was 19, and upgrading that to 22 also resolves the issue so I think that's all I need. Thank you!

**Comment by alex** [comment]
No problem. Sorry this breakage occurred, even if we don't know how to avoid it!

On Wed, Apr 27, 2022 at 2:12 PM arohm-ff ***@***.***> wrote:
>
> Ah right. I see now that the pyOpenSSL version failing in my example was 19, and upgrading that to 22 also resolves the issue so I think that's all I need. Thank you!
>
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you were mentioned.Message ID: ***@***.***>



-- 
All that is necessary for evil to succeed is for good people to do nothing.

**Comment by reaperhulk** [comment]
We re-added some symbols in 37.0.1 to minimize breakage. We still encourage users to upgrade to the latest pyOpenSSL as these will be removed again in a future release.
