### ISSUE TITLE
Ciphertext length must be equal to key size.

### ISSUE THREAD

**Issue by UsLpH** [pyca/cryptography#7301]
Error:
--------------------------------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\Attic\Desktop\shit.py", line 82, in <module>
    f.write(Decrypt(privKey, msg))
  File "C:\Users\Attic\Desktop\shit.py", line 46, in Decrypt
    original_message = private.decrypt(encrypted,padding.OAEP(mgf=padding.MGF1(algorithm=hashes.SHA256()),algorithm=hashes.SHA256(),label=None))
  File "C:\Users\Attic\AppData\Local\Programs\Python\Python310\lib\site-packages\cryptography\hazmat\backends\openssl\rsa.py", line 431, in decrypt
    raise ValueError("Ciphertext length must be equal to key size.")
ValueError: Ciphertext length must be equal to key size.
--------------------------------------------------------------------------------------------

Public Key : https://github.com/UsLpH/DB1/blob/main/public_key.pem
Encrypted Text : https://github.com/UsLpH/DB1/blob/main/test.encrypted

**Comment by UsLpH** [comment]
-------------------------------------------------------------------
def Decrypt(private, encrypted):
    key_size_bytes = (private.key_size + 7) // 8
    print(key_size_bytes)
    system("pause")
    original_message = private.decrypt(encrypted,padding.OAEP(mgf=padding.MGF1(algorithm=hashes.SHA256()),algorithm=hashes.SHA256(),label=None))
    return original_message
-------------------------------------------------------------------

**Comment by UsLpH** [comment]
alright lemme make it real quick
