### ISSUE TITLE
error parsing asn1 value: ParseError while decoding OCSP response from PostSignum Public CA 5

### ISSUE THREAD

**Issue by kidmin** [pyca/cryptography#7309]
cryptography 37.0.2 fails to parse an OCSP response from PostSignum Public CA 5.

* Versions of Python, ``cryptography``, ``cffi``, ``pip``, and ``setuptools``
  you're using
  * Python 3.8.5 (python38-3.8.5-1.amzn2.0.2.aarch64)
  * cryptography-37.0.2
  * cffi-1.15.0
  * pip 21.0.1 (python38-pip-21.0.1-4.amzn2.0.1.noarch)
* How you installed ``cryptography``
  * `pip3.8 install cryptography` from a shell
* Clear steps for reproducing your bug
  * Download a CA certificate of PostSignum Public CA 5 from https://crt.sh/?d=1165415888
  * Download a certificate issued from PostSignum Public CA 5 (e.g. https://crt.sh/?d=6844062976)
  * Get an OCSP response with `openssl ocsp -issuer 1165415888.crt -cert 6844062976.crt -url http://ocsp.postsignum.cz/OCSP/VCA5/ -respout ocsp-response` [3]
  * Parse the response with cryptography by [1]
    * expected result: OCSP response status is displayed
    * actual result: An exception is thrown from cryptography [2]
  * Note: OpenSSL 1.0.2k (openssl-1.0.2k-24.amzn2.0.2.aarch64) can parse the response: `openssl ocsp -noverify -text -respin ocsp-response` succeeds
  * Note: crt.sh can parse the response: https://crt.sh/?id=6844062976&opt=ocsp

[1] Python script to parse an OCSP response
```
from cryptography.x509 import ocsp
with open('ocsp-response', 'rb') as rfh:
    response_der = rfh.read()
ocsp_response = ocsp.load_der_ocsp_response(response_der)
print(ocsp_response.response_status)
```

[2] An exception while parsing the response
```
Traceback (most recent call last):
  File "test.py", line 4, in <module>
    ocsp_response = ocsp.load_der_ocsp_response(response_der)
  File "/home/ec2-user/.local/lib/python3.8/site-packages/cryptography/x509/ocsp.py", line 551, in load_der_ocsp_response
    return ocsp.load_der_ocsp_response(data)
ValueError: error parsing asn1 value: ParseError { kind: EncodedDefault, location: ["BasicOCSPResponse::tbs_response_data", "ResponseData::version"] }
```

[3] OCSP response (Note: the original file is in DER format, base64-encoded to paste into this issue)
```
MIIIqgoBAKCCCKMwggifBgkrBgEFBQcwAQEEggiQMIIIjDCCASigAwIBAKGBlDCB
kTELMAkGA1UEBhMCQ1oxFzAVBgNVBGETDk5UUkNaLTQ3MTE0OTgzMR0wGwYDVQQK
DBTEjGVza8OhIHBvxaF0YSwgcy5wLjEcMBoGA1UECxMTUG9zdFNpZ251bSBTZXJ2
aWNlczEsMCoGA1UEAxMjUG9zdFNpZ251bSBWQ0EgNSAtIE9DU1AgUmVzcG9uZGVy
IDEYDzIwMjIwNjA0MTM0MTU5WjBUMFIwPTAJBgUrDgMCGgUABBSuxvcZqW14YT8W
6vRjKPNjNFt/bQQU484xUfNMkfV9twWJsXjQowrGQ5kCBACn8IGAABgPMjAyMjA2
MDQxMzQxNTlaoSMwITAfBgkrBgEFBQcwAQIEEgQQFg/LHX4kFTqWrkBKeQJO0zAN
BgkqhkiG9w0BAQ0FAAOCAQEAk7aJJ4LatCLWyZqX1+FYFV0WeIck5CeJyqIZFwp0
z2mqOOUVXr4o2uA++4CA0lbeRzevPHt0aYgwB527Km+g3+XS/s5ZIdSzXFcAUSyq
k0nVgrJrj/XB2qIKVZm6MIzb6w5ZtZiGlOSnjzQFwZ9f7DcXOrleDP5AEYvE0mlw
+qsvRTYhJUKG7dJZ0QeuJRCREhfy0bt+FjGYH4/enyiNHl8mVYl7dQeYfIenBACD
/f92l05PkRp26RwkLMKfY2uchFpmSKIeY7dTVvplwNcrr7ztBlr06FU35so9NTWx
da6VVpEpkwMGxDgh7X6FQPa2GWv1DvIt2x11V+G2i7DylqCCBkgwggZEMIIGQDCC
BCigAwIBAgIEAKfp2jANBgkqhkiG9w0BAQsFADBmMQswCQYDVQQGEwJDWjEXMBUG
A1UEYRMOTlRSQ1otNDcxMTQ5ODMxHTAbBgNVBAoMFMSMZXNrw6EgcG/FoXRhLCBz
LnAuMR8wHQYDVQQDExZQb3N0U2lnbnVtIFB1YmxpYyBDQSA1MB4XDTIxMTAxNTEx
NDE1MFoXDTIyMTAxNTExNDE1MFowgZExCzAJBgNVBAYTAkNaMRcwFQYDVQRhEw5O
VFJDWi00NzExNDk4MzEdMBsGA1UECgwUxIxlc2vDoSBwb8WhdGEsIHMucC4xHDAa
BgNVBAsTE1Bvc3RTaWdudW0gU2VydmljZXMxLDAqBgNVBAMTI1Bvc3RTaWdudW0g
VkNBIDUgLSBPQ1NQIFJlc3BvbmRlciAxMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8A
MIIBCgKCAQEArE9ZZwzNtoMBjBLbgy2MRFUpoSvYJauIB5Jk3lKxhooX+mSU5Mpt
5gnR8nFdZcwthN6Iac5ae8YRD7RykAvqSNgDI2L7dCFQGUsKaD11Sr5w67Jo+4js
FQvIQdEXFKYCyc9NPj7Sqmul1x6O+9qas8SdwdZAhHM/Z3TAWheVJIr4F/6Nxt1W
gCglBCuJdLhzbKUeGWPmDZnj9D01uML1kAlNcR42aC8dSsocb8bDqChfeZf/RBjn
0YEOOuW/ZDu4kHqIPEC2nPwhJCVUhe9Jw6oQC3K8DKf4hDuWbFVn8SrjSyiA9Mg5
OM/w/LtNqQFuMKlaBF7xVk0w3Q4Sl8clKQIDAQABo4IByDCCAcQwggEABgNVHSAE
gfgwgfUwgfIGCWeBBgECAWaDEDCB5DCBuwYIKwYBBQUHAgIwga4agatUZW50byBj
ZXJ0aWZpa2F0IHBybyBlbGVrdHJvbmlja291IHBlY2V0IGJ5bCB2eWRhbiB2IHNv
dWxhZHUgcyBuYXJpemVuaW0gRVUgYy4gOTEwLzIwMTQuVGhpcyBpcyBhIGNlcnRp
ZmljYXRlIGZvciBlbGVjdHJvbmljIHNlYWwgYWNjb3JkaW5nIHRvIFJlZ3VsYXRp
b24gKEVVKSBObyA5MTAvMjAxNC4wJAYIKwYBBQUHAgEWGGh0dHA6Ly93d3cucG9z
dHNpZ251bS5jejBIBggrBgEFBQcBAQQ8MDowOAYIKwYBBQUHMAKGLGh0dHA6Ly9j
cnQucG9zdHNpZ251bS5jei9jcnQvcHNwdWJsaWNjYTUuY3J0MA8GCSsGAQUFBzAB
BQQCBQAwDgYDVR0PAQH/BAQDAgbAMBMGA1UdJQQMMAoGCCsGAQUFBwMJMB8GA1Ud
IwQYMBaAFOPOMVHzTJH1fbcFibF40KMKxkOZMB0GA1UdDgQWBBSvyvpb88Hbuaet
ThA/NRQD8CqUPDANBgkqhkiG9w0BAQsFAAOCAgEAFP+5SEWW6web9qg1ejY8JE+v
YAhC3/bA5hXefHYG69w0gm4hrZR87E32MJgVcvPjMYJhvJLdNIkFsqwDfQXS7oeK
naNp0KAIkurd0NJ9O7K/CsgWCEBRTaotFOU/VOoC0//X2ThWoKaQK++VndWBBN0r
84/2+bb68sU2TBsVV/SK1x4jf4uLKDEbbRH6ysdasQxRwtdGcXzs9fFrq3hY5T89
hzuZ8y3hkIe2RAh/s7+f8LkkuXbEcXJnvIDxPRiHmmWQ0rVKDAUIQUE8Oa+4Yvta
QEGhGmzzeInIhRCIwjoxbGoV6uBJb3ahBadc1an/sLQYXIzbBCq2HMNRDolvzWEB
UqAqeve5VbhCnmukcbfmcMDJp/536TyZwc+zbKdn+mP4b+uFn9m+rHXq0071jZv0
FTp+A5iSALzlTGCR26Pd0ffauOVQ3wBRn1qpaeDcXMKLnmxu/jdfZ8xMBZ44Koig
5vg//gt4jeoWXJwSBPE2Y0cwKztWB1qpX7AyXFAoXYoLHPgQ8u2tYewQa9YCJ/91
oq/oA3VQ3zXvxz+XYxZggmJwTU0lssSQaz2Cu8UgQyevvBGmksSrKlUzXij/Zc6k
Dlls45Vpl4MsSiHKEgWevxsj8CgmIOVpQ62LQPK4FV29h3rDiY8dSnETJkv9u6nt
2zhfrOmq38GeovgtbE8=
```

**Comment by alex** [comment]
So, the reason this is rejected is that `ResponseData` SEQUENCE from RFC 6960 defines the version field as: `version              [0] EXPLICIT Version DEFAULT v1`.

In DER, fields whose values match the `DEFAULT` must _never_ be encoded. But here it is encoded.

Which makes this invalid DER, which is why cryptography rejects it.

I would encourage you to reach out to the CA in question and inform them that their OCSP Responder is returning incorrectly encoded results.

**Comment by kidmin** [comment]
I understand there is a problem in the OCSP response.
Thank you very much for your help.

**Comment by alex** [comment]
FWIW we ran into a similar issue with OCSPRequests generated by macOS and we were able to get them to fix them: https://github.com/pyca/cryptography/issues/6688
