### ISSUE TITLE
Improve third party interop with __subclasshook__

### ISSUE THREAD

**Issue by lvh** [pyca/cryptography#735]
A play in several acts, involving a Python interpreter:

```python
>>> from cryptography.hazmat.backends import default_backend
>>> backend = default_backend()
>>> from pyblake2 import blake2b
>>> from cryptography.hazmat.primitives.kdf.hkdf import HKDF
>>> hkdf = HKDF(blake2b(),length=32, salt=b"hello", info=b"world", backend=backend)
```

Victory! Except: `hkdf.derive("secret")`:

```
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/usr/local/Cellar/python/2.7.5/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-pa
ckages/cryptography/hazmat/primitives/kdf/hkdf.py", line 87, in derive
    return self._expand(self._extract(key_material))
  File "/usr/local/Cellar/python/2.7.5/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-pa
ckages/cryptography/hazmat/primitives/kdf/hkdf.py", line 58, in _extract
    h = hmac.HMAC(self._salt, self._algorithm, backend=self._backend)
  File "/usr/local/Cellar/python/2.7.5/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-pa
ckages/cryptography/hazmat/primitives/hmac.py", line 27, in __init__
    raise TypeError("Expected instance of interfaces.HashAlgorithm.")
TypeError: Expected instance of interfaces.HashAlgorithm.
```
What is this [`HashAlgorithm`](https://cryptography.io/en/latest/hazmat/primitives/interfaces/#cryptography.hazmat.primitives.interfaces.HashAlgorithm)? It is a `name`, `digest_size` and `block_size`. But:

```
>>> h = blake2b()
>>> h.block_size
128
>>> h.digest_size
64
>>> h.name
'blake2b'
```

Perhaps I will inform the ABC of blake2b's special powers:

```
>>> from cryptography.hazmat.primitives.interfaces import HashAlgorithm
>>> HashAlgorithm.register(blake2b)
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/usr/local/Cellar/python/2.7.5/Frameworks/Python.framework/Versions/2.7/lib/python2.7/abc.py"
, line 108, in register
    raise TypeError("Can only register classes")
TypeError: Can only register classes
```

Alas!

Of course, another way would be an adapter in cryptography :)

**Comment by reaperhulk** [comment]
I think we've generally decided not to do this based on the length of time this issue has been sitting (and the difficulty of composing primitives across backends), so I'll close this for now.
