### ISSUE TITLE
Failed to install cryptography

### ISSUE THREAD

**Issue by Divyansh-Gemini** [pyca/cryptography#7544]
#### Chaquopy version
12.0.1

#### Relevant parts of your build.gradle file
        ndk {
            abiFilters "armeabi-v7a", "x86"
        }

        python {
            buildPython "C:/Users/LENOVO/AppData/Local/Programs/Python/Python310/python.exe"

            pip {
                install "camelot-py"
            }
        }

#### Describe your issue
```
Executing tasks: [:app:clean, :app:assembleDebug] in project C:\Users\LENOVO\AndroidStudioProjects\ExtractDatafromPDFTable

> Task :app:clean
> Task :app:preBuild UP-TO-DATE
> Task :app:preDebugBuild UP-TO-DATE
> Task :app:mergeDebugNativeDebugMetadata NO-SOURCE
> Task :app:compileDebugAidl NO-SOURCE
> Task :app:compileDebugRenderscript NO-SOURCE
> Task :app:generateDebugBuildConfig
> Task :app:extractPythonBuildPackages

> Task :app:generateDebugPythonRequirements
Chaquopy: Installing for armeabi-v7a
Looking in indexes: https://pypi.org/simple, https://chaquo.com/pypi-7.0
Collecting camelot-py
  Using cached https://files.pythonhosted.org/packages/3a/d3/08ae34725925bdaf85be36be7a230ba3ed7d6ae8e49a2276f1753620f347/camelot_py-0.10.1-py3-none-any.whl
Collecting chardet>=3.0.4 (from camelot-py)
  Using cached https://files.pythonhosted.org/packages/4c/d1/1b96dd69fa42f20b70701b5cd42a75dd5f0c7a24dc0abfef35cc146210dc/chardet-5.0.0-py3-none-any.whl
Collecting click>=6.7 (from camelot-py)
  Using cached https://files.pythonhosted.org/packages/c2/f1/df59e28c642d583f7dacffb1e0965d0e00b218e0186d7858ac5233dce840/click-8.1.3-py3-none-any.whl
Collecting numpy>=1.13.3 (from camelot-py)
  Using version 1.19.5 (newest version is 1.23.2, but Chaquopy prefers native wheels)
  Using cached https://chaquo.com/pypi-7.0/numpy/numpy-1.19.5-0-cp38-cp38-android_16_armeabi_v7a.whl
Collecting tabulate>=0.8.9 (from camelot-py)
  Using cached https://files.pythonhosted.org/packages/92/4e/e5a13fdb3e6f81ce11893523ff289870c87c8f1f289a7369fb0e9840c3bb/tabulate-0.8.10-py3-none-any.whl
Collecting pdfminer.six>=20200726 (from camelot-py)
  Using cached https://files.pythonhosted.org/packages/92/1c/f0e976509c8d453cb0f1b360619bbc2b588ef733c32780c9e0221918b7fa/pdfminer.six-20220524-py3-none-any.whl
Collecting PyPDF2>=1.26.0 (from camelot-py)
  Using cached https://files.pythonhosted.org/packages/41/e4/0832d46a130c2e94110ef9b973ae22dd2879b9bae0c5e714875656a45c7e/PyPDF2-2.10.3-py3-none-any.whl
Collecting pandas>=0.23.4 (from camelot-py)
  Using version 1.3.2 (newest version is 1.4.3, but Chaquopy prefers native wheels)
  Using cached https://chaquo.com/pypi-7.0/pandas/pandas-1.3.2-0-cp38-cp38-android_16_armeabi_v7a.whl
Collecting openpyxl>=2.5.8 (from camelot-py)
  Using cached https://files.pythonhosted.org/packages/7b/60/9afac4fd6feee0ac09339de4101ee452ea643d26e9ce44c7708a0023f503/openpyxl-3.0.10-py2.py3-none-any.whl
Collecting chaquopy-libgfortran>=4.9 (from numpy>=1.13.3->camelot-py)
  Using cached https://chaquo.com/pypi-7.0/chaquopy-libgfortran/chaquopy_libgfortran-4.9-0-py3-none-android_16_armeabi_v7a.whl
Collecting chaquopy-openblas>=0.2.20 (from numpy>=1.13.3->camelot-py)
  Using cached https://chaquo.com/pypi-7.0/chaquopy-openblas/chaquopy_openblas-0.2.20-5-py3-none-android_16_armeabi_v7a.whl
Collecting charset-normalizer>=2.0.0 (from pdfminer.six>=20200726->camelot-py)
  Using cached https://files.pythonhosted.org/packages/db/51/a507c856293ab05cdc1db77ff4bc1268ddd39f29e7dc4919aa497f0adbec/charset_normalizer-2.1.1-py3-none-any.whl
Collecting cryptography>=36.0.0 (from pdfminer.six>=20200726->camelot-py)
  Using cached https://files.pythonhosted.org/packages/89/d9/5fcd312d5cce0b4d7ee8b551a0ea99e4ea9db0fdbf6dd455a19042e3370b/cryptography-37.0.4.tar.gz
    ERROR: Command errored out with exit status 1:
     command: 'C:\Users\LENOVO\AppData\Local\Programs\Python\Python310\python.exe' -S -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\LENOVO\\AppData\\Local\\Temp\\pip-install-k1aelgpl\\cryptography\\setup.py'"'"'; __file__='"'"'C:\\Users\\LENOVO\\AppData\\Local\\Temp\\pip-install-k1aelgpl\\cryptography\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' --no-user-cfg egg_info --egg-base pip-egg-info
         cwd: C:\Users\LENOVO\AppData\Local\Temp\pip-install-k1aelgpl\cryptography\
    Complete output (14 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\LENOVO\AppData\Local\Temp\pip-install-k1aelgpl\cryptography\setup.py", line 14, in <module>
        from setuptools_rust import RustExtension
    ModuleNotFoundError: No module named 'setuptools_rust'
    
            =============================DEBUG ASSISTANCE==========================
            If you are seeing an error here please try the following to
            successfully install cryptography:
    
            Upgrade to the latest pip and try again. This will fix errors for most
            users. See: https://pip.pypa.io/en/stable/installing/#upgrading-pip
            =============================DEBUG ASSISTANCE==========================
    
    ----------------------------------------
    ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Failed to install cryptography>=36.0.0 from https://files.pythonhosted.org/packages/89/d9/5fcd312d5cce0b4d7ee8b551a0ea99e4ea9db0fdbf6dd455a19042e3370b/cryptography-37.0.4.tar.gz (from pdfminer.six>=20200726->camelot-py).
For assistance, please raise an issue at https://github.com/chaquo/chaquopy/issues.
Or try using one of the following versions, which are available as pre-built wheels: ['2.8', '3.3.2', '3.4.8'].
Chaquopy: Exit status 1

> Task :app:generateDebugPythonRequirements FAILED

> Task :app:mergeDebugPythonSources
Warning: Failed to compile to .pyc format: buildPython version 3.10.4 is incompatible. See https://chaquo.com/chaquopy/doc/current/android.html#android-bytecode.

> Task :app:javaPreCompileDebug
> Task :app:generateDebugResValues
> Task :app:generateDebugResources
> Task :app:checkDebugAarMetadata
> Task :app:packageDebugResources
> Task :app:createDebugCompatibleScreenManifests
> Task :app:extractDeepLinksDebug
> Task :app:parseDebugLocalResources
> Task :app:processDebugMainManifest
> Task :app:processDebugManifest
> Task :app:mergeDebugShaders
> Task :app:compileDebugShaders NO-SOURCE
> Task :app:generateDebugAssets UP-TO-DATE
> Task :app:generateDebugPythonAppAssets
> Task :app:generateDebugPythonLicenseAssets
> Task :app:mergeDebugResources
> Task :app:generateDebugPythonMiscAssets
> Task :app:mapDebugSourceSetPaths
> Task :app:processDebugJavaRes NO-SOURCE
> Task :app:checkDebugDuplicateClasses
> Task :app:desugarDebugFileDependencies
> Task :app:mergeDebugJavaResource
> Task :app:generateDebugPythonJniLibs
> Task :app:mergeLibDexDebug
> Task :app:mergeDebugJniLibFolders
> Task :app:validateSigningDebug
> Task :app:writeDebugAppMetadata
> Task :app:writeDebugSigningConfigVersions
> Task :app:processDebugManifestForPackage
> Task :app:mergeDebugNativeLibs

> Task :app:stripDebugDebugSymbols
Unable to strip the following libraries, packaging them as they are: libchaquopy_java.so, libcrypto_chaquopy.so, libpython3.8.so, libsqlite3_chaquopy.so, libssl_chaquopy.so.

> Task :app:mergeExtDexDebug
> Task :app:processDebugResources

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:generateDebugPythonRequirements'.
> Process 'command 'C:/Users/LENOVO/AppData/Local/Programs/Python/Python310/python.exe'' finished with non-zero exit value 1
  
  To view full details in Android Studio:
  * Click the 'Build: failed' caption to the left of this message.
  * Then scroll up to see the full output.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/7.3.3/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 16s
34 actionable tasks: 34 executed
```
![Screenshot (495)](https://user-images.githubusercontent.com/88696617/187033244-59943142-77a2-4f2b-9988-c0ba043640a6.png)
![Screenshot (496)](https://user-images.githubusercontent.com/88696617/187033279-9022463a-4610-44d3-a979-11ba2d1fc8fd.png)

**Comment by alex** [comment]
Did you try the things suggsted by the DEBUG ASSISTANCE?

It looks to me like gradle isn't using a sufficiently new version of pip.

I don't know anything about gradle, but finding a way to upgrade its pip will almost certainly fix this. In the alternative you could manually install the setuptools-rust dependency.

**Comment by Divyansh-Gemini** [comment]
Issue solved by adding:
```
pip {
    install "camelot-py"
    install "pdfminer.six==20220319"
    install "opencv-python"
}
```

https://stackoverflow.com/questions/73511896/failed-to-install-cryptography-in-android-studio-using-chaquopy
