### ISSUE TITLE
Windows Wheels don't work.

### ISSUE THREAD

**Issue by mhils** [pyca/cryptography#762]
Hi there,

the Windows wheel for cryptography on PyPI doesn't work. 
While it installs properly, it requires the msvc compiler on its first run.

<pre>
C:\Python27\Scripts>pip install https://pypi.python.org/packages/cp27/c/cryptogr
aphy/cryptography-0.2.2-cp27-none-win32.whl#md5=7f3979da8340a7fe3aa859d3bfc1a5f1
[...]
Successfully installed cryptography cffi six pycparser
Cleaning up...
</pre>

<pre>
C:\Python27>python
Python 2.7.6 (default, Nov 10 2013, 19:24:18) [MSC v.1500 32 bit (Intel)] on win
32
Type "help", "copyright", "credits" or "license" for more information.
>>> from cryptography import fernet
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python27\lib\site-packages\cryptography\fernet.py", line 23, in <modu
le>
    from cryptography.hazmat.backends import default_backend
  File "C:\Python27\lib\site-packages\cryptography\hazmat\backends\__init__.py",
 line 14, in <module>
    from cryptography.hazmat.backends import openssl
  File "C:\Python27\lib\site-packages\cryptography\hazmat\backends\openssl\__ini
t__.py", line 14, in <module>
    from cryptography.hazmat.backends.openssl.backend import backend
  File "C:\Python27\lib\site-packages\cryptography\hazmat\backends\openssl\backe
nd.py", line 564, in <module>
    backend = Backend()
  File "C:\Python27\lib\site-packages\cryptography\hazmat\backends\openssl\backe
nd.py", line 48, in __init__
    self._binding = Binding()
  File "C:\Python27\lib\site-packages\cryptography\hazmat\bindings\openssl\bindi
ng.py", line 83, in __init__
    self._ensure_ffi_initialized()
  File "C:\Python27\lib\site-packages\cryptography\hazmat\bindings\openssl\bindi
ng.py", line 99, in _ensure_ffi_initialized
    libraries)
  File "C:\Python27\lib\site-packages\cryptography\hazmat\bindings\utils.py", li
ne 72, in build_ffi
    ext_package="cryptography",
  File "C:\Python27\lib\site-packages\cffi\api.py", line 341, in verify
    lib = self.verifier.load_library()
  File "C:\Python27\lib\site-packages\cffi\verifier.py", line 74, in load_librar
y
    self._compile_module()
  File "C:\Python27\lib\site-packages\cffi\verifier.py", line 139, in _compile_m
odule
    outputfilename = ffiplatform.compile(tmpdir, self.get_extension())
  File "C:\Python27\lib\site-packages\cffi\ffiplatform.py", line 25, in compile
    outputfilename = _build(tmpdir, ext)
  File "C:\Python27\lib\site-packages\cffi\ffiplatform.py", line 47, in _build
    dist.run_command('build_ext')
  File "C:\Python27\lib\distutils\dist.py", line 972, in run_command
    cmd_obj.run()
  File "C:\Python27\lib\distutils\command\build_ext.py", line 337, in run
    self.build_extensions()
  File "C:\Python27\lib\distutils\command\build_ext.py", line 446, in build_exte
nsions
    self.build_extension(ext)
  File "C:\Python27\lib\distutils\command\build_ext.py", line 496, in build_exte
nsion
    depends=ext.depends)
  File "C:\Python27\lib\distutils\msvc9compiler.py", line 473, in compile
    self.initialize()
  File "C:\Python27\lib\distutils\msvc9compiler.py", line 383, in initialize
    vc_env = query_vcvarsall(VERSION, plat_spec)
  File "C:\Python27\lib\distutils\msvc9compiler.py", line 271, in query_vcvarsal
l
    raise DistutilsPlatformError("Unable to find vcvarsall.bat")
distutils.errors.DistutilsPlatformError: Unable to find vcvarsall.bat
</pre>

With Visual Studio 9 installed, I end up with 

<pre>
_cffi__x969a4f6ex69432c5f.c
C:\Python27\lib\site-packages\cryptography\hazmat\bindings\__pycache__\_cffi__x9
69a4f6ex69432c5f.c(165) : fatal error C1083: Cannot open include file: 'openssl/
aes.h': No such file or directory
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python27\lib\site-packages\cryptography\fernet.py", line 23, in <modu
le>
    from cryptography.hazmat.backends import default_backend
  File "C:\Python27\lib\site-packages\cryptography\hazmat\backends\__init__.py",
 line 14, in <module>
    from cryptography.hazmat.backends import openssl
  File "C:\Python27\lib\site-packages\cryptography\hazmat\backends\openssl\__ini
t__.py", line 14, in <module>
    from cryptography.hazmat.backends.openssl.backend import backend
  File "C:\Python27\lib\site-packages\cryptography\hazmat\backends\openssl\backe
nd.py", line 564, in <module>
    backend = Backend()
  File "C:\Python27\lib\site-packages\cryptography\hazmat\backends\openssl\backe
nd.py", line 48, in __init__
    self._binding = Binding()
  File "C:\Python27\lib\site-packages\cryptography\hazmat\bindings\openssl\bindi
ng.py", line 83, in __init__
    self._ensure_ffi_initialized()
  File "C:\Python27\lib\site-packages\cryptography\hazmat\bindings\openssl\bindi
ng.py", line 99, in _ensure_ffi_initialized
    libraries)
  File "C:\Python27\lib\site-packages\cryptography\hazmat\bindings\utils.py", li
ne 72, in build_ffi
    ext_package="cryptography",
  File "C:\Python27\lib\site-packages\cffi\api.py", line 341, in verify
    lib = self.verifier.load_library()
  File "C:\Python27\lib\site-packages\cffi\verifier.py", line 74, in load_librar
y
    self._compile_module()
  File "C:\Python27\lib\site-packages\cffi\verifier.py", line 139, in _compile_m
odule
    outputfilename = ffiplatform.compile(tmpdir, self.get_extension())
  File "C:\Python27\lib\site-packages\cffi\ffiplatform.py", line 25, in compile
    outputfilename = _build(tmpdir, ext)
  File "C:\Python27\lib\site-packages\cffi\ffiplatform.py", line 50, in _build
    raise VerificationError('%s: %s' % (e.__class__.__name__, e))
cffi.ffiplatform.VerificationError: CompileError: command '"C:\Program Files (x8
6)\Microsoft Visual Studio 9.0\VC\BIN\cl.exe"' failed with exit status 2
</pre>

Any pointers on how to fix that would be appreciated.

Thanks,
Max

**Comment by qianqianxiao** [comment]
I used pip install -I cffi==0.8.1, but when I used easy_install requests[security], It's already have this error

**Comment by reaperhulk** [comment]
This issue is a year old and the cffi problem described above is not an issue with current versions of cryptography. If you are getting an error claiming it can't find vcvarsall or a compiler please verify that your version of `pip` is the latest. Versions of pip older than 1.5 do not install wheels by default.

**Comment by reaperhulk** [comment]
Additionally, `easy_install` does not support wheels at all (as well as being a deprecated and inadvisable way to install python packages).

**Comment by qianqianxiao** [comment]
I used pip install requests[security], It's success. thinks for your help.

**Comment by dcl-lily** [comment]
_openssl.c
build\temp.win-amd64-2.7\Release\_openssl.c(429) : fatal error C1083: Cannot open include file: 'openssl/opensslv.h': No such file or directory
error: [Error 5] : 'c:\\users\\alex\\appdata\\local\\temp\\easy_install-lr3blj\\cryptography-1.4\\.eggs\\cffi-1.7.0-py2.7-win-amd64.egg\\_cffi_backend.pyd'

**Comment by ivictbor** [comment]
> 'openssl/opensslv.h': No such file or directory

dcl-lily, please try 
`python -m pip install --upgrade pip `
and 
`pip2 install cryptography`
I had same today
