### ISSUE TITLE
Decrypting messages on Windows 10 throws InvalidToken exception

### ISSUE THREAD

**Issue by saukijan** [pyca/cryptography#7797]
When we are trying to decrypt a UTF-8 string on Windows 10, **cryptography** module throws a `cryptography.fernet.InvalidToken` exception, even though the same string was successfully encrypted previously. Running the exact same code on Debian 11 works as expected.

<details>
<summary>Code to reproduce the issue</summary>

```python
from cryptography.fernet import Fernet
from base64 import urlsafe_b64encode
import keyring
import platform
import traceback
import logging
import subprocess


def _is_stdout(result: subprocess.CompletedProcess):
    if result.stderr == str():
        if result.stdout == str():
            return False
        else:
            return True
    else:
        return False


class __rpm:
    @staticmethod
    def check(name: str):
        result = subprocess.run(['rpm', '-q', name],
                                capture_output=True,
                                text=True
                                )
        return _is_stdout(result)


class __dpkg:
    @staticmethod
    def check(name: str):
        result = subprocess.run(['dpkg', '-l', name],
                                capture_output=True,
                                text=True
                                )
        return _is_stdout(result)


def __which(name: str):
    result = subprocess.run(['which', name],
                            capture_output=True,
                            text=True
                            )
    return _is_stdout(result)


def get_pkg_manager():
    if __which('dpkg'):
        return __dpkg()
    elif __which('rpm'):
        return __rmp()
    else:
        return None


def check_pkg(name: str):
    pkg_manager = get_pkg_manager()
    if pkg_manager is not None:
        return pkg_manager.check(name)


class Auth:
    def __init__(self, service_name: str):
        # Logger setup
        self.logger = logging.getLogger(__name__)
        self.logger.setLevel(logging.DEBUG)
        stream_handler = logging.StreamHandler()  # print to console
        formatter = logging.Formatter(
            '%(asctime)s | %(levelname)s | %(filename)s - %(message)s')
        stream_handler.setFormatter(formatter)
        self.logger.addHandler(stream_handler)

        # Cryptography setup
        self.service_name = service_name
        encryption_string = '1234567890abcdefghijklmnopqrstuv'  # used for testing only
        byte_string = bytes(encryption_string, 'utf-8')
        self.logger.debug(
            'Creating Fernet encryption key from byte string: {}'.format(byte_string))
        key = urlsafe_b64encode(byte_string)
        self.logger.debug('Setting Fernet encryption key to: {}'.format(key))
        self.crypto = Fernet(key)
        self.logger.debug('Fernet encryption key is set to: {}'.format(
            self.crypto._encryption_key))

        # Set Cryptography keyring backend
        system = platform.system()
        if system == 'Darwin':
            import keyring.backends.OS_X as backend
            keyring.set_keyring(backend.Keyring())
        elif system == 'Windows':
            import keyring.backends.Windows as backend
            keyring.set_keyring(backend.WinVaultKeyring())
        elif system == 'Linux':
            # check if kwalletmanager is installed
            if check_pkg('kwalletmanager') is True:
                import keyring.backends.kwallet as backend
                keyring.set_keyring(backend.DBusKeyring())
            # check if gnome-keyring is installed
            elif check_pkg('gnome-keyring') is True:
                import keyring.backends.SecretService as backend
                keyring.set_keyring(backend.Keyring())
        else:
            pass  # rely on autodiscovery for other platforms

    def saveCredentials(self, user: str, auth: str):
        try:
            self.logger.debug(
                'Saving credentials for User: {} with Auth: {}'.format(user, auth))
            self.logger.debug('Fernet encrypts authentication token with encription key {}'.format(
                self.crypto._encryption_key))
            hashed_auth = self.crypto.encrypt(bytes(auth, 'utf-8'))
            self.logger.debug(
                'Saving authentication in the keyring as: {}'.format(hashed_auth))
            keyring.set_password(self.service_name, user, hashed_auth)
            self.logger.info(
                'User-auth pair saved in keyring as: {}, {}'.format(self.service_name, user))
        except Exception as ex:
            error = ''.join(
                traceback.format_exception(None, ex, ex.__traceback__))
            raise RuntimeError(
                'Received an exception while encrypting authentication token for user {}. Exception: {}'.format(user, error))

    def getAuth(self, user: str):
        self.logger.debug('Using service: {} to fetch User {} authentication'.format(
            self.service_name, user))
        auth = str()
        try:  # get_credential throws if user does not exist
            hashed_auth = keyring.get_password(self.service_name, user)
            if hashed_auth is not None:
                self.logger.debug(
                    'Found hashed auth value: {} for user {}'.format(hashed_auth, user))
                self.logger.debug('Fernet decrypts authentication token with encription key {}'.format(
                    self.crypto._encryption_key))
                auth = self.crypto.decrypt(
                    bytes(hashed_auth, 'utf-8')).decode('utf-8')
                self.logger.info(
                    'Authentication token decrypted as: {} for user {}'.format(auth, user))
            else:
                self.logger.error('No authentication found in service {} for user {}'.format(
                    self.service_name, user))
        except Exception as ex:
            error = ''.join(
                traceback.format_exception(None, ex, ex.__traceback__))
            self.logger.error(
                'Received an exception while decrypting authentication token. Exception: {}'.format(error))
        return auth


if __name__ == '__main__':
    auth = Auth('TestAuth')
    auth.saveCredentials('test', 'secret')
    token = auth.getAuth('test')
    if token == 'secret':
        print('SUCCESS. Authentication token is correct!')
    else:
        print('FAILURE. Authentication token is wrong')
```
</details>

<details>
<summary>Output on Debian</summary>

```bash
2022-11-11 14:32:01,450 | DEBUG | crypto_test.py - Creating Fernet encryption key from byte string: b'1234567890abcdefghijklmnopqrstuv'
2022-11-11 14:32:01,450 | DEBUG | crypto_test.py - Setting Fernet encryption key to: b'MTIzNDU2Nzg5MGFiY2RlZmdoaWprbG1ub3BxcnN0dXY='
2022-11-11 14:32:01,451 | DEBUG | crypto_test.py - Fernet encryption key is set to: b'ghijklmnopqrstuv'
2022-11-11 14:32:01,596 | DEBUG | crypto_test.py - Saving credentials for User: test with Auth: secret
2022-11-11 14:32:01,598 | DEBUG | crypto_test.py - Fernet encrypts authentication token with encription key b'ghijklmnopqrstuv'
2022-11-11 14:32:01,602 | DEBUG | crypto_test.py - Saving authentication in the keyring as: b'gAAAAABjbk7RlyLXmj81EgziNQbnEuvtL4J-f828c1l8Ll08OOJw1l_bLwM5mKaWZu2sWAs8mM4Nn2JpgKkNU_umtEQbCu9sLQ=='
2022-11-11 14:32:01,614 | INFO | crypto_test.py - User-auth pair saved in keyring as: TestAuth, test
2022-11-11 14:32:01,615 | DEBUG | crypto_test.py - Using service: TestAuth to fetch User test authentication
2022-11-11 14:32:01,616 | DEBUG | crypto_test.py - Found hashed auth value: gAAAAABjbk7RlyLXmj81EgziNQbnEuvtL4J-f828c1l8Ll08OOJw1l_bLwM5mKaWZu2sWAs8mM4Nn2JpgKkNU_umtEQbCu9sLQ== for user test
2022-11-11 14:32:01,617 | DEBUG | crypto_test.py - Fernet decrypts authentication token with encription key b'ghijklmnopqrstuv'
2022-11-11 14:32:01,618 | INFO | crypto_test.py - Authentication token decrypted as: secret for user test
SUCCESS. Authentication token is correct!
```

</details>

<details>
<summary>Output on Windows</summary>

```bash
2022-11-11 14:32:26,311 | DEBUG | crypto_test.py - Creating Fernet encryption key from byte string: b'1234567890abcdefghijklmnopqrstuv'
2022-11-11 14:32:26,311 | DEBUG | crypto_test.py - Setting Fernet encryption key to: b'MTIzNDU2Nzg5MGFiY2RlZmdoaWprbG1ub3BxcnN0dXY='
2022-11-11 14:32:26,311 | DEBUG | crypto_test.py - Fernet encryption key is set to: b'ghijklmnopqrstuv'
2022-11-11 14:32:26,381 | DEBUG | crypto_test.py - Saving credentials for User: test with Auth: secret
2022-11-11 14:32:26,381 | DEBUG | crypto_test.py - Fernet encrypts authentication token with encription key b'ghijklmnopqrstuv'
2022-11-11 14:32:26,383 | DEBUG | crypto_test.py - Saving authentication in the keyring as: b'gAAAAABjbk7qzpwMI_rS6ppnLCN5svKcQNJX2Gin410zpOGBQHiYOB5RZhXuoT-DGc6Seu5LhJZX8ZGpmKIYB5j-yNRo_OXuwA=='
2022-11-11 14:32:26,400 | INFO | crypto_test.py - User-auth pair saved in keyring as: TestAuth, test
2022-11-11 14:32:26,400 | DEBUG | crypto_test.py - Using service: TestAuth to fetch User test authentication
2022-11-11 14:32:26,401 | DEBUG | crypto_test.py - Found hashed auth value: b'gAAAAABjbk7qzpwMI_rS6ppnLCN5svKcQNJX2Gin410zpOGBQHiYOB5RZhXuoT-DGc6Seu5LhJZX8ZGpmKIYB5j-yNRo_OXuwA==' for user test
2022-11-11 14:32:26,401 | DEBUG | crypto_test.py - Fernet decrypts authentication token with encription key b'ghijklmnopqrstuv'
2022-11-11 14:32:26,403 | ERROR | crypto_test.py - Received an exception while decrypting authentication token. Exception: Traceback (most recent call last):
  File "c:\Users\devel\Desktop\crypto_test.py", line 135, in getAuth
    auth = self.crypto.decrypt(
  File "C:\Users\devel\AppData\Local\Programs\Python\Python310\lib\site-packages\cryptography\fernet.py", line 85, in decrypt
    timestamp, data = Fernet._get_unverified_token_data(token)
  File "C:\Users\devel\AppData\Local\Programs\Python\Python310\lib\site-packages\cryptography\fernet.py", line 121, in _get_unverified_token_data
    raise InvalidToken
cryptography.fernet.InvalidToken

FAILURE. Authentication token is wrong
```

</details>

## Environment setup

cryptography package installed via **pip** on both Debian and Windows systems with: 

```bash
pip install cryptography 
```

<details>
<summary>Windows Setup</summary>

Windows 10 Enterprise version 21H2 OS Build 19044.2130

- Python 3.10.4
- pip 22.3.1
- setuptools 65.5.1
- cffi 1.15.1
- cryptography 38.0.3

</details>

<details>
<summary>Debian Setup</summary>

Debian Bullseye with KDE Plasma 5.20.5 Kernel Version 5.10.0-18-amd64

- Python 3.9.2
- pip 22.3.1
- setuptools 65.5.1
- cffi 1.15.1
- cryptography 38.0.3

</details>

**Comment by alex** [comment]
Somehow you are corrupting your input strings. If you look closely at the output on debian vs. windows you will see that on debian the hashed output is starts with a `g`, but on windows it starts with the `b'` prefix. This tells me you have a python string whose first character is `b`.

I don't know what's causing this, but it's not a bug in cryptography.

**Comment by saukijan** [comment]
Thanks for the quick reply! 

You are right, this looks like a keyring issue then. 

It looks like it's saving a byte string on windows, and a plain string on debian. I'll see if interpetring the string on Windows as a byte string helps.

**Comment by saukijan** [comment]
Yup, that was the issue, Debian keyring automatically decodes the byte string as a UTF-8 string before saving it, whereas Windows just saves it as is.
