### ISSUE TITLE
Incompatability with Alpine3.17 Docker container - OpenSSL FIPS_mode_set: symbol not found error

### ISSUE THREAD

**Issue by mrcoles** [pyca/cryptography#7868]
I’m suddenly getting the error “OpenSSL FIPS_mode_set: symbol not found error” in my `python:3.9-alpine` Docker container, which appears to have jumped from alpine3.16 to alpine3.17.

**Versions:**

* Docker container python:3.9.15-alpine3.17
* Python 3.9.15
* pip 22.0.4 from /usr/local/lib/python3.9/site-packages/pip (python 3.9)
* cryptography==3.3.2

**Installed via:**

* Inside a Docker container `python:3.9.15-alpine3.17`
* I’m using cryptography via this other python dependency: django-rest-knox==4.1.0 (https://james1345.github.io/django-rest-knox/)

**Steps to reproduce:**

Inside a python shell, I run the follow:

```python
from project.users.models import User;
from knox.models import AuthToken;
u = User.objects.get(id=1);
_, token = AuthToken.objects.create(user=u, expiry=None)
```

I get the error:

```bash
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/code.py", line 90, in runcode
    exec(code, self.locals)
  File "<console>", line 1, in <module>
  File "/usr/local/lib/python3.9/site-packages/knox/models.py", line 15, in create
    digest = crypto.hash_token(token, salt)
  File "/usr/local/lib/python3.9/site-packages/knox/crypto.py", line 31, in hash_token
    digest = hashes.Hash(sha(), backend=default_backend())
  File "/usr/local/lib/python3.9/site-packages/cryptography/hazmat/backends/__init__.py", line 15, in default_backend
    from cryptography.hazmat.backends.openssl.backend import backend
  File "/usr/local/lib/python3.9/site-packages/cryptography/hazmat/backends/openssl/__init__.py", line 7, in <module>
    from cryptography.hazmat.backends.openssl.backend import backend
  File "/usr/local/lib/python3.9/site-packages/cryptography/hazmat/backends/openssl/backend.py", line 117, in <module>
    from cryptography.hazmat.bindings.openssl import binding
  File "/usr/local/lib/python3.9/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 14, in <module>
    from cryptography.hazmat.bindings._openssl import ffi, lib
ImportError: Error relocating /usr/local/lib/python3.9/site-packages/cryptography/hazmat/bindings/_openssl.abi3.so: FIPS_mode_set: symbol not found
```

**How to fix:**

If I switch my Docker image to be `python:3.9-alpine3.16` instead of `python:3.9` (which is alpine3.17), then it works again.

I’m not sure where the right place is to report this, but let me know if this helps or if you need more information!

**Comment by alex** [comment]
Is your installation installing cryptography from a wheel or from an sdist?

**Comment by Tiwarim386** [comment]
> OpenSSL FIPS_mode_set: symbol not found error

wheel

**Comment by ryrebs** [comment]
I got the same error. 
Using matching versions below seems to solve the issue for me.

```
alpine 3.16  (contains openssl 1.1.1s)
cryptography == 3.4.7

```
or 

```
alpine 3.17  (contains openssl 3.0.7-r0)
cryptography == 3.4.8
```

**Comment by kaimast** [comment]
I see a similar issue when installing cryptography 3.4.4 from source on Arch Linux.

```
  File "/home/kai/dev/pyenv/lib/python3.10/site-packages/pkg_resources/__init__.py", line 1466, in run_script
    exec(script_code, namespace, namespace)
  File "/home/kai/dev/pyenv/lib/python3.10/site-packages/geni_lib-0.9.9.5-py3.10.egg/EGG-INFO/scripts/build-context", line 80, in <module>
  File "/home/kai/dev/pyenv/lib/python3.10/site-packages/geni_lib-0.9.9.5-py3.10.egg/EGG-INFO/scripts/build-context", line 62, in main
  File "/home/kai/dev/pyenv/lib/python3.10/site-packages/geni_lib-0.9.9.5-py3.10.egg/EGG-INFO/scripts/build-context", line 31, in parse_cert
  File "/home/kai/dev/pyenv/lib/python3.10/site-packages/cryptography-3.4.4-py3.10-linux-x86_64.egg/cryptography/x509/base.py", line 398, in load_pem_x509_certificate
    backend = _get_backend(backend)
  File "/home/kai/dev/pyenv/lib/python3.10/site-packages/cryptography-3.4.4-py3.10-linux-x86_64.egg/cryptography/hazmat/backends/__init__.py", line 23, in _get_backend
    return default_backend()
  File "/home/kai/dev/pyenv/lib/python3.10/site-packages/cryptography-3.4.4-py3.10-linux-x86_64.egg/cryptography/hazmat/backends/__init__.py", line 14, in default_backend
    from cryptography.hazmat.backends.openssl.backend import backend
  File "/home/kai/dev/pyenv/lib/python3.10/site-packages/cryptography-3.4.4-py3.10-linux-x86_64.egg/cryptography/hazmat/backends/openssl/__init__.py", line 6, in <module>
    from cryptography.hazmat.backends.openssl.backend import backend
  File "/home/kai/dev/pyenv/lib/python3.10/site-packages/cryptography-3.4.4-py3.10-linux-x86_64.egg/cryptography/hazmat/backends/openssl/backend.py", line 113, in <module>
    from cryptography.hazmat.bindings.openssl import binding
  File "/home/kai/dev/pyenv/lib/python3.10/site-packages/cryptography-3.4.4-py3.10-linux-x86_64.egg/cryptography/hazmat/bindings/openssl/binding.py", line 14, in <module>
    from cryptography.hazmat.bindings._openssl import ffi, lib
ImportError: /home/kai/dev/pyenv/lib/python3.10/site-packages/cryptography-3.4.4-py3.10-linux-x86_64.egg/cryptography/hazmat/bindings/_openssl.abi3.so: undefined symbol: FIPS_mode
```

I am trying to use an older version as newer versions of cryptography cannot open the certificates I use anymore. 

Is this older version still compatible with OpenSSL3 or could that be the culprit potentially?

**Comment by alex** [comment]
cryptography 35 is the first version that supports compiling against OpenSSL 3

**Comment by kaimast** [comment]
Actually I seem to encounter the same on the the `main` branch

```
  File "/home/kai/dev/pyenv/lib/python3.10/site-packages/geni_lib-0.9.9.5-py3.10.egg/geni/aggregate/core.py", line 226, in create_sliver
  File "/home/kai/dev/pyenv/lib/python3.10/site-packages/geni_lib-0.9.9.5-py3.10.egg/geni/aggregate/apis.py", line 135, in create_sliver
  File "/home/kai/dev/pyenv/lib/python3.10/site-packages/geni_lib-0.9.9.5-py3.10.egg/geni/aggregate/context.py", line 323, in get_slice_info
  File "/home/kai/dev/pyenv/lib/python3.10/site-packages/geni_lib-0.9.9.5-py3.10.egg/geni/aggregate/context.py", line 54, in __init__
  File "/home/kai/dev/pyenv/lib/python3.10/site-packages/geni_lib-0.9.9.5-py3.10.egg/geni/aggregate/context.py", line 63, in _build
  File "/home/kai/dev/pyenv/lib/python3.10/site-packages/geni_lib-0.9.9.5-py3.10.egg/geni/aggregate/context.py", line 78, in _download_credentials
  File "/home/kai/dev/pyenv/lib/python3.10/site-packages/geni_lib-0.9.9.5-py3.10.egg/geni/aggregate/frameworks.py", line 422, in get_slice_credentials
  File "/home/kai/dev/pyenv/lib/python3.10/site-packages/geni_lib-0.9.9.5-py3.10.egg/geni/aggregate/context.py", line 203, in ucred_api3
  File "/home/kai/dev/pyenv/lib/python3.10/site-packages/geni_lib-0.9.9.5-py3.10.egg/geni/aggregate/context.py", line 263, in _ucred_info
  File "/home/kai/dev/pyenv/lib/python3.10/site-packages/geni_lib-0.9.9.5-py3.10.egg/geni/aggregate/context.py", line 168, in userurn
  File "/home/kai/dev/pyenv/lib/python3.10/site-packages/geni_lib-0.9.9.5-py3.10.egg/geni/aggregate/frameworks.py", line 210, in userurn
  File "/home/kai/dev/pyenv/lib/python3.10/site-packages/cryptography-39.0.0.dev1-py3.10-linux-x86_64.egg/cryptography/hazmat/backends/__init__.py", line 8, in default_backend
    from cryptography.hazmat.backends.openssl.backend import backend
  File "/home/kai/dev/pyenv/lib/python3.10/site-packages/cryptography-39.0.0.dev1-py3.10-linux-x86_64.egg/cryptography/hazmat/backends/openssl/__init__.py", line 6, in <module>
    from cryptography.hazmat.backends.openssl.backend import backend
  File "/home/kai/dev/pyenv/lib/python3.10/site-packages/cryptography-39.0.0.dev1-py3.10-linux-x86_64.egg/cryptography/hazmat/backends/openssl/backend.py", line 63, in <module>
    from cryptography.hazmat.bindings.openssl import binding
  File "/home/kai/dev/pyenv/lib/python3.10/site-packages/cryptography-39.0.0.dev1-py3.10-linux-x86_64.egg/cryptography/hazmat/bindings/openssl/binding.py", line 14, in <module>
    from cryptography.hazmat.bindings._openssl import ffi, lib
ImportError: /home/kai/dev/pyenv/lib/python3.10/site-packages/cryptography-39.0.0.dev1-py3.10-linux-x86_64.egg/cryptography/hazmat/bindings/_openssl.abi3.so: undefined symbol: FIPS_mode
```
