### ISSUE TITLE
Runtime error: incompatible architecture (have 'arm64', need 'x86_64'))

### ISSUE THREAD

**Issue by rcwestlake** [pyca/cryptography#8170]
I get an error when I run my app. This started happening after reinstalling of my packages with `pip install -r requirements.txt`. 

```
python - 3.8.9
pip - 22.3.1
cffi - 1.15.1
cryptography - 3.4.8
```

I get this error:

```
Traceback (most recent call last):
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/ryanwestlake/Documents/Dev/challenger-api/venv/lib/python3.8/site-packages/django/utils/autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "/Users/ryanwestlake/Documents/Dev/challenger-api/venv/lib/python3.8/site-packages/django/core/management/commands/runserver.py", line 125, in inner_run
    autoreload.raise_last_exception()
  File "/Users/ryanwestlake/Documents/Dev/challenger-api/venv/lib/python3.8/site-packages/django/utils/autoreload.py", line 87, in raise_last_exception
    raise _exception[1]
  File "/Users/ryanwestlake/Documents/Dev/challenger-api/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 398, in execute
    autoreload.check_errors(django.setup)()
  File "/Users/ryanwestlake/Documents/Dev/challenger-api/venv/lib/python3.8/site-packages/django/utils/autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "/Users/ryanwestlake/Documents/Dev/challenger-api/venv/lib/python3.8/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/Users/ryanwestlake/Documents/Dev/challenger-api/venv/lib/python3.8/site-packages/django/apps/registry.py", line 116, in populate
    app_config.import_models()
  File "/Users/ryanwestlake/Documents/Dev/challenger-api/venv/lib/python3.8/site-packages/django/apps/config.py", line 269, in import_models
    self.models_module = import_module(models_module_name)
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/ryanwestlake/Documents/Dev/challenger-api/onboarding/models.py", line 7, in <module>
    from django_cryptography.fields import encrypt
  File "/Users/ryanwestlake/Documents/Dev/challenger-api/venv/lib/python3.8/site-packages/django_cryptography/fields.py", line 9, in <module>
    from django_cryptography.core.signing import SignatureExpired
  File "/Users/ryanwestlake/Documents/Dev/challenger-api/venv/lib/python3.8/site-packages/django_cryptography/core/signing.py", line 23, in <module>
    from ..utils.crypto import constant_time_compare, salted_hmac
  File "/Users/ryanwestlake/Documents/Dev/challenger-api/venv/lib/python3.8/site-packages/django_cryptography/utils/crypto.py", line 5, in <module>
    from cryptography.hazmat.primitives import constant_time, hashes, padding
  File "/Users/ryanwestlake/Documents/Dev/challenger-api/venv/lib/python3.8/site-packages/cryptography/hazmat/primitives/padding.py", line 11, in <module>
    from cryptography.hazmat.bindings._padding import lib
ImportError: dlopen(/Users/ryanwestlake/Documents/Dev/challenger-api/venv/lib/python3.8/site-packages/cryptography/hazmat/bindings/_padding.abi3.so, 0x0002): tried: '/Users/ryanwestlake/Documents/Dev/challenger-api/venv/lib/python3.8/site-packages/cryptography/hazmat/bindings/_padding.abi3.so' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64'))
```

**Comment by alex** [comment]
Please provide instructions for reproducing, we support and test for macOS on both arm64 and x86-64.

Based on the error I suspected you installed cryptography with an arm64 python and are now importing it with a rosetta2 (aka x86-64) python.

Please note that cryptography 3.4.8 is not supported anymore, so you may need to upgrade.

**Comment by rcwestlake** [comment]
Thanks @alex. I can try to create a reproducible repo. This is in our private repo. Basically, through creating a new virtual env, the old one got wiped out and now trying to initialize the virtual env is throwing this error. 

In the case where cryptography was installed with an arm64 python and now importing it with a rosetta2 (aka x86-64) python, how should I look at fixing? I can also upgrade to a supported version.

**Comment by reaperhulk** [comment]
It is unwise to ever build a venv for one arch and then use it under another. If all your native code is universal (Apple's term for binaries that contain multiple architectures) this will work, but if not then you'll get failures like this.

The best solution is to simply not do that. If that is (for whatever reason) not possible, then you need to ensure you have `universal2` wheels or build them yourself. `cryptography` ships those wheels in 36+.

**Comment by rcwestlake** [comment]
@reaperhulk Thanks. I joined this project a couple a couple years ago. At the time the main dev had an older mac so you can assume the `venv` was built for that arch. I was given an M1. I do remember that there were package install issues back then but somehow got passed them. I took over the project about six months ago. Forgive me for asking such an elementary question but it's not quite my expertise yet. If the best solution is to simply not mix archs, is it best to use something like Docker to ensure that the same env is being used every time?

**Comment by rcwestlake** [comment]
@alex and @reaperhulk I resolved this and will go ahead and close. I mistakenly was running a terminal (on my m1 machine) outside of Rosetta mode. I'm assuming that this was causing the incompatibility failures.

I also upgraded to a supported version of `cryptography`. After that, everything is back to running as expected. 

Thanks for the quick responses and pointing me in the right direction.
