### ISSUE TITLE
module 'cryptography.utils' has no attribute 'register_interface'

### ISSUE THREAD

**Issue by cross-hello** [pyca/cryptography#8255]
```sh
pip list |grep cryptography
> cryptography          39.0.1
```

replicate steps:
```python
>>> from scapy.all import *
>>> load_layer('tls')
ERROR: Loading module scapy.layers.tls.all
Traceback (most recent call last):
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\scapy\main.py", line 163, in _load
    mod = importlib.import_module(module)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\scapy\layers\tls\all.py", line 10, in <module>
    from scapy.layers.tls.cert import *  # noqa: F401
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\scapy\layers\tls\cert.py", line 47, in <module>
    from scapy.layers.tls.crypto.pkcs1 import pkcs_os2ip, _get_hash, \
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\scapy\layers\tls\crypto\pkcs1.py", line 98, in <module>
    @utils.register_interface(HashAlgorithm)
     ^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'cryptography.utils' has no attribute 'register_interface'

```

**Comment by alex** [comment]
You'll want to upgrade to scapy 2.5, which fixes this: https://github.com/secdev/scapy/commit/bb1ed01d469a2b155910f4b689cb1d0c7837225e

`register_interface` was never a public API, so we do not consider it a backwards-incompatible change to remove it.

**Comment by cross-hello** [comment]
[shy]  We may use another package for cryptography. So after uninstall `cryptography`,  code become normal,
