### ISSUE TITLE
AttributeError: module 'cryptography.utils' has no attribute 'Enum'

### ISSUE THREAD

**Issue by fhempy** [pyca/cryptography#9082]
* Versions of Python, ``cryptography``, ``cffi``, ``pip``, and ``setuptools``
  you're using
Python: 3.9.2
cryptography: 41.0.1
cffi: 1.15.1
pip: 23.1.2
setuptools: 67.8.0

* How you installed ``cryptography``
pip3 install -U cryptography

* Clear steps for reproducing your bug
I'm the maintainer of fhempy, which is an addon for an open source smart home solution. I'm using cryptography as part of the aiohomekit library. Unfortunately I have issues during the import of cryptography, see the log stacktrace below.
```
Failed to load module homekit: Traceback (most recent call last):
  File "/opt/fhem/.local/lib/python3.9/site-packages/fhempy/lib/fhem_pythonbinding.py", line 336, in handle_function
    module_object = await self.import_module(hash)
  File "/opt/fhem/.local/lib/python3.9/site-packages/fhempy/lib/fhem_pythonbinding.py", line 573, in import_module
    module_object = await utils.run_blocking(
  File "/opt/fhem/.local/lib/python3.9/site-packages/fhempy/lib/utils.py", line 72, in run_blocking
    return await asyncio.get_event_loop().run_in_executor(pool, function)
  File "/usr/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/fhem/.local/lib/python3.9/site-packages/fhempy/lib/homekit/homekit.py", line 5, in <module>
    import aiohomekit
  File "/opt/fhem/.local/lib/python3.9/site-packages/aiohomekit/__init__.py", line 46, in <module>
    from .controller import Controller
  File "/opt/fhem/.local/lib/python3.9/site-packages/aiohomekit/controller/__init__.py", line 19, in <module>
    from .abstract import TransportType
  File "/opt/fhem/.local/lib/python3.9/site-packages/aiohomekit/controller/abstract.py", line 28, in <module>
    from aiohomekit.model import Accessories, AccessoriesState, Transport
  File "/opt/fhem/.local/lib/python3.9/site-packages/aiohomekit/model/__init__.py", line 24, in <module>
    from aiohomekit.protocol.statuscodes import to_status_code
  File "/opt/fhem/.local/lib/python3.9/site-packages/aiohomekit/protocol/__init__.py", line 24, in <module>
    from cryptography.hazmat.primitives import serialization
  File "/opt/fhem/.local/lib/python3.9/site-packages/cryptography/hazmat/primitives/serialization/__init__.py", line 7, in <module>
    from cryptography.hazmat.primitives._serialization import (
  File "/opt/fhem/.local/lib/python3.9/site-packages/cryptography/hazmat/primitives/_serialization.py", line 17, in <module>
    class PBES(utils.Enum):
AttributeError: module 'cryptography.utils' has no attribute 'Enum'
```

It's really hard to reproduce as it happens only on Raspbian when running fhempy which tries to do the import. If I do it on the console or run the same program on crostini (Linux on Chrome OS) it works without any issues.

I would be glad if you could point me in the right direction as I can't find the cause for this issue. You can also see it in the Ubuntu tests I run in the github workflow: https://github.com/fhempy/fhempy/actions/runs/5236448852/jobs/9453997332

Many thanks for your support!

**Comment by fhempy** [comment]
I tried to install pyOpenSSL and it fixed the issues. I haven't had it installed before, now I'm running pyOpenSSL-23.2.0 and the issue is gone.

Could it be that pyOpenSSL is missing as a requirement for cryptography?

**Comment by reaperhulk** [comment]
`cryptography` definitely does not depend on `pyOpenSSL`. When you installed that version it would have upgraded your `cryptography` version though, which likely resolved an issue.

This sort of error typically occurs in environments where there are multiple package paths and part of `cryptography` gets imported from one version and part from another (e.g. cryptography < 35 does not have `utils.Enum`, but also no version of cryptography < 35 would try to import it).
