### ISSUE TITLE
ValueError: Encryption/decryption failed when len(data) > 190

### ISSUE THREAD

**Issue by zuhataslan** [pyca/cryptography#9404]
## ValueError: Encryption/decryption failed
I get this exception when data to encrypt is > 190 bytes.

### Versions
- python: 3.11.0
- pip: 23.2.1
- setuptools: 68.0.0
- cryptography: 41.0.3
- cffi: 1.15.1

### cryptography installation
Tried with below installation methods:
```sh
pip install cryptography
```

```sh
brew install openssl@3 rust
env OPENSSL_DIR="$(brew --prefix openssl@3)" pip install cryptography
```
```sh
brew install openssl@3 rust
env OPENSSL_STATIC=1 OPENSSL_DIR="$(brew --prefix openssl@3)" pip install cryptography
```
uninstalled prior reinstalling

### Steps to reproduce:
```py
from cryptography.hazmat.primitives import serialization, hashes
from cryptography.hazmat.primitives.asymmetric import padding

with open("public.rsa", "rb") as fh:
    pubkey = serialization.load_pem_public_key(fh.read())


def encrypt(data: bytes):
    chiper = pubkey.encrypt(
        data,
        padding.OAEP(
            mgf=padding.MGF1(algorithm=hashes.SHA256()),
            algorithm=hashes.SHA256(),
            label=None,
        ),
    )
    return chiper


# len 190
data = b"iiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii"
print(len(data))
print(encrypt(data))  # Works
print()


# len 191
data = b"jjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjj"
print(len(data))
print(encrypt(data))  # ValueError
```

#### When running:
```sh
$ python encrypt_this.py

190
b'(6\x86\xb6\x8e\r\xf0\xe0\x9a\xc6\xaa^\x93\x9e\xfb\xf0\xe65\xc0F\t\x8a\xa0d\xbb\xf3z9\xa5\x0b\x10\xdf\xdcm\xf1\x91y\xb6\xe7\'\x951\x997\xc9@/\xd2L]\xc3\xdc\x9c\xba\xd9W\x05\xbe\xecv\xffW6PD\xbdW\xbc\xabu\x999\x9c>\xee\xee\xb3$\x8cE-\x00)9\x8e\x18jLd\xea^\x9fU\x1c\xcc\xfa\xc8g:Uiw\xfdqJmE\xa7s\x9f\xf0\xc2\x9a\xe3#00M"z\x8d@X\xf0\xa3\xd1\x89\xf3n\xcd\xaf\xa8ro\xdf5\xe0n\xfdY\xe8:\x86\xe7\xe3\xbb\x94\x8d\xd5\xe0|\xe9\xbeMN\x97:\xbf\x05S%\xd0:y^\xff\x19\xde\xb0\xc6\x9fG?\xd1\xae\xf0\xed\xa5\x02\xa6\xd8\xcab\xdd\xbe\x0b\x05A\x9f\xfac\xaa\xe6\x1f\x17\xbdVp\x0b\x07\xef\x98m\xdf9\xee;\xeb0 \xbf\xf8\xad\xd9 9l\xdd\xbfhz\x85\x05\xd4.T0p\x08\xa4&\x9d\x04v\xcb\xfcH\xa6\x88f\x94d\x01\t\xd6\xa6\xb3\xd3\x9f\xc9\xd7\xc8A\x93G\xe9'

191
Traceback (most recent call last):
  File "/private/var/folders/8y/w5z66xwd7j97nrxjly9wdhf00000gq/T/tmp.7rU6r7CxJw/encrypt_this.py", line 30, in <module>
    print(encrypt(data))  # ValueError
          ^^^^^^^^^^^^^
  File "/private/var/folders/8y/w5z66xwd7j97nrxjly9wdhf00000gq/T/tmp.7rU6r7CxJw/encrypt_this.py", line 9, in encrypt
    chiper = pubkey.encrypt(
             ^^^^^^^^^^^^^^^
  File "/Users/xxx/.pyenv/versions/cryptography/lib/python3.11/site-packages/cryptography/hazmat/backends/openssl/rsa.py", line 550, in encrypt
    return _enc_dec_rsa(self._backend, self, plaintext, padding)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xxx/.pyenv/versions/cryptography/lib/python3.11/site-packages/cryptography/hazmat/backends/openssl/rsa.py", line 97, in _enc_dec_rsa
    return _enc_dec_rsa_pkey_ctx(backend, key, data, padding_enum, padding)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xxx/.pyenv/versions/cryptography/lib/python3.11/site-packages/cryptography/hazmat/backends/openssl/rsa.py", line 163, in _enc_dec_rsa_pkey_ctx
    raise ValueError("Encryption/decryption failed.")
ValueError: Encryption/decryption failed.
```

**Comment by alex** [comment]
This is expected, RSA can onyl encrypt data smaller than the key size (minus a few bytes of overhead).

**Comment by zuhataslan** [comment]
Right, everything is working as intended then but maybe the exception message could be a bit more descriptive. It took a while to figure out that the exception was thrown when the data exceeded a specific size.
