### ISSUE TITLE
Feature request: Windows ARM64 support / static build

### ISSUE THREAD

**Issue by TBSJordanNash** [pyca/cryptography#9519]
Please provide a static build for Windows ARM64. 

Thank you!

----------

[20230830_cryptography_install_failure.txt](https://github.com/pyca/cryptography/files/12478944/20230830_cryptography_install_failure.txt)

PS C:\Users\user.name> pip list
Package    Version
---------- -------
pip        23.2.1
setuptools 65.5.0

PS C:\Users\user.name> pip3 cache purge
Files removed: 27
PS C:\Users\user.name> pip3 -v install cryptography
Using pip 23.2.1 from C:\Users\user.name\AppData\Local\Programs\Python\Python311-arm64\Lib\site-packages\pip (python 3.11)
Collecting cryptography
  Downloading cryptography-41.0.3.tar.gz (630 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 630.1/630.1 kB 5.0 MB/s eta 0:00:00
  Running command pip subprocess to install build dependencies
  Collecting setuptools>=61.0.0
    Obtaining dependency information for setuptools>=61.0.0 from https://files.pythonhosted.org/packages/4f/ab/0bcfebdfc3bfa8554b2b2c97a555569c4c1ebc74ea288741ea8326c51906/setuptools-68.1.2-py3-none-any.whl.metadata
    Downloading setuptools-68.1.2-py3-none-any.whl.metadata (6.2 kB)
  Collecting wheel
    Obtaining dependency information for wheel from https://files.pythonhosted.org/packages/b8/8b/31273bf66016be6ad22bb7345c37ff350276cfd46e389a0c2ac5da9d9073/wheel-0.41.2-py3-none-any.whl.metadata
    Downloading wheel-0.41.2-py3-none-any.whl.metadata (2.2 kB)
  Collecting cffi>=1.12
    Downloading cffi-1.15.1.tar.gz (508 kB)
       -------------------------------------- 508.5/508.5 kB 4.6 MB/s eta 0:00:00
    Installing build dependencies: started
    Installing build dependencies: finished with status 'done'
    Getting requirements to build wheel: started
    Getting requirements to build wheel: finished with status 'error'
    error: subprocess-exited-with-error

    Getting requirements to build wheel did not run successfully.
    exit code: 1

    [35 lines of output]
    Traceback (most recent call last):
      File "C:\Users\user.name\AppData\Local\Programs\Python\Python311-arm64\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
        main()
      File "C:\Users\user.name\AppData\Local\Programs\Python\Python311-arm64\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
        json_out['return_val'] = hook(**hook_input['kwargs'])
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "C:\Users\user.name\AppData\Local\Programs\Python\Python311-arm64\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
        return hook(config_settings)
               ^^^^^^^^^^^^^^^^^^^^^
      File "C:\Users\user.name\AppData\Local\Temp\pip-build-env-mphof4q5\overlay\Lib\site-packages\setuptools\build_meta.py", line 355, in get_requires_for_build_wheel
        return self._get_build_requires(config_settings, requirements=['wheel'])
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "C:\Users\user.name\AppData\Local\Temp\pip-build-env-mphof4q5\overlay\Lib\site-packages\setuptools\build_meta.py", line 325, in _get_build_requires
        self.run_setup()
      File "C:\Users\user.name\AppData\Local\Temp\pip-build-env-mphof4q5\overlay\Lib\site-packages\setuptools\build_meta.py", line 507, in run_setup
        super(_BuildMetaLegacyBackend, self).run_setup(setup_script=setup_script)
      File "C:\Users\user.name\AppData\Local\Temp\pip-build-env-mphof4q5\overlay\Lib\site-packages\setuptools\build_meta.py", line 341, in run_setup
        exec(code, locals())
      File "<string>", line 126, in <module>
      File "<string>", line 105, in uses_msvc
      File "C:\Users\user.name\AppData\Local\Temp\pip-build-env-mphof4q5\overlay\Lib\site-packages\setuptools\_distutils\command\config.py", line 223, in try_compile
        self._compile(body, headers, include_dirs, lang)
      File "C:\Users\user.name\AppData\Local\Temp\pip-build-env-mphof4q5\overlay\Lib\site-packages\setuptools\_distutils\command\config.py", line 128, in _compile
        self.compiler.compile([src], include_dirs=include_dirs)
      File "C:\Users\user.name\AppData\Local\Temp\pip-build-env-mphof4q5\overlay\Lib\site-packages\setuptools\_distutils\_msvccompiler.py", line 343, in compile
        self.initialize()
      File "C:\Users\user.name\AppData\Local\Temp\pip-build-env-mphof4q5\overlay\Lib\site-packages\setuptools\_distutils\_msvccompiler.py", line 253, in initialize
        vc_env = _get_vc_env(plat_spec)
                 ^^^^^^^^^^^^^^^^^^^^^^
      File "C:\Users\user.name\AppData\Local\Temp\pip-build-env-mphof4q5\overlay\Lib\site-packages\setuptools\msvc.py", line 233, in msvc14_get_vc_env
        return _msvc14_get_vc_env(plat_spec)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "C:\Users\user.name\AppData\Local\Temp\pip-build-env-mphof4q5\overlay\Lib\site-packages\setuptools\msvc.py", line 190, in _msvc14_get_vc_env
        raise distutils.errors.DistutilsPlatformError("Unable to find vcvarsall.bat")
    distutils.errors.DistutilsPlatformError: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
    [end of output]

    note: This error originates from a subprocess, and is likely not a problem with pip.
  error: subprocess-exited-with-error

  Getting requirements to build wheel did not run successfully.
  exit code: 1

  See above for output.

  note: This error originates from a subprocess, and is likely not a problem with pip.
  error: subprocess-exited-with-error

  × pip subprocess to install build dependencies did not run successfully.
  │ exit code: 1
  ╰─> See above for output.

  note: This error originates from a subprocess, and is likely not a problem with pip.
  full command: 'C:\Users\user.name\AppData\Local\Programs\Python\Python311-arm64\python.exe' 'C:\Users\user.name\AppData\Local\Programs\Python\Python311-arm64\Lib\site-packages\pip\__pip-runner__.py' install --ignore-installed --no-user --prefix 'C:\Users\user.name\AppData\Local\Temp\pip-build-env-rebfbtqd\overlay' --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- 'setuptools>=61.0.0' wheel 'cffi>=1.12; platform_python_implementation != '"'"'PyPy'"'"'' 'setuptools-rust>=0.11.4'
  cwd: [inherit]
  Installing build dependencies ... error
error: subprocess-exited-with-error

× pip subprocess to install build dependencies did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

**Comment by reaperhulk** [comment]
https://cryptography.io/en/latest/faq/#will-you-upload-wheels-for-my-non-x86-non-arm64-cpu-architecture is relevant here despite this being ARM64. Notably, right now GitHub Actions does not offer ARM64 Windows runners so we have no way to run tests on that platform.

**Comment by TBSJordanNash** [comment]
@reaperhulk Thanks for the reply. 

I did find vs_BuildTools.exe (https://visualstudio.microsoft.com/visual-cpp-build-tools/), but I'm trying to find the most efficient incantation to enable pip to work, without having to grant myself local admin privileges and turn my workstation into a dev environment. 

I did see the documentation both for building it and for the limitations of support. Is there an efficient way to build this or do I just have to wait for the community (and GitHub infrastructure) to support ARM64?

**Comment by reaperhulk** [comment]
Unfortunately compilation on Windows is not simple and you'll need to have all the dependencies present either on your own system or on a build system (and then transfer the resulting wheel).

It's unfortunate that Microsoft has not chosen to expose support for their own OS in their CI systems.

**Comment by alex** [comment]
We'll ship official wheels when Microsoft (which owns both Windows and Github) offers a CI service we can use to test/build.
