### ISSUE TITLE
HKDF with SHAKE256 gives InternalError: Unknown OpenSSL error.

### ISSUE THREAD

**Issue by clonejo** [pyca/cryptography#9845]
I run into "cryptography.exceptions.InternalError: Unknown OpenSSL error." when i try to perform a HKDF key derivation with SHAKE256. HKDF with SHA256 works fine.

## Error Message
```
Traceback (most recent call last):
  File "[…]/cryptography-openssl-crash/./crypto.py", line 23, in <module>
    enc_key = derive_key(root)
              ^^^^^^^^^^^^^^^^
  File "[…]/./crypto.py", line 19, in derive_key
    return hkdf.derive(root)
           ^^^^^^^^^^^^^^^^^
  File "[…]/.cache/pypoetry/virtualenvs/cryptography-openssl-crash-X_c1qFin-py3.11/lib/python3.11/site-packages/cryptography/hazmat/primitives/kdf/hkdf.py", line 42, in derive
    return self._hkdf_expand.derive(self._extract(key_material))
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "[…]/.cache/pypoetry/virtualenvs/cryptography-openssl-crash-X_c1qFin-py3.11/lib/python3.11/site-packages/cryptography/hazmat/primitives/kdf/hkdf.py", line 36, in _extract
    h = hmac.HMAC(self._salt, self._algorithm)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
cryptography.exceptions.InternalError: Unknown OpenSSL error. This error is commonly encountered
                        when another library is not cleaning up the OpenSSL error
                        stack. If you are using cryptography with another library
                        that uses OpenSSL try disabling it before reporting a bug.
                        Otherwise please file an issue at
                        https://github.com/pyca/cryptography/issues with
                        information on how to reproduce this. ([])
```

## How to reproduce
crypto.py:
```python
#!/usr/bin/env python3

from cryptography.hazmat.primitives import hashes
from cryptography.hazmat.primitives.kdf.hkdf import HKDF


def derive_key(root):
    hkdf = HKDF(
        algorithm=hashes.SHAKE256(
            256
        ),  # cryptography.exceptions.InternalError: Unknown OpenSSL error.
        # algorithm=hashes.SHA256(),  # this works
        length=256 // 8,
        salt=None,
        info=None,
    )

    return hkdf.derive(root)


root = b"\x17" * 32
enc_key = derive_key(root)
print(enc_key)
```

```sh
pipx install poetry
poetry init
poetry add cryptography
poetry run ./crypto.py
```

~~The same happens when i try to use Hash() with SHAKE256(). SHAKE128() and SHA3_256() also seem to be affected.~~

## Versions
Python = 3.11.5
cryptography = 41.0.5
cffi = 1.16.0
pip = 23.3.1
setuptools = 68.2.2
```
>>> cryptography.hazmat.backends.openssl.backend.openssl_version_text()
'OpenSSL 3.1.4 24 Oct 2023'
```

Reproduces on both Fedora and Arch.

Thanks for having a look!

**Comment by alex** [comment]
Well that's fun. It seems likely to me that OpenSSL doesn't support HMAC-SHAKE256, which is a building block for HKDF.

Is there a reason you're using this particular set of primitives?

At a minimum this should raise an appropriate error. I'm not sure what it'd take to support it properly.

**Comment by clonejo** [comment]
```
echo -n "value-to-digest" | openssl dgst -shake256 -hmac "secret-key-here"   
Error setting context
```
Looks like you're right. (This was tested with my Arch's 3.1.3.)

**Comment by clonejo** [comment]
This OpenSSL bug issue seems to be related: https://github.com/openssl/openssl/issues/8563#issuecomment-476280463

Apparently HMAC is not specified for SHAKE?! I guess i'll look for a different solution :)
